### ISSUE TITLE
New email not showing up in inbox

### ISSUE THREAD

**Issue by dakontiva** [nextcloud/mail#4925] opened 2021-04-08 21:15 UTC
### Expected behavior
New email should show up in the priority inbox

### Actual behavior
I receive a notification about new mail but when I open the maill tab there is no new mail under priority inbox. New mail is only showing up after refreshing the page. This only happens with priority inbox, all inboxes view shows all new email immdediately as expcected.

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** gmail

### Server configuration

**Operating system**: Probably Debian 10 (Can't confirm as my hosting provider didn't provide it)

**Web server:** Don't know

**Database:** Mysql  10.5.8

**PHP version:** 7.4.13

**Nextcloud Version:** 20.0.7

#### Client configuration
**Browser:** Firefox 87

**Operating system:** Fedora 33

**Comment by anole1980** [comment] 2021-04-11 02:14
Looks like I got the same issue here. But I got it worse! The only way I can get a new mail is clearing the cache of a inbox.

**Comment by ChristophWurst** [comment] 2021-04-12 07:09
when this happens please try to inspect the oc_mail_messages table and the last few entries. You should be able to find the "ghost" message. Then tell me the values of flag_important, flag_flagged and flag_seen. I wonder if a certain combination of those three values causes the bug. Thanks.

**Comment by dakontiva** [comment] 2021-04-12 09:54
Unfortunately I can't check that as my hosting provider doesn't provide mysql access. I only have access to the Nextcloud admin web interface. Is there a way of checking that using admin interface? Or if you can provide a test instance with mysql access (sorry I am just a student and can't afford a VPS currently) I can setup my mail account and provide you more details.

**Comment by thstyl2000** [comment] 2021-04-13 07:28
I am experiencing sth similar (#4834), and have admin access to the instance. I am however not very knowledgeable with sql....would be grateful if you could give me some a bit more info on where to look for what...thanks!!

**Comment by miaulalala** [comment] 2021-04-13 08:43
@thstyl2000 do you have access to something like phpMyAdmin?

**Comment by thstyl2000** [comment] 2021-04-13 10:49
It has to be installed along with the nextcloud instance, right?
Well, no. But it looks like sth that may come in handy, so that I will probably install it in the future.

Is there another tool? (I am on Ubuntu, the server is running on a freenas)

**Comment by miaulalala** [comment] 2021-04-13 11:28
@thstyl2000 If you have access to the sql server via CLI, when running into this issue, do a select on the oc_mail_messages table like so:

`SELECT * from oc_mail_messages order by id desc limit 20;` I'm limiting this to 20 rows as to not get too many results. If your divergent messages don't show up in the result, try to increase limit to 50.

Since we only want to analyse messages that are not showing up in the priority inbox, do a second query:

`SELECT id, flag_important, flag_flagged, flag_seen from oc_mail_messages where id in(1, 2, 3 ) order by id desc limit 20;` 

Replace the ids in the part `id in (1, 2, 3)` with the ids of those entries that are supposed to show in the priority inbox but aren't there.

Also, just to clarify on this issue, @dakontiva, are those divergent mails actually marked as important? The priority in box does not update for every message, only those the mail server sees with a flag for `important`.

**Comment by dakontiva** [comment] 2021-04-13 11:34
@miaulalala shouldn't they appear in `other` category if they are not marked as `important`?

**Comment by miaulalala** [comment] 2021-04-13 11:38
@dakontiva yes, that's why I was asking. From the way you worded it I thought you meant it should show up under the Important section. So it does not show up in the `other` section either?

**Comment by dakontiva** [comment] 2021-04-13 11:47
ok let me clarify. I receive a desktop notification from firefox about new mail but when I open the firefox tab there is no new mail either under `important` or `other` category. If I refresh the page, I see the new mail in one of the categories (I suppose depending on how the mail app classifies it)

**Comment by miaulalala** [comment] 2021-04-13 11:49
OK I see, thanks for clarifying!

**Comment by thstyl2000** [comment] 2021-04-15 07:48
Ok, assuming we are looking at the same problem, here are the flags of a new email, which does not appear anywhere in the PI view, although the browser has sent the notification:

```
+-------+----------------+--------------+-----------+
| id    | flag_important | flag_flagged | flag_seen |
+-------+----------------+--------------+-----------+
| 61807 |              0 |            0 |         0 |
+-------+----------------+--------------+-----------+
```
Hope this helps...!

**Comment by thstyl2000** [comment] 2021-04-15 10:56
I just noticed that marking an email in "Other" as important, after waiting around 20sec one sees that the mark disappears.

**Comment by dakontiva** [comment] 2021-04-19 21:39
Not sure if this is related but I just saw that the mail app is logging a lot of these errors:
```
[PHP] Error: Error: ini_restore() has been disabled for security reasons at /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Util/Horde/String.php#152 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "ini_restore() h ... s", "/data/www/aniru ... p", 152, {input: null,fro ... e})
 1. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Util/Horde/String.php line 152
    ini_restore("track_errors")
 2. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Util/Horde/String.php line 96
    Horde_String::_convertCharset(null, "windows-1252", "utf-8")
 3. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime.php line 259
    Horde_String::convertCharset(null, "windows-1252", "utf-8")
 4. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Headers/Element/Multiple.php line 53
    Horde_Mime::decode("=?iso-8859-1?Q?RdV_pr=E9fecture?=")
 5. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Headers/Element.php line 79
    Horde_Mime_Headers_Element_Multiple->_setValue("=?iso-8859-1?Q?RdV_pr=E9fecture?=")
 6. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Headers/Element.php line 56
    Horde_Mime_Headers_Element->setValue("=?iso-8859-1?Q?RdV_pr=E9fecture?=")
 7. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Headers.php line 201
    Horde_Mime_Headers_Element->__construct("Thread-Topic", "=?iso-8859-1?Q?RdV_pr=E9fecture?=")
 8. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Headers.php line 371
    Horde_Mime_Headers->addHeader("Thread-Topic", "=?iso-8859-1?Q?RdV_pr=E9fecture?=")
 9. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Data/Fetch.php line 628
    Horde_Mime_Headers::parseHeaders(Horde_Stream_Temp {stream: null})
10. /data/www/anirudh.owncube.com/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Data/Fetch.php line 157
    Horde_Imap_Client_Data_Fetch->_getHeaders("0", 1, 3)
11. /data/www/anirudh.owncube.com/apps/mail/lib/Model/IMAPMessage.php line 178
    Horde_Imap_Client_Data_Fetch->getHeaderText("0", 1)
12. /data/www/anirudh.owncube.com/apps/mail/lib/Model/IMAPMessage.php line 687
    OCA\Mail\Model\IMAPMessage->getRawReferences()
13. /data/www/anirudh.owncube.com/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 378
    OCA\Mail\Model\IMAPMessage->toDbMessage(25)
14. <<closure>>
    OCA\Mail\Service\Sync\ImapToDbSynchronizer->OCA\Mail\Service\Sync\{closure}("*** sensitive parameters replaced ***")
15. /data/www/anirudh.owncube.com/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 379
    array_map(Closure {}, [OCA\Mail\Model\ ... "])
16. /data/www/anirudh.owncube.com/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php line 221
    OCA\Mail\Service\Sync\ImapToDbSynchronizer->runPartialSync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 25}, OC\AppFramework\ScopedPsrLogger {}, 42, [15,16,17,21,24, ... "])
17. /data/www/anirudh.owncube.com/apps/mail/lib/Service/Sync/SyncService.php line 121
    OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 25}, OC\AppFramework\ScopedPsrLogger {}, 42, [15,16,17,21,24, ... "], false)
18. /data/www/anirudh.owncube.com/apps/mail/lib/Controller/MailboxesController.php line 161
    OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 25}, 42, [7651,7649,7648, ... "], true, null)
19. /data/www/anirudh.owncube.com/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Mail\Controller\MailboxesController->sync(25, [7651,7649,7648, ... "], false, null)
20. /data/www/anirudh.owncube.com/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Control ... {}, "sync")
21. /data/www/anirudh.owncube.com/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Control ... {}, "sync")
22. /data/www/anirudh.owncube.com/lib/private/Route/Router.php line 309
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {id: "25",_route: "mail.mailboxes.sync"})
23. /data/www/anirudh.owncube.com/lib/base.php line 1008
    OC\Route\Router->match("/apps/mail/api/mailboxes/25/sync")
24. /data/www/anirudh.owncube.com/index.php line 37
    OC::handleRequest()

POST /index.php/apps/mail/api/mailboxes/25/sync
from 90.73.218.80 by anirudh at 2021-04-19T21:36:34+00:00
```

**Comment by ChristophWurst** [comment] 2021-04-26 07:12
I don't think so @dakontiva but thanks for keeping an eye open on any related bugs.

If I'm not mistaken I also ran into this the other day. I think the problem is more of an issue with how we store the sync results locally and how they propagate to the individual mailbox sections than anything wrong on the back-end. I'll try to reproduce on my dev instance once I figured out when this happens. As far as I can tell it doesn't occur all the time, at least for me.

**Comment by thstyl2000** [comment] 2021-04-26 10:57
Thanks for looking into it! Well in my case it is sadly the standard behavior for all incoming mails....it feels as if the browser "view" does not sync automatically.
I don't know if this is relevant, but I noticed that a calendar event which was added via caldav (davx5), appears in the browser only after a refresh.

**Comment by mptei** [comment] 2021-12-03 07:53
I have the same problem with Mail 1.11.0 (Nextcloud 22.2.3). I got a notification about 4 new emails, but the PI view hasn't changed at all (even after waiting several minutes).
All flag_* columns contains 0. Column structure_analyzed is 1.

**Comment by ChristophWurst** [comment] 2021-12-03 08:23
The front-end only synchronizes the unfiltered inboxes, not the filtered priority inboxes. Thus there is a notification but no new email.

**Comment by mptei** [comment] 2021-12-03 11:07
This makes me wonder why you didn't close that issue already if this is the expected behavior.
On the other hand a "priority inbox" which is not refreshing seems strange to me.
What is the idea behind that? What use-case is this for?

**Comment by ChristophWurst** [comment] 2021-12-03 12:22
It's not expected. I just tried to explain why this happens :-)

**Comment by mptei** [comment] 2021-12-03 12:26
Ups, sorry for my misunderstanding.

**Comment by brzd** [comment] 2022-01-02 15:28
After updating to Mail 1.11.5, the new mails are not shown in "All inboxes" - even after hitting the "r" on keyboard. To me at least, this is not expected or preferred way of using the mail inboxes. I can understand that using the "Important  and new" -view is preferred by some, but it should not hinder the use of the mail app itself.

I would prefer using simple and clean folder for incoming mail.

Or did I misunderstand something? Please, advise is welcome.

> Mail 1.11.5, Nextcloud 22.2.3

**Comment by miaulalala** [comment] 2022-01-13 14:12
@DocSniper can you open your Browser Console and see if there's any errors? Javascript or other?

**Comment by brzd** [comment] 2022-01-13 14:18
Here's also some info from the browser console:

jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 172 globals.js:62:15
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11

**Comment by GretaD** [comment] 2022-01-13 14:24
> @DocSniper can you open your Browser Console and see if there's any errors? Javascript or other?

I can reproduce this error and theres no error related directly to this problem.

**Comment by DocSniper** [comment] 2022-01-13 17:38
My different browser consoles give me different output of type error, very strange. 
Chromium doesn't show anything special, but Firefox and Falkon show something about sync error, maybe this is the crux.
[nc-mail-20220113.log](https://github.com/nextcloud/mail/files/7864777/nc-mail-20220113.log)

**Comment by dustbro** [comment] 2022-01-14 09:44
Same thing here since the last update.

**Comment by st3iny** [comment] 2022-01-14 14:42
It seems like the whole refresh button is broken by now. It doesn't work on any mailbox for me. Switching the mailbox and then back again will show the new emails.

**Comment by DocSniper** [comment] 2022-01-14 17:15
I saw this pull request ( https://github.com/nextcloud/mail/pull/5948 ) and patched it into my nextcloud installation. 
Now the mails are displayed shortly after receipt in the folder, as we are used to. 
So the problem seems to be fixed now. Thanks @st3iny

**Closed** 2022-01-19 11:26 UTC
Labels: bug, 3. to review
