### ISSUE TITLE
Problem with USERID

### ISSUE THREAD

**Issue by khayman123** [nextcloud/mail#970] opened 2018-07-13 18:22 UTC
Hi. I've deployed nextcloud in my infrastructure, integrate with my ldap and finnaly I've wantedt to enable mail. I've added to config.php:
```
 'app.mail.accounts.default' => [
    'email' => '%EMAIL%',
    'imapUser' => '%USERID%',
    'imapHost' => 'imap.myserver.com',
    'imapPort' => 143,
    'imapSslMode' => 'tls',
    'smtpUser' => '%USERID%',
    'smtpHost' => 'smtp.myserver.com',
    'smtpPort' => 25,
    'smtpSslMode' => 'tls',
  ],
```

but when I've logon to app and go to mail, I saw this:
Account
Name: "display name from ldap"
Email: "email from ldap"
imap server: imap.myserver.com
Port: 143 STARTTLS
Imap User: **"email from ldap"**
Imap Password: Empty

smtp server: smtp.myserver.com
Port: 25STARTTLS
SmtpUser: **"email from ldap"**
Smtp Password: Empty

It behaves very strange, and I cant figure why is that.

When I set   'email' => '', Imap user and Smtp user were empty too.

**Comment by khayman123** [comment] 2018-07-14 12:10
I forgot to mention, that username, which is using to logon to nextcloud, is different than email, both username and email are get from ldap backend, used in nextcloud.

**Comment by ChristophWurst** [comment] 2018-07-23 07:52
> Imap User: "email from ldap"

From looking at the [code](https://github.com/nextcloud/mail/blob/master/lib/Service/DefaultAccount/Config.php), it's not clear why that happens. The only possibility I see is `IUser::getUID()` returns the user's email instead of its username. @blizzz any idea if this is to be expected or caused by misconfiguration on the LDAP app?

**Comment by blizzz** [comment] 2018-07-31 09:56
Sorry, I don't understand what is expected and what is the actual behaviour. Could you elaborate? Also, the LDAP config (`occ ldap:show-config`) would help.

**Comment by ChristophWurst** [comment] 2018-11-08 10:38
No info provided -> closing

**Comment by staeglis** [comment] 2018-12-14 13:17
Hi,

we have the same problem. Here is the requested output.

Cheers,
Stefan

`+-------------------------------+-------------------------------------------------------------------------+
| Configuration                 | s01                                                                     |
+-------------------------------+-------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                       |
| homeFolderNamingRule          |                                                                         |
| lastJpegPhotoLookup           | 0                                                                       |
| ldapAgentName                 | cn=?, OU=?,OU=?,dc=?,dc=?                                               |
| ldapAgentPassword             | ***                                                                     |
| ldapAttributesForGroupSearch  |                                                                         |
| ldapAttributesForUserSearch   |                                                                         |
| ldapBackupHost                |                                                                         |
| ldapBackupPort                |                                                                         |
| ldapBase                      | dc=?,dc=?                                                               |
| ldapBaseGroups                | ?                                                                       |
| ldapBaseUsers                 | OU=?,dc=?,dc=?                                                          |
| ldapCacheTTL                  | 600                                                                     |
| ldapConfigurationActive       | 1                                                                       |
| ldapDefaultPPolicyDN          |                                                                         |
| ldapDynamicGroupMemberURL     |                                                                         |
| ldapEmailAttribute            | mail                                                                    |
| ldapExperiencedAdmin          | 0                                                                       |
| ldapExpertUUIDGroupAttr       |                                                                         |
| ldapExpertUUIDUserAttr        | cn                                                                      |
| ldapExpertUsernameAttr        |                                                                         |
| ldapGidNumber                 | gidNumber                                                               |
| ldapGroupDisplayName          | cn                                                                      |
| ldapGroupFilter               | (&(|(objectclass=top)))                                                 |
| ldapGroupFilterGroups         |                                                                         |
| ldapGroupFilterMode           | 0                                                                       |
| ldapGroupFilterObjectclass    | top                                                                     |
| ldapGroupMemberAssocAttr      | gidNumber                                                               |
| ldapHost                      | ldaps://?                                                               |
| ldapIgnoreNamingRules         |                                                                         |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(|(samaccountname=%uid)(|(cn=%uid))))         |
| ldapLoginFilterAttributes     | cn                                                                      |
| ldapLoginFilterEmail          | 0                                                                       |
| ldapLoginFilterMode           | 0                                                                       |
| ldapLoginFilterUsername       | 1                                                                       |
| ldapNestedGroups              | 0                                                                       |
| ldapOverrideMainServer        |                                                                         |
| ldapPagingSize                | 500                                                                     |
| ldapPort                      | 636                                                                     |
| ldapQuotaAttribute            |                                                                         |
| ldapQuotaDefault              |                                                                         |
| ldapTLS                       | 0                                                                       |
| ldapUserAvatarRule            | default                                                                 |
| ldapUserDisplayName           | displayname                                                             |
| ldapUserDisplayName2          |                                                                         |
| ldapUserFilter                | (&(|(objectclass=user)))                                                |
| ldapUserFilterGroups          |                                                                         |
| ldapUserFilterMode            | 0                                                                       |
| ldapUserFilterObjectclass     | user                                                                    |
| ldapUuidGroupAttribute        | auto                                                                    |
| ldapUuidUserAttribute         | auto                                                                    |
| turnOffCertCheck              | 0                                                                       |
| turnOnPasswordChange          | 0                                                                       |
| useMemberOfToDetectMembership | 1                                                                       |
+-------------------------------+-------------------------------------------------------------------------+
`

**Comment by blizzz** [comment] 2018-12-18 12:03
The user id is, according to the configuration, created from the value of the "cn" attribute. Which is already a strange choice, usually, but it depends on how this is used.

User IDs are only assigned once, so if the configuration was different at the time of the mapping of that user (e.g. when it was set to mail), this might have been  the source. Changing the user id is not supported, however.

**Comment by staeglis** [comment] 2018-12-19 11:22
Ok I've tested it with a new account successfully now. But I can't see any difference between the old and the new account in the table oc_ldap_user_mapping.  owncloud_name is equal to directory_uuid for both accounts.

**Comment by blizzz** [comment] 2018-12-19 12:20
Then in any way `$user->getUID()` should return the UUID.

**Comment by staeglis** [comment] 2019-01-11 12:17
Where is the user object used in the code created?

**Comment by e-user** [comment] 2019-03-21 09:49
I'm having a similar problem, only that NextCloud Mail tries to use the _Internal Username_ from LDAP integration for `%USERID`, which is a UUID. The correct element needed for logging in to IMAP would be `uid` (which is also used for logging into to NextCloud). 

The output from `occ ldap:show-config` is as follows.

```
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                        |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                          |
| homeFolderNamingRule          |                                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                                          |
| ldapAgentName                 | uid=nextcloud,cn=sysaccounts,cn=etc,dc=in,dc=company,dc=tld                                                                |
| ldapAgentPassword             | ***                                                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                                                            |
| ldapAttributesForUserSearch   |                                                                                                                            |
| ldapBackupHost                |                                                                                                                            |
| ldapBackupPort                |                                                                                                                            |
| ldapBase                      | cn=accounts,dc=in,dc=company,dc=tld                                                                                        |
| ldapBaseGroups                | cn=accounts,dc=in,dc=company,dc=tld                                                                                        |
| ldapBaseUsers                 | cn=accounts,dc=in,dc=company,dc=tld                                                                                        |
| ldapCacheTTL                  | 600                                                                                                                        |
| ldapConfigurationActive       | 1                                                                                                                          |
| ldapDefaultPPolicyDN          |                                                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                                                            |
| ldapEmailAttribute            | mail                                                                                                                       |
| ldapExperiencedAdmin          | 0                                                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                                                            |
| ldapExpertUUIDUserAttr        |                                                                                                                            |
| ldapExpertUsernameAttr        |                                                                                                                            |
| ldapGidNumber                 | gidNumber                                                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                                         |
| ldapGroupFilter               | (&(|(objectclass=groupofnames)))                                                                                           |
| ldapGroupFilterGroups         |                                                                                                                            |
| ldapGroupFilterMode           | 1                                                                                                                          |
| ldapGroupFilterObjectclass    | ipaobject                                                                                                                  |
| ldapGroupMemberAssocAttr      | gidNumber                                                                                                                  |
| ldapHost                      | ipa.in.company.tld                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                            |
| ldapLoginFilter               | (&(&(|(objectclass=ipaobject))(|(memberof=cn=ipausers,cn=groups,cn=accounts,dc=in,dc=company,dc=tld)))(uid=%uid))          |
| ldapLoginFilterAttributes     |                                                                                                                            |
| ldapLoginFilterEmail          | 0                                                                                                                          |
| ldapLoginFilterMode           | 0                                                                                                                          |
| ldapLoginFilterUsername       | 1                                                                                                                          |
| ldapNestedGroups              | 0                                                                                                                          |
| ldapOverrideMainServer        |                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                        |
| ldapPort                      | 389                                                                                                                        |
| ldapQuotaAttribute            |                                                                                                                            |
| ldapQuotaDefault              |                                                                                                                            |
| ldapTLS                       | 0                                                                                                                          |
| ldapUserAvatarRule            | default                                                                                                                    |
| ldapUserDisplayName           | displayname                                                                                                                |
| ldapUserDisplayName2          |                                                                                                                            |
| ldapUserFilter                | (&(|(objectclass=ipaobject))(|(memberof=cn=ipausers,cn=groups,cn=accounts,dc=in,dc=company,dc=tld)))                       |
| ldapUserFilterGroups          | ipausers                                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                                          |
| ldapUserFilterObjectclass     | ipaobject                                                                                                                  |
| ldapUuidGroupAttribute        | auto                                                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                                                       |
| turnOffCertCheck              | 0                                                                                                                          |
| turnOnPasswordChange          | 0                                                                                                                          |
| useMemberOfToDetectMembership | 1                                                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------+
```

**Comment by blizzz** [comment] 2019-03-21 11:11
> I'm having a similar problem, only that NextCloud Mail tries to use the Internal Username from LDAP integration for %USERID, which is a UUID. 

The mail app does not have access to LDAP attributes. But, I guess, it could use the loginname which is stored in the session, which then should work for you.

**Comment by e-user** [comment] 2019-03-22 08:24
> > I'm having a similar problem, only that NextCloud Mail tries to use the Internal Username from LDAP integration for %USERID, which is a UUID.
> 
> The mail app does not have access to LDAP attributes. But, I guess, it could use the loginname which is stored in the session, which then should work for you.

This would indeed solve the problem in this case, as the login names are identical.

**Comment by futatuki** [comment] 2019-05-31 08:37
Hi,
I also have same problem.  However I think object to hold session information, IUserSession, dosen't hold username to use for session login.  Public interface for IUserSession can return only IUser object for user information.

In my case, fortunately local part of email address is identical with user id for email services, so I extended config to be able to use %LOCALPART%, which means local part of %EMAIL% email address.

```
--- lib/Service/DefaultAccount/Config.php.orig  2019-04-18 01:50:05.000000000 +0900
+++ lib/Service/DefaultAccount/Config.php       2019-05-31 09:30:22.964106000 +0900
@@ -108,7 +108,8 @@ class Config {
        }
 
        /**
-        * Replace %USERID% and %EMAIL% to allow special configurations
+        * Replace %USERID%, %EMAIL%, %LOCALPART% to allow special
+        * configurations
         *
         * @param string $original
         * @param IUser $user
@@ -119,7 +120,10 @@ class Config {
                        $original = str_replace('%USERID%', $user->getUID(), $original);
                }
                if (!is_null($user->getEMailAddress())) {
-                       $original = str_replace('%EMAIL%', $user->getEMailAddress(), $original);
+                       $email = $user->getEMailAddress();
+                       $localpart = preg_replace('/@[^@]+$/', '', $email);
+                       $original = str_replace('%EMAIL%', $email, $original);
+                       $original = str_replace('%LOCALPART%', $localpart, $original);
                }
                return $original;
        }
```

**Comment by blizzz** [comment] 2019-06-03 11:49
it's not exposed in the public API indeed

**Comment by futatuki** [comment] 2019-06-07 14:46
Here is an ugly hack to access LDAP attribute for `$uid`.  With `'app.mail.accounts.default'`  array element `'ldapUid'`, which expected to be specified the attribute for user id on LDAP, this replaces `%LDAPUID%` to user id on LDAP.

```
--- lib/Service/DefaultAccount/Config.php.orig  2019-04-18 01:50:05.000000000 +0900
+++ lib/Service/DefaultAccount/Config.php       2019-06-07 23:09:52.313557000 +0900
@@ -108,18 +108,42 @@ class Config {
        }
 
        /**
-        * Replace %USERID% and %EMAIL% to allow special configurations
+        * Replace %USERID%, %LDAPUID%, %EMAIL%, %LOCALPART% to allow special
+        * configurations
         *
         * @param string $original
         * @param IUser $user
         * @return string
         */
        private function buildUserEmail(string $original, IUser $user) {
-               if (!is_null($user->getUID())) {
+               $uid= $user->getUID();
+               if (!is_null($uid)) {
                        $original = str_replace('%USERID%', $user->getUID(), $original);
                }
-               if (!is_null($user->getEMailAddress())) {
-                       $original = str_replace('%EMAIL%', $user->getEMailAddress(), $original);
+               $email = $user->getEMailAddress();
+               if (!is_null($email)) {
+                       $localpart = preg_replace('/@[^@]+$/', '', $email);
+                       $original = str_replace('%EMAIL%', $email, $original);
+                       $original = str_replace('%LOCALPART%', $localpart, $original);
+               }
+               $backend = $user->getBackend();
+               if (isset($this->data['ldapUid']) && method_exists($backend, 'getBackendName') && $backend->getBackendName() == 'LDAP' && $uid) {
+                       $access = $backend->getLDAPAccess($uid);
+                       $dn = $access->username2dn($uid);
+                       if (!$dn || !($ldapuid = $access->readAttribute($dn, $this->data['ldapUid'], $access->connection->ldapUserFilter))) {
+                               $ldapuid = $uid;
+                       }
+                       else {
+                               if (is_array($ldapuid)) {
+                                       $ldapuid = count($ldapuid) > 0 ? $ldapuid[0] : $uid;
+                               }
+                       }
+               }
+               else {
+                       $ldapuid = $uid;
+               }
+               if ($ldapuid) { 
+                       $original = str_replace('%LDAPUID%', $ldapuid, $original);
                }
                return $original;
        }

```

**Comment by jsalatiel** [comment] 2019-09-02 17:09
> > I'm having a similar problem, only that NextCloud Mail tries to use the Internal Username from LDAP integration for %USERID, which is a UUID.
> 
> The mail app does not have access to LDAP attributes. But, I guess, it could use the loginname which is stored in the session, which then should work for you.

I am facing the same problem with the UUID. Could you expose the loginname in some variable ?

**Comment by ChristophWurst** [comment] 2019-09-03 14:28
> Could you expose the loginname in some variable ?

Yes, that could be done via https://github.com/nextcloud/server/blob/ecd0d39c304597c77639600a40db25e86fa5a126/lib/public/Authentication/LoginCredentials/ICredentials.php#L43-L50

**Comment by ChristophWurst** [comment] 2019-12-17 16:44
Provisioning was reworked in #2259. Please let us know if this is still a problem.

**Closed by ChristophWurst** 2019-12-17 16:44 UTC
Labels: 0. to triage, bug, help wanted

**Comment by pillarama** [comment] 2023-09-06 10:23
I believe I'm still seeing this issue with my server. I'm running Nextcloud 27.0.2 and I have only just installed the mail app - version 3.3.1 to replace Rainloop which was discontinued (and didn't experience this issue btw)

I also use LDAP authentication for my NextCloud users which is backed onto FreeIPA server and all LDAP users are getting a UUID in the user part everywhere that the username should feature in the mail app - therefore login to the IMAP server fails.

I was able to implement the above workaround patch by futatuki (although in a different file since I guess the code has changed a bit in 4 years). This worked perfectly though when I now use %LOCALPART% instead of %USERID% in the config. Could this patch be implemented into the upstream?

It's worth noting that the use of a UUID as the internal Username in Nextcloud for LDAP users is by design of the LDAP App as described on the LDAP settings page when switching to "Expert" view:

_"By default the internal username will be created from the UUID attribute. It makes sure that the username is unique and characters do not need to be converted. The internal username has the restriction that only these characters are allowed: [a-zA-Z0-9_.@-]. Other characters are replaced with their ASCII correspondence or simply omitted. On collisions a number will be added/increased. The internal username is used to identify a user internally. It is also the default name for the user home folder. It is also a part of remote URLs, for instance for all DAV services. With this setting, the default behavior can be overridden. Changes will have effect only on newly mapped (added) LDAP users. "_

Happy to assist further if I can.

**Comment by futatuki** [comment] 2023-09-06 11:07
> I was able to implement the above workaround patch by futatuki (although in a different file since I guess the code has changed a bit in 4 years).

Actually I still use the patch with minor modification against `lib/ServiceProvisioning/Config.php`:

```
--- lib/Db/Provisioning.php.orig        2021-07-05 15:52:57.000000000 +0900
+++ lib/Db/Provisioning.php     2021-07-10 22:16:05.939553000 +0900
@@ -129,18 +129,42 @@ class Provisioning extends Entity implements JsonSeria
        }
 
        /**
-        * Replace %USERID% and %EMAIL% to allow special configurations
+        * Replace %USERID%, %LDAPUID%, %EMAIL%, %LOCALPART% to allow special
+        * configurations
         *
         * @param string $original
         * @param IUser $user
         * @return string
         */
        private function buildUserEmail(string $original, IUser $user) {
-               if ($user->getUID() !== null) {
+               $uid= $user->getUID();
+               if ($uid !== null) {
                        $original = str_replace('%USERID%', $user->getUID(), $original);
                }
-               if ($user->getEMailAddress() !== null) {
-                       $original = str_replace('%EMAIL%', $user->getEMailAddress(), $original);
+               $email = $user->getEMailAddress();
+               if ($email !== null) {
+                       $localpart = preg_replace('/@[^@]+$/', '', $email);
+                       $original = str_replace('%EMAIL%', $email, $original);
+                       $original = str_replace('%LOCALPART%', $localpart, $original);
+               }
+               $backend = $user->getBackend();
+               if (isset($this->data['ldapUid']) && method_exists($backend, 'getBackendName') && $backend->getBackendName() == 'LDAP' && $uid) {
+                       $access = $backend->getLDAPAccess($uid);
+                       $dn = $access->username2dn($uid);
+                       if (!$dn || !($ldapuid = $access->readAttribute($dn, $this->data['ldapUid'], $access->connection->ldapUserFilter))) {
+                               $ldapuid = $uid;
+                       }
+                       else {
+                               if (is_array($ldapuid)) {
+                                       $ldapuid = count($ldapuid) > 0 ? $ldapuid[0] : '';
+                               }
+                       }
+               }
+               else {
+                       $ldapuid = $uid;
+               }
+               if($ldapuid) {
+                       $original = str_replace('%LDAPUID%', $ldapuid, $original);
                }
                return $original;
        }
```
