### ISSUE TITLE
Mail on OVH: no 'sent' and 'draft' folders

### ISSUE THREAD

**Issue by hubertkn** [nextcloud/mail#372] opened 2017-05-10 23:52 UTC
### Steps to reproduce
1.Install/Add Mail app to nextcloud 11.0.3
2.Add email account at ovh server
3.

### Expected behaviour
See all folders, not only INBOX

### Actual behaviour
Only INBOX folder available

![nextcloud](https://cloud.githubusercontent.com/assets/28611780/25925915/0c6d34a6-35ec-11e7-9bb4-b00ba4cd165f.png)

![ovh roundcube](https://cloud.githubusercontent.com/assets/28611780/25925931/2103af62-35ec-11e7-8208-c5097ddbc537.png)

### Mail app

**Mail app version:** 0.6.4

**Mailserver or service:** ovh

**Transport security - IMAP:** SSL/TLS

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:** 1

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:** 5.6.30

**Version:** 11.0.3

**Updated from an older version or fresh install:** update

**List of activated apps:**

 Activity 2.4.1
Collaborative tags 1.1.3
Comments 1.1.0
Deleted files 1.1.0
External storage support 1.1.2
Federation 1.1.1
File sharing 1.1.1
First run wizard 2.0
Gallery 16.0.0
Log Reader 2.0.0.
Nextcloud announcements 1.0
Notifications 1.0.1
Password policy 1.1.0
PDF viewer 1.0.1
Server info 1.1.1
Share by mail 1.0.1
Text editor 2.2
Theming 1.1.1
Update notification 1.1.1
Usage survey 0.1.5
Versions 1.4.0
Video player 1.0.0
AppOrder 0.3.3
Calendar 1.5.2
Contacts 1.5.3
Mail 0.6.4
Notes 2.2.0
Tasks 0.9.5

**The content of config/config.php:**

<details>

  'dbtype' => 'mysql',
  'version' => '11.0.3.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'defaultapp' => 'apporder',
  'maintenance' => false,
  'debug' => false,
  'theme' => '',
  'loglevel' => 2,
  'app.mail.imaplog.enabled' => true,
  'app.mail.smtplog.enabled' => true,

```
</details>

#### Client configuration
**Browser:** Firefox 52

**Operating system:** Windows 7

#### Logs
##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>

------------------------------
>> Wed, 10 May 2017 23:44:11 +0000
>> Connection to: imap://ssl0.ovh.net:993/
>> Server connection took 0.0227 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot on host 157 ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: NAME@SERVER.PL)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS MULTIAPPEND UNSELECT IDLE CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS QUOTA] Logged in
>> Command 1 took 0.0571 seconds.
C: 2 LIST () "" (*)
S: * LIST () "." "INBOX"
S: * LIST () "." "INBOX.Drafts"
S: * LIST () "." "INBOX.INBOX.Junk"
S: * LIST () "." "INBOX.INBOX.Trash"
S: * LIST () "." "INBOX.INBOX.Sent"
S: * LIST () "." "INBOX.INBOX.Drafts"
S: * LIST () "." "INBOX.Sent"
S: 2 OK List completed.
>> Command 2 took 0.0038 seconds.
C: 3 LIST () "" (INBOX INBOX.Drafts INBOX.Sent INBOX.INBOX.Drafts INBOX.INBOX.Junk INBOX.INBOX.Sent INBOX.INBOX.Trash) RETURN (STATUS (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN))
S: * LIST () "." "INBOX.Sent"
S: * STATUS "INBOX.Sent" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1400274171 UNSEEN 0)
S: * LIST () "." "INBOX.Drafts"
S: * STATUS "INBOX.Drafts" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1400274170 UNSEEN 0)
S: * LIST () "." "INBOX"
S: * LIST () "." "INBOX.Drafts"
S: * STATUS "INBOX.Drafts" (MESSAGES 0 RECENT 0 UIDNEXT 6 UIDVALIDITY 1400274174 UNSEEN 0)
S: * LIST () "." "INBOX.INBOX.Junk"
S: * STATUS "INBOX.INBOX.Junk" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1400274172 UNSEEN 0)
S: * LIST () "." "INBOX.INBOX.Trash"
S: * STATUS "INBOX.INBOX.Trash" (MESSAGES 21 RECENT 3 UIDNEXT 22 UIDVALIDITY 1400274173 UNSEEN 0)
S: * LIST () "." "INBOX.INBOX.Sent"
S: * STATUS "INBOX.INBOX.Sent" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1400274171 UNSEEN 0)
S: * LIST () "." "INBOX.INBOX.Drafts"
S: * STATUS "INBOX.INBOX.Drafts" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1400274170 UNSEEN 0)
S: * LIST () "." "INBOX.Sent"
S: * STATUS "INBOX.Sent" (MESSAGES 1 RECENT 0 UIDNEXT 2 UIDVALIDITY 1400274175 UNSEEN 0)
S: 3 OK List completed.
>> Command 3 took 0.017 seconds.
C: 4 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 18 RECENT 0 UIDNEXT 39 UIDVALIDITY 1400274169 UNSEEN 0)
S: 4 OK Status completed.
>> Command 4 took 0.002 seconds.
C: 5 LOGOUT
S: * BYE Logging out
S: 5 OK Logout completed.
>> Command 5 took 0.0024 seconds.
------------------------------
>> Wed, 10 May 2017 23:44:12 +0000
>> Connection to: imap://ssl0.ovh.net:993/
>> Server connection took 0.0175 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot on host 157 ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: NAME@SERVER.PL)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS MULTIAPPEND UNSELECT IDLE CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS QUOTA] Logged in
>> Command 1 took 0.0547 seconds.
C: 2 EXAMINE INBOX
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 18 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1400274169] UIDs valid
S: * OK [UIDNEXT 39] Predicted next UID
S: * OK [HIGHESTMODSEQ 1] Highest
S: 2 OK [READ-ONLY] Select completed.
>> Command 2 took 0.0025 seconds.
C: 3 UID SORT RETURN (ALL COUNT) (DATE) US-ASCII UNDELETED
S: * ESEARCH (TAG "3") UID ALL 2,4:8,10:11,16,18:20,33:38 COUNT 18
S: 3 OK Sort completed (0.000 secs).
>> Command 3 took 0.0015 seconds.
C: 4 UID FETCH 2,4:8,10:11,16,18:20,33:38 (ENVELOPE FLAGS RFC822.SIZE INTERNALDATE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (IMPORTANCE LIST-POST X-PRIORITY CONTENT-TYPE)])
emails here
S: 4 OK Fetch completed.
>> Command 4 took 0.0895 seconds.
C: 5 LOGOUT
S: * BYE Logging out
S: 5 OK Logout completed.
>> Command 5 took 0.0015 seconds.

</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by pieter-groeneweg** [comment] 2017-05-16 10:47
Bit different here.
All folders show but drafts. It says to have 2 drafts but on click says it cannot find any of them.

**Comment by biva** [comment] 2018-05-03 13:28
Any news on this one? I'm also experiencing issues with OVH ("Sent" folder empty). It was also mentioned in https://github.com/nextcloud/mail/issues/386. @flesser did you file a new issue following @ChristophWurst request?

**Comment by StCyr** [comment] 2019-05-27 14:13
I'd like to resurect this issue.

I'm using nextcloud with OVH and have the same issue.

Here's what my folder structure looks like: 

![image](https://user-images.githubusercontent.com/8179031/58425113-4f484a00-8099-11e9-980e-695b13e26373.png)

I've enabled Horde_Imap_client debugging (as explained in https://dev.horde.org/imap_client/documentation.php) and could get the following logs:

```
>> Mon, 27 May 2019 14:02:33 +0000
>> Connection to: imap://ssl0.ovh.net:993/
>> Server connection took 0.0537 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot on host 64 ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: cyrille@acme.org)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE QUOTA] Logged in
>> Command 1 took 0.1803 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 ENABLE QRESYNC
C: 3 LIST () "" (*)
S: * ENABLED QRESYNC
S: 2 OK Enabled (0.000 + 0.000 secs).
>> Command 2 took 0.0361 seconds.
S: * LIST () "." INBOX
S: * LIST () "." INBOX.Work
S: * LIST () "." INBOX.INBOX.Drafts
S: * LIST () "." INBOX.INBOX.Junk
S: * LIST () "." INBOX.INBOX.Trash
S: * LIST () "." INBOX.INBOX.Sent
S: * LIST () "." INBOX.Drafts
S: * LIST () "." INBOX.Divers
S: * LIST () "." INBOX.Debian
S: * LIST () "." INBOX.Debian.website
S: * LIST () "." "INBOX.Sent Messages"
S: * LIST () "." "INBOX.Deleted Messages"
S: 3 OK List completed (0.000 + 0.000 secs).
>> Command 3 took 0.0384 seconds.
C: 4 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX (MESSAGES 37 UIDNEXT 1677 UIDVALIDITY 1542314601 HIGHESTMODSEQ 4414)
S: 4 OK Status completed (0.000 + 0.000 secs).
>> Command 4 took 0.0146 seconds.
C: 5 STATUS INBOX (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX (MESSAGES 37 UIDNEXT 1677 UIDVALIDITY 1542314601 HIGHESTMODSEQ 4414)
S: 5 OK Status completed (0.000 + 0.000 secs).
>> Command 5 took 0.0138 seconds.
C: 6 STATUS INBOX.Work (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.Work (MESSAGES 21 UIDNEXT 23 UIDVALIDITY 1542314609 HIGHESTMODSEQ 21)
S: 6 OK Status completed (0.000 + 0.000 secs).
>> Command 6 took 0.0214 seconds.
C: 7 STATUS INBOX.INBOX.Drafts (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.INBOX.Drafts (MESSAGES 0 UIDNEXT 179 UIDVALIDITY 1542314602 HIGHESTMODSEQ 534)
S: 7 OK Status completed (0.000 + 0.000 secs).
>> Command 7 took 0.0137 seconds.
C: 8 STATUS INBOX.INBOX.Junk (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.INBOX.Junk (MESSAGES 34 UIDNEXT 35 UIDVALIDITY 1542314604 HIGHESTMODSEQ 69)
S: 8 OK Status completed (0.000 + 0.000 secs).
>> Command 8 took 0.0305 seconds.
C: 9 STATUS INBOX.INBOX.Trash (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.INBOX.Trash (MESSAGES 137 UIDNEXT 138 UIDVALIDITY 1542314605 HIGHESTMODSEQ 124)
S: 9 OK Status completed (0.000 + 0.000 secs).
>> Command 9 took 0.0151 seconds.
C: 10 STATUS INBOX.INBOX.Sent (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.INBOX.Sent (MESSAGES 55 UIDNEXT 56 UIDVALIDITY 1542314603 HIGHESTMODSEQ 58)
S: 10 OK Status completed (0.000 + 0.000 secs).
>> Command 10 took 0.0142 seconds.
C: 11 STATUS INBOX.Drafts (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.Drafts (MESSAGES 6 UIDNEXT 397 UIDVALIDITY 1542314611 HIGHESTMODSEQ 1168)
S: 11 OK Status completed (0.000 + 0.000 secs).
>> Command 11 took 0.0135 seconds.
C: 12 STATUS INBOX.Divers (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.Divers (MESSAGES 62 UIDNEXT 72 UIDVALIDITY 1542314610 HIGHESTMODSEQ 31)
S: 12 OK Status completed (0.000 + 0.000 secs).
>> Command 12 took 0.014 seconds.
C: 13 STATUS INBOX.Debian (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.Debian (MESSAGES 65 UIDNEXT 66 UIDVALIDITY 1542314608 HIGHESTMODSEQ 26)
S: 13 OK Status completed (0.000 + 0.000 secs).
>> Command 13 took 0.0141 seconds.
C: 14 STATUS INBOX.Debian.website (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS INBOX.Debian.website (MESSAGES 10 UIDNEXT 11 UIDVALIDITY 1542314612 HIGHESTMODSEQ 7)
S: 14 OK Status completed (0.000 + 0.000 secs).
>> Command 14 took 0.0268 seconds.
C: 15 STATUS "INBOX.Sent Messages" (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS "INBOX.Sent Messages" (MESSAGES 42 UIDNEXT 47 UIDVALIDITY 1542314606 HIGHESTMODSEQ 54)
S: 15 OK Status completed (0.000 + 0.000 secs).
>> Command 15 took 0.0245 seconds.
C: 16 STATUS "INBOX.Deleted Messages" (MESSAGES UIDNEXT UIDVALIDITY HIGHESTMODSEQ)
S: * STATUS "INBOX.Deleted Messages" (MESSAGES 39 UIDNEXT 1331 UIDVALIDITY 1542314607 HIGHESTMODSEQ 1484)
S: 16 OK Status completed (0.000 + 0.000 secs).
>> Command 16 took 0.014 seconds.
C: 17 LIST () "" (INBOX INBOX.Work INBOX.INBOX.Drafts INBOX.INBOX.Junk INBOX.INBOX.Trash INBOX.INBOX.Sent INBOX.Drafts INBOX.Divers INBOX.Debian INBOX.Debian.website "INBOX.Sent Messages" "INBOX.Deleted Messages") RETURN (STATUS (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN))
S: * LIST () "." INBOX.Drafts
S: * STATUS INBOX.Drafts (MESSAGES 6 RECENT 0 UIDNEXT 397 UIDVALIDITY 1542314611 UNSEEN 0)
S: * LIST () "." INBOX
S: * STATUS INBOX (MESSAGES 37 RECENT 0 UIDNEXT 1677 UIDVALIDITY 1542314601 UNSEEN 1)
S: * LIST () "." INBOX.Work
S: * STATUS INBOX.Work (MESSAGES 21 RECENT 0 UIDNEXT 23 UIDVALIDITY 1542314609 UNSEEN 0)
S: * LIST () "." INBOX.INBOX.Drafts
S: * STATUS INBOX.INBOX.Drafts (MESSAGES 0 RECENT 0 UIDNEXT 179 UIDVALIDITY 1542314602 UNSEEN 0)
S: * LIST () "." INBOX.INBOX.Junk
S: * STATUS INBOX.INBOX.Junk (MESSAGES 34 RECENT 0 UIDNEXT 35 UIDVALIDITY 1542314604 UNSEEN 0)
S: * LIST () "." INBOX.INBOX.Trash
S: * STATUS INBOX.INBOX.Trash (MESSAGES 137 RECENT 0 UIDNEXT 138 UIDVALIDITY 1542314605 UNSEEN 0)
S: * LIST () "." INBOX.INBOX.Sent
S: * STATUS INBOX.INBOX.Sent (MESSAGES 55 RECENT 0 UIDNEXT 56 UIDVALIDITY 1542314603 UNSEEN 0)
S: * LIST () "." INBOX.Drafts
S: * STATUS INBOX.Drafts (MESSAGES 6 RECENT 0 UIDNEXT 397 UIDVALIDITY 1542314611 UNSEEN 0)
S: * LIST () "." INBOX.Divers
S: * STATUS INBOX.Divers (MESSAGES 62 RECENT 0 UIDNEXT 72 UIDVALIDITY 1542314610 UNSEEN 0)
S: * LIST () "." INBOX.Debian
S: * STATUS INBOX.Debian (MESSAGES 65 RECENT 0 UIDNEXT 66 UIDVALIDITY 1542314608 UNSEEN 0)
S: * LIST () "." INBOX.Debian.website
S: * STATUS INBOX.Debian.website (MESSAGES 10 RECENT 0 UIDNEXT 11 UIDVALIDITY 1542314612 UNSEEN 0)
S: * LIST () "." "INBOX.Sent Messages"
S: * STATUS "INBOX.Sent Messages" (MESSAGES 42 RECENT 0 UIDNEXT 47 UIDVALIDITY 1542314606 UNSEEN 0)
S: * LIST () "." "INBOX.Deleted Messages"
S: * STATUS "INBOX.Deleted Messages" (MESSAGES 39 RECENT 1 UIDNEXT 1331 UIDVALIDITY 1542314607 UNSEEN 2)
S: 17 OK List completed (0.000 + 0.000 secs).
>> Command 17 took 0.0235 seconds.
```

Do you see what's going wrong here?

**Comment by StCyr** [comment] 2019-05-27 14:45
Some additional info...

In the list:

```
S: * LIST () "." INBOX
S: * LIST () "." INBOX.Work
S: * LIST () "." INBOX.INBOX.Drafts
S: * LIST () "." INBOX.INBOX.Junk
S: * LIST () "." INBOX.INBOX.Trash
S: * LIST () "." INBOX.INBOX.Sent
S: * LIST () "." INBOX.Drafts
S: * LIST () "." INBOX.Divers
S: * LIST () "." INBOX.Debian
S: * LIST () "." INBOX.Debian.website
S: * LIST () "." "INBOX.Sent Messages"
S: * LIST () "." "INBOX.Deleted Messages"
```

The folder "INBOX.INBOX.Sent" only contains email with the User-Agent header set to "Roundcube Webmail/1.3.8". So, these are emails I've sent from OVH's Webmail application.

So, I believe folders "INBOX.INBOX.Drafts", "INBOX.INBOX.Junk", "INBOX.INBOX.Trash", and "INBOX.INBOX.Sent' are all folders managed by OVH. 

OTH, folder "INBOX.Sent Messages" have their User-Agent header set to "Horde Application Framework 5". So, these are emails sent from nextcloud's mail app.

So, I believe folders "INBOX.Sent Messages", "INBOX.Deleted Messages", and "INBOX.Drafts" have been created by nextcloud's mail app.

The remaining folder (eg: "INBOX.Work", "INBOX.Divers", "INBOX.Debian", "INBOX.Debian.website") are all folders that I've manually created.

**Comment by Thatoo** [comment] 2019-12-04 13:23
Hello, we are unfortunately experimenting the same issue at my workplace.
We have our emails also hosted by OVH and if, between OVH's roundcube and evolution on our computers, there is no problem, our folder on our nextcloud's mail app are completly mixed up as shown by other users below.
How can we help to solve this issue?

**Comment by StCyr** [comment] 2019-12-06 08:42
Hi @nextcloud/mail 

I believe I've made an intersting analysis of the OVH sent/draft/... folders.

Could you please have a look at it and give your opinion on my analysis, and, if possible, how the issue should be fixed?

Best regards,

Cyrille

**Comment by jancborchardt** [comment] 2019-12-09 08:18
@ChristophWurst what do you think?

@StCyr I support you in any way to just make this a simple flat list, as would be expected – not all as subfolders of the inbox. :)

**Comment by ChristophWurst** [comment] 2019-12-20 08:04
> So, I believe folders "INBOX.Sent Messages", "INBOX.Deleted Messages", and "INBOX.Drafts" have been created by nextcloud's mail app.

We create a `Sent` and `Draft` mailbox if necessary. But `Sent messages` doesn't sound like something this app creates.

**Comment by ChristophWurst** [comment] 2019-12-20 08:07
Btw, this OVH thing. Is it possible to get a free account there? Then I can try with my local setup and attach a debugger to get more insights.

**Comment by Thatoo** [comment] 2019-12-20 19:31
ok

**Comment by StCyr** [comment] 2019-12-29 19:06
> Btw, this OVH thing. Is it possible to get a free account there? Then I can try with my local setup and attach a debugger to get more insights.

Hi @ChristophWurst 

I have an account that I don't use which I believe I may give you the credentials. Can we exchange this in private? @daita has my contact details

**Comment by Thatoo** [comment] 2020-01-01 21:10
> Btw, this OVH thing. Is it possible to get a free account there? Then I can try with my local setup and attach a debugger to get more insights.

@ChristophWurst Did you get my email with id and password for an OVH account?

**Comment by ChristophWurst** [comment] 2020-01-07 12:38
Nope, didn't get anything

**Comment by Thatoo** [comment] 2020-01-12 19:03
> Nope, didn't get anything

I sent it the 20/12/2019 à 20:37 to your email *h*******@*i*z*er******rst.*t

**Comment by ChristophWurst** [comment] 2020-01-21 13:33
Thanks, @Thatoo. Got the email but missed it because of the subject.

I can connect to the account. And it does only have one mailbox: `INBOX`.

So, I started a new message. And I can see the drafts request return HTTP200. All good. Then I reload and find the new mailbox `INBOX.Drafts` with the messages.

Then I send the message. All good. I reload the page and there is an `INBOX.Sent`.

The only problem is that Draft and Sent are shows as subfolders of the inbox. That is know, however: https://github.com/nextcloud/mail/issues/2000

**Comment by Thatoo** [comment] 2020-01-23 15:25
If the problem is similar to the Cyrus Server then we can close one of the two issue to concentrate everything on one issue.
This issue (OVH) is much older (11 May 2017) than the Cyrus Server (7 Sep 2019).

**Comment by ChristophWurst** [comment] 2020-01-23 15:31
Yes, makes sense!

Thanks for your help!

**Closed by ChristophWurst** 2020-01-23 15:31 UTC
Labels: 1. to develop, bug
