### ISSUE TITLE
Save Mails in eml Format in Nextcloud Folder

### ISSUE THREAD

**Issue by ralfi** [nextcloud/mail#7847] opened 2022-12-29 09:44 UTC
### Is your feature request related to a problem? Please describe.

Save Mails is atm only available for Download 

### Describe the solution you'd like

It would be helpfull to have a mail context menu item to save mail in eml format in NC folder

### Additional context

Thanks a lot and have a great new year!

**Comment by rebootit** [comment] 2023-01-18 16:49
It would be very usefull for most of my clients that are hôtels, they create a folder for each customer and they save the mails into this folder by downloading them and them uploading them.

**Comment by ChristophWurst** [comment] 2024-10-16 11:48
This is a duplicate of https://github.com/nextcloud/mail/issues/675.

**Closed by ChristophWurst** 2024-10-16 11:48 UTC
Labels: enhancement, 0. to triage
