### ISSUE TITLE
Trashed mails still appears in Inbox

### ISSUE THREAD

**Issue by PVince81** [nextcloud/mail#6933] opened 2022-07-26 09:37 UTC
### Steps to reproduce

1. Every day, get spam emails into Inbox in thunderbird "Hello dear"
2. Get angry at spam and hit the "delete" key to have it trashed
3. 8 days later
4. Open "Inbox" in the mail app

### Expected behavior

Trashed email not visible in inbox

### Actual behavior

Spam email still visible in "Inbox"

<img width="939" alt="image" src="https://user-images.githubusercontent.com/277525/180974725-afad3028-b701-4368-a83b-b24a4c2288e9.png">

<img width="948" alt="image" src="https://user-images.githubusercontent.com/277525/180974975-113bb33f-98ee-41cd-811d-bb309974d1bd.png">

### Mail app version

the one from c.nc.com

### Additional info

this is not the first time it happens, there are 1-2 other such emails

not all of them appear, so maybe there's a race condition of sorts in indexing ?

also strange: I created a "Spam" directory under "Inbox" in thunderbird but it also doesn't appear in the mail app.

maybe the mail app is behind on its cron jobs ?

**Comment by peppinoita** [comment] 2022-08-09 15:02
same issue on my side.
Delete mail from another email client and sometimes the email is still in nx mail inbox without content.

**Comment by nRaecheR** [comment] 2022-08-10 12:58
I think this is a duplicate of #3049

**Comment by ChristophWurst** [comment] 2024-09-19 14:49
Yes it's a duplicate

**Closed by ChristophWurst** 2024-09-19 14:49 UTC
Labels: bug, 0. to triage
