### ISSUE TITLE
Problems getting emails since update to 0.21.0

### ISSUE THREAD

**Issue by HelmutGH** [nextcloud/mail#2396] opened 2019-12-18 21:45 UTC
### Expected behavior
when opening the mail app and selecting the inbox, the mails in the inbox should be displayed

### Actual behavior
there is only an endless Loading messages...
andd in the log I see the following:

TypeError: Return value of OCA\Mail\Address::getEmail() must be of the type string, null returned

/var/www/clients/client0/web2/web/apps/mail/lib/Address.php - line 80: 
OCA\Mail\Address->getEmail()

the Sent Mail folder can be viewed normaly

### Mail app

**Mail app version: 0.21.0

**Mailserver or service: own server running postfix and courier

### Server configuration

**Operating system: Centos 6

**PHP version: 7.2

**Nextcloud Version: 17.0.1

#### Client configuration
**Browser:  Firefox 71.0

**Operating system: Windows 10

**Comment by ChristophWurst** [comment] 2019-12-19 07:25
So this only happens for the inbox? Sounds like a bug triggered by data. Please post the full error log line from nextcloud.log.

**Comment by HelmutGH** [comment] 2019-12-19 09:13
I have 2 mail accounts configured, from the same mail server. One if them removes emails by pop3 access, and there are now only 2 new messages, which are now displayed in mail app. The other account still have all messages in inbox and there the problem still exists. So it is really depending on the data received from the server.
Here the full logline from nextcloud.log:

{"reqId":"Xfs7Aec3Ng37YZyXqlk2iAAAAAM","level":3,"time":"2019-12-19T08:55:29+00:00","remoteAddr":"x.x.x.x","user":"Helmut","app":"index","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages","message":{"Exception":"TypeError","Message":"Return value of OCA\\Mail\\Address::getEmail() must be of the type string, null returned","Code":0,"Trace":[{"file":"\/var\/www\/clients\/client0\/web2\/web\/apps\/mail\/lib\/Address.php","line":80,"function":"getEmail","class":"OCA\\Mail\\Address","type":"->","args":[]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/apps\/mail\/lib\/AddressList.php","line":92,"function":"jsonSerialize","class":"OCA\\Mail\\Address","type":"->","args":[]},{"function":"OCA\\Mail\\{closure}","class":"OCA\\Mail\\AddressList","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/apps\/mail\/lib\/AddressList.php","line":93,"function":"array_map","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/apps\/mail\/lib\/Model\/IMAPMessage.php","line":416,"function":"jsonSerialize","class":"OCA\\Mail\\AddressList","type":"->","args":[]},{"function":"jsonSerialize","class":"OCA\\Mail\\Model\\IMAPMessage","type":"->","args":[]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/lib\/public\/AppFramework\/Http\/JSONResponse.php","line":71,"function":"json_encode","args":[[{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"},{"header":null,"htmlMessage":"","plainMessage":"","attachments":[],"__class__":"OCA\\Mail\\Model\\IMAPMessage"}],1]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\JSONResponse","type":"->","args":[]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\MessagesController"},"index"]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\MessagesController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"3","folderId":"SU5CT1g=","_route":"mail.messages.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"3","folderId":"SU5CT1g=","_route":"mail.messages.index"}]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"3","folderId":"SU5CT1g=","_route":"mail.messages.index"}]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/mail\/api\/accounts\/3\/folders\/SU5CT1g%3D\/messages"]},{"file":"\/var\/www\/clients\/client0\/web2\/web\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/clients\/client0\/web2\/web\/apps\/mail\/lib\/Address.php","Line":64,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"17.0.1.1"}

**Comment by ChristophWurst** [comment] 2019-12-19 09:40
Could you open that mailbox with another IMAP client and inspect the 20 most recent messages? There seems to be at least one where the recipient isn't a typical ´user@domain.tld` address. I think that is where this app fails.

**Comment by HelmutGH** [comment] 2019-12-19 10:58
Sorry, this mailbox is used by more users, I  already took a look with other imap client and saw an email with strange header, but unfortunately this email gets deleted by somebody, so I can not see it anymore and I don't remember what exactly was strange in the header, but as far as I remember, something which should be there was empty. Sorry that I can not give you more information now.
Best regards, Helmut

**Comment by ChristophWurst** [comment] 2019-12-19 12:21
Okay, no worries, Helmut. I will close this ticket then because without the email we can't reproduce or fix the problem.

Please let us know if this ever occurs again!

**Closed by ChristophWurst** 2019-12-19 12:21 UTC
Labels: 0. to triage, bug, regression
