### ISSUE TITLE
Umlaute are not rendered correctly anymore at outgoing e-mails

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/mail#7589] opened 2022-11-14 12:07 UTC
### Steps to reproduce

Write email with German umlauts  in html and send it to exchange.
respond to the email from exchange / outlook.
See how they are encoded incorrectly in the outgoing emails

### Expected behavior

ä,ö,ü and other Umlaute will be sent correctly as done before in previouse versions

### Actual behavior

Renders umlaute wrong / broken:

Gerne kÃ¶nnen wir ein BeratungsgesprÃ¤ch vereinbaren in dem wir die offenen Fragen und Punkte und wenn Sie mÃ¶chten auch die klÃ¤rung durchgehen.

### Mail app version

 2.1.0

### Mailserver or service

self hosted (no issues sending through other clients such as outlook or thunderbird)

### Operating system

Linux

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

**Comment by miaulalala** [comment] 2022-11-14 12:09
Duplicate of https://github.com/nextcloud/mail/issues/7497

**Closed by miaulalala** 2022-11-14 12:09 UTC
Labels: bug, 0. to triage
