### ISSUE TITLE
encrypt password.

### ISSUE THREAD

**Issue by gurussia** [nextcloud/mail#795] opened 2018-02-21 09:37 UTC
Hi guys.

The other day, user try check his e-mail and it day him no plain password accepted. User can check his e-mail with android client when he enable encrypt password.

**Comment by ChristophWurst** [comment] 2018-02-21 09:49
Hi!

Thank you for your report. It looks like your report is missing some important sections of your [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md). Please complete it so that we get a better understanding of your setup and the problem to be able to fix the issue. What are the steps to reproduce your problem?

Passwords are encrypted by default. There is no option to enable password encryption. Also, what Android client are you talking about? There is no Android client for Nextcloud mail.

Thank you.

**Comment by gurussia** [comment] 2018-02-25 19:47
lets try make it simple, becouse some developers don't make it simple.

Now in the history of nextcloud, it creata nextcloud mail application, to century 21 it arrive nextcloud mail applications. So when nextcloud mail application is enabled it the upper it comment nextcloud mail. So, when user see it he press on nextcloud mail application and tell himself " Wowwww i can sync all my e-mail " So he go to nextcloud mail application and he write everything to be secured. Now when he press connect or accept, it comment error: So in log it comment: No plain password... Like i say there is developers who don't want to make it simple, so why peoples who write this issue need to write it simple. Now there is issue : nextcloud mail application don't encrypt password. Nextcloud mail application send plain text password,  so ChristophWurst  don't try lie me. Maybe i will not try write more to nextcloud. nextcloud in general is good program, but it lack developers TELL ALL THE TRUE. include nextcloud send data to nextcloud servers... when it is explicity tell don't send data to nextcloud... necloud xmm application client has BUGS and they developers don't want to SOLVE it, becouse they can't repoduce it. But i solve it. Why should i tell the developers the answer. When marcel if i remember from xmpp he don't want to move his ass and make decent manuals or other peoples from nextclouds... Nextcloud is good program, but there is developers who will break nextcloud. So i have more things to do. include nextcloud don't work with php7.2 i post photos and morris comment me it is normal AND THIS IS LIE. in nextcloud circle app there is bugs and developers don't want to move they ass. So i will not help.

And i don't acceput your Thank you.

DO peoples need to thank someone when they want to kill them. Do peoples need to thank developers who try try comment we are improving every time program and in the meantime they try to see how to implement some spying broken bug and with every new version it broke, or much memory. Include i just remember, how i say in nextcloud xmpp application. When nextcloud xmpp application is enabled, nextcloud server is working slow, if you intent send one simply . " Yes one simply. "dot" "  you have to wait from 2 min. to 5 min. And it is not nextcloud has been bad installed How i say i solve it and the culpit of THIS are bad developers.

Now go fast and close this issue becouse peoples don't need to see that in real nextcloud some developers are bad. But don't worry i will make backup of this issue, becouse there will be more peoples who will complaint and answer of nextcloud will be sorry, thank you, it your fault and etc...

**Comment by rullzer** [comment] 2018-02-25 20:24
@gurussia this is no way to respond. All @ChristophWurst did was ask for more information. If you can't be civil don't expect people to fix bugs you encounter.

I'll close this issue as you apparently refuse to provide the requested information and to fill out the issue tempalte.

**Closed by rullzer** 2018-02-25 20:24 UTC
Labels: 0. to triage, needs info

**Comment by ChristophWurst** [comment] 2018-02-26 09:52
I've no idea why this escalated this way, but as @rullzer mentioned, this is a completely inappropriate message.

Please take a look at https://nextcloud.com/code-of-conduct/.

I'm locking this ticket now.
