### ISSUE TITLE
None to be translated

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/mail#1865] opened 2019-07-19 12:47 UTC
There are no words to translate in Transifex:
```
inbox
Select option
List is empty
Forward
```
1. Inbox:
![obraz](https://user-images.githubusercontent.com/47037905/61535828-813fb200-aa33-11e9-814a-043610170cbb.png)
---
![obraz](https://user-images.githubusercontent.com/47037905/61538609-0b8b1480-aa3a-11e9-8879-352e54332a40.png)

2. New message:
![obraz](https://user-images.githubusercontent.com/47037905/61535707-3b82e980-aa33-11e9-8ef4-069d8d71dd8b.png)
---
![obraz](https://user-images.githubusercontent.com/47037905/61535871-9b799000-aa33-11e9-91d9-ed18ef3687f6.png)

3. Reading the message:
![obraz](https://user-images.githubusercontent.com/47037905/61536058-07f48f00-aa34-11e9-86d1-1f80fa9c6f81.png)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.15.1

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
16.0.3

**Comment by ChristophWurst** [comment] 2019-07-30 09:15
Edit to https://github.com/nextcloud/mail/blob/866ebaecf2e16b2072ed5036473860b52d37798e/src/components/Message.vue#L32 to `:value="t('mail', 'Forward')"` and submit a PR ;-)

`inbox` is the actual ID of the IMAP folder. nothing to translate here.

the rest is caused by https://github.com/nextcloud/nextcloud-vue, please report it there

**Comment by ChristophWurst** [comment] 2019-12-17 16:41
> to `:value="t('mail', 'Forward')"` and submit a PR ;-)

Fixed by https://github.com/nextcloud/mail/pull/1774

**Closed by ChristophWurst** 2019-12-17 16:41 UTC
Labels: 0. to triage, bug
