### ISSUE TITLE
Configurable default for email classification

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6390] opened 2022-05-09 18:31 UTC
### Is your feature request related to a problem? Please describe.

As an admin I might not want my users to use email classification by default. E.g. because it causes additional server load, or because it doesn't fit the user's email handling.

### Describe the solution you'd like

Add a configuration option that makes the feature opt-in instead of opt-out.

By default, classification [should still be on](https://github.com/nextcloud/mail/issues/6482#issuecomment-1129149201).

### Describe alternatives you've considered

N/a

### Additional context

Ref https://github.com/nextcloud/mail/issues/5260

**Comment by tobox** [comment] 2022-05-09 21:38
I disabled the feature for all my users in the DB a long time ago. I just recently found out that the 2 new users that were added after that were always wondering who was messing with their emails, as all other users had no problems. I would very much appreciate the feature request!

**Comment by Sierrol1** [comment] 2022-06-23 09:01
Hey tobox, can u tell us the DB where u made the changes. I tried to find the entry in it but i didn't.
This feature is a real showstopper for any updates at our company. and disable it globally would be a huge improvement.

**Comment by tobox** [comment] 2022-06-23 09:23
By looking at the mysql_history file, I think I iterated through all users an set the following for each user:

`insert into oc_preferences values("REPLACE_WITH_USERNAME","mail","tag-classified-messages","false");                                                                                                                                              
`

**Comment by m-a-v** [comment] 2023-05-29 20:44
Crazy idea to activate such a "feature" as default. Took quite a while to detect the root cause why Thunderbird was tagging everything as important ...

**Comment by damnms** [comment] 2023-12-22 10:26
yeah, crazy is it. i mean, if one has to active it, he knows what he is doing. but once this crazy thing runned automatically without explizit activating it, hundreds of emails are tagged as important, even if they are not :X

is there any way how to disable this ~~bug~~ feature on a complete instance? none of my few users want this, i am absolutely sure. they would go nuts if suddenly many emails are flagged as important, without doing anything.

**Comment by Routhinator** [comment] 2024-01-19 18:26
This issue needs a way, way higher priority level. This feature is not well developed, the classification is poor and it messes up potentially 1000s of emails for users and admin that then need to be fixed. 

We'd really like to use the mail app as it integrates with the calendar and storage, but this feature is a deal breaker. It should be off by default and opt-in until it has actually been fleshed out properly. 

There are other areas where the app could be improved instead of trying to compete with Gmails priority inbox (a feature most of our users disable in Gmail or moved away from Gmail from _because_ it can be just as bad at determining importance) - this should be a stretch goal feature and not a main focus for the team. For example the app currently cannot properly display folder structure in IMAP in it's sidebar, so if you have shared mailboxes you lose the context of which account owns all the ambiguous "inbox" folders.. something so simple. And here we are on the AI hype train instead...

**Comment by damienvancouver** [comment] 2024-04-23 01:16
The issue isn't so much whether you are a fan of Priority Inbox, but that by marking messages as "Important" on the IMAP server, Nextcloud is breaking them in other IMAP clients.  

 I get hundreds of emails a day in my job as a netadmin and I read my emails in Thunderbird becuase I do not like webmail. But I have Nextcloud Mail hooked up so that I can see my mail and use webmail in my nextcloud if I have to.   The end result of that is that 9 out of 10 messages are marked Important in my Thunderbird, including all sorts of automated messages that aren't in any way important (while other actually important emails from humans are left non-important)..  

This completely wrecks the usability of thunderbird (and other imap clients).  People shouldn't be forced to only use Nextcloud Mail, it's IMAP, they might have a variety of clients/devices hooked up.

If Nextcloud Mail were to instead store its data locally about which messages it figures are which category it would be fine and not a bug.  But instead it swerves outside its lane and adds the Important tag on the IMAP server, overloading that tag's purpose for its own uses, which breaks all other IMAP clients!

Is that not a bug???   Couldn't NC Mail be refactored to locally classify messages by Msg-ID or something like that using the Nextcloud database or object cache, and not change priority in IMAP unless the end user changes the message priority?

**Comment by damnms** [comment] 2024-04-23 08:00
my 2 cent: get something other than nextcloud. i dropped the project "migrating to nextcloud" because of those thingens. feels way to alpha/beta/experimental for me, nothing a company needs. it also seems no one of the dev's cares about this bug. reminds me of the "what the customer wanted" meme

**Comment by ChristophWurst** [comment] 2024-04-23 08:56
> it's IMAP, they might have a variety of clients/devices hooked up

This was the point. The feature should be interoperable across clients. If you mark a message as important, it should show as important on all other clients too.

**Comment by damnms** [comment] 2024-04-23 09:12
@ChristophWurst its not the job of nextcloud to decide what is important or not. If someone manually marks an email as important, thats ok when all imap clients show it then as important. But again: its not the job of nextcloud to overwrite the importance (or unimportance) of emails. nextcloud will never ever 100% safely know if something is important or not. on my side, it was about 100 emails that were automaticaly set as important which were absolutely unimportant (automated emails). and important emails (the sender marked it as important) suddenly were not important anymore. just dont do that (imho).

**Comment by ttmooney** [comment] 2024-04-23 09:16
All —Why not just include an admin option to shut off the classification system? I would switch it off, but some would not.I run a filter now to remove tags in the inbox.TSent from my iPadOn 23 Apr 2024, at 10:13, damnms ***@***.***> wrote:﻿
@ChristophWurst its not the job of nextcloud to decide what is important or not. If someone manually marks an email as important, thats ok when all imap clients show it then as important. But again: its not the job of nextcloud to overwrite the importance (or unimportance) of emails. nextcloud will never ever 100% safely know if something is important or not. on my side, it was about 100 emails that were automaticaly set as important which were absolutely unimportant (automated emails). and important emails (the sender marked it as important) suddenly were not important anymore. just dont do that (imho).

**Comment by damienvancouver** [comment] 2024-04-23 16:46
> All —Why not just include an admin option to shut off the classification system? 

because breaking all other IMAP clients is a bug, and this fix still leaves it defaulted on for new installs and so we are sending out buggy code as default-enabled.  that's ridiculous!

The bikeshed war over whether or not classification system should be on or off by default is a different issue than the butg where the classification wrecks all other email clients.

I think we should file a new bug to that respect, Mail needs to store its classification internally and not overide the Impotant tag on the IMAP server.  IT has no business doing so in an automated fashion, that is in fact vendor lockin which is supposed to be what Nextcloud avoids.

Thoughts?  Should I post this stuff as a bug?   Not the same as this issue, which discusses the default on/off (I know which default I will be choosing!)

**Closed** 2024-04-30 10:09 UTC
Labels: enhancement, 3. to review
