### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#5318] opened 2021-07-12 09:44 UTC
### Expected behavior
Autocomplete should work when I type `company`. It used to work in the past weeks.

### Actual behavior
Autocomplete doesn't happen and the request to `/apps/mail/api/autoComplete?term=company` seems to never finish.
![Screenshot 2021-07-12 at 11 42 47](https://user-images.githubusercontent.com/878997/125266766-6f353900-e306-11eb-8507-f29a7cceb288.png)

### Mail app

c.nc.c

#### Client configuration
**Browser:** Safari 14.1

**Operating system:** macOS

**Comment by ChristophWurst** [comment] 2021-07-12 09:47
it works for me. the request is answered promptly and I get the expected result. @GretaD @miaulalala can you reproduce?

**Comment by GretaD** [comment] 2021-07-12 10:07
I cannot reproduce it either, but sometimes it takes 1-2 seconds to show a result if my inbox is synchronizing.

**Comment by miaulalala** [comment] 2021-07-12 10:51
Also working for me, same as for greta - sometimes a bit sluggish but it returns the proper results.

**Comment by miaulalala** [comment] 2021-07-12 10:54
> Client configuration
> Browser: Safari 14.1
>
> Operating system: macOS

guess I'll get out my mac then

**Comment by miaulalala** [comment] 2021-07-12 11:12
Safai works as well.

**Comment by LukasReschke** [comment] 2021-07-12 12:06
Maybe this is just related to general server slowness? I also encounter 45s wait times on other requests. (e.g. https://github.com/nextcloud/spreed/issues/5990)

**Comment by ChristophWurst** [comment] 2021-07-12 12:08
Could it be too many requests? Do you have many tabs open for the same domain @LukasReschke? IIRC browser only allow like 8-10 connections per domain at a time.

**Comment by LukasReschke** [comment] 2021-07-12 12:09
I have 2 tabs open 🙈

**Comment by miaulalala** [comment] 2021-07-19 08:46
@LukasReschke has closing the other tabs resolved you issue?

**Closed** 2021-08-05 13:17 UTC
Labels: 0. to triage, bug
