### ISSUE TITLE
"e.label is undefined" when selecting a contact

### ISSUE THREAD

**Issue by trendzetter** [nextcloud/mail#939] opened 2018-06-12 08:32 UTC
## Steps to reproduce
1. Open nextcloud contacts
2. Select a contact
3. Click on the mail icon

## Expected behaviour
Either a new mail should be created with the selected contact in to:
Or a search should be performed for mails from and to that contact.

## Actual behaviour
The mail section opens, an error appears on top **"Error: e.label is undefined. Report a bug.**

## Error
```
e.label is undefined
r</</<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:75:21326
S/</<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:135865
S/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:135735
r</<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:75:21278
main@https://xyz.mydomain.tld/apps/mail/js/build/build.js:246:144906
u@https://xyz.mydomain.tld/apps/mail/js/build/build.js:246:150202
r@https://xyz.mydomain.tld/apps/mail/js/build/build.js:246:150324
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:104438
_renderHtml@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:106010
_renderTemplate@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:105877
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:105652
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
rt@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:97081
show@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:98154
showChildView@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:104088
onShowComposer@https://xyz.mydomain.tld/apps/mail/js/build/build.js:283:10046
v@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:155000
g@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:154809
h@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:152755
s</o.Backbone</u.trigger@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:154702
_handleMailto/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:201:2991
```

Loglevel is 0 but no error concerning mail to be found. I am willing to check the log settings if there is more info you need.

**Comment by ChristophWurst** [comment] 2018-06-18 09:36
Looks like a duplicate of https://github.com/nextcloud/mail/issues/930.

Thanks for your report!

**Closed by ChristophWurst** 2018-06-18 09:36 UTC

**Comment by ChristophWurst** [comment] 2018-06-18 09:37
Note to myself: we need some mechanism to read source maps on the client-side to decipher that stack trace :see_no_evil:
