### ISSUE TITLE
Date and time issue with our mails

### ISSUE THREAD

**Issue by CamZie** [nextcloud/mail#3386] opened 2020-07-24 08:30 UTC
Hello,

I would like to report our issue with the date and time of our mails when using the Mail app on our Nextcloud 18 installations.

**Actual behaviour**
The dates are showing wrong like either very very old like from the 19's or from the future like .e.g 2036 etc. On our webmail the dates are showing correctly.

**Nextcloud versions currently tested:** 18.0.6 and 18.0.7
**Mail app version** 1.4.1

**Comment by GretaD** [comment] 2020-07-24 10:32
Hello @CamZie,  can you please send us any error shown on your web console when you open Nextcloud mail app, and the log from nextcloud.log. 
I tried to reproduce it on my 18.6 and everything looks fine there.

**Comment by CamZie** [comment] 2020-07-24 14:36
@GretaD Please find below the web console logs when the app has been accessed:
```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).                      global.js:10
```
There seems to be no logs on Nextcloud regarding this.

**Comment by ChristophWurst** [comment] 2020-08-10 10:51
Could you inspect the table `oc_mail_messages`, try to find the message by subject and see what `sent_at` is set to?

**Comment by CamZie** [comment] 2020-08-17 06:59
@ChristophWurst as requested you can find below some examples of the emails showing the wrong date:

The first one is 14 years old and the second example is 8 years in the future

<details>
<Summary> oc_mail_messages examples </Summary>

```
*************************** 2. row ***************************
                id: 83867
               uid: 375
        message_id: **REMOVED***
        mailbox_id: 740
           subject: **REMOVED***
           sent_at: 1163581991
     flag_answered: 0
      flag_deleted: 0
        flag_draft: 0
      flag_flagged: 0
         flag_seen: 1
    flag_forwarded: 0
         flag_junk: 0
      flag_notjunk: 0
  flag_attachments: 0
    flag_important: 0
structure_analyzed: 1
      preview_text: 
        updated_at: 1597646973
*************************** 407. row ***************************
                id: 96273
               uid: 411
        message_id: ***REMOVED***
        mailbox_id: 740
           subject: **REMOVED***
           sent_at: 1846463571
     flag_answered: 0
      flag_deleted: 0
        flag_draft: 0
      flag_flagged: 0
         flag_seen: 1
    flag_forwarded: 0
         flag_junk: 0
      flag_notjunk: 0
  flag_attachments: 0
    flag_important: 1
structure_analyzed: 1
      preview_text: 
        updated_at: 1597646811
```
</details>

**Comment by ChristophWurst** [comment] 2020-08-17 07:20
Thanks for that info, @CamZie. So the database values are already off, hence it's some issue with reading the data from IMAP or a conversion on the way. Our code uses Horde to get the timestamp https://github.com/nextcloud/mail/blob/e380adfc02d1cbec1bc88c68327be713b026adbc/lib/Model/IMAPMessage.php#L458.

Could you inspect the source of those two messages to get the headers, most importantly the `date`? 
![Bildschirmfoto von 2020-08-17 09-19-38](https://user-images.githubusercontent.com/1374172/90368749-dbfa7180-e06a-11ea-8557-db2c9a5d5894.png)

**Comment by CamZie** [comment] 2020-08-17 09:05
@ChristophWurst Thank you as well for the information.

We had a look on the headers of the two mails using the mail app, and the "date" is showing correctly. So the issue seems to be the conversion on the way.

**Comment by ChristophWurst** [comment] 2020-08-17 09:08
Could you post the raw values?

**Comment by CamZie** [comment] 2020-08-17 13:14
The mail from 14 years ago
`Date: Thu, 25 Jun 2020 12:16:56 +0200`

The mail 8 years in the future
`Date: Fri, 07 Aug 2020 16:53:23 +0000`

**Comment by GretaD** [comment] 2021-07-13 09:31
Hi @CamZie can you still reproduce this error? We had many releases since you reported this bug.

**Comment by ChristophWurst** [comment] 2022-02-28 10:03
> The mail 8 years in the future
> Date: Fri, 07 Aug 2020 16:53:23 +0000

I've created a message with that date and it showed up correctly.

**Comment by ChristophWurst** [comment] 2024-02-26 09:57
Closing as not reproducible as per above

**Closed by ChristophWurst** 2024-02-26 09:57 UTC
Labels: bug, 0. to triage
