### ISSUE TITLE
Popup window disappears after ca. 5 sec

### ISSUE THREAD

**Issue by beccon4** [nextcloud/mail#8980] opened 2023-10-20 07:48 UTC
### Steps to reproduce

1. In Mail klick on the ... menu and select something i.e. "view source"
2. the windows with the source code appears for ca. 5 seconds
3. the window disappears with no trace 

### Expected behavior

the windows stays open until I close it myself

### Actual behavior

This is a more general issue as it also occures when I try to import an incoming calendar event in vain. (please see #8458 and #8335) I tried both Firefox and Chromium on an Ubuntu 22.04 desktop. And it touches another issue #5984 where I tried to retrieve data from a html email which Mail could not display properly.

Keeping the mouse pinter within the window does not help. THe issue occurs in the following ... menu items
- create calendar event
- create task
- view source
- edit key words
but not in 
- create as new message

### Mail app version

3.4.3

### Mailserver or service

Host Europe

### Operating system

Ubuntu 22.04

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment] 2023-10-20 08:04
Duplicate of https://github.com/nextcloud/mail/issues/8753

**Comment by JohannesGGE** [comment] 2023-10-26 16:15
Fixed by https://github.com/nextcloud/mail/issues/8753

**Closed by JohannesGGE** 2023-10-26 16:15 UTC
Labels: bug, 0. to triage
