### ISSUE TITLE
Not everything is displayed in the preferred language

### ISSUE THREAD

**Issue by MeCias** [nextcloud/mail#1232] opened 2018-10-25 08:42 UTC
Hello,

another thing that I noticed is that not all of the displayed information are in the language that my user profile is set up. In my case British English is my preferred language even if I stay in Germany. 

![annotation](https://user-images.githubusercontent.com/4476171/47487183-3dbc6c80-d842-11e8-83cb-8083e0105303.jpg)

![annotation2](https://user-images.githubusercontent.com/4476171/47487284-6cd2de00-d842-11e8-85d5-53488674d558.jpg)

**Comment by nickvergessen** [comment] 2018-11-06 14:38
Well, how do you generate those timestamps?
I guess some plugin/module is not getting the language correctly.

**Comment by ChristophWurst** [comment] 2018-11-07 10:49
I think it just uses the `moment` magic from server.

Template is at https://github.com/nextcloud/mail/blob/2156b57761826ce3ed3ccea41c6783bbe0bb7ab0/js/templates/message-list-item.html#L36-L40

@nickvergessen this is low prio as it's the old code base so this might be resolved already.

**Comment by ChristophWurst** [comment] 2018-11-07 10:50
https://github.com/nextcloud/mail/blob/2156b57761826ce3ed3ccea41c6783bbe0bb7ab0/js/templatehelpers/relativeModifiedDate.js generates the relative modified date.

**Comment by MeCias** [comment] 2019-05-09 05:26
Just updated to NC 16 and the mail app 0.14.0. The time stamp is still German even if the preferred language is English.

**Comment by ChristophWurst** [comment] 2019-05-09 07:10
This will be fixed via https://github.com/nextcloud/server/pull/14784

**Comment by MeCias** [comment] 2019-11-05 07:38
It is still an open issue and the fix that is available not implemented in the recent NC version.

**Comment by ChristophWurst** [comment] 2019-11-05 09:38
https://github.com/nextcloud/mail/issues/1232#issuecomment-490772194

**Comment by wiswedel** [comment] 2020-01-02 06:36
duplicate of https://github.com/nextcloud/server/issues/15457?

**Comment by jancborchardt** [comment] 2020-02-27 12:31
Yep, closing as duplicate of server issue https://github.com/nextcloud/server/issues/15457

**Closed by jancborchardt** 2020-02-27 12:31 UTC
Labels: 1. to develop, blocked, bug
