### ISSUE TITLE
PHP max-version is 7.2

### ISSUE THREAD

**Issue by jernst** [nextcloud/mail#1468] opened 2019-01-14 21:32 UTC
On Arch, and thus UBOS, we are now on PHP 7.3, so we can't run this app any more.

Current PHP upstream is 7.3.1. http://www.php.net/ChangeLog-7.php

**Comment by ChristophWurst** [comment] 2019-01-15 07:33
Duplicate of https://github.com/nextcloud/mail/issues/1425. See #1323

**Closed by ChristophWurst** 2019-01-15 07:33 UTC
Labels: 0. to triage, bug
