### ISSUE TITLE
Sending to groups [$45]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#41] opened 2016-09-05 11:15 UTC
Typing a group name into the »to« field should autocomplete from the »Groups« in the Contacts app as well. This would allow you to write emails to your »Sports« or »Work« groups quickly.

cc @aspdye @Toub @virgilekat @ttjaden since you requested that. :)

**Comment by ttjaden** [comment] 2016-09-05 12:02
Thanks @jancborchardt for this news. Maybe you have a little extra-information for me, 'cause I'm confused about the owncloud/nextcloud thing:
1. Will the Mail-App be the same for owncloud and nextcloud?
2. I tested the feature, but in mail 0.5.3 the autocomplete doenst work with the groups from the contacts apps.
Would be great if you guys really can make this work! :-)

**Comment by jancborchardt** [comment] 2016-09-05 14:52
@ttjaden the main contributors to the Mail app (@ChristophWurst is the main maintainer) moved to Nextcloud as the more community-oriented project. Hence we don’t really test on ownCloud anymore and while the app might run there it’s not tested. So we decided to also move/fork the repository.
Same happened btw to the News and Gallery apps as the maintainers moved. And likely the Calendar is going to move soon too.

Regarding the feature, it’s not there yet. This is just an issue tracking the request. :) Also this is a community project so any contribution is welcome! :rocket:

**Comment by Ecphrasis** [comment] 2016-12-25 04:14
Any news of this missing feature ? ;) Actually, rainloop and Mail don't allow to send mails to a group and it's a very missing feature...

**Comment by lafrech** [comment] 2017-01-13 09:10
I'm looking for a collaborative work platform and I'm thinking of using NextCloud. AFAIK, there is no support for mailing lists, already.

The "send to group" feature could provide that if it actually sent to `sports@groups.my_nextcloud.tld` rather than explicitly expanding to the group members.

For a complete mailing list support, it should also be able to receive e-mails to `sports@groups.my_nextcloud.tld` from the outside and redirect them.

I'm not sure what the best strategy would be. Maybe mailing lists should be a separate Nextcould app. And maybe it would be better to interface an existing solution like Mailman than reinventing the wheel.

Sorry if I'm off-topic. I thought this feature request might arise at some point, so rather mention it before the "sending to groups" feature reaches an advanced conception stage.

**Comment by jancborchardt** [comment] 2017-01-14 16:06
So @Ivansss @nickvergessen @schiessle @LukasReschke who of you implemented this in the Spreed video calls app? :) Basically here it would only be:
- adding the contact groups to the autocomplete dropdown
- populating the »to« (or »cc« field, depending on where the group name was typed) with all people from that group

**Comment by alexanderdd** [comment] 2017-09-18 17:22
yep, missing this feature too.

**Comment by nickvergessen** [comment] 2017-09-19 08:28
Currently we ping the Sharees endpoint:
https://github.com/nextcloud/spreed/blob/master/js/app.js#L42-L111

That returns users, groups and (maybe for a future feature) circles.
The actual work to get their email addresses has to be done manually.

**Comment by alexanderdd** [comment] 2017-10-06 18:23
I miss this feature every day =(
It has been requested a year ago.

Currently there is no way to send an email to a group. You have to type every member by hand. Kinda defeats the idea of contact groups. I am hoping somebody who knows how to code can put a little energy into this. I would soooo appreciated it ;DD

**Comment by myrho** [comment] 2017-11-23 08:44
I'd give it a shot. Anybody working on this already?

**Comment by ChristophWurst** [comment] 2017-11-23 08:52
@myrho I'm not aware of anybody working on this at the moment. Feel free to dive into this 😉 

Let me know how you want to approach it, so that I can give you early feedback/guidance!

**Comment by myrho** [comment] 2017-11-23 09:53
1. Add a `Service/GroupsIntegration` using `OCP/GroupInterface`
2. Group name is put in the recipient field as is.
3. Let send expand the group name to its users' email addresses on the server side. 

I would no expand the group on the client side since it might be many recipients which would be hard to handle (eg. if user wants to remove the group from the recipients).

Perhaps the group name should be prefixed or wrapped to avoid ambiguity with group names which look like email addresses?

**Comment by ChristophWurst** [comment] 2017-11-23 11:03
> OCP/GroupInterface

A quick look at https://github.com/nextcloud/server/blob/master/lib/public/GroupInterface.php shows that this interface is about Nextcloud groups, not contact groups. Those are different.

**Comment by myrho** [comment] 2017-11-23 11:21
Ok, I just realized that this issue is about groups from the Contacts App not the nextcloud groups. 

Anyway, since autocomplete also searches nextcloud user names besides contacts, shouldn't it - if we add this group search feature - search nextcloud groups too?

**Comment by ChristophWurst** [comment] 2017-11-23 12:05
> Anyway, since autocomplete also searches nextcloud user names besides contacts, shouldn't it - if we add this group search feature - search nextcloud groups too?

Yup, sure. That's the idea behind this. The main *problem* is that it probably requires changes to the Nextcloud server too because it doesn't expose groups right now.

**Comment by jancborchardt** [comment] 2017-11-23 12:37
I know in the original issue it says from the Contacts app, but ideally groups are taken from both Contacts _and_ the user management. :) As people would expect it to work for both if it works for one.

**Comment by myrho** [comment] 2017-11-23 13:25
[OCP/GroupInterface](https://github.com/nextcloud/server/blob/master/lib/public/GroupInterface.php) can't be used to access nextcloud groups?

**Comment by mc9625** [comment] 2017-11-28 11:03
Actually send a message to nextcloud group of users (not only contacts), would be very helpful.

**Comment by myrho** [comment] 2018-02-23 08:33
Ok, I've implemented autocomplete for nextcloud groups so far. 

Please, could someone have a quick look and let me know whether I'm on the right way?
https://github.com/nextcloud/mail/compare/master...myrho:autocomplete-groups

The next steps would be:
* Add autocomplete for Contacts group
* Expand groups to recepients before sending (on server side)

**Comment by ChristophWurst** [comment] 2018-02-23 09:08
@myrho your code looks very good! Could you please submit a pull request? Thanks!

**Comment by myrho** [comment] 2018-02-28 13:54
It seems OCP\Contacts` and `OCP\Contacts\IManager` don't expose a method 
* to get Contacts groups 
* and to get users for a Contacts group 

So I think these need to be implemented for the server first. Am I right?

**Comment by ChristophWurst** [comment] 2018-02-28 14:26
> So I think these need to be implemented for the server first. Am I right?

Yes, you are (https://github.com/nextcloud/mail/issues/41#issuecomment-346601091).

**Comment by BiMeWe** [comment] 2018-03-09 08:10
I'm all for Nexcloud (Core or with an App) to allow **easy on-the-Webserver-Mailing-Lists**. It would be very workgroup oriented to even expand the functionality to (all) group members to **create sub-groups for specific topics** in which only a selection of the parental group is a member and receives emails. 
A further step would be to **integrate it with the Task (&Calendar) App** to combine those functionalities with groups. 
Office365>Planner/Hub gives those/similar functionalities but IMHO not in a very polished and good way yet.

**Comment by alexanderdd** [comment] 2018-03-26 13:58
Wait, this issue is only partly fixed via pull request https://github.com/nextcloud/mail/pull/810
The implementatuon of contact groups was the actual bug report (scroll up), nextcloud group support was only added later in the discussion.

I am very happy that this is going forward, but we are not there yet. And while I really want to reward @myrho for his work, I don't think it's fair if he gets the full bounty cause the issue is not actually fixed yet. Btw the bounty should be waaaaay higher, if anyone has a dime to spare :-)

**Comment by myrho** [comment] 2018-03-26 14:04
Yes, I agree. This issue is not fixed yet.

**Comment by ChristophWurst** [comment] 2018-03-26 14:10
> I am very happy that this is going forward, but we are not there yet. And while I really want to reward @myrho for his work, I don't think it's fair if he gets the full bounty cause the issue is not actually fixed yet. Btw the bounty should be waaaaay higher, if anyone has a dime to spare :-)

Sorry, my bad. Reopened the issue.

FYI bountysource requires a confirmation about whether the issue has been solved from the people who posted it.

**Comment by floeschie** [comment] 2019-07-16 07:41
Added another 15 US$ at Bountysource. Would like to see this feature as well!

**Comment by alexanderdd** [comment] 2019-09-15 09:10
I just noticed that the TO field recognizes user groups (thanks to @myrho's work), but IMO it should expand to the individual email addresses. Should I create a separate bug report for this, or does it belong here?

**Comment by MrNterra** [comment] 2019-10-03 11:03
Added 40$ at Bountysource, since I would really love to see this feature coming to my NGOs Nextcloud server!

**Comment by dieter-wilhelm** [comment] 2019-12-27 14:37
Added 50 $ at Bountysource, since I think such a feature is indispensible when adminstrating larger communities which are not necessarily nextcloud members.

I don't care if such a feature is implemented as circles or contact groups or even mail app. aliases!

**Closed** 2020-01-16 16:06 UTC
Labels: 1. to develop, bounty, enhancement
