### ISSUE TITLE
Mails deleted from server will not be automatically deleted at mail and cannot be deleted afterwards manually

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/mail#9652] opened 2024-05-17 07:25 UTC
### Steps to reproduce

1. Configure an IMAP Inbox with mail
2. Send 20-30 mails to your inbox
3. Wait till they are avialable in mail
4. delete them on external Mail client
5. Navigate back to Mail
6. Reload
7. Try to delete the mails as they won't dissappear

### Expected behavior

Mails which are deleted from the server are also deleted from mail

### Actual behavior

Mails which are deleted from server keep existing in mail and cannot be manually deleted (screenshot)
![image](https://github.com/nextcloud/mail/assets/17781278/37e96a8c-b6dc-4860-be92-1f2b0ba875c9)

### Mail app version

3.6.1

### Mailserver or service

self hosted imap server

### Operating system

Ubuntu LTS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

**Comment by blacklight** [comment] 2024-05-17 08:22
Sounds like a duplicate of https://github.com/nextcloud/mail/issues/9168, which has been open for a few months.

**Comment by GVLLIFESTYLE** [comment] 2024-05-17 10:09
true story, can be closed

**Comment by violoncelloCH** [comment] 2024-06-24 06:55
duplicate of #9168

**Closed by violoncelloCH** 2024-06-24 06:55 UTC
Labels: bug, 0. to triage
