### ISSUE TITLE
Right column is no longer responsive

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#7323] opened 2022-09-26 19:05 UTC
### Steps to reproduce

1) Open the app
2) Open a thread
3) Open the sidebar if it is not open
4) Resize the browser window to 1517px or less

### Expected behavior

The right column should shrink

### Actual behavior

The right column does not shrink and content overflows

![image](https://user-images.githubusercontent.com/42591237/192359171-add17141-ddd4-469d-8090-4ea91747959e.png)

### Mail app version

latest RC for NC25

**Comment by ChristophWurst** [comment] 2022-09-27 07:09
What? :laughing:

**Comment by szaimen** [comment] 2022-09-27 07:11
It overflows the available space and I cannot scroll sideways...

**Comment by ChristophWurst** [comment] 2022-09-27 07:15
I can reproduce. Reproduction steps and title adjusted to make it clear for others.

**Comment by GretaD** [comment] 2022-09-27 08:29
this should be most probably fixed on nc/vue because i can reproduce it on contacts too. Will check calendar soon

**Closed** 2022-10-02 09:11 UTC
Labels: bug, 3. to review, design, regression
