### ISSUE TITLE
Allow both reply to sender and reply to all

### ISSUE THREAD

**Issue by freekvh** [nextcloud/mail#686] opened 2017-12-22 05:41 UTC
### Steps to reproduce
1. Start typing a reply below an email
2. Hit Reply (for me it's in dutch "Antwoorden")
3. The mail goes to everyone on the list

### Expected behaviour
Reply to the original sender of the email.

### Actual behaviour
The button says reply and not reply to all, by default one should reply only to the original sender.

### Mail app

**Mail app version:** (see apps admin page)
 0.7.6

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**:
Linux

**Web server:**
Nginx

**Database:**
MariaBD

**PHP version:**
7

**Version:** (see admin page)
Nextcloud 12.0.4

**Updated from an older version or fresh install:**
Updated

**Comment by ChristophWurst** [comment] 2017-12-27 07:34
Known issues. Basically it was decided that the default is *reply to all*. I'm not a big fan of it either as it limits certain workflows and two dedicated buttons should be used instead.

**Comment by ChristophWurst** [comment] 2017-12-27 07:38
This is a duplicate of https://github.com/nextcloud/mail/issues/598

**Closed by ChristophWurst** 2017-12-27 07:38 UTC
Labels: 1. to develop, bug, feature parity
