### ISSUE TITLE
Mailbox doesn't open if there's an IMAP folder that cannot be opened

### ISSUE THREAD

**Issue by segdy** [nextcloud/mail#5153] opened 2021-06-10 06:24 UTC
### Expected behavior

Mailbox should always open (and show mails).
IMAP folders that cannot be opened should be ignored (or marked grey, or with a lock or similar, as any other IMAP client does).

### Actual behavior

Mailbox does not open at all. It basically breaks the app completely.

Log message entry:

```
[mail] Error: OCA\Mail\Exception\ServiceException: IMAP error: You do not have adequate permissions to carry out this operation. at <<closure>>

0. /var/www/edward/apps/mail/lib/Service/MailManager.php line 129
   OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {}, OC\AppFramework\ScopedPsrLogger {})
1. /var/www/edward/apps/mail/lib/Controller/PageController.php line 119
   OCA\Mail\Service\MailManager->getMailboxes(OCA\Mail\Account {})
2. /var/www/edward/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Mail\Controller\PageController->index()
3. /var/www/edward/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\PageController {}, "index")
4. /var/www/edward/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\PageController {}, "index")
5. /var/www/edward/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "mail.page.index"})
6. /var/www/edward/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/")
7. /var/www/edward/index.php line 37
   OC::handleRequest()

GET /edward/index.php/apps/mail/
from 53.43.142.171 by user at 2021-06-10T06:14:23+00:00
```

### Mail app

**Mail app version:** 1.9.5 (latest)

**Mailserver or service:** dovecot on Debian (own mail server)

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.27-1~deb10u1

**Nextcloud Version:** 20.0.10 (latest stable)

#### Client configuration
**Browser:** all

**Operating system:** all

**Comment by ChristophWurst** [comment] 2021-06-10 06:33
duplicate of https://github.com/nextcloud/mail/issues/1735, but you seem to be aware of that.

**Closed by ChristophWurst** 2021-06-10 06:33 UTC
Labels: 0. to triage, bug
