### ISSUE TITLE
big amount of recipients are shown badly

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#3893] opened 2020-10-26 08:36 UTC
![grafik](https://user-images.githubusercontent.com/24530680/97150674-c42c2180-176e-11eb-8700-8e96e8f39fc5.png)

**Comment by ChristophWurst** [comment] 2020-10-27 10:21
Duplicate of https://github.com/nextcloud/mail/issues/3743

**Closed by ChristophWurst** 2020-10-27 10:21 UTC
Labels: 0. to triage, bug
