### ISSUE TITLE
Message id field too short.

### ISSUE THREAD

**Issue by noci2012** [nextcloud/mail#3244] opened 2020-06-11 22:06 UTC
### Expected behavior
Just store the values (or truncate them to a reasonable length.

### Actual behavior
A mail message has been seen that had a 291 character messageID (from a Gmail newsgroup).
the Database only allows for 255 characters. 
Altering the column to varchar(512) solved the issue.
OCA\Mail\Exception\ServiceException: Sync failed for 1:xxxxxxxxxxxxxx: An exception occurred while executing 'INSERT INTO `oc_mail_messages` (`uid`, `message_id`, `mailbox_id`, `subject`, `sent_at`, `flag_answered`, `flag_deleted`, `flag_draft`, `flag_flagged`, `flag_seen`, `flag_forwarded`, `flag_junk`, `flag_notjunk`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [10860, "<!&!LgAAAAAAAABT9+\/sIFA8SJAslOm3G8sIAQB5w+hiN\/NDTaiBprnRSqJWAAAASnfKAABGAAAAAAAAAFP37+wgUDxIkCyU6bcbywgHAHnD6GI380NNqIGmudFKolYAAABKd8oAAOgd8kisjBtKnvjDvJVREZ4A5LIqguUAAAAAAAAQAAAAweHh2l1vH0O7lcwe8Y\/8QzMAAABCZXRhbGluZ3NoZXJpbm5lcmluZyAyMDE2MDA0OSBtZXQgZGF0dW0gMzAtMTAtMjAxNgA=@gmail.com>", 11, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6", 1477834496, false, false, false, false, true, false, false, false]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message_id' at row 1

Mail app version: (see apps admin page, e.g. 0.5.3)
1.3.5

Mailserver or service: (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Dovecot internal server

Server configuration
Operating system: (e.g. Debian 8)
Gentoo

Web server: (e.g. Apache, Nginx,...)
Nginx

Database: (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

PHP version: (e.g. 7.0)
7.3

Nextcloud Version: (see admin page, e.g. 13.0.2)
18.0.6

Client configuration
Browser: (e.g. Firefox 48)
Chromium

Operating system: (e.g. Arch Linux)
Gentoo Linux

**Comment by ChristophWurst** [comment] 2020-06-15 06:31
Duplicate of https://github.com/nextcloud/mail/issues/3154, fixed by https://github.com/nextcloud/mail/pull/3164. See https://help.nextcloud.com/t/mail-v1-4-0-ready-for-testing/84227/3 for a prerelease that fixes this.

**Closed** 2020-06-15 06:31 UTC
Labels: bug, duplicate
