### ISSUE TITLE
Scrollbar is overflowing composer modal

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/mail#6272] opened 2022-04-19 15:07 UTC
The new message modal's scoll bar is overflowing the modal content.

**Comment by JuliaKirschenheuter** [comment] 2022-05-05 13:15
@st3iny , @miaulalala , @GretaD could you reproduce it? If yes - i will make a description for this ticket. If not - i will close this one. I can not reproduce it anymore.

**Comment by st3iny** [comment] 2022-05-06 15:26
Yes, I can still reproduce it. Take a look on how the modal looks on Firefox:

![image](https://user-images.githubusercontent.com/1479486/167163344-219e0046-f8f5-48ba-a770-05c6ae058678.png)


This is purely cosmetic and unfortunately can't be fixed easily. We have no real control over the rendering of the scroll bar (the browser does that). I'd say to keep it as is.

---

**PS:** We could draw inspiration from Boostrap. They just add a dedicated footer and header to modals to circumvent this problem. Take a look:

![image](https://user-images.githubusercontent.com/1479486/167163771-d616b0ae-aa2c-473f-a6cf-6f531e54a3eb.png)

**Comment by JuliaKirschenheuter** [comment] 2022-05-10 12:11
Thank you Richard!

> **PS:** We could draw inspiration from Boostrap. They just add a dedicated footer and header to modals to circumvent this problem. Take a look:
> 
> ![image](https://user-images.githubusercontent.com/1479486/167163771-d616b0ae-aa2c-473f-a6cf-6f531e54a3eb.png)


@jancborchardt , @nimishavijay could we move on this way?

**Comment by nimishavijay** [comment] 2022-05-10 12:30
This approach sounds good! Would it be possible to retain the same space above the "From" field even if we use a header? So that in the end it looks like this?

![image](https://user-images.githubusercontent.com/52440189/167628010-79cd7584-1322-43dc-955a-c36f7358df61.png)

**Comment by ChristophWurst** [comment] 2024-07-01 14:27
This longer happens. Only the message body scrolls, not the other elements.

**Closed by ChristophWurst** 2024-07-01 14:27 UTC
Labels: bug, design, 0. to triage, feature:editor
