### ISSUE TITLE
Can't login to E-Mail / Create Account

### ISSUE THREAD

**Issue by TheSkrypt** [nextcloud/mail#3903] opened 2020-10-28 10:28 UTC
### Expected behavior
Can't login to E-Mail / Create Account

### Actual behavior
Request failed with error 500 or Unable to create an account error message

### Mail app

**Mail app version:** 1.5.1

**Mailserver or service:** seznam.cz

### Server configuration

**Operating system**: Ubuntu 20

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.4.11

**Nextcloud Version:** 20.0.1

#### Client configuration
**Browser:* Firefox 81.0.2

**Operating system:** Windows 10

I use PHP7.4 FPM and whatever I do, I can't get the mail plugin to work. It didn't work on Nextcloud 19, it doesn't work on nextcloud 20.

I tried emails under my own domain with SMTP/IMAP of seznam, tried e-mails under the seznam domain and even tried gmail. Nothing works.

**Comment by ChristophWurst** [comment] 2020-10-28 10:29
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by TheSkrypt** [comment] 2020-10-28 10:33
> 
> 
> The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/stable/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

Hi, thanks for the reply.

Now it just shows an internal server error when opening the mail plugin and this is the error it gives:

```
    Code: 0
    Message: explode() expects parameter 1 to be string, null given
    File: /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php
    Line: 110


Trace

#0 /var/www/nextcloud/lib/private/AppFramework/App.php(152): OC\AppFramework\Http\Dispatcher->dispatch()
#1 /var/www/nextcloud/lib/private/Route/Router.php(308): OC\AppFramework\App::main()
#2 /var/www/nextcloud/lib/base.php(1009): OC\Route\Router->match()
#3 /var/www/nextcloud/index.php(37): OC::handleRequest()
#4 {main}
```

**Comment by ChristophWurst** [comment] 2020-10-28 10:37
I'm seeing this issue for the very first time. Does anyhting else on that instance work?

**Comment by TheSkrypt** [comment] 2020-10-28 10:38
Yes, everything else works as usual. Is there any way I can reset the mail plugin completely?

**Comment by TheSkrypt** [comment] 2020-10-28 10:39
Before it just wouldn't connect, but the mail login screen would still show up. Now it doesn't even show up anymore.

**Comment by ChristophWurst** [comment] 2020-10-28 10:55
If you couldn't set up an account there is nothing to reset. No data was created in that case.

**Comment by TheSkrypt** [comment] 2020-10-28 10:59
> 
> 
> If you couldn't set up an account there is nothing to reset. No data was created in that case.


Nevermind, I reseted the mail plugin and now the setup / login screen shows up again.

I've checked the horde_imap.log and it successfully connected. Then I checked the horde_smtp.log and successfully logged in too. 

However, nextcloud.log shows this:
{"reqId":"4FFjk1exTgIMD99gDzmK","level":3,"time":"2020-10-28T11:56:01+00:00","remoteAddr":"IP_ADDRESS","user":"USErNAME","app":"mail","method":"GET","url":"/apps/mail/api/mailboxes?accountId=1","message":{"Exception":"Exception","Message":"explode() expects param>


and it again returned error 500. Any ideas how to fix this please?

**Comment by ChristophWurst** [comment] 2020-10-28 11:01
> explode() expects param

the message is truncated. could you please post the full log entr?

**Comment by TheSkrypt** [comment] 2020-10-28 11:04
> 
> 
> > explode() expects param
> 
> the message is truncated. could you please post the full log entr?
Oh sorry, here it is:

`{"reqId":"4FFjk1exTgIMD99gDzmK","level":3,"time":"2020-10-28T11:56:01+00:00","remoteAddr":"IP","user":"USERNAME","app":"mail","method":"GET","url":"/apps/mail/api/mailboxes?accountId=1","message":{"Exception":"Exception","Message":"explode() expects parameter 1 to be string, null given","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"explode() expects parameter 1 to be string, null given","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":227,"function":"explode"},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":206,"function":"guessSpecialUse","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":162,"function":"detectSpecialUse","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","line":101,"function":"detectFolderSpecialUse","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailManager.php","line":126,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":92,"function":"getMailboxes","class":"OCA\\Mail\\Service\\MailManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","Line":227},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.1.1"}`

**Comment by ChristophWurst** [comment] 2020-10-28 11:07
This is a duplicate of https://github.com/nextcloud/mail/issues/2105

**Closed by ChristophWurst** 2020-10-28 11:07 UTC
Labels: 0. to triage, bug

**Comment by TheSkrypt** [comment] 2020-10-28 11:21
> 
> 
> This is a duplicate of #2105

OMG it worked! #2105 Thanks!
