### ISSUE TITLE
Signature image and Grammarly

### ISSUE THREAD

**Issue by jvalters** [nextcloud/mail#3209] opened 2020-06-05 12:19 UTC
Hello, 

Is it possible to please add an option to allow an HTML signature or to allow us to add an image to the signature?

Also, I see that Grammarly don't show up on the e-mail composing, can you please check and change the e-mail text field to text or what is required so that Grammarly would work?

I think, that this module is very good but needs a bit improvement also one of the improvements would be if there would be shown better the unread emails not only making back headers, but also some additional icons like a green dot or something.

Thanks.

**Comment by ChristophWurst** [comment] 2020-06-05 12:58
> Is it possible to please add an option to allow an HTML signature or to allow us to add an image to the signature?

Duplicate of https://github.com/nextcloud/mail/issues/2733.

> Also, I see that Grammarly don't show up on the e-mail composing, can you please check and change the e-mail text field to text or what is required so that Grammarly would work?

We use CKEditor. Does it work on the [demos](https://ckeditor.com/ckeditor-5/demo/)?

**Comment by jvalters** [comment] 2020-06-05 13:04
Hello, 

I can confirm, that on CKEditor demos it also doesn't work. 
But other sites like google translate and others Grammarly works perfect, I think it is Just some tag that is written different also in Github Grammarly works perfectly.

**Comment by ChristophWurst** [comment] 2020-06-05 14:42
we use ckeditor v5. those are older releases. would be great if you could dig a bit deeper to see if there are newer tickets for this. I'm not sure if we can add that data attribute so easily as described on SO as the element is rendered by the ckeditor lib.

**Comment by jvalters** [comment] 2020-06-05 14:48
Please leave this ticket open, I will check next week for this.
I would like to help you make this app even better if you don't mind.

Thanks.

**Comment by ChristophWurst** [comment] 2020-06-05 14:51
Take your time :)

Of course we appreciate any help to improve this app. Thanks a lot :)

**Comment by jvalters** [comment] 2020-06-20 22:45
Hello, 

I have found that:
Here Grammarly works: https://ckeditor.com/docs/ckeditor4/latest/examples/spellchecker.html

Believe that you need to change: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-scayt_autoStartup

**Comment by ChristophWurst** [comment] 2020-06-22 10:24
See https://github.com/nextcloud/mail/issues/3209#issuecomment-639538997. That is for CKEditor 4. And we use 5.

**Comment by jvalters** [comment] 2020-10-16 17:37
Hello, 

As I see grammarly is now working in e-mail.
But I would like to know about signatures, will there be a option to add HTML signature and picture?

Thanks.

**Comment by ChristophWurst** [comment] 2020-10-27 15:39
Good to know this Grammarly issue is resolved.

Images support in message bodies and signatures is being worked on: https://github.com/nextcloud/mail/issues/2733

**Closed by ChristophWurst** 2020-10-27 15:39 UTC
Labels: 0. to triage, enhancement
