### ISSUE TITLE
Add shortcut to archive email

### ISSUE THREAD

**Issue by meichthys** [nextcloud/mail#7027] opened 2022-08-17 13:51 UTC
### Is your feature request related to a problem? Please describe.

Archiving an email is not easy.

### Describe the solution you'd like

Currently the only way to archive an email is to use the `...` context menu and then choose move message, then choose the Archive folder.

Ideally we should have a one click archive button or a keyboard shortcut. Thunderbird for example uses the `a` key to archive.

### Describe alternatives you've considered

Drag and dropping emails to the archive folder works on desktop but doesn't work great on mobile or touch-based devices.

**Comment by ChristophWurst** [comment] 2022-08-17 13:53
Duplicate of https://github.com/nextcloud/mail/issues/22

**Closed by ChristophWurst** 2022-08-17 13:53 UTC
Labels: enhancement, 0. to triage
