### ISSUE TITLE
Abnormal display of mail header and body

### ISSUE THREAD

**Issue by finale-z** [nextcloud/mail#3878] opened 2020-10-22 23:30 UTC
### Expected behavior
Tell us what should happen

### Actual behavior
All characters except English in the received email header are displayed as garbled code, and the body is only displayed in a small window which can only display 6 lines of text.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.5.0
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
foxmail

### Server configuration

**Operating system**: (e.g. Debian 8)
docker
**Web server:** (e.g. Apache, Nginx,...)
Nginx
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
 7.4.11
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
20.0.0
#### Client configuration
**Browser:** (e.g. Firefox 48)
Chrome-vaapi
**Operating system:** (e.g. Arch Linux)
Manjaro

**Comment by ChristophWurst** [comment] 2020-10-23 06:29
screenshot please

**Comment by finale-z** [comment] 2020-10-25 01:20
The blue area on the right is the entire area where the message body can be displayed.
![Screenshot_20201025_091518](https://user-images.githubusercontent.com/33062701/97096751-116d9d80-1660-11eb-91b7-f0492f063227.png)

**Comment by st3iny** [comment] 2020-10-25 16:11
I can partially reproduce the mail content bug on master. Somehow the message container div has `min-height: 50vh` but does not scale beyond that. If I manually remove the min-height property I get the same result as in the screenshots.

**Comment by Lettly** [comment] 2020-10-25 17:01
As far i can see if this bug happens, the source of a email is available. If it diden't happen the source isn't available. Like: 
![image](https://user-images.githubusercontent.com/24634460/97113576-a10c5e00-16eb-11eb-86a1-76d92bacf695.png)
and
![image](https://user-images.githubusercontent.com/24634460/97113615-ed579e00-16eb-11eb-81d4-5a2b55451666.png)
I don't know if this tow things are correlated

**Comment by Lettly** [comment] 2020-10-25 17:08
> I can partially reproduce the mail content bug on master. Somehow the message container div has `min-height: 50vh` but does not scale beyond that. If I manually remove the min-height property I get the same result as in the screenshots.

![image](https://user-images.githubusercontent.com/24634460/97113822-07de4700-16ed-11eb-94af-52e077a4c540.png)

**Comment by st3iny** [comment] 2020-10-25 18:36
This bug is fixed via #3697 and got backported to v1.5. The fix should be included in the next release.

Seems like `min-height: 50vh` is intended here. I guess it prevents excessive scrolling when there are multiple emails in a thread.

**Comment by st3iny** [comment] 2020-10-26 10:27
@finale-z What about: 
> All characters except English in the received email header are displayed as garbled code

Could you provide a screenshot?

**Comment by finale-z** [comment] 2020-10-27 03:28
> @ finale-z怎么样：
> 
> > 收到的电子邮件标题中除英语以外的所有字符均显示为乱码
> 
> 您可以提供屏幕截图吗？

I've replied to the screenshot above

**Comment by ChristophWurst** [comment] 2020-10-27 15:17
Thanks for the screenshot.

Duplicate of https://github.com/nextcloud/mail/issues/3696

**Closed by ChristophWurst** 2020-10-27 15:17 UTC
Labels: 0. to triage, bug
