### ISSUE TITLE
Mail password displayed in plain text in nextcloud log

### ISSUE THREAD

**Issue by jeancf** [nextcloud/mail#847] opened 2018-03-26 08:27 UTC
### Steps to reproduce
1. Setup next mail account
2. Enter incorrect IMAP/SMTP password
3. Account creation fails
4. Check Nexcloud log and see password displayed in plain text

### Expected behaviour
The password should not appear

### Actual behaviour

    OCA\Mail\Exception\ClientException: Creating account failed: Error connecting to SMTP server.
    
    [internal function] OCA\Mail\Controller\AccountsController->create('JC Francois', 'jc@proximus...', '', 'imap.proximus.b...', 993, 'ssl', 'pr385988@proxim...', 'PasswordInPlainText', 'relay.proximus....', 587, 'tls', 'pr385988@proxim...', 'PasswordInPlainText', false)

### Mail app

**Nextcloud version: 13.0.1**

**Mail app version: 0.7.10**

**Mailserver or service: proximus.be**

**Number of accounts: 1**

**Comment by ChristophWurst** [comment] 2018-03-26 08:31
Duplicate of #823

**Closed by ChristophWurst** 2018-03-26 08:31 UTC
