### ISSUE TITLE
manage/move/delete mail with shift & control

### ISSUE THREAD

**Issue by mrAceT** [nextcloud/mail#5986] opened 2022-01-27 10:05 UTC
### Feature Request
When managing (a lot of)  mail, it would be so handy if one could select multiple mails via shift or control to move/delete multiple mails

#### Summary
with shift: select one, and a few/more lower an other one, and all in between get selected also
with control: each click adds that mail to the selection

That way one can more easily manage/move/delete a lot of mail, now it must be done one by one(?)

**Comment by miaulalala** [comment] 2022-01-27 10:07
Duplicate of #5955

**Closed by miaulalala** 2022-01-27 10:07 UTC
Labels: enhancement, 0. to triage
