### ISSUE TITLE
Failed integrity check after update to 0.7.3

### ISSUE THREAD

**Issue by ripper17** [nextcloud/mail#519] opened 2017-09-12 15:19 UTC
After upgrading to 0.7.3 in Nextcloud (through the command line, the online-update got stuck somewhere), I'm getting the following:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- mail
	- INVALID_HASH
		- vendor/doctrine/instantiator/src/Doctrine/Instantiator/Exception/UnexpectedValueException.php

Raw output
==========
Array
(
    [mail] => Array
        (
            [INVALID_HASH] => Array
                (
                    [vendor/doctrine/instantiator/src/Doctrine/Instantiator/Exception/UnexpectedValueException.php] => Array
                        (
                            [expected] => 472909b8419ce9621486019580610aba1f4c607fb82e8ce3114516b7f2c5eb3d623e25d1e2aaf16b3e1ccbaf6fbe345e40d28164e03802c76f4ec4af6c0a470e
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

        )
)
```

**Comment by ChristophWurst** [comment] 2017-09-13 15:02
> through the command line

How did you do that?

**Comment by ripper17** [comment] 2017-09-14 05:48
`php occ upgrade`
I don't know if it is possible to update a specific APP from the command line, but since the rest of my NC was up-to-date anyway, I didn't see any risk in running that command

**Comment by ChristophWurst** [comment] 2017-09-14 09:57
AFAIK that doesn't download the app for you. Did you download/unzip it manually?

**Comment by ripper17** [comment] 2017-09-14 10:51
No, I didn't download anything manually.

As far as I remember, this is how it went for me:
1.) I entered my NC
2.) There was a notification about an APP-Update for Mail
3.) I went to the APPs part (in the browser)
4.) I hit "Update"
5.) NC went into maintenance mode and never returned from to non-maintenance
6.) I ran 
`php occ maintenance:mode --off`
7.) I went back to the browser where I got some notification about pending updates, I hit "Update" in the browser
8.) The online-update failed with no helpful message, NC was back in maintenance mode
9.) See 6
10.) I ran 
`php occ upgrade`

which (accourding to the CL-output finished fine:

> Set log level to debug
> Turned on maintenance mode
> Updating database schema
> Updated database
> Updating <mail> ...
> Purify and migrate collected mail addresses
> 
>  Done
>  1/1 [============================] 100%
> Updated <mail> to 0.7.3
> Checking for update of app activity in appstore
> Checked for update of app "activity" in appstore 
> Checking for update of app admin_audit in appstore
> Checked for update of app "admin_audit" in appstore 
> Checking for update of app bruteforcesettings in appstore
> Checked for update of app "bruteforcesettings" in appstore 
> Checking for update of app calendar in appstore
> Checked for update of app "calendar" in appstore 
> Checking for update of app comments in appstore
> Checked for update of app "comments" in appstore 
> Checking for update of app contacts in appstore
> Checked for update of app "contacts" in appstore 
> Checking for update of app dav in appstore
> Checked for update of app "dav" in appstore 
> Checking for update of app federatedfilesharing in appstore
> Checked for update of app "federatedfilesharing" in appstore 
> Checking for update of app federation in appstore
> Checked for update of app "federation" in appstore 
> Checking for update of app files in appstore
> Checked for update of app "files" in appstore 
> Checking for update of app files_pdfviewer in appstore
> Checked for update of app "files_pdfviewer" in appstore 
> Checking for update of app files_sharing in appstore
> Checked for update of app "files_sharing" in appstore 
> Checking for update of app files_texteditor in appstore
> Checked for update of app "files_texteditor" in appstore 
> Checking for update of app files_trashbin in appstore
> Checked for update of app "files_trashbin" in appstore 
> Checking for update of app files_versions in appstore
> Checked for update of app "files_versions" in appstore 
> Checking for update of app files_videoplayer in appstore
> Checked for update of app "files_videoplayer" in appstore 
> Checking for update of app firstrunwizard in appstore
> Checked for update of app "firstrunwizard" in appstore 
> Checking for update of app gallery in appstore
> Checked for update of app "gallery" in appstore 
> Checking for update of app logreader in appstore
> Checked for update of app "logreader" in appstore 
> Checking for update of app lookup_server_connector in appstore
> Checked for update of app "lookup_server_connector" in appstore 
> Checking for update of app mail in appstore
> Checked for update of app "mail" in appstore 
> Checking for update of app nextcloud_announcements in appstore
> Checked for update of app "nextcloud_announcements" in appstore 
> Checking for update of app notifications in appstore
> Checked for update of app "notifications" in appstore 
> Checking for update of app oauth2 in appstore
> Checked for update of app "oauth2" in appstore 
> Checking for update of app password_policy in appstore
> Checked for update of app "password_policy" in appstore 
> Checking for update of app provisioning_api in appstore
> Checked for update of app "provisioning_api" in appstore 
> Checking for update of app richdocuments in appstore
> Checked for update of app "richdocuments" in appstore 
> Checking for update of app serverinfo in appstore
> Checked for update of app "serverinfo" in appstore 
> Checking for update of app sharebymail in appstore
> Checked for update of app "sharebymail" in appstore 
> Checking for update of app survey_client in appstore
> Checked for update of app "survey_client" in appstore 
> Checking for update of app systemtags in appstore
> Checked for update of app "systemtags" in appstore 
> Checking for update of app templateeditor in appstore
> Checked for update of app "templateeditor" in appstore 
> Checking for update of app theming in appstore
> Checked for update of app "theming" in appstore 
> Checking for update of app twofactor_backupcodes in appstore
> Checked for update of app "twofactor_backupcodes" in appstore 
> Checking for update of app updatenotification in appstore
> Checked for update of app "updatenotification" in appstore 
> Checking for update of app user_ldap in appstore
> Checked for update of app "user_ldap" in appstore 
> Checking for update of app workflowengine in appstore
> Checked for update of app "workflowengine" in appstore 
> Starting code integrity check...
> Finished code integrity check
> Update successful
> Turned off maintenance mode
> Reset log level

When I logged back into NC, I got the warning about failed integrity check

**Comment by ChristophWurst** [comment] 2017-09-14 14:14
I will try to reproduce/check the signature.

**Comment by ChristophWurst** [comment] 2017-09-19 14:23
Can't reproduce. Integrity check passes on my instance.

**Comment by ripper17** [comment] 2017-09-19 15:04
Anything I could do to provide further info or to resolve the issue? I'm still getting the same error.

Which two values are compared here, anyway? One must be from the source (I guess), is that some md5 sum of the package? Is the other one coming from some DB entry?

**Comment by ChristophWurst** [comment] 2017-09-19 15:12
> Anything I could do to provide further info or to resolve the issue? I'm still getting the same error.
> 
> Which two values are compared here, anyway? One must be from the source (I guess), is that some md5 sum of the package? Is the other one coming from some DB entry?

There's a signature file in the `appinfo` directory of a packaged app. Your Nextcloud server compares hash values from that files with the actual files on the file system.

**Comment by ripper17** [comment] 2017-09-20 07:10
Huh, that's quite interesting.
So I misread the output of the "integrity check" page and look in the signature file for the "current" signature
 I got 6 entries in the signature file with the "current" signature (cf83e1357...)

All of them are inside a .hg directory:
```
vendor\/kwi\/urllinker\/.hg\/cache\/checkisexec
vendor\/kwi\/urllinker\/.hg\/cache\/checklink
vendor\/kwi\/urllinker\/.hg\/cache\/checklink-target
vendor\/kwi\/urllinker\/.hg\/store\/phaseroots
vendor\/kwi\/urllinker\/.hg\/store\/undo.phaseroots
vendor\/kwi\/urllinker\/.hg\/undo.bookmarks
```
I'm guessing that these files shouldn't acutally be in the release package and subsequently also not in the signature file? All files are 0 byte in size

Back to topic :-)
Not very surprisingly after the above, the file 
`vendor/doctrine/instantiator/src/Doctrine/Instantiator/Exception/UnexpectedValueException.php`
is 0 byte in size which I presume is incorrect?

Should I simply try to uninstall and then reinstall the APP?

**Comment by ChristophWurst** [comment] 2017-09-20 07:15
> is 0 byte in size which I presume is incorrect?
> 
> Should I simply try to uninstall and then reinstall the APP?

Yes, please try that. Backup/delete the old app folder and download the archive manually. I checked the file manually and that class file is *not* empty actually. Hence it seems there was an issue with extracting the archive and the integrity check correctly detected this 😁 
![bildschirmfoto von 2017-09-20 09-13-11](https://user-images.githubusercontent.com/1374172/30631360-3beb8574-9de4-11e7-8837-4732c5d8d8cd.png)


You can find the archive here https://apps.nextcloud.com/apps/mail

**Comment by ChristophWurst** [comment] 2017-09-20 07:16
I'm closing this ticket now. Thanks!

**Closed by ChristophWurst** 2017-09-20 07:16 UTC
Labels: needs info
