### ISSUE TITLE
Send button disabled in Compose or Draft

### ISSUE THREAD

**Issue by rmkeen** [nextcloud/mail#2977] opened 2020-04-23 19:57 UTC
### Expected behavior
Select sending account. Enter recipient. Enter subject. Enter body. Click send.

### Actual behavior
Send button is disabled and never enables even when everything is filled in. Draft saves as changes are made. Can switch between drafts but send remains disabled. 

Can click reply on an inbox item and send is enabled, when I click send the message does send.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.3.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
rackspace

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.4

**Web server:** (e.g. Apache, Nginx,...)
Apache2

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.2.24

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
18.0.3

#### Client configuration
chrome

**Operating system:** (e.g. Arch Linux)
Windows 10

**Comment by ChristophWurst** [comment] 2020-04-24 06:06
Duplicate of https://github.com/nextcloud/mail/issues/2769. You have to click on the recipients in the dropdown.

**Closed** 2020-04-24 06:07 UTC
Labels: 0. to triage, bug
