### ISSUE TITLE
Incorrect Subject

### ISSUE THREAD

**Issue by drfuture** [nextcloud/mail#325] opened 2017-02-28 11:21 UTC
### Steps to reproduce
That's the Problem - i don't know in witch special case this problem exists.
i have it 3 Times the last ~10 Weeks - so ~ 30 Mails written.

1.  revieve a Mail
2. write a answere 
3. klick Answer > Mail would be send.

### Expected behaviour
The Mailanswere is send with AW: *the old Subject*

### Actual behaviour
A complete different subject is send out, every time it was a different one. The first time the "old" Mail has no Subject - other 2 Mails there was a old Subject. But every Time the Subject was a complete different one maybe from a other Mail.
So there is no line that shows the Subject ob the Mail that would be send out - i have no change to see it befor the false e-mail was send out.

### Mail app

**Mail app version:** 0.6.2
**Mailserver or service:** The last one Gmail, the first time postfix private
**Transport security - IMAP:** SSL Both
**Transport security - SMTP:** SSL (Gmail) No Privat
**Number of accounts: ** 3

### Server configuration
**Operating system**: Suse Linux 43 
**Web server:** nginx
**Database:** mariadb
**PHP version:** 5.6
**Version:** (see admin page) 11.02
**Updated from an older version or fresh install:** Updated
**List of activated apps:**
Mail, Contacts, DirectMenu, Calendar, AppOrder, Keeweb

#### Client configuration
**Browser:** Chrome 56
**Operating system:** Windows 7 x64

**Comment by ChristophWurst** [comment] 2017-09-12 11:30
@jancborchardt you seem to use replies a lot. Have you ever experienced this issue?

**Comment by jancborchardt** [comment] 2017-09-12 11:58
I never had the "wrong subject" issue as far as I can recall.

Only the "empty subject" we had recently and fixed.

@drfuture did you have this recently or is this not reproducible anymore?

**Comment by drfuture** [comment] 2017-09-26 08:06
since the day a posted the Bug, i never seen it again, but as posted the bug wasn`t only once.
maybe its fixed.

Maybe you could change the Topic to Feature-Request to show the Subject that would be send out on an answer in little size unter "to: " or same size on the right side after "to: " so it is possible to Change the subject too.

**Comment by ChristophWurst** [comment] 2019-12-17 16:29
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version after that, feel free to reopen.

**Closed by ChristophWurst** 2019-12-17 16:29 UTC
Labels: 1. to develop, bug
