### ISSUE TITLE
HTML message formatting

### ISSUE THREAD

**Issue by republicus** [nextcloud/mail#2495] opened 2020-01-19 01:17 UTC
### Expected behavior
HTML messages should be formatted properly.

As seen in email-client software:
![image](https://user-images.githubusercontent.com/47370709/72672842-003b9480-3a2f-11ea-90a3-a0e33a0bcd84.png)

### Actual behavior
Formatting is displayed improperly.
1. Lots of unused space on left, right, and below message.
2. Nextcloud Mail does display HTML formatted messages properly (including Nextcloud standard messages.)

Same message as viewed in Nextcloud Mail: 
![gifcam](https://user-images.githubusercontent.com/47370709/72672826-b0f56400-3a2e-11ea-88b1-99ca9ca8fd49.gif)

### Mail app

**Mail app version:** 1.0.0
**Mailserver or service:** Postfix/Dovecot

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache
**Database:** MariaDB
**PHP version:** PHP 7.3.11-1
**Nextcloud Version:** 17.0.2

#### Client configuration
**Browser:** Chrome 74.0.3729.169
**Operating system:** Windows 10

**Comment by ChristophWurst** [comment] 2020-01-20 14:32
@jancborchardt what's the issue here? The way Nextcloud's emails are styled or the way we display them?

**Comment by republicus** [comment] 2020-01-27 21:50
It may be the Nextcloud emails styling. 
I am comparing to another rich email which appears normally in Mail App:

![image](https://user-images.githubusercontent.com/47370709/73216963-09122180-4125-11ea-88c3-f3553c501896.png)

**Comment by jancborchardt** [comment] 2020-03-31 15:23
So these are 2 separate issues I’d say – one is with our notification mails, and one is the issue of how we display HTML mails in dark theme.

@republicus do you know how other platforms like GNOME, macOS, Android and others deal with HTML mails in dark theme – if you can check and take screenshots that would help a lot. :)

**Comment by republicus** [comment] 2020-04-02 00:42
The only dark theme specific formatting issue I see is the background style --where it dark when it should be light.  Otherwise, I have identical results with the light theme.
Because of that, I'm assuming your later request is moot. 

It could be the formatting in mail
![GIF 4-1-2020 8-36-50 PM](https://user-images.githubusercontent.com/47370709/78199048-98ef8700-7458-11ea-8771-d0fa9bebd86e.gif)

**Comment by jancborchardt** [comment] 2020-04-02 07:40
Ok, so the dark theme issue seems to be a duplicate of https://github.com/nextcloud/mail/issues/1742
And the issue with the notification mail belongs in the server repository at https://github.com/nextcloud/server/issues → could you open it there? Thanks!

**Closed by jancborchardt** 2020-04-02 07:40 UTC
Labels: 1. to develop, bug, help wanted, papercut

**Comment by rchovan** [comment] 2020-04-02 07:56
Hi, 
will that other issues solve this one ? 

- wrong rendering HTML message. When I open it for example in Rainloop, it is displayed correctly. 
- empty, not used space for HTML message

![image](https://user-images.githubusercontent.com/6713920/78223967-071f6280-74c8-11ea-97a2-aff73505862f.png)

**Comment by jancborchardt** [comment] 2020-04-02 08:51
@rchovan for the rendering issue, please open a new issue with examples from any HTML mails which have this issue so we can identify a common pattern.

For the empty unused space, this is fixed with https://github.com/nextcloud/mail/pull/2222 :)
