### ISSUE TITLE
Write an e-mail without making navigation impossible

### ISSUE THREAD

**Issue by handkerchief333** [nextcloud/mail#9231] opened 2024-01-09 08:47 UTC
### Is your feature request related to a problem? Please describe.

When you create a new e-mail, the pop-up appears. Now you can no longer navigate or read e-mails, but only compose the e-mail. You always have to close and reopen the pop-up.

### Describe the solution you'd like

It is necessary to open and read other emails in the same browser window at the same time as composing emails, as you often have to refer to emails or read something again when composing emails. Gmail solves this very elegantly by docking the compose window at the bottom right, but without obstructing navigation in Gmail. You can easily open and view other emails while composing an email.

**Comment by ChristophWurst** [comment] 2024-01-09 08:49
Duplicate of https://github.com/nextcloud/mail/issues/2831

**Closed by ChristophWurst** 2024-01-09 08:49 UTC
Labels: enhancement, 0. to triage
