### ISSUE TITLE
Mass deletion of emails

### ISSUE THREAD

**Issue by tony4212** [nextcloud/mail#1506] opened 2019-01-30 15:19 UTC
### Feature Request

One of the biggest issues with this app is that the user doesn't have the capability to check off or select emails and delete said emails all at once. It would be nice to do this, especially when you have a large amount of emails in the trash bin. 
#### Summary

A simple way to either have the capability to select all emails in the trash bin for mass deletion and or have the ability to check / select the emails you want to delete in inbox.

**Comment by ChristophWurst** [comment] 2019-01-30 15:22
Duplicate of https://github.com/nextcloud/mail/issues/1008.

**Closed by ChristophWurst** 2019-01-30 15:22 UTC
Labels: 0. to triage, enhancement
