### ISSUE TITLE
Menu entry of the mail account not visible - 3.5.6

### ISSUE THREAD

**Issue by pongraczi** [nextcloud/mail#9362] opened 2024-02-21 07:41 UTC
### Steps to reproduce

1. Open mail app + add a new account
2. The account name there is the three-dot menu - click it
3. The popup menu appears, but the first entry: Account settings or something not visible. Check the screenshot below.
4. Only solution to "click" on it by using keyboard and press enter.
![kep-160](https://github.com/nextcloud/mail/assets/5891983/07c91a87-b92e-4870-9d80-d661337e65b7)

### Expected behavior

The full menu should be visible, so, the **Y** offset should be the header instead of zero (I just assume).

### Actual behavior

Not visible, check the screenshot above.

### Mail app version

3.5.6

### Mailserver or service

not relevant

### Operating system

not relevant, Nexctloud-All-in-one 27.1.5

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by ChristophWurst** [comment] 2024-02-21 07:43
Duplicate of https://github.com/nextcloud/mail/issues/8474

**Closed by ChristophWurst** 2024-02-21 07:43 UTC
Labels: bug, 0. to triage

**Comment by pongraczi** [comment] 2024-02-21 07:44
Aaaand surprise, now it is working as expected, only thing I reloaded the mail app.

**Comment by ChristophWurst** [comment] 2024-02-21 07:44
Yes, it is a bit random :s
