### ISSUE TITLE
Call to a member function getDelimiter() on bool

### ISSUE THREAD

**Issue by acsfer** [nextcloud/mail#3568] opened 2020-09-08 16:14 UTC
### Expected behavior
Configure Gmail account, get into it.

### Actual behavior
`Call to a member function getDelimiter() on bool` after configured the account.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.4.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
GMail

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18.04

**Web server:** (e.g. Apache, Nginx,...)
Nginx

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0)
7.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
19.0.2

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox

**Operating system:** (e.g. Arch Linux)
Ubuntu

```
[mail] Error: Exception: Call to a member function getDelimiter() on bool at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\FoldersController {}, "index")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "index", OC\AppFramework\ ... {}, {accountId: "2", ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "2", ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {accountId: "2", ... "})
4. /var/www/nextcloud/lib/base.php line 1012
   OC\Route\Router->match("/apps/mail/api/accounts/2/folders")
5. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /apps/mail/api/accounts/2/folders
```

**Comment by ChristophWurst** [comment] 2020-09-08 17:09
This is a duplicate of https://github.com/nextcloud/mail/issues/2105

Thanks for the well structured report :v:

**Closed** 2020-09-08 17:09 UTC
Labels: 0. to triage, bug
