### ISSUE TITLE
Cannot edit account when connection timesout on wrong password

### ISSUE THREAD

**Issue by Yamakasi** [nextcloud/mail#235] opened 2016-12-13 17:02 UTC
### Steps to reproduce
1. Change password on mailsystem
2. Open mailapp
3. Try to edit account.

### Expected behaviour
Open the edit lightbox for the account

### Actual behaviour
Nothing, it keeps loading the maibox page on the right

### Mail app

**Mail app version:** (see apps admin page)
All

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
All

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
All

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
All

**Number of accounts:**
All

**Mail app version build date:** (only if you are using a Nightly Build)
All

### Server configuration
**Operating system**:
All

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
7.1

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by Yamakasi** [comment] 2016-12-16 16:09
Can anyone pick this up, it's kinda annoying.

**Comment by ChristophWurst** [comment] 2016-12-16 17:04
Hi,

this is a duplicate of https://github.com/nextcloud/mail/issues/152. Let's continue there :-)

**Closed by ChristophWurst** 2016-12-16 17:04 UTC

**Comment by Yamakasi** [comment] 2016-12-16 21:01
Oh sorry :) thanks! will do.
