### ISSUE TITLE
remove Account provisioning 

### ISSUE THREAD

**Issue by Tealk** [nextcloud/mail#6889] opened 2022-07-15 12:45 UTC
### Steps to reproduce

1. delete a previously created Account provisioning 
2. opening the mail app
3. no way to delete the mail account

### Expected behavior

that the account is automatically removed or a delete button would be available

### Actual behavior

a mailbox is displayed which cannot be deleted

### Mail app version

1.13.6

### Operating system

Debian

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MariaDB

**Comment by miaulalala** [comment] 2022-07-20 09:41
Hi, can you elaborate a bit? 
Are these the steps you take? 
1) You create an provisioning config
2) Existing accounts are provisioned. 
3) Then you delete the provisioning via the "Delete & unprovision, but the accounts are not deleted.

Can you have a look at your logs please to see if there are any errors?

**Comment by Tealk** [comment] 2022-07-20 11:02
> Are these the steps you take?
> 
>     1. You create an provisioning config
> 
>     2. Existing accounts are provisioned.
> 
>     3. Then you delete the provisioning via the "Delete & unprovision, but the accounts are not deleted.

yes

because of the log I must look later whether I still find that

**Comment by Tealk** [comment] 2022-08-03 07:52
> Can you have a look at your logs please to see if there are any errors?

I don't have the logs from that time anymore, I set logrotate very short

**Comment by miaulalala** [comment] 2022-08-03 14:26
Can you reproduce the error and then look at your logs?

**Comment by Tealk** [comment] 2022-08-03 15:42
So just create a configuration again and delete it?
What happens to the one that is still displayed?

**Comment by ryomahostingph** [comment] 2022-10-01 12:49
how to fix these? we experiencing this also

**Comment by Tealk** [comment] 2022-10-01 13:28
I use PostgreSQL and have uninstalled the app and then cleaned the database and then reinstalled the app.

```
occ app:remove mail

sudo -u postgres psql

\c nextcloud

nextcloud=# DROP TABLE
   oc_mail_accounts,
   oc_mail_aliases,
   oc_mail_attachments,
   oc_mail_classifiers,
   oc_mail_coll_addresses,
   oc_mail_local_messages,
   oc_mail_mailboxes,
   oc_mail_message_tags,
   oc_mail_messages,
   oc_mail_provisionings,
   oc_mail_recipients,
   oc_mail_tags,
   oc_mail_trusted_senders
CASCADE;

DELETE FROM oc_migrations WHERE app='mail';

DELETE FROM oc_appconfig WHERE appid = 'mail';

occ app:install mail
```

**Comment by ryomahostingph** [comment] 2022-10-01 13:41
im using nextcloud AIO can i delete it here?
nextcloud-aio-database

**Comment by Tealk** [comment] 2022-10-01 14:44
I don't know enough about docker to give you any tips; don't want to destroy anything.

**Comment by pgaufillet** [comment] 2023-02-28 15:48
I confirm this incorrect behaviour still occur in 25.0.4. No specific message seen in the journal.

**Comment by ChristophWurst** [comment] 2023-02-28 16:34
It happens because of https://github.com/nextcloud/mail/pull/6325. The provisioning is deleted but kept in cache. Thus the app recreates the accounts. And eventually they are dangling provisioned accounts with no associated config.

**Comment by ChristophWurst** [comment] 2023-10-25 08:51
Fixed by https://github.com/nextcloud/mail/pull/8993.

**Closed** 2023-12-27 14:41 UTC
Labels: bug, 3. to review
