### ISSUE TITLE
Error while creating the account: Creating account failed: Error connecting to SMTP server.

### ISSUE THREAD

**Issue by mzryz** [nextcloud/mail#873] opened 2018-04-18 09:43 UTC
### Steps to reproduce
1. Add e-mail service
2. Manually configure (enter all details correct)
3. That's it
ps - I followed the steps in a previous reported error similar to this without any luck, as you can see from my config.php

### Expected behaviour
It should load my inbox

### Actual behaviour
I get message Error while creating the account: Creating account failed: Error connecting to SMTP server.

### Mail app

**Mail app version:** (see apps admin page)
0.7.10
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Kolabnow
settings: https://kb.kolabnow.com/documentation/generic-imap-client-setup-guide
**Number of accounts:**
1

### Server configuration

**Operating system**:
Linux
**Web server:**
Siteground
**Database:**
Mysql
**PHP version:**
 5.6.30 
**Version:** (see admin page)
13.0.1
**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
<?php
$CONFIG = array (
  'instanceid' => 'ocf7bcf73x3c',
  'passwordsalt' => 'CJca4EtnUo2merKht+dHDmfDwSTufs',
  'secret' => 'tGO8cPE3jnTw9k+71sxkhP65MfPLfoW7bXiFnpBgCdQShkuT',
  'trusted_domains' => 
  array (
    0 => 'www.website.com',
  ),
  'dbtype' => 'mysql',
  'version' => '13.0.1.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'maintenance' => false,
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'website.com',
  ‘mail_smtptimeout’ => ‘30’,
  ‘app.mail.transport’ => ‘php-mail’,
);

</details>

#### Client configuration
**Browser:**
Firefox latest
**Operating system:**
Win 8.1
##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
"app":"PHP","method":"PROPFIND","url":"\/nextcloud\/remote.php\/dav\/files\/\/","message":"Use of undefined constant mail\u0092 - assumed 'mail\u0092' at \/home\/systimms\/public_html\/nextcloud\/config\/config.php#28","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.1.1"}

```
Insert your server log here
```
</details>

##### IMAP log (data/horde_imap.log)
<details>
------------------------------
>> Wed, 18 Apr 2018 09:35:24 +0000
>> Connection to: imap://imap.kolabnow.com:993/
>> Server connection took 0.7936 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE MUPDATE=mupdate://mupdate.mykolab.com/ AUTH=PLAIN AUTH=LOGIN SASL-IR] ext-imapf001.mykolab.com Cyrus IMAP Murder 2.5.11-41-gd53406f3f-Kolab-2.5.11-15.1.el7.kolab_16 server ready
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: me@me)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxten QUOTA NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES ANNOTATEMORE ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-MYRIGHTS WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE URLAUTH URLAUTH=BINARY X-NETSCAPE MUPDATE=mupdate://mupdate.mykolab.com/ LOGINDISABLED X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE] Success (tls protection) SESSIONID=<cyrus-imapd-28527-1524044125-1-1010284079889825307>
>> Command 1 took 0.2825 seconds.
C: 2 LOGOUT
S: * BYE LOGOUT received
S: 2 OK Completed
>> Command 2 took 0.2556 seconds.

```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```
</details>

##### SMTP log (data/horde_smtp.log)
<details>
SMTP log is completely empty, 0 bytes
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
```
</details>

**Comment by ChristophWurst** [comment] 2018-04-30 06:51
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by tenbob** [comment] 2018-05-01 15:06
I have the same problem. In my case it's caused by my hosting provider blocking any connection to a remote SMTP server. However, I can still send email via local php mail. As I see it, there are two problems.

(1) The configuration for the IMAP and SMTP servers is in the same dialog. So you can't set up one without the other. The two configurations should be completely independent. Because SMTP can't connect, I can't configure IMAP either. Can they be split, or is there a way to enter null data for SMTP?

(2) Is there a way to use php mail as the sending method in Mail? This works fine with my hosting provider. I can already receive admin messages from Nextcloud using this method.

**Comment by ChristophWurst** [comment] 2018-05-07 06:15
> (2) Is there a way to use php mail as the sending method in Mail? This works fine with my hosting provider. I can already receive admin messages from Nextcloud using this method.

https://github.com/nextcloud/mail/blob/master/doc/admin.md#use-php-mail-for-sending-mail

**Comment by tenbob** [comment] 2018-05-09 16:15
Thanks @ChristophWurst. That worked perfectly. You just add `'app.mail.transport' => 'php-mail'` to `nextcloud/config/config.php`. Then it ignores SMTP settings and uses php-mail instead.

**Comment by ChristophWurst** [comment] 2018-11-08 10:37
Issue seems fixed -> closing

**Closed** 2018-11-08 10:37 UTC
Labels: 0. to triage, needs info

**Comment by lopar** [comment] 2019-01-08 16:31
Issue still here.
I try to connect to my mail provider, and get an error:

Debug | PHP | stream_socket_client():  unable to connect to ssl://mail.adm.tools:465 (Permission denied) at  /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php#267
-- | -- | --

But when I check connection, it's active:

[root@localhost ~]# telnet mail.adm.tools 465
Trying 185.104.44.69...
Connected to mail.adm.tools.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by gianks** [comment] 2019-07-08 22:22
> Issue seems fixed -> closing

Hi, i'm having the same issue on a self hosted instance of the latest univention VmWare image.
Tried the suggested debug level setting but no additional information have been found in nextcloud.log and data/horde_imap.log doesn't exists.

Telnet shows no troubles to communicate with the mail server, both imap and smtp.
Any suggestion?
Thanks

**Comment by ChristophWurst** [comment] 2019-08-05 10:42
> Any suggestion?

https://github.com/nextcloud/mail/issues/873#issuecomment-386967633
