### ISSUE TITLE
New mail shown in search results

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/mail#953] opened 2018-06-25 10:50 UTC
### Expected behavior

When you're viewing search results, new mail should not be shown if it doesn't match the filter

### Actual behavior

New mail is shown on top of the message list as if there was no search active.

**Comment by ChristophWurst** [comment] 2018-06-25 11:04
Duplicate of https://github.com/nextcloud/mail/issues/812?

**Comment by StCyr** [comment] 2021-01-23 14:16
This is not the case anymore on v1.8

**Closed by StCyr** 2021-01-23 14:16 UTC
Labels: 1. to develop, bug
