### ISSUE TITLE
Message preview line in of Nextcloud notifications in message list is ALL-CAPS

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#8899] opened 2023-09-28 10:33 UTC
### Steps to reproduce

1. Get a notification from Nextcloud, like an event invite or a Forms response
2. Open Nextcloud Mail
3. Look at the message preview line of that mail in the message list

### Expected behavior

The preview line shows normally.

### Actual behavior

The preview line is displayed in ALL-CAPS and also with a space ahead. It is fine for other emails (although double line breaks are rendered as double spaces which looks a bit off too):
![image](https://github.com/nextcloud/mail/assets/925062/0eb9d4f2-b50b-4f02-bbf6-bb5cb271b9fb)

### Mail app version

Latest on cloud.nc

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment] 2023-09-28 10:44
Duplicate of https://github.com/nextcloud/mail/issues/8222

**Closed by ChristophWurst** 2023-09-28 10:44 UTC
Labels: bug, 0. to triage, skill:frontend
