### ISSUE TITLE
List view for NC Mail

### ISSUE THREAD

**Issue by lp-SRO** [nextcloud/mail#8827] opened 2023-09-01 02:29 UTC
### Describe the solution you'd like

I would like an adjustable list view. Especially if the first emails in a mailbox are spam emails, it would be much better if they were not opened in the split view right away. In a list view, you could delete them in advance.

**Comment by ChristophWurst** [comment] 2023-10-24 17:42
Duplicate of https://github.com/nextcloud/mail/issues/8811?

**Comment by ChristophWurst** [comment] 2024-10-16 11:59
Duplicate and delivered

**Closed by ChristophWurst** 2024-10-16 11:59 UTC
Labels: enhancement, 0. to triage
