### ISSUE TITLE
back button from email to inbox is dead in mobile

### ISSUE THREAD

**Issue by dutch666** [nextcloud/mail#3055] opened 2020-05-04 20:18 UTC
### Expected behavior
Tell us what should happen
from within your email, in mobile, you should click litte arrow and see the inbox again, 

### Actual behavior
Tell us what happens instead

the button is dead

### Mail app. 

**Mail app version:** (see apps admin page, e.g. 0.5.3)
newest version

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
horde

### Server configuration

**Operating system**: (e.g. Debian 8)
linux

**Web server:** (e.g. Apache, Nginx,...)
apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mysql

**PHP version:** (e.g. 7.0)
7.2
**Nextcloud Version:** (see admin page, e.g. 13.0.2) 
18.04

#### Client configuration
**Browser:** (e.g. Firefox 48)
mobile, samsung browser, and chrome browser. note 10

**Operating system:** (e.g. Arch Linux)
android newest version

![95397198_235189304433285_8353735317982806016_n](https://user-images.githubusercontent.com/36723240/81009516-ceeea500-8e22-11ea-9633-8ee26b94176c.jpg)

**Comment by ChristophWurst** [comment] 2020-05-05 07:17
Duplicate of https://github.com/nextcloud/mail/issues/2942

**Closed by ChristophWurst** 2020-05-05 07:17 UTC
Labels: 0. to triage, bug
