### ISSUE TITLE
Reply (all) creates a new mail for the sender only

### ISSUE THREAD

**Issue by StefInP** [nextcloud/mail#10142] opened 2024-09-13 20:41 UTC
### Steps to reproduce

1. Receive a message with several recipients
2. Click the ‘reply‘ button (not the ‘reply to sender only‘)
3. A new message is created with only the sender address in ‘To‘ fied. The addresses of other recipients are not put in the ‘Cc‘ field

### Expected behavior

The addresses of all the recipients of the original message should appear in the ‘Cc’ field of the reply message.

### Actual behavior

See step 3 above

### Mail app version

3.7.8

### Mailserver or service

Several

### Operating system

NC 29.0.4 (official AIO 9.4.1)

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment] 2024-09-14 13:35
i can reproduce the error on stable3.7, but the issue is fixed on stable4.0

**Comment by ChristophWurst** [comment] 2024-09-14 13:44
Same as https://github.com/nextcloud/mail/issues/10089?

**Comment by GretaD** [comment] 2024-09-14 13:51
> Same as #10089?

no really, this is a different button and its only broken on > stable4.0

#10142 is for the reply all button and its only broken on stable3.7

**Comment by Bolli84** [comment] 2024-10-14 17:42
Same here. With the current release 3.7.8 I get the reply only to the sender.

**Comment by Bolli84** [comment] 2024-10-15 07:23
Addition: The button at the end of the page works, but the button in the context menu on the right does not work

**Closed as completed** 2024-12-18 21:55 UTC
Labels: bug, 3. to review

**Comment by ChristophWurst** [comment] 2024-12-19 05:55
Dear @StefInP, thank you for the feedback.
