### ISSUE TITLE
Auto-responder for holidays

### ISSUE THREAD

**Issue by MrLaffer** [nextcloud/mail#1099] opened 2018-09-12 08:45 UTC
### Feature Request

I would be pleased about an automatic reply function for incoming mails. That's a nice feature for vacation absences.

#### Summary

I would be pleased about an automatic reply function for incoming mails. That's a nice feature for vacation absences.

**Comment by ChristophWurst** [comment] 2018-09-14 06:44
This can be done with [sieve](https://wiki2.dovecot.org/Pigeonhole/Sieve/Examples#Vacation_auto-reply) it seems, so I'd say this is a duplicate of https://github.com/nextcloud/mail/issues/44.

Thanks for reporting.

**Closed by ChristophWurst** 2018-09-14 06:44 UTC
