### ISSUE TITLE
Picture in signature

### ISSUE THREAD

**Issue by CATER-COM** [nextcloud/mail#2938] opened 2020-04-17 17:31 UTC
I don't found any way to insert picture like logo in my signature. A simple way could be providing a text to past HTML code.
Another way even better could be providing a button to choose a picture in nextcloud gallery.

Thanks for all

**Comment by ChristophWurst** [comment] 2020-04-20 06:20
Duplicate of https://github.com/nextcloud/mail/issues/2733

**Closed by ChristophWurst** 2020-04-20 06:20 UTC
Labels: 0. to triage, enhancement
