### ISSUE TITLE
Stuck context menu

### ISSUE THREAD

**Issue by rcargnelutti** [nextcloud/mail#3597] opened 2020-09-17 11:46 UTC
**Expected behavior**
When inside the “Inbox”, when the option “delete” in the context menu is selected, the context menu vanishes, and the message that was selected is immediately moved to the “Trash”.

**Actual behavior**
When I use the delete option, in the context menu, inside “Sent”, “Drafts” and “Trash”, the context menu gets stuck. It won’t vanish until I click outside the menu area and the selected message stays in the box. After a while the message will appear on the “Trash”, not immediately as expected.

**Mail app version**: 1.4.1
**Mail Server or service**: MXRoute (IMAP)
**Server configuration**
**Operating system**: CentOS 7.6
**Web server**: Apache Version 2.4.46
**Database**: MySQL 10.3.24
**PHP version**: 7.3.6
**Nextcloud Version**: 19.0.3
**Client configuration**
**Browser**: Google Chrome Version 84 / 85 (official) 64 bits and Firefox Version 80.0.1 (64-bits)
**Operating system**: Ubuntu 20.04, Mint 20, Debian 10 (buster) and Windows 10 Pro

**Comment by ChristophWurst** [comment] 2020-09-21 09:25
Possibly related to https://github.com/nextcloud/nextcloud-vue/issues/1384#issuecomment-690202738

**Comment by StCyr** [comment] 2020-10-04 08:43
can't reproduce this issue in the "Sent" and "Trash" folder with latest release.

But the "Drafts" folder seems to have problems idd

**Comment by StCyr** [comment] 2020-10-21 09:52
Hello @rcargnelutti ,

We have merged a change that should fix your issue. Next version of Mail (1.6) should see your issue resolved.

BR,

Cyrille

**Closed** 2020-10-21 14:38 UTC
Labels: 1. to develop, bug
