### ISSUE TITLE
Mailto links doesn't work with Firefox and IMAP account

### ISSUE THREAD

**Issue by DiGGeR2** [nextcloud/mail#655] opened 2017-12-04 19:54 UTC
### Steps to reproduce
1. Click on a mailto link with Firefox and Mail for the mailto default app
2. It redirect to 
https://nextcloud.xyz.com/nextcloud/index.php/apps/mail/#mailto?to=user%2540domain.com
3. And then redirect to https://nextcloud.xyz.com/nextcloud/index.php/apps/mail/#accounts/29/folders/SU5CT1g=
and no new mail is generated :(

### Actual behaviour
I use Firefox and the mailto url in the configuration is
https://nextcloud.xyz.com/nextcloud/index.php/apps/mail/compose?uri=%s

### Mail app

**Mail app version: 0.7.5

**Mailserver or service: webmail.ems-app.com

**Transport security - IMAP: SSL, TLS

**Transport security - SMTP: SSL, TLS

**Number of accounts: 2 (same error with 1 account)

**Comment by ChristophWurst** [comment] 2017-12-04 19:57
I'm confused. This is a duplicate of #654, right?

**Comment by ChristophWurst** [comment] 2017-12-04 19:57
Or is this meant to replace the other ticket?

**Comment by DiGGeR2** [comment] 2017-12-04 20:08
Sorry... just correcting the title now.  It's another issue

**Comment by ChristophWurst** [comment] 2019-12-17 16:31
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version after that, feel free to reopen.

v0.12.0+ has a completely new front-end. This has to be re-tested.

**Closed by ChristophWurst** 2019-12-17 16:31 UTC
Labels: 1. to develop, bug
