### ISSUE TITLE
Errors when nextcloud group insert as mail destination

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/mail#1845] opened 2019-07-07 18:50 UTC
Nextcloud 15.0.9.1
Ubuntu 18.04.2 LTS
PostgreSQL 10.9
apache 2.4.29
php 7.2.19
mail 0.11.1

If the nextcloud group name is written in Cyrillic, then when substituting as a recipiens we gett: "554 5.5.1 Error: no valid recipients" "Horde_Mime_Exception: Server is not accepting SMTP connections."

If the nextcloud group name is written with a minus sign, then the first part of the text before the sign is used as mail recipients, minus and he last part clings to the last recipient in the group list,
which causes an error on the mail server.

**Comment by ChristophWurst** [comment] 2019-08-05 12:46
please use the issue template next time

**Comment by bfritscher** [comment] 2020-01-09 20:54
I think this is a Duplicate of #2440

**Comment by ChristophWurst** [comment] 2020-01-10 09:55
And 15 is reaching EOL https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Closed** 2020-01-10 09:54 UTC
Labels: 0. to triage, bug
