### ISSUE TITLE
SPAM!!!!!!

### ISSUE THREAD

**Issue by tempuser779** [nextcloud/mail#785] opened 2018-02-15 13:28 UTC
Hi, guys. What about "rules  for SPAM" function for mail app or any other email sorting rules? You can imagine what happens without it ...

**Comment by ChristophWurst** [comment] 2018-02-15 13:55
Duplicate of https://github.com/nextcloud/mail/issues/44

Generally, spam should be handled on the mail server level, not each individual client.

**Closed by ChristophWurst** 2018-02-15 13:55 UTC
