### ISSUE TITLE
option to de-activate the “important box”

### ISSUE THREAD

**Issue by tasstra** [nextcloud/mail#3503] opened 2020-09-01 19:14 UTC
an option to de-activate the “important box” would be nice :)

and show "favorites box" only when there are favourites.

Thanks!

**Comment by StCyr** [comment] 2020-09-07 12:16
Do you mean the "priority inbox" @tasstra ?

**Comment by ChristophWurst** [comment] 2020-09-07 12:21
yes

**Comment by mase76** [comment] 2020-10-08 17:46
I agree. I don't use that box, too.

**Comment by ChristophWurst** [comment] 2020-10-08 17:57
duplicate of https://github.com/nextcloud/mail/issues/3265

**Closed by ChristophWurst** 2020-10-08 17:57 UTC
Labels: 1. to develop, enhancement, help wanted

**Comment by ChristophWurst** [comment] 2020-11-03 19:39
@tasstra @mase76 please see https://github.com/nextcloud/mail/issues/3968 :v:
