### ISSUE TITLE
After entering Account setting klick on "+ New message" not working until refresh.

### ISSUE THREAD

**Issue by benkees** [nextcloud/mail#2601] opened 2020-02-03 13:00 UTC
### Expected behavior
After entering Account settings a klick on "+ New message" should show the form for a new mail.

### Actual behavior
After entering Account settings a klick on "+ New message" the right panel is emptied. Also after klicking e.g. on Inbox, afterwards the klick on "+ New message" is effectless. Refreshing the page and then klicking it, works again.

### Mail app

**Mail app version:** 1.1.2
**Mailserver or service:** IMAP/SMTP

### Server configuration

**Operating system**: Debian Buster

**Web server:** Apache

**DB** mysql Version: 10.3.18 

**PHP version:**  7.3.11 

**Nextcloud Version:** 17.0.3

#### Client configuration
**Browser:** tested on
Firefox 68.4.1esr (64-Bit)
Chrome Version 79.0.3945.130 (Offizieller Build) (64-Bit)
Chromium Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.11 (64-bit)

**Operating system:** Debian Jessie

**Comment by ChristophWurst** [comment] 2020-02-03 13:34
Duplicate of https://github.com/nextcloud/mail/issues/110

**Closed by ChristophWurst** 2020-02-03 13:34 UTC
Labels: 0. to triage, bug
