### ISSUE TITLE
Exception: DraftsController::update()

### ISSUE THREAD

**Issue by handkerchief333** [nextcloud/mail#9314] opened 2024-02-10 08:35 UTC
### Steps to reproduce

1. Use mail app 
2. create a message
3. check your drafts
4. check your logs

### Expected behavior

No error logs and not multiple drafts of the same message.

### Actual behavior

Many drafts are created on an ongoing basis, even though I don't want to and only write a message.
I also see error messages like this in the logs:

Error log:

```
[mail] Error: Exception: OCA\Mail\Controller\DraftsController::update(): Argument #2 ($accountId) must be of type int, null given, called in /home/www.example.com/web/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file '/home/www.example.com/web/apps/mail/lib/Controller/DraftsController.php' line 155 at <<closure>>

0. /home/www.example.com/web/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Mail\\Con ... "], "update")
1. /home/www.example.com/web/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\DraftsController", "update", ["OC\\AppFramewo ... "], ["{id}","mail.drafts.update"])
2. /home/www.example.com/web/lib/base.php line 1068
   OC\Route\Router->match("/apps/mail/api/drafts/%7Bid%7D")
3. /home/www.example.com/web/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: OCA\Mail\Controller\DraftsController::update(): Argument #2 ($accountId) must be of type int, null given, called in /home/www.example.com/web/lib/private/AppFramework/Http/Dispatcher.php on line 230 at <<closure>>

0. /home/www.example.com/web/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Mail\Controller\DraftsController->update("*** sensitive parameters replaced ***")
1. /home/www.example.com/web/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Mail\\Con ... "], "update")
2. /home/www.example.com/web/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Mail\\Con ... "], "update")
3. /home/www.example.com/web/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\DraftsController", "update", ["OC\\AppFramewo ... "], ["{id}","mail.drafts.update"])
4. /home/www.example.com/web/lib/base.php line 1068
   OC\Route\Router->match("/apps/mail/api/drafts/%7Bid%7D")
5. /home/www.example.com/web/index.php line 36
   OC::handleRequest()

PUT /index.php/apps/mail/api/drafts/%7Bid%7D
```

### Mail app version

3.5.4

### Operating system

FreeBSD 13.2

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

 Work on this is probably already underway:
 - https://help.nextcloud.com/t/email-drafts-problem/92083/5
 - #4768

**Comment by dasroo** [comment] 2024-02-20 18:45
Im seeing something very similar. 
Nextcloud 28.0.2

**Comment by joshtrichards** [comment] 2024-09-09 14:30
Duplicate of #9147

**Closed by joshtrichards** 2024-09-09 14:30 UTC
Labels: bug, 0. to triage
