### ISSUE TITLE
Draft text gets deleted when resizing window

### ISSUE THREAD

**Issue by StCyr** [nextcloud/mail#5729] opened 2021-11-17 12:21 UTC
### Expected behavior
When resizing the browser's window while writing a message, the text shouldn't get lost

### Actual behavior
If I shrink the width of the browser's window enough that the 2 left panels get hidden, at the exact moment when the 2 left panels disappear the text of the message I'm writing gets deleted.

### Mail app

**Mail app version:** 1.10.5

**Mailserver or service:** Not relevant

### Server configuration

**Operating system**: Debian 11

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 22.0.0

#### Client configuration
**Browser:** Firefox 94.0.1 64bits

**Operating system:** Windows 10 20H2

**Comment by dodedodo** [comment] 2022-03-20 11:42
This is definitely a problem. I've had multiple messages just disappear on me.  If you're lucky you'll find your message in the drafts folder. Otherwise, you just have to start over.

I'm surprised this bug hasn't gotten more traction yet. Does this only happen under specific circumstances maybe? Would be interesting to see if there are users that do not encounter this bug. React with a :+1: or :-1:  on the opening post if you can or cannot reproduce this. 

Resizing seems to re-initialize CKEditor. It also triggers a mailbox sync, but that's not a problem. Here's a bit of console output.
![image](https://user-images.githubusercontent.com/3252036/159159852-548c90d4-f846-444b-a3dd-d4a4371a327c.png)

**Comment by GretaD** [comment] 2022-03-21 10:17
we moved the "new message" composer into a modal, so resizing will not break the draft anymore. And the only way to write a new message is via modal. 
The modal will be released this week

**Closed** 2024-07-01 13:37 UTC
Labels: bug, 0. to triage
