### ISSUE TITLE
this.model.get(...)[0] is undefined.

### ISSUE THREAD

**Issue by trendzetter** [nextcloud/mail#911] opened 2018-05-16 12:39 UTC
## Steps to reproduce
1. Log on to nextcloud, click on the mail menu item
2. Select a folder containing a null email

## Expected behaviour
The emails in the folder are listed

## Actual behaviour
An error message appears on top inviting me to file a bug. The list of mails is not displayed. 

## Error
The logs in the backend do not display an error (in debug it says: "loading messages of folder <VHJhc2g=>"). I will try not to forget to check the serverlogs tonight.

Automatically added by the link from within Nextcloud:
```
this.model.get(...)[0] is undefined
onRender@https://xyz.mydomain.tld/apps/mail/js/build/build.js:225:1364
f@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:84546
triggerMethod@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:96256
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:105717
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
rt@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:97081
addChildView@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:115039
_addChild@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:114690
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
v.forEach@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:135421
_showCollection@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:112827
_renderChildren@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:112493
renderChildren@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:128504
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:128335
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
rt@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:97081
show@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:98154
showChildView@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:104088
onRender@https://xyz.mydomain.tld/apps/mail/js/build/build.js:283:9339
f@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:84546
triggerMethod@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:96256
render@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:105717
O@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141362
v.bind</r<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:141566
w/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:134777
rt@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:97081
show@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:98154
showChildView@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:104088
showFolderContent@https://xyz.mydomain.tld/apps/mail/js/build/build.js:283:15062
v@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:155118
g@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:154809
h@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:152755
s</o.Backbone</u.trigger@https://xyz.mydomain.tld/apps/mail/js/build/build.js:39:154702
l/<@https://xyz.mydomain.tld/apps/mail/js/build/build.js:68:18683

```

**Comment by Falseee** [comment] 2018-05-17 21:44
@ChristophWurst 
Meistens die Spam emails.

**Comment by trendzetter** [comment] 2018-05-25 20:21
I am still struggling to get an imap.log
This is in my config.php
  'debug' => true,
  'app.mail.imaplog.enabled' => true,
  'loglevel' => 0,
  'logfile' => '/var/www/nextcloud/data/nextcloud.log',
I am now getting lines in nextcloud.log. Is there anything else I should set to point imap.log to the right location and how to I do it?

**Comment by trendzetter** [comment] 2018-05-25 20:47
This is the spam that causes the issue:
[null-email.txt](https://github.com/nextcloud/mail/files/2040831/null-email.txt)

**Comment by terrar** [comment] 2018-05-26 15:17
I use a Mailadress without any "from" in my forum, as an noreply-address.
My Provider offers to disable pop and imap to only use smtp in the settings.
So i don't think that only spammer use this.

Just tested the case with nextcloud/mail, same error as trendzetter.
Other Mailclients (TB, Android Mail,..) work as expected.

**Comment by ChristophWurst** [comment] 2018-05-28 05:56
> Other Mailclients (TB, Android Mail,..) work as expected

It's a bug: https://github.com/nextcloud/mail/issues/911#issuecomment-389551789.

Pull requests with null checks before accessing the address are very welcome :)

**Comment by Pammetje** [comment] 2018-06-02 07:31
I also have this problem caused by an (internal) mail from root@freebsd  which is a valid e-mail address. I know I am not able to send this e-mail around the internet/world (because it has not TLD) , but its a valid (internal) e-mail address.

Please fix this bug !

**Comment by ChristophWurst** [comment] 2018-06-04 05:45
> Please fix this bug !

You are very welcome to help us with this issue.

**Comment by Pammetje** [comment] 2018-06-04 07:41
I would love to if I had the skills to do so

**Comment by trendzetter** [comment] 2018-06-04 11:19
This project is dead if the author isn't willing to fix such fatal bugs which are 2 or 3 obvious lines. I know some php and I could propose something but I guess then begins the "you are not following the style guide" answers. I don't think this is a sustainable attitude. It's progress or dying. Seeing these answers I guess it's dying.

**Comment by ChristophWurst** [comment] 2018-06-04 11:36
@trendzetter please see https://nextcloud.com/code-of-conduct/.

If you looked carefully you would have noticed that I've actually self-assigned to this ticket, which means I'm planning on working on this. Since it's not my only task at the moment I've not yet had a chance to tackle it, however. Therefore, anybody is very welcome to jump in and help. That's how open source works.

**Comment by Pammetje** [comment] 2018-06-04 11:50
@ChristophWurst, no problem, I will just wait. Of course there is more too do in life than 24/7 bugfixing open source code. :-)

**Comment by trendzetter** [comment] 2018-06-04 11:54
No-one should make demands that it should be faster but it appeared as if you were dropping it and just saying fix it or live it it. Self assigning can be have a placeholder function. Demanding pull requests is just as helpful as begging "fix it". Anyway, there seem to be not too much momentum in nextcloud, I am worried that ultimately I will have to return to big slurp corp because the alternative is buggy, lacking features and not progressing fast enough. If the major component mail is carried by a student in his spare time demanding pull requests from random bug submitters that isn't much of an organisational foundation. Some oos project manage to probably work like that but the bigger ones, I don't know, it's mostly associations backed by an umbrella of corporations.

**Comment by omegasupreme3** [comment] 2018-08-10 12:48
I am also experiencing this bug. Just our of curiosity (no pressure meant), can you tell us something about the status of this bug?

**Comment by ChristophWurst** [comment] 2018-08-13 09:13
I've not yet had time to work on this.

**Comment by foxbow** [comment] 2018-08-13 09:15
I wanted to check into this but unfortunately deleted the offending mail, so I no longer have a testcase at hand =/

**Comment by ChristophWurst** [comment] 2018-08-16 13:14
Fix can be found at https://github.com/nextcloud/mail/pull/1031.

**Closed** 2018-08-21 05:57 UTC
Labels: 3. to review, bug
