### ISSUE TITLE
Mail-Source View only 5 seconds

### ISSUE THREAD

**Issue by pc-erwin** [nextcloud/mail#8987] opened 2023-10-23 10:18 UTC
### Steps to reproduce

1.click on any e-Mail
2.click in E-Mail on 3dot-Menue
3.click on 'Quellen ansehen' or 'View Source'

### Expected behavior

a small window with the Source-Information will be open, but only for 5 seconds.
It is impossible to read any Information in 5 Seconds

### Actual behavior

a small window with the Source-Information will be open, but only for 5 seconds.
It is impossible to read any Information in 5 Seconds

### Mail app version

3.4.3

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment] 2023-10-23 11:14
Duplicate of https://github.com/nextcloud/mail/issues/8753

**Closed by ChristophWurst** 2023-10-23 11:14 UTC
Labels: bug, 0. to triage
