### ISSUE TITLE
'Mark all as read' for folder doesn't work

### ISSUE THREAD

**Issue by meichthys** [nextcloud/mail#7036] opened 2022-08-17 18:09 UTC
### Steps to reproduce

1. Open Mail App and ensure multiple messages are unread
2. Use context menu on folder and choose to "Mark all as read"
3. Verify if the messages have been marked as read

### Expected behavior

All messages should be marked as read and the number of unread emails should be 0

### Actual behavior

No emails are marked as read.

### Mail app version

1.13.8

### Mailserver or service

generic imap

### Operating system

Windows 10

### PHP engine version

PHP 8.1

### Additional info

Using Nextcloud VM
Trying to mark all as read in my "Archive" folder.

**Comment by meichthys** [comment] 2022-09-09 13:55
Just following up to indicate that this is still a bug as of Mail v2.0.0-beta.4 (NC 25 beta5)

**Comment by JuliaKirschenheuter** [comment] 2022-10-03 14:33
I've tested and its works. @st3iny could you reproduce it?

**Comment by meichthys** [comment] 2022-10-03 16:55
@JuliaKirschenheuter Which version are you testing against? 
I'm on ` 2.0.0-rc.1`

**Comment by st3iny** [comment] 2022-10-04 09:22
I just tested this on latest main and couldn't reproduce it. Please let us know which IMAP server are using. Also, could you please run `occ mail:account:diagnose <account-id>`. You can get the account id by running `occ mail:account:export <user-id>`.

**Comment by meichthys** [comment] 2022-10-04 11:25
@st3iny I'm using zoho:
imappro.zoho.com

Here's the diagnostics:

'''
IMAP capabilities:- ACL- AUTH- CHILDREN- CONDSTORE- ESEARCH- ID- IDLE- IMAP4REV1- LIST-EXTENDED- LIST-STATUS- LITERAL-- MOVE- NAMESPACE- SASL-IR- UIDPLUS- UNSELECT- WITHIN- XLISTAccount has 72006 messages in 12 mailboxes
'''

**Comment by JuliaKirschenheuter** [comment] 2022-10-04 13:16
Dear @meichthys 

we can't reproduce this bug anymore. Please update dependencies and please try to reproduce this bug again (after clicking to "Mark all as read" it needs 1-2 seconds).
If you would reproduce it, i will have a look again.

For now i'll close this ticket. Thank you!

**Comment by meichthys** [comment] 2022-10-04 17:05
@st3iny Is there a specific IMAP capability that is required for this to work? It works the default mail app on my phone, but not in nextcloud mail :/

@JuliaKirschenheuter I do see the "Mark all as read" option grey out for about 1-2 seconds, but even after waiting for a significant amount of time, the unread items are still unread:
![image](https://user-images.githubusercontent.com/10717998/193881909-3ea5a50d-accd-42a7-8147-67a6b724569c.png)

Afaik, all of my dependencies are up to date. 
I'm also using the Nextcloud VM and i believe that comes with the needed dependencies. Could it be that the mailbox is too large (over 60k messages)?

**Comment by ChristophWurst** [comment] 2022-10-05 12:59
Are the messages marked as read in other clients?

**Comment by miaulalala** [comment] 2022-10-05 16:35
The log points toward a PHP8.1 incompatibility:
```  "message": "Return type of OCA\\Mail\\AddressList::count() should either be compatible with Countable::count(): int, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at /var/www/nextcloud/apps/mail/lib/AddressList.php#108",```

**Comment by meichthys** [comment] 2022-10-05 22:16
> Are the messages marked as read in other clients?

Yes it works fine in thunderbird.

**Comment by meichthys** [comment] 2022-10-06 01:00
@miaulalala Here's the contents around line 108 in the file:

```
        #[ReturnTypeWillChange]
        public function jsonSerialize() {
                return array_map(function (Address $address) {
                        return $address->jsonSerialize();
                }, $this->addresses);
        }

        /**
         * @return int
         */
        public function count() {                        <---------- Line 108
                return count($this->addresses);
        }

```

**Comment by ChristophWurst** [comment] 2022-10-06 06:14
> > Are the messages marked as read in other clients?
> 
> Yes it works fine in thunderbird.

If *mark all as read* here shows all messages as rad in Thunderbird problem is not a missing update of the messages on IMAP but that our app doesn't reflect the changes.

**Comment by meichthys** [comment] 2023-02-15 14:12
Just following up here to indicate that i'm still seeing this issue in v2.3.0A1

**Comment by auroraanna** [comment] 2023-08-22 12:24
So the only issue now is that you have to force re-fresh to see the change?

**Comment by auroraanna** [comment] 2023-08-22 12:31
I think the performance could be improved by not sending a request for every envelope to the server but instead sending one request and having the server change every envelope.

**Comment by auroraanna** [comment] 2023-08-23 10:26
I don't know the backend so if this was to be implemented then someone else'd need to do it.

**Closed** 2023-09-12 11:41 UTC
Labels: bug, 3. to review, regression
