### ISSUE TITLE
Mail server settings change does not enable save button

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#9931] opened 2024-07-28 14:10 UTC
### Steps to reproduce

1. Change IMAP server port
2. Type IMAP password again (do not remember if it's required to enable save)

### Expected behavior

"Save" button is enabled

### Actual behavior

"Save" button is still disabled

### Mail app version

3.7.5

### Mailserver or service

imap.free.fr

### Operating system

Windows

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

NC 29.0.4 from docker compose

**Comment by Forza-tng** [comment] 2024-08-08 13:49
As a workaround you can use `occ mail:account:update --imap-password xx --smtp-password xx <id>`. The `id` can be found in the sql database, table `oc_mail_accounts`.

**Comment by ChristophWurst** [comment] 2024-08-08 14:16
Duplicate of https://github.com/nextcloud/mail/issues/2600

**Comment by Forza-tng** [comment] 2024-08-08 14:58
> Duplicate of #2600

I do not think that is the same issue. The issue now is that it is not possible to save changes even if password was entered. Ir perhaps we need to type in both imap AND smtp passwords to be able to save?

**Comment by ChristophWurst** [comment] 2024-08-08 15:07
Yes, both. Try it

**Closed** 2024-08-08 18:45 UTC
Labels: bug, 0. to triage
