### ISSUE TITLE
Activity Notification emails do not display properly in mail app: 2 scroll  bars, extended header

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/mail#1052] opened 2018-08-23 09:05 UTC
### Expected behavior
Activity notification should appear similar to how it does with other webmail clients
see screenshot from gmail webclient
![activity-mail1](https://user-images.githubusercontent.com/21287394/44515306-cad52f00-a6f4-11e8-9f50-d289a8fce4be.png)

### Actual behavior
2 scrollbars with actual content at bottom of the second scroll bar with very long scroll time
![activity-mail2](https://user-images.githubusercontent.com/21287394/44515264-a5482580-a6f4-11e8-8902-2593565e2eab.png)

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
0.8.3
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail (GSuite)
**Number of accounts:** (e.g. 1 or 2)
1

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 18,04
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite, PostgreSQL,...)
MySQL
**PHP version:** (e.g. 7.0)
7.+
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
13.0.5
**Updated from an older version or fresh install:**
Fresh Install

#### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu desktop 18.04

**Comment by jancborchardt** [comment] 2020-02-27 12:08
Closing this as duplicate ofhttps://github.com/nextcloud/mail/issues/599 which also has a bounty on it already. :)

**Closed by jancborchardt** 2020-02-27 12:08 UTC
Labels: 1. to develop, bug
