### ISSUE TITLE
Nextcloud Mail not showing all emails

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#605] opened 2017-11-07 13:43 UTC
As I noticed last week, the mail app isn't showing all emails for me. Some mails are randomly not shown in my inbox.

This is my productive mail. @ChristophWurst Happy to debug this with you or grant you access somehow to the SQL database if it would help.

**Comment by LukasReschke** [comment] 2017-11-07 13:44
The mails are shown in Thunderbird though.

**Comment by ChristophWurst** [comment] 2017-11-07 14:40
Does that happen in the unified inbox? I remember a bug report where someone didn't see mail with special characters in the subject.

**Comment by LukasReschke** [comment] 2017-11-07 16:02
Unified Inbox? I only have one Inbox, I guess ;-)

**Comment by ChristophWurst** [comment] 2017-11-07 16:26
Okay, then it's a different bug.

**Comment by ashgoodman** [comment] 2018-08-31 04:58
I have this issue as well. Messages will appear, them vanish. Only to reappear on page refresh

**Comment by ChristophWurst** [comment] 2018-09-01 09:41
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

**Comment by ashgoodman** [comment] 2018-09-01 16:28
Will do, will post when I next notice the issue occuring

**Comment by ChristophWurst** [comment] 2019-12-17 16:48
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version after that, feel free to reopen.

**Closed by ChristophWurst** 2019-12-17 16:48 UTC
Labels: 1. to develop, bug
