### ISSUE TITLE
Remember selected inbox (save UI state)

### ISSUE THREAD

**Issue by ya-d** [nextcloud/mail#5515] opened 2021-09-08 16:56 UTC
### Feature Request

Would be great if Mail could remember the last active inbox and open the same inbox when returning to the app. Task for example remembers which list you worked in.

Would also help bypass priority inbox or give users choice between a single or shared inbox without additional settings. (See #3265)

Thanks for considering and all the great work ❤️

**Comment by ChristophWurst** [comment] 2021-09-08 17:43
Duplicate of https://github.com/nextcloud/mail/issues/1665

**Closed by ChristophWurst** 2021-09-08 17:43 UTC
Labels: enhancement, 0. to triage
