### ISSUE TITLE
Display of subfolders

### ISSUE THREAD

**Issue by Django-BOfH** [nextcloud/mail#2833] opened 2020-03-30 17:18 UTC
### Expected behavior
The column width of the folder view should either adjust dynamically or you should at least be in a position to manually change the column width yourself.

### Actual behavior
The column width of the folder view is fixed and cannot be changed. So only a fraction of the folder structure is displayed and you can only guess in which subfolder you are.
![Bildschirmfoto zu 2020-03-30 19-12-51](https://user-images.githubusercontent.com/6991904/77941499-8ccdc300-72ba-11ea-824a-165c0b191149.png)
The usability of the mail plugin is therefore zero.

### Mail app

**Mail app version:** 1.1.4

**Mailserver or service:** mailserver.guru

### Server configuration

**Operating system**: Centos 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 18.0.3

#### Client configuration
**Browser:** Firefox 74.0

**Operating system:** Fedora 31

**Comment by ChristophWurst** [comment] 2020-03-31 07:37
@jancborchardt

**Comment by jancborchardt** [comment] 2020-03-31 10:38
This is not an issue with the width of the navigation, but with how we display these subfolders:
- The "Mailinglisten" folder should not be displayed as a subfolder of the inbox, but as a regular folder down the list. This will already regain the space lost by a) indenting it and 2) writing "INBOX/" in front of it.
- I’m a bit confused about the 3rd part here which just says "Mail/". Does it belong to the folder name "Mailinglisten/Mail"?
- Then, all the text where now barely 2 characters are readable of should then be visible as once-indented subfolders of a first-level folder called "Mailinglisten" (or Mailinglisten/Mail depending on what the naming is).

**Comment by jancborchardt** [comment] 2020-03-31 10:40
Actually this seems to be a duplicate of **Subfolders shown repeatedly with full path (dovecot IMAP server) #689**. Can you confirm @Django-BOfH?

**Comment by Django-BOfH** [comment] 2020-03-31 11:57
WOW, an three years old issue? 
Well, as it is now, it's definitely not usable.

Basically, it's like a very thick encyclopedia/book with a torn out table of contents. Sure, the contents are still there, but finding the place is much more difficult. At some point you will throw the book away because you have lost interest in it.  

![nextcloud-mail](https://user-images.githubusercontent.com/6991904/78022120-b50a0000-7354-11ea-89ec-fd844addf076.png)

**Comment by jancborchardt** [comment] 2020-03-31 12:31
Please consider that you are talking to actual humans here, and that we have been friendly even though the comment on Twitter was quite horrible.

Yes, sometimes issues are older cause development takes time and things need to be prioritized. Still we are pro-active. Feel free to throw the book away if you like, that is better than needing to hear complaints from people for work you give away freely.

**Comment by Django-BOfH** [comment] 2020-03-31 13:23
My comment on Twitter was horrible? Well, that's how I am, the most horrible person you can imagine. :) No, certainly not. In a short message, besides the content, to transport emotions is not so easy ... at least for me.

I'm not a programmer myself, but from more than 10 years of experience with mail as postmaster, I can only report what works and what definitely doesn't work. To discuss every 2 years that I still don't consider the mail client ready for production (and to give reasons for this) and therefore can't recommend it is of course one way. I can't rewrite the MUA or the frontend for this myself, I can only tell you that it can't be used as it is at the moment. 
For easier understanding I showed you a part of my inbox and also compared it with a book/encyclopedia. If this helps you to understand the actual problem, then I'm glad that I contributed to the solution of the problem.

**Comment by Django-BOfH** [comment] 2020-03-31 17:33
HI Jan-Christoph,

thank you first of all for taking the time to deal with the existing problem!

I have inserted the view of a Thunderbird MUA below. It should be displayed in the same way as Outlook, Thunderbird, kmail, Horde, roundcube and even Apple, but unfortunately the mail-plugin from nextcloud is not.

Should the MUA plugin ever display such folder structures correctly, we can also address other topics, such as maintaining and managing sieve rules on the IMAP server. 

But as long as the view is unfortunately a little bit buggy in my eyes at the moment, I can't approve of the application. But I look forward to the day when the topic will be implemented ...

Have a nice day!
Django

**Comment by Django-BOfH** [comment] 2020-03-31 17:39
Oh yes, assuming that the esteemed programming team intends to take up the issue and put it on the agenda / todo list, you are welcome to leave the issue(s) open.

On the other hand, it would of course be perfectly okay if I close the issue immediately if it is foreseeable that nothing can/should happen here in the near future.

**Comment by ph00lt0** [comment] 2020-06-29 17:31
I have a similar issue. The sub folders are displayed as INBOX.Folder name or INBOX.Folder name. Folder name etc.

**Comment by ChristophWurst** [comment] 2020-06-29 17:36
:point_down: 

> Actually this seems to be a duplicate of **Subfolders shown repeatedly with full path (dovecot IMAP server) #689**

:point_up:

**Closed by ChristophWurst** 2020-06-29 17:36 UTC
Labels: 0. to triage, bug
