### ISSUE TITLE
Allow/block certain mail providers

### ISSUE THREAD

**Issue by diemelone** [nextcloud/mail#4601] opened 2021-02-26 13:37 UTC
Admins should be able to set certain mail providers on a blocklist/allowlist

eg if you use nc for a certain club/company/etc. you wouldn't want any private emails taking up space, therefore I'd like to only allow accounts ending with @example.com, @example.org, ...

**Comment by ChristophWurst** [comment] 2021-02-26 15:21
sounds like an enterprise feature

**Comment by ChristophWurst** [comment] 2021-02-26 15:40
duplicate of https://github.com/nextcloud/mail/issues/4317

**Closed by ChristophWurst** 2021-02-26 15:40 UTC
Labels: 0. to triage, enhancement, enterprise

**Comment by diemelone** [comment] 2021-02-26 16:33
Almost, #4317 was just a whitelist, I'm suggesting a whitelist aswell.
> 
> 
> duplicate of #4317
