### ISSUE TITLE
The images have been blocked to protect your privacy

### ISSUE THREAD

**Issue by kieeps** [nextcloud/mail#6008] opened 2022-02-02 09:56 UTC
### Expected behavior
The image should be shown

### Actual behavior
When i use brave browser i get the message "The images have been blocked to protect your privacy" even though i have "always show images from...." 
When i try to view it in firefox instead i dont even get the message, it just wont show.

### Mail app
1.11.6

### Mailserver:
dovecot/postfix

### Server configuration

Nextcloud docker container from linuxserver.io

Alpine 

Nginx 1.20.2

MariaDB 10.5.13

PHP 7.4.26

Nextcloud 23.0.0

#### Client configuration
Brave 1.35.89
Firefox 96.0.3

**Operating system:** 
Arch Linux / Windows

**Comment by GretaD** [comment] 2022-02-02 10:48
I cannot reproduce this error, but i found an error with the threading when the message has images, i will see if this is somehow connected. 

Can you please send us the nextcloud.log or/and console log when you open the message that is suppose to show the image.

Also, please check if its on your Account Settings - Trusted Senders, the email/domain is registered.

**Comment by kieeps** [comment] 2022-02-02 11:41
turns out the mail contains "External images", i tried it in another client and it also complained :) that app let me view them anyway thoug... any way to change the strictness?

**Comment by ChristophWurst** [comment] 2022-02-02 13:08
if the email doesn't contain anything sensitive you may share it with us publicly as an .eml export or similar

**Comment by kieeps** [comment] 2022-02-03 18:05
> if the email doesn't contain anything sensitive you may share it with us publicly as an .eml export or similar

yes! sorry for the late reply but the particular email i had problems with had a lot of private info in it, but basically i'w only noticed it in mails from "Patreon", and today i got one that didn't contain anything sensitive :) but it has the same problems as before.
[remote_content.tar.gz](https://github.com/nextcloud/mail/files/7997102/remote_content.tar.gz)

**Comment by kieeps** [comment] 2022-02-03 18:08
i'll also add a screenshot of how it looks after "always show images from patron"

![how_it_looks_like](https://user-images.githubusercontent.com/8442058/152402821-6debe3cc-07c9-499c-ba8e-f24628b931d6.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-05-23 03:39
I want to disable this. Privacy is not important to me; such inconvenience should consequently be configurable.

**Comment by meichthys** [comment] 2022-11-29 15:30
Just for reference, I'm still seeing this in Mail v2.1.2
I'm using Firefox 107, and when clicking "Show images always for <domain>", i do see the images, but if i navigate away from the email and back to it, then the images are hidden again.

For reference, even the emails sent by nextcloud are blocked:
![image](https://user-images.githubusercontent.com/10717998/204571882-d640d67b-e795-43b6-acea-2ae7ff4bb0db.png)
![image](https://user-images.githubusercontent.com/10717998/204571892-a6d7f467-7df4-4e53-8b25-b0c7c671b0f4.png)

**Comment by GretaD** [comment] 2022-11-30 15:19
I tried to reproduce this till stable1.14 and all looks fine. 
@meichthys after you click always show for.. is that email/domain shown on Account Settings->Trusted users? Please check before reloading and after reloading if its saved on trusted users.

**Comment by meichthys** [comment] 2022-11-30 17:56
After updating to 2.1.3 everything is working fine. Perhaps it was some weird caching issue. I guess we can close this?

**Closed** 2022-11-30 18:01 UTC
Labels: bug, 1. to develop, needs info
