### ISSUE TITLE
mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "windows-1250"

### ISSUE THREAD

**Issue by jejusek** [nextcloud/mail#8529] opened 2023-06-07 06:27 UTC
### Steps to reproduce

1.
2.
3.

### Expected behavior

It shows me a text of message.

### Actual behavior

The message "not found" is given instead of the text of the message.

```
Log:
[mail] Error: Exception: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "windows-1250" in file '/var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php' line 464 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1058
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

Caused by:

ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "windows-1250" at <<closure>>

 0. /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php line 464
    mb_convert_encoding()
 1. /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php line 395
    OCA\Mail\IMAP\ImapMessageFetcher->loadBodyData()
 2. /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php line 346
    OCA\Mail\IMAP\ImapMessageFetcher->handleTextMessage()
 3. /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php line 379
    OCA\Mail\IMAP\ImapMessageFetcher->getPart()
 4. /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php line 341
    OCA\Mail\IMAP\ImapMessageFetcher->handleMultiPartMessage()
 5. /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php line 201
    OCA\Mail\IMAP\ImapMessageFetcher->getPart()
 6. /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php line 297
    OCA\Mail\IMAP\ImapMessageFetcher->fetchMessage()
 7. <<closure>>
    OCA\Mail\IMAP\MessageMapper->OCA\Mail\IMAP\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php line 298
    array_map()
 9. /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php line 84
    OCA\Mail\IMAP\MessageMapper->findByIds()
10. /var/www/nextcloud/apps/mail/lib/Service/MailManager.php line 194
    OCA\Mail\IMAP\MessageMapper->find()
11. /var/www/nextcloud/apps/mail/lib/Controller/MessagesController.php line 220
    OCA\Mail\Service\MailManager->getImapMessage()
12. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Mail\Controller\MessagesController->getBody()
13. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
14. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
15. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
16. /var/www/nextcloud/lib/base.php line 1058
    OC\Route\Router->match()
17. /var/www/nextcloud/index.php line 36
    OC::handleRequest()
```

GET /apps/mail/api/messages/34362/body
from 192.168.1.236 by Andrzej at 2023-06-06T16:27:53+00:00

### Mail app version

 3.1.1

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

<html><body>

Error | mail | Exception: mb_convert_encoding():  Argument #3 ($from_encoding) contains invalid encoding "windows-1250"  in file '/var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php'  line 464
-- | -- | --

</body>
</html>

**Comment by ChristophWurst** [comment] 2023-06-07 08:33
Duplicate of https://github.com/nextcloud/mail/issues/1037

**Closed** 2023-06-07 08:33 UTC
Labels: bug, 0. to triage
