### ISSUE TITLE
Mail crashes next cloud at next start

### ISSUE THREAD

**Issue by rasugo** [nextcloud/mail#883] opened 2018-04-28 16:22 UTC
### Steps to reproduce
1. Enable Mail
2. Configure an IMAP account
3. Test the account navigating the mails
4. reboot the machine
5. when going to the login page

### Expected behaviour
Login screen should appear with the username/password request

### Actual behaviour
empty page with some php code.

### Mail app

**Mail app version: 0.7.10** (see apps admin page)

**Mailserver or service: OVH** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Number of accounts: 1**

### Server configuration

**Operating system: Debian**

**Web server: NGINX**

**Database: MySQL**

**PHP version: **

**Version:** (see admin page)

**Updated from an older version or fresh install:**
Update from previous mail app

**List of activated apps:**
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.72.41"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.72.41\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}
</details>

#### Client configuration
**Browser: Safari**

**Operating system: Mac OS X 10.13.4**

##### Web server error log
Class 'OCA\Mail\HordeTranslationHandler' not found

##### Server log (data/nextcloud.log)
<details>
empty
</details>

##### IMAP log (data/horde_imap.log)
<details>
empty
</details>

##### SMTP log (data/horde_smtp.log)
<details>
empty
</details>

##### Browser log
<details>
not available
</details>

**Comment by ChristophWurst** [comment] 2018-04-30 07:30
> Class 'OCA\Mail\HordeTranslationHandler' not found

That should not have happened. How did you install the app?

**Comment by ChristophWurst** [comment] 2018-04-30 07:31
The Nextcloud mail app offers an extensive logging system to make it easier identifying and tracking down bugs. Please enable [debug mode](https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode) and set the log [level to debug](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/logging_configuration.html) in your admin settings. Then, try to reproduce your issue and take another look at `data/nextcloud.log`, `data/horde_imap.log` and `data/horde_smtp.log`.

In your case, I'm especially interested in the nextcloud.log file. It definitely should contain a line if this fatal error. If not, your setup might have some severe issues (e.g. due to misconfiguration).

**Comment by ChristophWurst** [comment] 2018-11-08 10:37
No info provided -> closing

**Closed by ChristophWurst** 2018-11-08 10:37 UTC
Labels: 0. to triage, needs info
