### ISSUE TITLE
Can't send mail because send button hidden

### ISSUE THREAD

**Issue by pdwonline** [nextcloud/mail#887] opened 2018-05-02 09:17 UTC
I am running nextcloud from docker (wonderfall/nextcloud) and using Firefox, but also reproduced thus using chrome.  When using the chat app in Nextcloud, the send button from the mail application dissapears behind the internal chat column on the right hand side.

### Steps to reproduce
1. Enable the chat app in nextcloud and see that the chat users are shown on the right
2. start the mail application and create a new mail
3. Notice that the send mail button is hidden.

### Expected behaviour
Send button should remain visible even if the viewport is smaller due to the chat window

### Actual behaviour
Send button is aligned absolute. therefore it remains right even if the viewport is resized

### Mail app
**Mail app version: 0.7.10

**Comment by ChristophWurst** [comment] 2018-05-07 06:14
Duplicate of #654

**Closed by ChristophWurst** 2018-05-07 06:14 UTC
