### ISSUE TITLE
Keeps loading inbox forever "error: MailboxLockedError: undefined"

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/mail#3830] opened 2020-10-17 08:22 UTC
### Expected behavior

the mail app should just load my inbox like all the other folders

### Actual behavior

Trying to load the inbox of my main account, from a dovecot IMAP server running on the same machine, It keeps loading forever and never finishes. A side effect is that entering the mail app by clicking the envelope icon in the menu bar doesn't work or takes very long. The only way to  For other subfolders of the same account, and for other accounts it work, but not for the inbox. Tried with Firefox and with Chrome. There are 2500 messages in the inbox. Some of the subfolders have more messages in them.  
With previous versions of the mail app, there had been no issues.

In the firefox developer tools, when I turn on network analysis I see error messages like

```
[INFO] mail: Mailbox is locked 
{…}
​
app: "mail"
​
error: MailboxLockedError: undefined
​
uid: "**********"
​
<prototype>: Object { … }
ConsoleLogger.js:46:18

```
This message keeps repeating itself over and over

### Mail app

**Mail app version:**  1.50

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

Self-hosted dovecot 2.3.7.2, on the same server as the nextcloud installation, on Ubuntu 20.04

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** Mariadb

**PHP version:** 7.4

**Nextcloud Version:** 20.0.0

#### Client configuration
**Browser:** tried Firefox 81.0 and Chrome  86

**Operating system:** Debian GNU/Linux Bullseye

**Comment by ChristophWurst** [comment] 2020-10-19 06:46
> Mailbox is locked

This is not the actual error. The error happened before and left the mailbox locked. Take another look at your logs. There should be something logged with level error.

You can also run the sync from the CLI with `occ mail:account:sync <id>` as that will give you all the debug output.

**Comment by vasyugan** [comment] 2020-10-21 07:58
OK, here is what I have for you:

https://gist.github.com/vasyugan/390db5899f7a49a2e55686df91a43f13

**Comment by ChristophWurst** [comment] 2020-10-21 08:02
Thanks. So it is a duplicate of https://github.com/nextcloud/mail/issues/2968.

**Closed** 2020-10-21 08:02 UTC
Labels: 0. to triage, bug
