### ISSUE TITLE
Save Mail to Nextcloud folder directly

### ISSUE THREAD

**Issue by tobefrank1** [nextcloud/mail#8647] opened 2023-07-24 10:51 UTC
### Is your feature request related to a problem? Please describe.

It is possible to download a mail to the active computer. 

But it is not possible to save to a Nextcloud folder directly.  
This would be very handy, if you like to keep the information in the cloud and like to use the e-mail as a reference or part of a report.

If I am wrong, please tell me how to save the mail to the cloud directly.

### Describe alternatives you've considered

Of course, one can download the mail to the computer and upload it to the Nextcloud. 
But this 

### Additional context

Your mail program has evolved allot over the time, please keep up your good work

**Comment by ChristophWurst** [comment] 2023-07-24 13:36
Dup of https://github.com/nextcloud/mail/issues/675

**Comment by tobefrank1** [comment] 2023-08-02 06:52
As it is a "not planned feature" for the app....  

Just to let people know, snappy mail has this feature and is also well integrated in Nextcloud.

**Comment by ChristophWurst** [comment] 2023-08-02 07:11
Duplicate of https://github.com/nextcloud/mail/issues/675

**Closed by ChristophWurst** 2023-08-02 07:11 UTC
Labels: enhancement, 0. to triage
