### ISSUE TITLE
Error updating App to 0.7.4

### ISSUE THREAD

**Issue by ppascher** [nextcloud/mail#587] opened 2017-10-31 11:22 UTC
Hello

I tried to apply yesterday's mail app update (0.7.4 – 2017-10-30) coming from 0.7.3 via GUI. I didn't pay much attention and just noticed today that my server is still in maintenance mode.
Sorry for the sparse information, can provide more when I get home (nextcloud 12.0.3, php 7.1, postgresql 10).

When I open my nextcloud server's url I am greeted with:
```
App update required
These apps will be updated:

    Mail (mail)

Please make sure that the database, the config folder and the data folder have been backed up before proceeding. 
```

When I proceed to click on 'Start update' I get a message saying:
```

Update to 12.0.3

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_activity_activity_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_activity_activity_id... ^
Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_activity_activity_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT 
min_value, increment_by FROM 
"oc_activity_activity_id... ^
The update was unsuccessful. Please report this issue to the Nextcloud community.

```

### Steps to reproduce
1. Update Mail App from 0.7.3 to 0.7.4 via web gui

### Expected behaviour
App should be updated

### Actual behaviour
update is unsuccessful, server remains in maintenance mode

**Comment by ChristophWurst** [comment] 2017-10-31 11:50
Hi,

from the information you've given I assume this is a duplicate of https://github.com/nextcloud/server/issues/5930.

Thanks for reporting

**Closed by ChristophWurst** 2017-10-31 11:50 UTC

**Comment by ppascher** [comment] 2017-10-31 20:23
Thanks for your hint. This seems to be exactly the issue. 
Changing "nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php" according to [this comment](https://github.com/nextcloud/server/issues/5930#issuecomment-339495122) fixed the issue for me.
