### ISSUE TITLE
Out of office support

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/mail#1599] opened 2019-03-12 16:32 UTC
@konisolde want this feature :grin: :tada: 

:wave: @ChristophWurst

**Comment by ChristophWurst** [comment] 2019-03-12 17:10
As this can be done [with Sieve](https://wiki2.dovecot.org/Pigeonhole/Sieve/Examples#Vacation_auto-reply), this is a duplicate of https://github.com/nextcloud/mail/issues/44 :)

**Closed by ChristophWurst** 2019-03-12 17:10 UTC
Labels: 0. to triage, enhancement
