### ISSUE TITLE
Mail-app disappeared after update to Nextcloud 20.0.6

### ISSUE THREAD

**Issue by schorsch2** [nextcloud/mail#4408] opened 2021-01-26 06:41 UTC
### Expected behavior
Mail app in the list of avaiable apps

### Actual behavior
mail app can not be found

### Mail app

**Mail app version: 1.8.0

**Mailserver or service:postfix

### Server configuration

**Operating system**: docker container

**Database:** PostgreSQL

**PHP version:** 20.0.6

**Nextcloud Version:**  20.0.6

#### Client configuration
**Browser:** Firefox 84.0.2

**Operating system:**Windows

`

Error | core | Exception: Could not download app mail/var/www/html/lib/private/legacy/OC_App.php - line 422: OC\Installer->downloadApp("mail")/var/www/html/lib/private/Updater.php - line 462: OC_App->enable("mail")/var/www/html/lib/private/Updater.php - line 266: OC\Updater->upgradeAppStoreApps([ "bruteforc ... "], true)/var/www/html/lib/private/Updater.php - line 130: OC\Updater->doUpgrade("20.0.6.1", "20.0.5.2")/var/www/html/core/Command/Upgrade.php - line 255: OC\Updater->upgrade()/var/www/html/3rdparty/symfony/console/Command/Command.php - line 255: OC\Core\Command\Upgrade->execute(Symfony\Comp ... {}, Symfony\Comp ... {})/var/www/html/3rdparty/symfony/console/Application.php - line 1000: Symfony\Component\Console\Command\Command->run(Symfony\Comp ... {}, Symfony\Comp ... {})/var/www/html/3rdparty/symfony/console/Application.php - line 271: Symfony\Component\Console\Application->doRunCommand(OC\Core\Comm ... }}, Symfony\Comp ... {}, Symfony\Comp ... {})/var/www/html/3rdparty/symfony/console/Application.php - line 147: Symfony\Component\Console\Application->doRun(Symfony\Comp ... {}, Symfony\Comp ... {})/var/www/html/lib/private/Console/Application.php - line 215: Symfony\Component\Console\Application->run(Symfony\Comp ... {}, Symfony\Comp ... {})/var/www/html/console.php - line 100: OC\Console\Application->run()/var/www/html/occ - line 11: require_once("/var/ww
-- | -- | --

`

**Comment by ChristophWurst** [comment] 2021-01-26 07:48
Duplicate of https://github.com/nextcloud/mail/issues/4383

**Closed by ChristophWurst** 2021-01-26 07:48 UTC
Labels: 0. to triage, bug
