### ISSUE TITLE
Abnormal mail view

### ISSUE THREAD

**Issue by qdrop17** [nextcloud/mail#3882] opened 2020-10-24 07:55 UTC
Hello everyone.

I'm using the most recent version of Mail and the most recent version of Chrome Unfortunately the view of the mail is pretty buggy:

![image](https://user-images.githubusercontent.com/42340241/97071193-fa3a9b80-15de-11eb-870b-6b9a6c0a5594.png)

It's cut off in about 1/3rd of the screen, leaving the rest just blank.

Is this a known bug? Any help is appreciated.

Best

**Comment by Lettly** [comment] 2020-10-25 07:14
I have the same problem 
![image](https://user-images.githubusercontent.com/24634460/97101020-05063680-169a-11eb-85a1-fce58d2584e3.png)

**Comment by st3iny** [comment] 2020-10-25 16:06
Possible duplicate of #3878

**Comment by st3iny** [comment] 2020-10-25 18:35
This bug was fixed via #3697 and backported to v1.5. The fix will be included in the next release (v1.5.1).

**Closed** 2020-10-26 10:30 UTC
Labels: bug, duplicate
