### ISSUE TITLE
store attachements in incoming mails automatically in a folder

### ISSUE THREAD

**Issue by fds2610** [nextcloud/mail#4304] opened 2020-12-31 15:07 UTC
### Feature Request

When receiving incoming mails, detach attachments automatically and store in a folder. Add external link to email to attachment.

#### Summary

to automize mail work, I want to store all attachments in a folder structure like
documents
 +-- contracts
 +-- vehicles
   +---- car
   +---- trailer
 +-- insurances
   +---- health insurance
   +---- retirements
   +---- car insurance
 +-- etc...

This means I have to detach all important attachments from emails and sort into my folder structure. Now I would find it more convenient if all incoming attachements were automatically stored into an "inbox" folder in my structure, so i will just have to move them afterwards but will not have to search for important documents in my mails if i forgot to store the attachements.

In a future version I would love to add rules to store attachements automatically in the correct folder depending on sender orsubject or mail content... !?

**Comment by ChristophWurst** [comment] 2021-02-23 15:45
duplicate of https://github.com/nextcloud/mail/issues/249

so this isn't a supported or planned feature, but we want to soon look into more workflow integrations and then this should be possible to define as user workflow.

**Closed by ChristophWurst** 2021-02-23 15:45 UTC
Labels: 0. to triage, enhancement
