### ISSUE TITLE
Options to not auto mark as read when opening a message

### ISSUE THREAD

**Issue by junpet** [nextcloud/mail#3785] opened 2020-10-09 14:59 UTC
### Feature Request

Currently if you open an unread message, it will be marked as read. It would be nice, if there would be an option in the Settings like `Opt out auto mark as read` or something like that. The default would be false/uncheck, like how currently things work.

#### Summary

Option to disable auto mark as read messages when opening them.

**Comment by ChristophWurst** [comment] 2020-10-14 09:05
Duplicate of https://github.com/nextcloud/mail/issues/3723

**Closed by ChristophWurst** 2020-10-14 09:05 UTC
Labels: 0. to triage, enhancement

**Comment by ChristophWurst** [comment] 2026-03-12 07:36
Sure, you can open a feature request
