### ISSUE TITLE
More sources to get avatars from [$15]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#236] opened 2016-12-14 01:15 UTC
Oftentimes the avatars in the inbox look like this:
![capture du 2016-12-14 02-11-14](https://cloud.githubusercontent.com/assets/925062/21165944/bc048644-c1a2-11e6-937b-a3294f6489b0.png) ![capture du 2016-12-14 02-10-47](https://cloud.githubusercontent.com/assets/925062/21165945/bc1c720e-c1a2-11e6-8567-cb2e6e7f69f5.png) ![capture du 2016-12-14 02-10-21](https://cloud.githubusercontent.com/assets/925062/21165946/bc1fce4a-c1a2-11e6-9c4e-f648d8fe64cf.png)

That’s really sad but unavoidable. You’re not going to have all of these mails in your Contacts, especially not from notifications of Twitter or Meetup or Facebook or Wikimedia, DHL, Amazon, etc blabla.

So how about when there’s no avatar we try to get something from another source?
1. Contacts app / federation (for people you know) cc @schiessle 
2. Gravatar (if people use that)
3. Favicon of the domain (especially good for notifications)
4. More …?

cc @BernhardPosselt @nextcloud/news since you fetch the favicons of sites in the News app.

**Comment by jancborchardt** [comment] 2017-07-04 13:18
Getting the favicon of the domain as a fallback at least for popular services like Twitter notifications, Amazon mails, Github notifications, Instagram etc. would already make it a lot nicer. :)

**Comment by ChristophWurst** [comment] 2017-08-28 09:04
@jancborchardt dude, again you filed a duplicate of your own issue #463 🙈 

But well, now @jakobsack gets $50+$15 🚀

**Comment by ChristophWurst** [comment] 2017-11-20 07:37
Fixed by #469

**Closed by ChristophWurst** 2017-11-20 07:37 UTC
Labels: 3. to review, bounty, design, enhancement
