### ISSUE TITLE
Opening emails in sub folder

### ISSUE THREAD

**Issue by tanghus** [nextcloud/mail#1888] opened 2019-08-02 08:42 UTC
### Expected behavior
When expanding a sub folder, I should be able to directly click on and open an email from the message list.

### Actual behavior
The email never loads. No error messages.
One way to get it to load, is to first expand the folder, then click on the same folder and **then** click on the sub folder you originally wanted to open. Then the message list is populated and the first message loads.
The other way around doesn't work, e.g. first clicking on the folder, the expanding it.

Also, sub folders are prefixed with the name of the parent folder, e.g.
```
Notifications
    Notifications.Nextcloud
    Notifications.Github
    ...
```
Besides these few issues, the app has really improved! Thanks and :+1: 

### Mail app
**Mail app version:**
0.15.1

**Mailserver or service:**
Dovecot

### Server configuration
I'm on a shared hosting, so I don't have all info

**Operating system**: (e.g. Debian 8)
`uname -a` says: `Linux ngcobalt83.example.com 4.19.46 #1 SMP Wed May 29 12:40:11 CEST 2019 x86_64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz GenuineIntel GNU/Linux`
No idea which distro.

**Web server:** (e.g. Apache, Nginx,...)
Some apache version

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySQL/MariaDB. Not sure.

**PHP version:**
7.1

**Nextcloud Version:**
16.0.2

#### Client configuration
**Browser:**
Firefox 68.0.1

**Operating system:** (e.g. Arch Linux)
Kubuntu 19.04

**Comment by ChristophWurst** [comment] 2019-08-05 09:28
> Besides these few issues, the app has really improved! Thanks and +1

:heart:

**Comment by th3raid0r** [comment] 2019-08-07 03:27
Also experiencing this issue in addition to https://github.com/nextcloud/mail/issues/1854. The only email I can open has a ton of attachments and is in the root inbox folder.

**Comment by th3raid0r** [comment] 2019-08-10 00:04
@ChristophWurst - I plan to add detail to these ( this one and #1854) issues over this weekend. Please let me know if there is anything specific that would help. (In addition to the info requested in the template.)

For now, I can say that I am using the ProtonMail email service with a custom domain.

Their SMTP/IMAP configuration is unique in that the server is installed locally and interacts with their API. I've confirmed that it works without any issue on Thunderbird using identical configuration, thus indicating no issues with my network configuration or the ProtonMail Bridge software. I have logs from both ends, the messages don't even appear to be requested in _*this*_ particular issue. 

In #1854 however, the message definitely appears to be queried successfully on the backend, but no message body is displayed. The only exception to this rule is one email I have with a bunch of attachments. I have yet to dive into the source to determine why this might be. 

I suspect it may be because of the self-signed certificate. However, I'm not seeing any errors that would indicate this.

I can force an error to occur, but it's only when I am trying to view certain parent folders where the only child objects are directories. It might be a related, but different issue. I'll have to investigate further.

I'll be back tomorrow with as much info as I can gather.

**Comment by lorddoumer** [comment] 2019-08-12 15:01
Same problem as @tanghus describes, also persists on 16.0.3 with mail app 0.15.2

**Comment by ChristophWurst** [comment] 2019-08-26 07:53
This is actually a duplicate of https://github.com/nextcloud/mail/issues/1847

**Closed by ChristophWurst** 2019-08-26 07:53 UTC
Labels: 1. to develop, bug, regression
