### ISSUE TITLE
Signature of mails does not work on a reply or a transfer

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/mail#6968] opened 2022-08-10 08:56 UTC
### Steps to reproduce

- Select an email
- Click on the button to reply or forward

### Expected behavior

The signature appears 

### Actual behavior

The signature does not appear

### Mail app version

1.13.8

### Mailserver or service

Infomaniak and INOS

### Operating system

Docker| OpenMediaVault

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment] 2022-08-10 09:35
@kesselb :eye:

**Comment by kesselb** [comment] 2023-07-18 18:39
Thank you for your report :+1: 

Closing, as I'm unable to reproduce it anymore.

**Closed by kesselb** 2023-07-18 18:39 UTC
Labels: bug, 0. to triage
