### ISSUE TITLE
Attachments not visible for some mails.

### ISSUE THREAD

**Issue by simon1964** [nextcloud/mail#4758] opened 2021-03-14 12:28 UTC
### Expected behavior
An paperclip icon showing their is an attachment visible in the list of mail as well as in the opened mail.

### Actual behavior
The paperclip is only visible in the list of mail, not in the opened mail.
This behavior is true for all mail form a specific sender. Other senders are OK.
Changes since the last time I know it worked:
-mail upgrade to 1.9.3
-nextcloud upgrade from 20 to 21
-Debian upgrade from 10 (buster) to 11 (Bullseye)

### Mail app

**Mail app version: 1.93

**Mailserver or service: dovecot

### Server configuration

**Operating system**: Debian 11

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version: 21

#### Client configuration
**Browser:** Firefox / Chrome / Edge

**Operating system:** Linux / Windows

**Comment by ChristophWurst** [comment] 2021-03-15 07:24
would it be possible to share the source of that email if it doesn't contain anything sensitive? I'd like to inspect the headers of the attachments, especially their content types.

**Comment by Michael2222** [comment] 2021-03-15 09:32
Hello,

I have the same problem: MS-Teams invitaion, but no displayed the *.ics file and so no button to copy in my calendar.
If I open the mail in another mail client program, the *.ics file is here.

Regards
   Michael

**Comment by ChristophWurst** [comment] 2021-03-15 09:52
https://github.com/nextcloud/mail/issues/4463 for the teams issue.

@simon1964 if you are also referring to an email from teams then we can close this ticket as duplicate.

**Comment by StCyr** [comment] 2021-03-15 11:24
might also be linked to https://github.com/nextcloud/mail/pull/4667

**Comment by simon1964** [comment] 2021-03-15 17:00
Hope this helps. Tried to copy the whole maildir file in, but that didn't work.

--000000000000325c2d05bd935466--
--000000000000325c2f05bd935468
Content-Type: application/pdf; name="NVC Needs vs. Strategies.pdf"
Content-Disposition: attachment; filename="NVC Needs vs. Strategies.pdf"
Content-Transfer-Encoding: base64
Content-ID: <f_kmampzbx0>
X-Attachment-Id: f_kmampzbx0

**Comment by mfavoretto** [comment] 2021-03-16 12:44
I also have the same problem

The paperclip appears only the general view of emails

**Comment by StCyr** [comment] 2021-03-16 12:46
> I also have the same problem
> 
> The paperclip appears only the general view of emails

If you could provide me with the source of such a message I could investigate (I might be the responsible of this bug)

**Comment by mfavoretto** [comment] 2021-03-16 12:50
> 
> 
> > I also have the same problem
> > The paperclip appears only the general view of emails
> 
> If you could provide me with the source of such a message I could investigate (I might be the responsible of this bug)

OK no problem

Just tell me how can I get this font

**Comment by StCyr** [comment] 2021-03-16 12:58
in the message's detail view, in the menu, there's an option "View source": 

![image](https://user-images.githubusercontent.com/8179031/111312402-88cbba00-865f-11eb-8d23-3ddeee5b91cd.png)

Just click on that button and copypaste the result in any pastebin service of your choice

**Comment by mfavoretto** [comment] 2021-03-16 13:17
> 
> 
> in the message's detail view, in the menu, there's an option "View source":
> 
> ![image](https://user-images.githubusercontent.com/8179031/111312402-88cbba00-865f-11eb-8d23-3ddeee5b91cd.png)
> 
> Just click on that button and copypaste the result in any pastebin service of your choice

Ok, this is the link

https://pastebin.ubuntu.com/p/pdbZCQZnnN/

**Comment by StCyr** [comment] 2021-03-16 13:50
Works well here:

![image](https://user-images.githubusercontent.com/8179031/111320068-e9122a00-8666-11eb-8388-586fd5873f40.png)

**Comment by mfavoretto** [comment] 2021-03-16 14:03
well not here... 

![image](https://user-images.githubusercontent.com/39807578/111321321-94f74d80-8646-11eb-822e-890bf86c012d.png)

**Comment by StCyr** [comment] 2021-03-16 15:02
ahah it doesn't work on my dev box. So it must be a regression. I'll investigate

**Comment by StCyr** [comment] 2021-03-16 15:54
@ChristophWurst 

The hasAttachments() function in IMAPMessage.php returns false for the example email.

The reason is that the following test is true for the attachement:

https://github.com/nextcloud/mail/blob/ac234efa78471bad0c298b661ef487f7cb7d5b88/lib/Model/IMAPMessage.php#L330

Any idea why this test is there? Should we simply drop it? Or change it to something like?:

```
			if ($p->getContentId() !== null && $filename === null) {
				continue;
			}
```

**Comment by ChristophWurst** [comment] 2021-03-16 16:20
I think the check was there to find out of a part is an *inline message*. https://serverfault.com/questions/398962/does-the-presence-of-a-content-id-header-in-an-email-mime-mean-that-the-attachme says this isn't very reliable.

**Comment by StCyr** [comment] 2021-03-17 08:09
fix proposed: https://github.com/nextcloud/mail/pull/4776

**Comment by MarianoRD** [comment] 2021-03-17 14:25
I can confirm I have this issue with all my emails.

mail: 1.9.3
Nextcloud: 20.0.8.1

```
Return-Path: --redacted--
X-Original-To: --redacted--
Delivered-To: --redacted--
Received: from mail-ot1-f45.google.com (mail-ot1-f45.google.com [209.85.210.45])
	by --redacted-- (Postfix) with ESMTPS id 88E073E874
	for --redacted--; Tue, 16 Mar 2021 21:28:19 +0100 (CET)
Authentication-Results: hosting.nodosdev.com;
	dkim=pass (2048-bit key; unprotected) header.d=gmail.com header.i=@gmail.com header.b="DgFfqye5";
	dkim-atps=neutral
Received: by mail-ot1-f45.google.com with SMTP id a17so9256990oto.5
        for --redacted--; Tue, 16 Mar 2021 13:30:38 -0700 (PDT)
......
MIME-Version: 1.0
From: --redacted--
Date: Tue, 16 Mar 2021 16:30:24 -0400
Message-ID: --redacted--
Subject: --redacted--
To: --redacted--
Content-Type: multipart/mixed; boundary="00000000000013ef0305bdad3d57"
--00000000000013ef0305bdad3d57
Content-Type: multipart/alternative; boundary="00000000000013ef0005bdad3d55"
--00000000000013ef0005bdad3d55
Content-Type: text/plain; charset="UTF-8"
--00000000000013ef0005bdad3d55
Content-Type: text/html; charset="UTF-8"
<div dir="auto"></div>
--00000000000013ef0005bdad3d55--
--00000000000013ef0305bdad3d57
Content-Type: image/jpeg; name="Screenshot_20210225-152003-1.jpg"
Content-Disposition: attachment; filename="Screenshot_20210225-152003-1.jpg"
Content-Transfer-Encoding: base64
Content-ID: <1783cba980cf27196e1>
X-Attachment-Id: 1783cba980cf27196e1
```

This is only one example of the ones failing.

![image](https://user-images.githubusercontent.com/10457534/111483249-40ada580-86fa-11eb-9ae5-88496467b1e3.png)

**Comment by wabadoo-wabadee** [comment] 2021-03-25 14:26
I can verify this problem. Whenever I send an e-mail with attachment from my work (office 365) account to my private e-mail (accessed via nextcloud mail app) I'm unable to open the attachment. 

Will more examples of failed mails help or is the problem already identified? I would gladly provide help as my family is using nextcloud mail as mail app and right now they lose trust as they have to open some attachments on their phones and send them to themselves via messenger which is quite a pain for non-tech people.

Thanks for your time working on this app. It's really nice how good contacts, files and other nextcloud stuff is integrated.

**Comment by StCyr** [comment] 2021-03-25 14:38
We've developed a fix. It should be merged very soon

**Comment by wabadoo-wabadee** [comment] 2021-03-26 10:30
yesterday's new version (1.9.4) did not contain a fix for this issue...

**Comment by ChristophWurst** [comment] 2021-03-26 10:35
> yesterday's new version (1.9.4) did not contain a fix for this issue...

did you see the changelog? nobody claimed this would be fixed. see the referenced pull requests

**Comment by ChristophWurst** [comment] 2021-03-26 10:35
also @wabadoo-wabadee why do you react to your own comment? do you fish for reactions?

**Comment by wabadoo-wabadee** [comment] 2021-03-26 10:53
yeah, sorry for not knowing that "it should be merged very soon" does not mean the next version. maybe I just was hoping for too much. 

For 12 days, the app is broken regarding some attachments. Not suitable for production use. If you really would want to build a good software, you would prioritize that over things like pictures for dark themes. Just my two cents. Now go and hide my comment again.

No, I do not fish for reactions. I wanted to express disillusionment as described above. I can't understand where your negativity and unpleasantnes is coming from. I offered help, I have no insights in the development process and therefore did not know that it was not fixed by now. Or at least not released.

Whatever. I do not wish to participate in such a unnecessarily rough conversation.

**Comment by ChristophWurst** [comment] 2021-03-26 11:37
Have a god one :v:

**Closed** 2021-03-26 12:24 UTC
Labels: 1. to develop, bug, regression
