### ISSUE TITLE
Missing Account Color Marker

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#7513] opened 2022-11-02 14:29 UTC
### Steps to reproduce

1. Open Mail app with 2 accounts
2. Select Unified Inbox
3.

### Expected behavior

Color marker in front of every mail

### Actual behavior

No Marker

### Mail app version

2.0.3

### Additional info

I saw the marker was removed with #6981, but the styling seems always here, as I could find 

```
<style nonce="">.mail-message-account-color[data-v-433b9883]{position:absolute;left:0px;width:2px;height:69px;z-index:1}[...]</style>
```
 in the header.

In #6981, there was no rationale for the removal. Can someone give one ?
Since there is still some styling available, can we enable it back through Theming, if it can't be enabled by default or through a setting ?

Thank you

**Comment by ChristophWurst** [comment] 2022-11-02 15:23
> In #6981, there was no rationale for the removal. Can someone give one ?

I can't find a ticket but it was part of the "new design" for Mail 2.0 / Nextcloud 25. @nimishavijay @jancborchardt can you shed some light?

**Comment by mat-m** [comment] 2022-11-20 14:51
@nimishavijay @jancborchardt Typical use cases: 
* Deleted an email from unified inbox. 2 se conds after, decided, it's better to triage in archive. Color marker is helpful to know which Trash to look into, rather than iterate on all 
* Received a parcel arrival notification. If it's not on the expected account, it is easier to detect phishing.

**Comment by nimishavijay** [comment] 2022-11-22 23:16
The rounded corners did make it difficult to indicate the account color, but it was more about simplifying the interface by removing non-essential info. If you are using the unified inbox, it is unlikely that you are differentiating between the multiple emails you have and simply want a list of all messages. This was the idea behind removing it. 

If we are reintroducing it, one solution is changing the color of the unread marker for unread emails in the unified inbox. For read emails it seems a bit more challenging because of the rounded corners 🤔

**Comment by mat-m** [comment] 2022-11-30 22:56
@nimishavijay I have many use cases:
*  Some phishing are very convincing, so identifying easily that this kind of mail should not be in this mailbox help a lot.
* When you're sorting out recent emails, having the color helps to triage
* When you're searching for an email in a known period, without being sure which mailbox it's in (searching in 2 mailboxes out of 7)

Color can be between the sender icon and the text block. Quick try with 2px padding on app-content-list-item-icon and 2px border on list-item-content
![image](https://user-images.githubusercontent.com/1039753/204920250-8933e890-f37f-4e8f-995f-11cc400afa8c.png)

If you don't want it by default, just set it to 0px border, so people who want it can override the width in the Theming plugin ?

I also tried with backgrounds, but it's too much color (rgba color of account with 5% transparency) and will mess with hover and selected

**Comment by mat-m** [comment] 2022-12-03 17:10
We can also imagine to have a permanent dot near the avatar, like:
![image](https://user-images.githubusercontent.com/1039753/205453008-38fe9d3d-bd10-4ad6-bc9e-80ffe183f1d7.png)

In the same spirit that you list both "from" and "to" mail adresses in the envelope head, we would have the sender and the  mailbox's recipient

**Comment by mat-m** [comment] 2022-12-14 21:13
Another use case: mail deleted too fast. It helps to know which trash we should search in

**Comment by jancborchardt** [comment] 2022-12-20 14:55
@mat-m for the case of deleting mails too fast, we really need "undo" instead, so it’s a different solution. :) https://github.com/nextcloud/mail/issues/978

Regarding phishing protection, we automatically block images from all sources (unless specifically marked as trusted before), and we show the email of the sender in plaintext as well. We can certainly do some more improvements here, but a color marking for an account seems to be a not very obvious adjustment to protect from scams.


The reasoning about removing the color marking is:
- Some apps do it (like K-9 Mail) but more widely used apps like Gmail mobile and iOS Mail do not differentiate
- The color would be completely arbitrary, we had issues with color conflicts before, and then people need to go and customize
- Color alone can only be supporting info, it’s not accessible in itself
- Introducing another dot would conflict with the unread indicator dot we now use
- In practice it often seems to be obvious which account a mail belongs to

**Comment by mat-m** [comment] 2022-12-28 23:23
@jancborchardt : Answering quickly to your 3 items:
* Agree on the undo, that's a trade-off I'm using on NC Mail. Issue is 4 y.o., so fortunate we have it. No blames here, I totally understand choices are to be made. Maybe that's a point: keep colors until this issue is solved :wink: :innocent: 
* Yes. I also got mails without images. That does not cover all the cases (more below)
* Do you plan to remove all color references then ? (more below)

**About scam/spam/phishing :** 

* When a  Paypal mail is arriving on Account B, I can reject it as phishing since it is not used for Paypal, without even opening it;  but I need to know it went to Account B
* Sender's email is not shown on hover in Mail 2.2.2. Expected, regression ? Currently, I need to `view source` to find it when there is no images to block.
* On a well-crafted email, I need to search which account it targeted. If the sender was in BCC, I can only resort to open the source and check the headers, or loop on all accounts to see where it is stored.
* For me, it's more a first-level filter than an "adjustment" for junk. That's how my brain works. I do not pretend everyone with multiple accounts will need it.

**About colors for account:**

We still have colors in front of accounts for now. Do you plan to also remove them ? I hope not.
I actually do use **K9-Mail** and its color markers :wink: . I  even chose the colors myself in K-9 to know the match between account and color.
For imported accounts in **gmail**, I actually defined some labels to identify them. I'm that type of user. 

I understand that my usage model may not be the heart of the target for NC Mail, but it would be nice to have a way to keep colors and their productivity improvements they bring, at least through  Theming Custom CSS. Having colors items with a size of zero, or display:none, and being able to _activate_  them for whoever wants it. My guess is that the users that finds value in colored accounts are mostly willing to get their hands dirty for this.
To keep color visible in Message list, we can have it like K-9, a small vertical bar in front of the sender or the subject. My opinion is that the color is more useful in the messages list to differentiate them, but at least we can have it in the preview pane (in front of the thread subject, maybe)
Naïve question: About NC Mail usage models, I'm curious to know whether you have personas to describe redline scenarios & behaviors within the app ?

**More on my use cases of colors:** 

That's how my brain process information, and I was relieved to find a match in NC Mail at first :smile: 
I don't expect you to find alternatives in NC mail, but maybe it will provide other views on NC Mail usage, and hopefully support my request to keep colors.

* The color tells me also where to move  the mail (should I need to scroll the account list or not)  to put it in another folder
* The color tells me also where to search for other mails from the same sender in an preset folder (often faster than search, although it improved recently)
* Be in the unified inbox to see all new/unprocessed mails at once. Checking in the same time if I received the expected mail on Account C is easier with color than checking against the sender (which I may not know with precision, it could be just a domain origin, etc.) .
* On your last point: For daily matters and registered accounts yes. The main issue os with all the other cases, and there are more and more.
   One example:  Two orders went to Account A & B. Same carrier. Mails are now often not mentioning the shop, so knowing the DHL mail arrived into Account A is time-saving (even more on Christmas time :christmas_tree: ).

**Comment by mat-m** [comment] 2023-06-18 15:35
@jancborchardt @nimishavijay : Last release of K-9 mail, moving to be Mozilla Thunderbird Mobile app, has even put the account name label with its color when reading the mail itself.

Below, **matm** is the name I gave the mail account on which I received this spam:

![image](https://github.com/nextcloud/mail/assets/1039753/e69361df-72ac-4f92-af2c-6caa2d1f79a4)

**Comment by marcotrevisan** [comment] 2023-10-24 18:42
Hi all,
  just adding my +1: please add the option to enable some color / marker / anything else in the unified view that makes it possible for the user to tell what account an incoming email belongs to. 
That way you'd have the best of both worlds: all emails sorted in a single folder **and**  a hint on where they have arrived.
Personally I don't agree on the assumption that when I use the unified view I don't need to know which account an email belongs to. 
I use unified folders all the day in Thunderbird with the "account" column enabled, I feel lost for not having it in NC mail.

Thanks!

**Comment by mat-m** [comment] 2023-12-30 22:22
@jancborchardt: I just re-read your rationale on removing color, and realized I missed a point:

I don't know for iOS mail, but GMAIL app allows to set a label based on the account, so even if it's not native, you have an easy way to identify the belonging account for an email.

So another +1 to bring them back :)

**Comment by mat-m** [comment] 2024-03-24 23:10
@nimishavijay : Can we consider to have a colored dot on the lower left part of the sender "icon" (horizontal symmetry from the important marker) ?
![image](https://github.com/nextcloud/mail/assets/1039753/5f2a207e-2f9b-44ef-8d36-42c9449f0f41)

**Comment by GretaD** [comment] 2024-10-16 11:53
This is not a bug because there was a decision to remove the color marker. This is a feature request. @mat-m can you please open a feature request ticket with your proposal?

**Closed by GretaD** 2024-10-16 11:53 UTC
Labels: bug, 0. to triage
