### ISSUE TITLE
This app does not respect the "Allow sharing with groups"-setting

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/mail#6017] opened 2022-02-08 13:26 UTC
### Expected behavior

Given the following settings

![Screenshot from 2022-02-08 14-23-03](https://user-images.githubusercontent.com/1863453/152995821-62defa89-63b3-4153-99b7-091632ec4caa.png)

When you write a new email, you shouldn't be proposed autocompletion emails from users from groups you are not in.

### Actual behavior

It does propose you all the emails of the instance.

### Steps to reproduce

1. configure the sharing settings like in the screenshot
2. create a new email
3. start to type in the to field and get autocompletion proposition from users outside your groups.

### Mail app version

1.11.6

### Mailserver or service

Not relevant.

### Operating system

Not relevant.

### PHP engine version

Other

### Web server

Other

### Database

Other

### Additional info

Relates to this bug:
https://github.com/nextcloud/server/issues/25390

On shared instance, this is a privacy issue.

**Comment by kesselb** [comment] 2022-05-20 22:41
Hey @pierreozoux :wave: 

I need some help with your bug report. 

**Sharing Settings**

![image](https://user-images.githubusercontent.com/3902676/169619486-2bfcac44-6fe1-43e1-9163-3397874c6da3.png)

**Users & Groups**

![image](https://user-images.githubusercontent.com/3902676/169619540-9cfaeb0a-cce4-4a71-9247-58e876987e47.png)

**Test Case 1**

- Login as alice
- Write a new message

| Input To | Suggestion |
| --- | --- |
| bob | - |
| john | - |
| house | House Greyjoy (Nextcloud)<br>House Stark (Nextcloud) |
| night | Night's Watch (Nextcloud)
| admin | admin (Nextcloud) |

* (Nextcloud) = Group in Nextcloud

**Test Case 2**

- Login as alice
- Write a new message to `join@nightswatch.got`
- Sent the message

| Input To | Suggestion |
| --- | --- |
| night | join@nightswatch.got<br>Night's Watch (Nextcloud)

`join@nightswatch.got` is returned by the address collector (as we wrote an email earlier)

Night's Watch (Nextcloud) = Group in Nextcloud


**Test Case 3**

- Login as alice
- Open contacts
- Add a new contact Robb Stark with email robb@stark.got
- Open mail
- Write a new message

| Input To | Suggestion |
| --- | --- |
| robb | Robb Stark (robb@stark.got) |

Robb Stark (robb@stark.got) is a direct match from contacts then

Test Case 1, 2 and 3 look okay. I also had a quick look at the auto completion service. We use three sources: Contacts, Groups and collected addresses. 

Can you share some more details how to reproduce it :thinking:

**Comment by unteem** [comment] 2022-08-24 09:54
Hi @kesselb 

This looks definitely like a duplicate of https://github.com/nextcloud/mail/issues/6148

I'll answer for @pierreozoux 

Its weird I cannot replicate on a fresh install but on our current install we do have the issue of the autocompletion settings being ignored...

If I allow auto-completion for users in the same groups:
I should only see users from that group in the autocompletion when I start to type a recipient
What I actually see is an auto-completion of all the users in the instance. 

If I disable auto-completion, I should not get any auto-completion when I start to type a recipient
What I actually get is an auto-completion of all the users. 

Can it be something that is messed up during an upgrade when there was this issues ? We still have some stuff in the db that should be cleaned up ?

We had this issue for a while now - see https://github.com/nextcloud/mail/issues/848 & https://github.com/nextcloud/mail/issues/171- I think it was fixed at one point but we had regressions (not sure about this one).

Thanks

**Comment by unteem** [comment] 2022-08-24 10:23
Ok... its getting weirder... 

Now its working as supposed. I tweaked a bit with the sharing settings and went back to the initial settings and its working as supposed... 

I'll check with the users that reported this issue but you can forget about my previous message... at least for now... and ever I hope :)

Sorry for the noise

**Comment by hrenard** [comment] 2022-08-25 10:11
Hi @kesselb,

As I understand it, the ContactsManager (lib/private) is not responsible for filtering the results. Then, I don't see how the code would filter by groups as it only filters on `shareapi_allow_share_dialog_user_enumeration`. https://github.com/nextcloud/mail/blob/ca3f9296ba110725863f4a83e984a9bd77ac1776/lib/Service/ContactsIntegration.php#L56-L63

I believe we need something like [this](https://github.com/nextcloud/server/blob/9b5569ff74bbc099af7c2010471bae8958aa9dd4/lib/private/Collaboration/Collaborators/MailPlugin.php#L141-L157).

Have I missed something ?

Thanks !

**Comment by ChristophWurst** [comment] 2022-10-12 09:22
Label dropped because it was a duplicate of the attribute at https://github.com/orgs/nextcloud/projects/61. The priority does **not** change.

**Closed** 2022-11-28 18:32 UTC
Labels: bug, 3. to review, feature:integration, needs info
