### ISSUE TITLE
Unable to reply to emails with gmail

### ISSUE THREAD

**Issue by stratacast** [nextcloud/mail#192] opened 2016-11-11 18:50 UTC
### Steps to reproduce
1. Open up an email
2. Can't click on reply because it's grayed out

### Expected behaviour
Reply shouldn't be grayed out, and I should be able to reply to messages

### Actual behaviour
Reply button is grayed out, can't respond to emails via mail client

### Mail app

**Mail app version:** (see apps admin page)
0.6.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
TLS

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**
1

### Server configuration
**Operating system**: Ubuntu Server 16.04

**Web server:** Apache 2.4.18

**Database:** 10.0.27-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:**  PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Version:** (see admin page)
10.0.1

**Updated from an older version or fresh install:**
Updated from version 10.0.0

**List of activated apps:**
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.6.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - spreedme: 0.3.3
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'information',
  'passwordsalt' => 'salt',
  'secret' => 'secret',
  'trusted_domains' => 
  array (
    0 => 'trusted_domain0',
    1 => 'trusted_domain1',
    2 => 'localhost',
    3 => 'internal_ip',
  ),
  'datadirectory' => '/var/data',
  'overwrite.cli.url' => 'domainname',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'databasename',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'theAdministrator',
  'dbpassword' => 'the_password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'loglevel' => 0,
  'mail_smtpmode' => 'smtp',
);

I removed confidential information to protect myself from possible attack
<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:** Firefox, Chromium

**Operating system:** Fedora 25

**Comment by scroom** [comment] 2017-01-21 23:01
I'm experiencing the same with my self hosted mail server. 

I can forward mails and send new mails but the reply button is grayed out so it is not possible to reply emails. Can I provide more information?

**Comment by ChristophWurst** [comment] 2017-01-23 07:19
I'm pretty sure this is a duplicate of https://github.com/nextcloud/mail/issues/287#issuecomment-272818353. Can you confirm? :-)

**Comment by scroom** [comment] 2017-01-23 13:00
@ChristophWurst I can confirm for my case. Sorry.

**Comment by scroom** [comment] 2017-01-23 13:03
Maybe the visbility of the reply field should be increased? I just haven't realized that there is a field to type in and thought that such a field would be opened by clicking on "reply".

**Comment by ChristophWurst** [comment] 2017-01-23 14:50
No worries. Actually this has been reported several times now, which indicates that we should re-think that user interface and interaction

cc @jancborchardt

**Closed by ChristophWurst** 2017-01-23 14:50 UTC
