### ISSUE TITLE
Some email's in mail app use black text on dark backgorund

### ISSUE THREAD

**Issue by gigibu5** [nextcloud/mail#2482] opened 2020-01-15 07:40 UTC
![slika](https://user-images.githubusercontent.com/16723465/72414438-85deec00-3772-11ea-8eb9-d0931dc150b5.png)
The problem is most likely the use of HTML and CSS in email, which set the text color. A simple solution is a white background.

**Comment by ChristophWurst** [comment] 2020-01-15 09:20
@jancborchardt ideas? shall we remove our text color overwrite?

**Comment by jancborchardt** [comment] 2020-01-16 00:04
@gigibu5 we need some more info here. Do you use the dark theme? Or is this with regular theme and a special email?

If it’s with dark theme, we just need to invert the color overwrite to use a light text color, right?

**Comment by gigibu5** [comment] 2020-01-16 19:46
Yes, I am using the dark theme and yes, that will be the optimal solution. The problem that I'm thinking of right now is, how will you filter through email's and figure out which text you need to invert.

**Comment by jancborchardt** [comment] 2020-01-18 12:40
Right, so there’s 2 solutions:
- Quick but doesn’t look good: Simply set the background of HTML mails to white
- Looks nice but probably takes time or is not feasible: Set the text of HTML mails to white (at least when the text is dark) and try to do that properly for all sorts of mails

**Comment by gigibu5** [comment] 2020-01-19 09:51
I have just thought of a simpler solution. I recived an email from Moodle, which text was unformated and it looked fine:
![image](https://user-images.githubusercontent.com/16723465/72678777-4df4e300-3aa9-11ea-9453-6f7d241cb2ac.png)
If we scan the email for HTML/CSS code in them, background color will usually be in body or container id, text will be in p-tag, we can compare the values and determine if they are light or dark. If light, set background to nextcloud background color and text to white. I think this would be an most optimal solution.

**Comment by jancborchardt** [comment] 2020-01-19 12:40
@gigibu5 wouldn’t this result in plain text mails being shown proper in dark mode but HTML mails being shown with bright background? Or do I misunderstand? :) If you do have a proposal, you can also try implementing it and open a pull request if you like. :balloon:

**Comment by rigrig** [comment] 2020-03-11 17:15
Maybe you could use
```css
#message-container {
    filter: invert(100%);
}
```
To simply invert message colors completely?
It might need some fiddling to double-invert images (and maybe other things?)
(And people replying with "my comments in red" will become even more of an annoyance)

Actual screenshots: (inverted by adjusting CSS through Firefox developer console)
| Regular  | Dark theme | Dark theme Inverted |
| ---------- | ---------------- | --------------------------- |
| ![image](https://user-images.githubusercontent.com/2941436/76441420-a7013900-63bf-11ea-9e44-a0ece6076c53.png) | ![image](https://user-images.githubusercontent.com/2941436/76441782-46263080-63c0-11ea-84b4-4d285fd3e378.png) | ![image](https://user-images.githubusercontent.com/2941436/76441906-69e97680-63c0-11ea-8c02-1c001d0ed607.png) |

Test message:
```html
<div>Regular text</div>
<div>&nbsp;</div>
<div><span style="color: #000000;">Black text</span></div>
<div>&nbsp;</div>
<div><span style="color: #ffffff;">White text</span><br /><br /></div>
<div><span style="background-color: #000000;">Black background</span></div>
<div>&nbsp;</div>
<div><span style="background-color: #ffffff;">White background</span></div>
<div>&nbsp;</div>
<div><span style="color: #000000; background-color: #ffffff;">Black-on-white text</span></div>
<div>&nbsp;</div>
<div><span style="color: #ffffff; background-color: #000000;">White-on-black text</span></div>
```

**Comment by rigrig** [comment] 2020-03-11 17:16
This issue looks like a duplicate of #1742

**Comment by jancborchardt** [comment] 2020-04-02 07:36
Yes, thanks @rigrig – closing as duplicate of https://github.com/nextcloud/mail/issues/1742 :)

**Closed by jancborchardt** 2020-04-02 07:36 UTC
Labels: 1. to develop, bug
