### ISSUE TITLE
incomplete list of email in the inbox

### ISSUE THREAD

**Issue by dutch666** [nextcloud/mail#3054] opened 2020-05-04 20:12 UTC
### Expected behavior
Tell us what should happen

on mobile, when scrolling thru emails, new emails should appear when you reach bottom of list.

### Actual behavior
Tell us what happens instead

after 20 emails, the list just stops,

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3). newest update

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

horde

### Server configuration

**Operating system**: (e.g. Debian 8) linux

**Web server:** (e.g. Apache, Nginx,...) apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL) mysql

**PHP version:** (e.g. 7.0) 7.2

**Nextcloud Version:** (see admin page, e.g. 13.0.2) 18.04

#### Client configuration
**Browser:** (e.g. Firefox 48)

mobile, samsung note, chrome and samsung browser

**Operating system:** (e.g. Arch Linux)

android newest

![95280715_230564698210278_3061785595798880256_n](https://user-images.githubusercontent.com/36723240/81009013-db263280-8e21-11ea-951d-848561bd9201.jpg)

**Comment by kevgathuku** [comment] 2020-05-21 15:00
This seems to be a duplicate of https://github.com/nextcloud/mail/issues/2943
Right @dutch666?

**Comment by ChristophWurst** [comment] 2020-06-02 09:25
yes! Thanks :)

**Closed by ChristophWurst** 2020-06-02 09:25 UTC
Labels: 0. to triage, bug
