### ISSUE TITLE
Dialogs close automatically after a few seconds.

### ISSUE THREAD

**Issue by powerpaul17** [nextcloud/mail#8873] opened 2023-09-19 09:48 UTC
### Steps to reproduce

1. Choose option to move a message into a folder
2. The dialog for choosing the destination folder opens
3. After a few seconds - while trying to select the desired folder - the dialog closes automatically

### Expected behavior

The dialogs should not close until the user has chosen the desired option.

### Actual behavior

Dialogs close automatically after a few seconds.

### Mail app version

3.4.0

### Mailserver or service

postfix

### Operating system

Linux

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

PostgreSQL

**Comment by JohannesGGE** [comment] 2023-10-23 10:31
Duplicate of https://github.com/nextcloud/mail/issues/8753

**Closed by JohannesGGE** 2023-10-23 10:31 UTC
Labels: bug, 0. to triage, regression
