### ISSUE TITLE
Chinese (GBK) encode error 

### ISSUE THREAD

**Issue by mashirozx** [nextcloud/mail#3856] opened 2020-10-20 21:40 UTC
### Expected behavior
Tell us what should happen

Setting a [QQ Mail](https://mail.qq.com/) (which is the largest Email provider in China) account, and Email's in my inbox with Chinese title and summary should be display in Chinese normally.

### Actual behavior
Tell us what happens instead

But Email title and summary encode error:
![image](https://user-images.githubusercontent.com/16148054/96645983-fea45180-135d-11eb-9a3d-13a1ee087045.png)

It should be:
![image](https://user-images.githubusercontent.com/16148054/96646492-ce10e780-135e-11eb-879b-66f3d3fb13ce.png)

I think the reason is because not handle the original Chinese context encoded in [GBK](https://en.wikipedia.org/wiki/GBK_(character_encoding)) correctly.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
	1.5.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
QQ Mail (https://mail.qq.com)

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu18.04 (host) , runs in Docker (image: nextcloud:latest)

**Web server:** (e.g. Apache, Nginx,...)
Docker (image: nextcloud:latest) behind Nginx proxy

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
PostgreSQL

**PHP version:** (e.g. 7.0)
Docker (image: nextcloud:latest)

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
Nextcloud 20.0.0

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment] 2020-10-21 06:28
Duplicate of https://github.com/nextcloud/mail/issues/3794

**Closed by ChristophWurst** 2020-10-21 06:28 UTC
Labels: 0. to triage, bug
