### ISSUE TITLE
Support Multiselect of Emails using Shift key

### ISSUE THREAD

**Issue by basilweibel** [nextcloud/mail#8048] opened 2023-02-18 19:58 UTC
### Is your feature request related to a problem? Please describe.

Right now you need to start multiselect of emails via the ... menu which is cumbersome. I would expect that pressing shift would allow me to select multiple messages but instead it opens (in chrome) a new window.

### Describe the solution you'd like

Implement multiselect using shift + click on the keyboard for many messages and ctrl/cmd + click for selected few messages.

**Comment by small1** [comment] 2023-03-07 07:37
This is basically a duplicate of #7276

**Comment by ChristophWurst** [comment] 2023-03-17 11:37
This is one of the enhancements listed there so I'm okay with two tickets. I'll link this one in the other.

**Comment by rcsilva83** [comment] 2023-06-14 17:13
This must be a simple code change but with a great gain in UX

**Comment by ChristophWurst** [comment] 2023-06-15 18:34
> This must be a simple code

Probably. Wanna try?

**Comment by rcsilva83** [comment] 2023-06-15 19:06
Yes I can but I need some guidance. How does the Mail app team envision this feature to be implemented? One suggestion would be to make it similar SOGo: change list item icon to a checkbox on mouse over:

![Sogo multiselect](https://github.com/nextcloud/mail/assets/45306/c225db4d-ac28-4d5f-a4c7-38de7a8759c9)

What do you think?

**Comment by small1** [comment] 2023-06-15 19:13
I'm only from community. But the multi select  regardless of how it looks visually has to work the same as in outlook or other emails.  Shift click and control click. And preferably it should also support marking with spacebar and keyboard movements

This is how most users expect it to work (i have introduced mail to several customers the last year .. and this is a pain point for business users)

**Closed** 2023-06-19 07:05 UTC
Labels: enhancement, 3. to review
