### ISSUE TITLE
Nextcloud 29 and 30 : The tags are written in white on a white background (illegible).

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/mail#10025] opened 2024-08-20 12:13 UTC
### Steps to reproduce

I discovered by chance that Nextcloud Mail supports the tags I've created and managed in Thunderbird. The problem is that they're unreadable. The problem only arises with the light theme (see the 2 screenshots). I also have the impression that the color is hard-applied (inline style) and I don't know if this is normal. In any case, as it stands, with the light theme, the tags are practically invisible.

### Bright theme : 
![2024-08-20_14-03](https://github.com/user-attachments/assets/945db173-86e5-4c39-9b27-bd4da5f6d432)

### Dark theme : 
![2024-08-20_14-06](https://github.com/user-attachments/assets/8cf3c507-3628-4347-af2d-1fb68a34e52f)

### Expected behavior

Tags should be written in black with bright theme.

### Actual behavior

Written in white, and almost unreadable.

### Mail app version

3.7.7

### Operating system

CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database

MariaDB

**Comment by Jerome-Herbinet** [comment] 2024-08-20 12:14
@nextcloud/designers

**Comment by ChristophWurst** [comment] 2024-08-20 12:21
Duplicate of https://github.com/nextcloud/mail/issues/5149

**Closed by ChristophWurst** 2024-08-20 12:21 UTC
Labels: bug, design, 0. to triage, feature:tags
