### ISSUE TITLE
Mail to Contact Group

### ISSUE THREAD

**Issue by BlueCaos** [nextcloud/mail#936] opened 2018-06-11 07:54 UTC
### Question

Hi everyone!
So My question is, if it is possible to use a Contatsgroup as recipient. I disovered, that it is possible to use nextcloud groups. But it would be neat, if it was possible to write mails to the contact groups as well.
If it is currently implemented, I am sorry to bother you 🙈

**Comment by ChristophWurst** [comment] 2018-06-18 09:34
I guess this is a duplicate of #41 then :wink: 

For reference, @myrho was working on the Nextcloud groups integration (https://github.com/nextcloud/mail/pull/810). That could be extended to also support contacts groups.

**Closed by ChristophWurst** 2018-06-18 09:34 UTC
