### ISSUE TITLE
Feature to move emails from a mailserver to Nextcloud for long-term storage

### ISSUE THREAD

**Issue by HammyHavoc** [nextcloud/mail#9551] opened 2024-04-11 05:00 UTC
### Is your feature request related to a problem? Please describe.

After a while, I simply don't need certain emails on a mailserver and they take up storage on both the mail service and devices synced to them, but I do still need to keep them.

### Describe the solution you'd like

I would like a feature to "Archive on Nextcloud" or "Transfer to Nextcloud" on specific emails, specific email threads, or emails labelled with a specific tag, e.g. "Store on Nextcloud", so I could even pick emails to be archived long-term on the Nextcloud server from my phone's Gmail client.

These emails transferred to Nextcloud should still appear within the Nextcloud Mail interface, but perhaps with a ❄️ icon somewhere to indicate that they're in deep-freeze long-term storage on the Nextcloud server, but not on the mailserver itself.

### Describe alternatives you've considered

Gmail AppScript, but it's quite limited when it comes to interacting with third-party servers beyond the Google ecosystem.

### Additional context

I think it would make sense to store them as files for easy restoration via other utilities if required: https://en.wikipedia.org/wiki/Maildir

**Comment by andreas1107** [comment] 2024-05-24 07:44
I would also appreciate such a feature. Another option that fills a similar use case is to enable POP3 support, so that Nextcloud mail could be used as an email backup solution.

**Comment by EmersonHeiderich** [comment] 2024-07-26 13:04
This feature would be perfect. The POP3 option would also be viable.

**Comment by ChristophWurst** [comment] 2024-07-26 13:06
@andreas1107 @EmersonHeiderich add your :+1: to https://github.com/nextcloud/mail/issues/9551#issue-2236914107. A comment causes unnecessary notifications for people subscribed to the topic. Thanks.

**Comment by ChristophWurst** [comment] 2024-10-24 12:20
@HammyHavoc Thank you for your feature request. This appears to be a duplicate of https://github.com/nextcloud/mail/issues/9240, albeit with a slightly different motivation. The feature is mostly the same, so I'll close this ticket.

**Closed by ChristophWurst** 2024-10-24 12:20 UTC
Labels: enhancement, 0. to triage
