### ISSUE TITLE
Provisioning Configurations is not working

### ISSUE THREAD

**Issue by Brondil** [nextcloud/mail#7578] opened 2022-11-11 11:51 UTC
### Steps to reproduce

1.Going to Account provisioning
2.Clicking on Add new config
3.Appearing form for settings 
4.Entering all settings fields except Sieve and Alliases
5. Clicking on Save Config

### Expected behavior

Configurations saved and I can provision all accounts

### Actual behavior

Nothing happens when I try to save config, when I reload the page there is no configuration

### Mail app version

2.1.0

### Mailserver or service

Exchenge

### Operating system

Debian 11

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database

PostgreSQL

### Additional info

Trying from different browsers like Firefox 106.0.5 (64bit), Google Chrome 107.0.5304.87 (64bit) and having same result.

**Comment by RegExe** [comment] 2022-11-12 05:12
I am experiencing this issue as well as it seems to be broken javascript that affects the submit buttons on all forms on the "Groupware" configuration page as you cannot save the spam/ham form either.

Mail app version
2.1.0

Mailserver or service
Postfix/Dovecot

Operating system
Debian 10

PHP engine version
PHP 8.1

Web server
Apache2

Database
MariaDB

**Comment by Samonitari** [comment] 2022-11-13 18:15
I am also experiencing this.

My user backend is OpenLDAP, and nextcloud works fine, profile shows my email, but provision config cannot be saved

**Comment by Samonitari** [comment] 2022-11-14 05:14
I installed 1.14.2 from tar.gz, and issue persists.

**Mail app version**
2.1.0 **and 1.14.2

**Mailserver or service**
Postfix, Dovecot and OpenLDAP

**Operating system**
OpenSUSE 15.4

**PHP engine version**
PHP 8.0.24

**Web server**
Caddy

**Database**
PostgreSQL

**Comment by miaulalala** [comment] 2022-11-14 08:59
Duplicate of https://github.com/nextcloud/mail/issues/7426 which has been fixed

**Closed by miaulalala** 2022-11-14 08:59 UTC
Labels: bug, 0. to triage

**Comment by Samonitari** [comment] 2022-11-14 11:25
Well, 1.14.3-alpha.1 doesn't seem to solve this!
