### ISSUE TITLE
Subfolders are not expandable/collapsible (fix 606)

### ISSUE THREAD

**Issue by omocinteractive** [nextcloud/mail#732] opened 2018-01-23 19:35 UTC
### Steps to reproduce
1. Open Mail-App
2. Click on "Show all folders"

### Expected behaviour
open folders

### Actual behaviour
not open folders only changing text to "close folders"

### Mail app

**Mail app version: 0.7.9

**Mailserver or service: own server with plesk, webmail horde, courier imap, postfix

Fix #606 with z-indx is not working. Workaround:

delete &.collapsible:not(.open) { > ul, > .folders {...} on line 851

**Comment by ChristophWurst** [comment] 2018-02-01 14:51
@jancborchardt ping

**Comment by skjnldsv** [comment] 2018-02-08 07:56
I can't reproduce! Works fine here :/
![kazam](https://user-images.githubusercontent.com/14975046/35961410-e4c55b4c-0cad-11e8-81b4-14dd36646861.gif)

**Comment by jancborchardt** [comment] 2018-02-08 07:58
Yeah, works fine for me too.

**Comment by ChristophWurst** [comment] 2018-02-08 08:14
Cannot reproduce -> closing

**Comment by omocinteractive** [comment] 2018-02-08 10:29
... i installed the latest version and it definitely not working:
![ordner](https://user-images.githubusercontent.com/20245225/35968070-1292d9a4-0cc3-11e8-8c25-0345f7a26084.gif)

**Comment by ChristophWurst** [comment] 2018-02-08 11:05
Then please complete the [issue template](https://raw.githubusercontent.com/nextcloud/mail/master/.github/issue_template.md) so that we get a better understanding of your setup and the problem to be able to fix the issue.

Thank you.

**Comment by skjnldsv** [comment] 2018-02-08 11:16
And clear your cache! :D

**Comment by zpuskas** [comment] 2018-02-09 07:49
I have the same issue on a fresh OC13 installation with Mail 0.7.9. I noticed though that if I click the "show all folders" the drop down actually has items it's just they are not visible (though examining via Firefox's developer tools clearly show the folders are there). I can also click the invisible items and the respective folders load.

**Comment by omocinteractive** [comment] 2018-02-09 09:40
... i replaced all files, cleared my cache and tried it on different browser - allways the same. see my configuration issue template for details. what kind of information do you need exactly? i think it is a problem with js/css (see my workaround - the folders have been loaded but js/css don't show them). i disabled pagespeed-mod also and other apache-mods (because of js-problems in nextcloud and other projects).

**Comment by ChristophWurst** [comment] 2018-02-09 09:52
Any errors in your js console?

**Comment by omocinteractive** [comment] 2018-02-09 09:54
... no errors!

**Comment by skjnldsv** [comment] 2018-02-09 10:12
You need to clear your appdata server cache. @rullzer? 😂

**Comment by omocinteractive** [comment] 2018-02-09 10:39
... do you have a short tip or little how-to? i found nothing for clearing app cache under nextcloud.

**Comment by skjnldsv** [comment] 2018-02-09 12:45
@omocinteractive sorry, you can try the dedicated app rullzer made here :
https://github.com/rullzer/appdatacleaner

Then use the occ command line to clear css and js! :)

**Comment by omocinteractive** [comment] 2018-02-09 12:51
... thx a lot! i will try it on weekend :)

**Comment by omocinteractive** [comment] 2018-02-11 16:57
... sorry, nothing happend. i think it is'nt a problem of caching (see @zpuskas posting - fresh installation). i merged the output css file - it is exactly the same. i will wait for new versions, maybe some day it will work. and - if it is a problem of caching - there is a generally problem with nc updater, i think ...

**Comment by ChristophWurst** [comment] 2018-02-13 16:20
Hey @omocinteractive,

are you using a mailserver that has an INBOX prefix? There are known bugs with those. Try clicking the inbox icon and its subfolders will magically expand 😉

**Comment by omocinteractive** [comment] 2018-02-13 17:49
ARRRRGH - 10.000 kisses :) Yes, my mailserver use an INBOX prefix! Thx a lot!

**Comment by ChristophWurst** [comment] 2018-02-14 08:46
Now that I understand the problem, I'm pretty sure this is a duplicate of https://github.com/nextcloud/mail/issues/386

**Closed by ChristophWurst** 2018-02-14 08:46 UTC
Labels: 0. to triage, needs info
