### ISSUE TITLE
Back to mail list button not working

### ISSUE THREAD

**Issue by maurerle** [nextcloud/mail#2927] opened 2020-04-17 08:48 UTC
### Expected behavior
On Clients with a smaller width (half Desktop or mobile) the arrow button in the top left makes it possible to go back to the list view from a single selected mail. 

### Actual behavior
Back button does not do anything. So there is no way to return to list view on smaller clients.

### Mail app

**Mail app version:** 1.3.2

#### Client configuration
**Browser:** Firefox 75, Chrome 81 on Win10 and Brave Browser on Android.

**Comment by ChristophWurst** [comment] 2020-05-11 07:07
Closing as duplicate of https://github.com/nextcloud/mail/issues/2942 (though you were faster but there is more feedback there)

**Closed by ChristophWurst** 2020-05-11 07:07 UTC
Labels: 0. to triage, bug
