### ISSUE TITLE
"Accept" button is not displayed correctly (CSS)

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/mail#8465] opened 2023-05-10 13:22 UTC
### Steps to reproduce

1. When receiving a .ICS invitation
2. See the Accept button shifted when other buttons are well aligned.

### Expected behavior

Accept button should be aligned with other buttons

### Actual behavior

Accept button is shifted in CSS for whatever reason

![image](https://github.com/nextcloud/mail/assets/6248852/e8aba3fc-95b1-450f-a97f-31d2587ff00a)

![image](https://github.com/nextcloud/mail/assets/6248852/d1ca4da3-eb17-41ae-8f03-77a0b08a0f59)

### Mail app version

3.1.1

### Mailserver or service

Posftix / Dovecot

### Operating system

Debian 11

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MySQL

**Comment by auroraanna** [comment] 2023-08-11 12:47
Could not reproduce on version 3.4.0-beta.2 regardless of viewport size:
![image](https://github.com/nextcloud/mail/assets/81317317/90ade406-e447-4b35-b5ed-c536756babf2)

**Comment by ChristophWurst** [comment] 2023-08-11 12:52
Closing as not reproducible. Thanks @auroraanna!

@Mer0me if you still have the issue please let us know and we can reopen the ticket.

Thank you for the feedback

**Closed by ChristophWurst** 2023-08-11 12:52 UTC
Labels: bug, design, 0. to triage, feature:imip

**Comment by Mer0me** [comment] 2023-08-26 13:53
I can confirm the fix. Thanks !
