### ISSUE TITLE
[feature request] Account name aliases

### ISSUE THREAD

**Issue by JasMich** [nextcloud/mail#2726] opened 2020-03-05 10:56 UTC
### Feature Request

I would like to create aliases for mail accounts. E.g. I have set up two mail addresses, me@foo.com and me@bar.com which are linked together (mails from me@bar.com are redirected to me@foo.com on the mail server and vice versa). It would be cool if I could just create an alias within Nextcloud Mail allowing me to select "me@foo.com" and "me@bar.com" in the "From" field when writing a new mail without setting up both mailboxes (as then all mails were shown twice).

![image](https://user-images.githubusercontent.com/29313398/75974566-4feaf800-5ed7-11ea-891b-513a8415eab5.png)

Same would apply to names. E.g. with the same mail address I maybe sometimes want to be shown by my first name, by my GitHub name or by my last name.

#### Summary

We'd need a button within the "Edit account" section to add name/address aliases which are then shown up in the account list when writing a new mail.

May be related to #1722 .

**Comment by ChristophWurst** [comment] 2020-03-05 14:37
> May be related to #1722 .

Yep, it's a duplicate of that ticket :)

Did you :+1: your own ticket intentionally? :laughing:

**Closed by ChristophWurst** 2020-03-05 14:37 UTC
Labels: 0. to triage, enhancement

**Comment by JasMich** [comment] 2020-03-05 16:51
Oh, sorry for opening.
