### ISSUE TITLE
Ability to map the sent, draft and deleted folders to other IMAP names

### ISSUE THREAD

**Issue by beccon4** [nextcloud/mail#2919] opened 2020-04-16 13:01 UTC
### Feature Request
Allow to assign Sent/Draft/Trash folders to IMAP folders.

#### Summary
My other mail programs - Thunderbird, K9, Rainloop (for the time being:-) ) use localized folder names for sent (INBOX.Gesendet)   draft (INBOX.Entwürfe) and deleted (INBOX.Papierkorb). I couldn't find an option to assign Mail's folders to these IMAP folders. (actually Mail generates a new ones e.g. IMAP.Sent)

**Comment by ChristophWurst** [comment] 2020-04-16 13:03
Duplicate of https://github.com/nextcloud/mail/issues/2035 :)

**Closed by ChristophWurst** 2020-04-16 13:03 UTC
Labels: duplicate, enhancement
