### ISSUE TITLE
Mail-App search/autocomplete in/with System Contacts/ LDAP

### ISSUE THREAD

**Issue by AlexanderZuehr** [nextcloud/mail#7305] opened 2022-09-22 07:23 UTC
### Is your feature request related to a problem? Please describe.

I've integrated our Active-Directory Users into the Nextcloud over the LDAP-Protocol with the LDAP user and group backend APP.
All AD Users are shown as Nextcloud Users and are also searchable within the top right System Contacts search menu.
Sadly they are not shown in the Contacts-App of each User. This is not really a Problem if the Mail App would use the Nextcloud System Contacts (searchable at the top right menu).

The Calendar App is doing this and sees all System Contacts and the Contacts from the Contacts App, the Mail App is not.

### Describe the solution you'd like

I'd like the Mail App to not just use the Contacts saved in the Contacts App, but also use the Contacts in the System Contacts (searchable at the top right menu).

### Describe alternatives you've considered

As an alternative, all imported Active-Directory Users could be imported into the Contacts App, but i have over 100 Users (a lot of manual work) and furthermore Apps like the Calender App search in the Contacts App and also in the System Contacts. After adding a user into the Contacts App, the User is listed twice in the Calender App, so this would fix the Mail App and break the Calendar App.

**Comment by Zupe007** [comment] 2022-09-27 11:11
@ChristophWurst 
Is this possible and easy to do for you?

**Comment by ChristophWurst** [comment] 2022-09-28 07:27
Possibly. Why did you add a rocket emoji to your own ticket?

**Comment by ChristophWurst** [comment] 2022-09-28 07:27
You can also install https://apps.nextcloud.com/apps/ldap_contacts_backend

**Comment by Zupe007** [comment] 2022-09-28 14:56
@ChristophWurst 
Ldap Contacts backend app is breaking the ldap user and group backend app for me, maybe that is a configuration problem but i would prefer the mail app to search in the system contacts to let it behave the same as the calender app. Furthermore my understanding of the Ldap contacts app is that it adds the functionality to add systems contacts directly to the contacts app but this would be needed to do for every user.
I tried some things in Github and added the rocket just for testing purposes to know what would happen.

**Comment by BiglifeMatt** [comment] 2023-02-25 11:49
This is the most critical piece for my team to be able to switch to using the Mail app.  Otherwise we are sticking with SnappyMail.  While the Contacts from LDAP can be looked up through the user search bar, that only triggers a direct email but doesn't let you drop in ad-hoc groups from the TO; field.  I would appreciate other features in the Mail app because of the deeper interactivity with the rest of Nextcloud, but this issue is too much of a frustration for our team.

**Comment by ChristophWurst** [comment] 2023-03-01 16:31
https://github.com/nextcloud/server/issues/19575 could help with this as well. @BiglifeMatt do you have anyone in your team with developing skills?

**Comment by BiglifeMatt** [comment] 2023-03-01 16:45
@ChristophWurst  I wish.  I am the team :)  I've touched on development before but never been too deep in understanding myself.

**Comment by BiglifeMatt** [comment] 2023-03-08 15:59
@ChristophWurst I'm wondering if we are looking in the wrong place for what is missing here... basically it looks like Nextcloud already identifies all of my LDAP accounts within the Nextcloud Users sections, either in the Users search at the top search bar or in the Admin Users section.  So perhaps that is where all of the other apps are pulling from when I go to share files, deck assignments, add to calendar events, and even circles.  Those all lookup the users fine.  It is only in Mail and adding users to Contact Groups that I do not see the Users available in the lookup.  Does this help with the location of where the auto-lookup should be done?

**Comment by BiglifeMatt** [comment] 2023-05-02 11:00
@AlexanderZuehr are you still pursuing a solution with this?  I'd still love to move to Nextcloud Mail from Snappymail just for the integration with other apps but I was hoping we could figure the LDAP suggestions out.  Additionally, I would like to see simplified Sieve filter rules as my users cannot create their own using the code method in the Mail app, but that is a separate issues.  Just saying, I'd like to be using this app but cannot promote it at this stage.

**Comment by AlexanderZuehr** [comment] 2023-05-02 11:36
@BiglifeMatt my company is using nextcloud as yours. I am not a developer for nextcloud and sadly i dont have the knowledge to fix this.
I would love to have this feature.

**Comment by ChristophWurst** [comment] 2023-05-30 07:03
Duplicate of https://github.com/nextcloud/mail/issues/1215

**Closed by ChristophWurst** 2023-05-30 07:03 UTC
Labels: enhancement, 0. to triage
