### ISSUE TITLE
Calendar integration - automatically show incoming (new) appointments in the calendar as tentative

### ISSUE THREAD

**Issue by sascha08-15** [nextcloud/mail#9470] opened 2024-03-15 07:58 UTC
### Is your feature request related to a problem? Please describe.

The problem is I do not see incoming invitations in my calendar but have to go to the mail I got the invite. 

### Describe the solution you'd like

Like in outlook, I'd expect incoming appointments to show up as tentative (do not auto reply) in my default (configured) calendar. This would (perhaps) mean .ical, .ics files would be processed by the mail plugin.

### Describe alternatives you've considered

Automation with Zapier and integration of mail and caldav as a workaround. Nasty hack instead of having the perfect toolchain in nextcloud.

### Additional context

Maybe this can be developed as separate plugin and must not be part of the mail app. But it's very closely related to the mail plugin.

**Comment by beccon4** [comment] 2024-03-27 08:20
I'd be happy to be able to get incoming appointments into the calendar without having to download them first to my terminal in the first place. Doing daily chores such as keeping schedules are quite tedious with Nextcloud: go to Mail, download the .ics or .ical attachment (which in some cases is not possible because Mail recognises it as an appointment but is unable to insert it into its calendar :-(  )  - then go to Calendar and import it. (and whan at a untrusted terminal delete the .ics/.ical file)

**Comment by ChristophWurst** [comment] 2024-10-24 12:08
Duplicate of https://github.com/nextcloud/mail/issues/7750

**Closed by ChristophWurst** 2024-10-24 12:08 UTC
Labels: enhancement, 0. to triage
