### ISSUE TITLE
"Sent" does not open

### ISSUE THREAD

**Issue by jh537** [nextcloud/mail#285] opened 2017-01-14 19:56 UTC
### Steps to reproduce
1. Klick Sent
2. Konnte Gesendet nicht laden :-|
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Mail app

**Mail app version:** (see apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
gleisnetze.de
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
tls
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
tls
**Number of accounts:**
2
**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:
ubuntu 16.04
**Web server:**
apache
**Database:**
mariadb
**PHP version:**
7.0
**Version:** (see admin page)

**Updated from an older version or fresh install:**
fresh
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml


**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocfjsrilo359",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.gleisnetze.de"
        ],
        "default_language": "de",
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/www.gleisnetze.de\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nc1",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_domain": "gleisnetze.de",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
TypeError: Argument 1 passed to OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in /var/www/html/nextcloud/apps/mail/lib/Model/ConvertAddresses.php on line 74

    /var/www/html/nextcloud/apps/mail/lib/Model/ConvertAddresses.php - line 74: OCA\Mail\Model\IMAPMessage->hordeToAssoc(Object(Horde_Mail_Rfc822_Group))
    /var/www/html/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 225: OCA\Mail\Model\IMAPMessage->convertAddressList(Object(Horde_Mail_Rfc822_List))
    /var/www/html/nextcloud/apps/mail/lib/Model/IMAPMessage.php - line 494: OCA\Mail\Model\IMAPMessage->getToList(true)
    /var/www/html/nextcloud/apps/mail/lib/Mailbox.php - line 190: OCA\Mail\Model\IMAPMessage->jsonSerialize()
    /var/www/html/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 137: OCA\Mail\Mailbox->getMessages(0, 21, '')
    [internal function] OCA\Mail\Controller\MessagesController->index(3, 'U2VudA==', 0, 20, '', NULL)
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'index')
    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'index')
    /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/mail/acco...')
    /var/www/html/nextcloud/index.php - line 40: OC handleRequest()
    {main}

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment] 2017-01-17 07:28
> TypeError: Argument 1 passed to OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in /var/www/html/nextcloud/apps/mail/lib/Model/ConvertAddresses.php on line 74

Duplicate of https://github.com/nextcloud/mail/issues/53

**Closed by ChristophWurst** 2017-01-17 07:28 UTC
