### ISSUE TITLE
HTLM messages dont expand depending on size

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#8194] opened 2023-03-03 10:24 UTC
### Steps to reproduce

1. Open an html message that is longer than a paragraph
2. See the size
3.

### Expected behavior

The message expands depending on the height of the screen

### Actual behavior

Its always a default small size

### Mail app version

3.0.0-beta.2

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

![Screenshot from 2023-03-03 11-21-21](https://user-images.githubusercontent.com/12728974/222696248-9a7beb88-d188-47d4-bfde-ba44d2fbc97b.png)

**Comment by GretaD** [comment] 2023-03-03 10:26
I thinks its a nc/vue regression, but instead of reverting, we should fix this one mail

**Comment by hamza221** [comment] 2023-03-15 13:44
It's solved on the latest main, I'll try to find out the cause of the bug

**Comment by ChristophWurst** [comment] 2023-03-16 07:35
Most likely the iframe resizer script is not loaded in the iframe.

![Bildschirmfoto vom 2023-03-16 08-35-10](https://user-images.githubusercontent.com/1374172/225546621-2f154048-98a7-4873-a8c5-173c86ca70f9.png)

**Comment by ChristophWurst** [comment] 2023-03-21 07:29
stable3.0 is still broken accoring to latest reports

**Comment by ChristophWurst** [comment] 2023-03-21 07:38
https://github.com/davidjbradshaw/iframe-resizer/commit/392cd561d2b350a8587a8ce9b95ada111a5ef9ce

**Comment by ChristophWurst** [comment] 2023-03-23 09:46
Fixed by https://github.com/nextcloud/mail/pull/8265

**Closed** 2023-03-23 09:46 UTC
Labels: bug, 3. to review, design, regression, skill:frontend
