### ISSUE TITLE
Email is sent but stuck in Outbox too.

### ISSUE THREAD

**Issue by holybank** [nextcloud/mail#9621] opened 2024-05-02 02:45 UTC
### Steps to reproduce

1. Add a new message
2. Send email
3. Mail is sent
4. Mail also stuck in Outbox

### Expected behavior

Mail is sent and not stuck in Outbox

### Actual behavior

Mail is sent and stuck in Outbox

### Mail app version

3.6.0

### Mailserver or service

Modoboa

### Operating system

Ubuntu 22.04

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

PostgreSQL

### Additional info

browser console errors:

> AvatarService.js:36 
>  GET https://{host}/index.php/apps/mail/api/avatars/url/MAILER-DAEMON%40{domain} 404 (Not Found)
> OutboxService.js:72 
>  POST https://{host}/index.php/apps/mail/api/outbox/37 500 (Internal Server Error)
> actions.js:134 [ERROR] mail: Failed to send message 37 from outbox 
> {app: 'mail', uid: '{user}', level: 2, error: a}
> actions.js:182 [ERROR] mail: Could not delay-send message 37 
> {app: 'mail', uid: '{user}', level: 2, message: {…}}
> vuex.esm.js:542 Uncaught (in promise) 
> a {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}

![image](https://github.com/nextcloud/mail/assets/60592334/32b284c9-f9ad-43b0-8854-d63926402488)

NextCloud version 28.0.4.1

If you need any more information or logs, please tell me where to get such information too. I'm new to this.

**Comment by ChristophWurst** [comment] 2024-05-06 14:08
Duplicate of https://github.com/nextcloud/mail/issues/8435.

A fix is coming with v3.7.

**Comment by miaulalala** [comment] 2024-07-01 08:47
Fixed in 3.7

**Closed by miaulalala** 2024-07-01 08:47 UTC
Labels: bug, 0. to triage

**Comment by axraph** [comment] 2024-07-05 15:27
I am having the same problem, the email is sent but it's stuck in the outbox.

I'm running NextCloud version 29.0.3 - and Mail app version 3.7.2

Errors in console:
<img width="770" alt="Screen Shot 2024-07-05 at 6 11 00 PM" src="https://github.com/nextcloud/mail/assets/54176057/517bcdd0-85d1-48c6-8db2-4b709ba1b5dd">

Errors in admin log:
<img width="1684" alt="Screen Shot 2024-07-05 at 6 23 59 PM" src="https://github.com/nextcloud/mail/assets/54176057/59c5eec6-c8e5-4cca-b32d-afd0be826a6a">

**Comment by Isac99** [comment] 2024-07-06 22:06
Had the same issue and worked out that the outbox is the table oc_mail_local_messages. Check the message and delete it. For me there was only one message so I emptied the table. Warning will stop in the log after this action.

**Comment by axraph** [comment] 2024-07-07 06:29
> Had the same issue and worked out that the outbox is the table oc_mail_local_messages. Check the message and delete it. For me there was only one message so I emptied the table. Warning will stop in the log after this action.

Yea I deleted the message from the outbox too. Now I'm giving SnappyMail a try, not as pretty but actually working.

**Comment by miaulalala** [comment] 2024-07-08 10:04
> I am having the same problem, the email is sent but it's stuck in the outbox.
> 
> I'm running NextCloud version 29.0.3 - and Mail app version 3.7.2
> 
> Errors in console: <img alt="Screen Shot 2024-07-05 at 6 11 00 PM" width="770" src="https://private-user-images.githubusercontent.com/54176057/346167512-517bcdd0-85d1-48c6-8db2-4b709ba1b5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzMwNTYsIm5iZiI6MTcyMDQzMjc1NiwicGF0aCI6Ii81NDE3NjA1Ny8zNDYxNjc1MTItNTE3YmNkZDAtODVkMS00OGM2LThkYjItNGI3MDliYTFiNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5NTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NmQzYjg1MTMxOGQwZGNiZjNhODkwYjA3NzBiN2E3YzE5Y2I1NzFkY2ZmMWNiZmNmMWNmNjBkZTY4YmRmYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C60TH84Ti60ItqT_-RkbJ0eOR3efuEdLDA-xKQTH-E4">
> 
> Errors in admin log: <img alt="Screen Shot 2024-07-05 at 6 23 59 PM" width="1684" src="https://private-user-images.githubusercontent.com/54176057/346168022-59c5eec6-c8e5-4cca-b32d-afd0be826a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzMwNTYsIm5iZiI6MTcyMDQzMjc1NiwicGF0aCI6Ii81NDE3NjA1Ny8zNDYxNjgwMjItNTljNWVlYzYtYzhlNS00Y2NhLWIzMmQtYWZkMGJlODI2YTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA5NTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOTZiNjBmMDJkODcwMjU3MmQ0YWIzYjUxNjFlNTRiYjVlMThjNDU2OTUyM2ViYmQ5ZWVkNjE2NGFmMGJjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MrxJhVazKM7EFuMaDE-2tWYP5lCuiRab9Flttngt1is">
> 
> @ChristophWurst @miaulalala

We have 3 states for the outbox when a send error happens
	- the mail was sent but couldn't be copied to the sent mailbox. This error will be handled by the logic and the copy operation will be tried again.
	- the send was unsuccessful with a state than can be retried (ex: the SMTP server couldn't be reached). We will retry sending the message again.
	- the send operation might or might not have failed - the error you have. As we have no way to determine if the message was sent or not, we do nothing with the message. We don't want to assume it was sent (a double send is not a desired outcome) but we also don't want to delete the message in case the mail was NOT sent. So it's up to the account owner to determine what happens next.

**Comment by axraph** [comment] 2024-07-09 10:37
Thank you @miaulalala for the explanation. It makes sense.

It also begs the followup question, what makes the mail app (horde) consider the send state "unclear" in my case, although all other mail clients are okay with it? I've been using this particular mail server (CPanel) for years with a myriad of email clients such as Apple Mail, Thunderbird, Roundcube, Gmail, and lately SnappyMail. They all produce no errors when sending and messages get moved from the outbox to sent without fail. 

Maybe you've been testing with "fancier" enterprise mail servers, which makes total sense. Perhaps you could consider revisiting this at a later stage to make the app more forgiving for smaller setups?

Thanks a lot!

**Comment by miaulalala** [comment] 2024-07-10 08:48
Some of the errors entirely depends on your mail server configuration - in my setup for example I wasn't able to observe the copy error, but other Devs with a dovecot setup for example had an issue because of the number of connections that were attempted in a certain amount of time. Since we still want to be robust in this, we decided to add the copy retry.

As for the indeterminate errors, the SMTP connection read and write methods in Horde might throw a `\Horde_Smtp_Exception::DISCONNECT` error, a `\Horde_Smtp_Exception::SERVER_READERROR`  or a `\Horde_Smtp_Exception::SERVER_WRITEERROR` at any time in the transmission flow. So it could happen at the end of a command sequence so the mail is sent, but there's no corresponding SMTP reply, or it could happen in the middle of a command sequence. I could also imagine an issue with Horde and how it deals with the SMTP replies, although that is just a hunch, not a definitive. 

We have no way of knowing what happened, and as far as I know there is no part in the SMTP protocol that allows for a query to the state of the message.

There might possibly be a better way to do this, but I haven't found it (yet). Suffice to say we had issues with duplicate / multiple send operations on the same email before we split the error handling into multiple states. Unfortunately I can't make any promises about looking into this, as that would mean digging into the RFCs and unfortunately, my time is limited at the moment.

Does this answer your questions?

**Comment by axraph** [comment] 2024-07-10 10:45
Thanks @miaulalala for taking the time to explain this. You're correct, my setup is utilizing Dovecot, as I have no access to its configuration I suppose it's time to consider other options for mail hosting.

Thank you for all the support and the brilliant work!
