### ISSUE TITLE
getSubject() return value must be string not bool

### ISSUE THREAD

**Issue by LloydS42** [nextcloud/mail#4596] opened 2021-02-26 11:01 UTC
Expected behavior
When opening email mailbox no email will shown.

Actual behavior
in example with id 11:
```
occ mail:account:sync 11
[...]
[debug] Initial sync 11:INBOX - fetch all messages from IMAP took 2s
[debug] Unlocking mailbox 23 from vanished messages sync
[debug] Unlocking mailbox 23 from changed messages sync
[debug] Unlocking mailbox 23 from new messages sync

In ImapToDbSynchronizer.php line 238:
  Sync failed for 11:INBOX: Return value of OCA\Mail\Model\IMAPMessage::getSubject() must be of the type string, bool returned

In IMAPMessage.php line 276:
  Return value of OCA\Mail\Model\IMAPMessage::getSubject() must be of the type string, bool returned

occ mail:account:diagnose 11
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR
- STARTTLS

Account has 2 messages in 2 mailboxes
```

Mail app
Mail app version: 1.8.3

Mailserver or service: Personally hosted postfix and dovecot email server. The mail server is running using a Let's Encrypt certificate. Nextcloud and the email server are on the same machine. Login info is correct. Server settings are correct.

Server configuration
Operating system: Gentoo Kernel 5.4.97 x64 musl

Web server: Apache 2.4.46

Database: PostgreSQL 12.6

PHP version: 7.4.15

Nextcloud Version: 20.0.8

Client configuration
Browser: Chrome 88.0.4324.182 running on Debian 10.8 (64-bit)

Operating system: Linux (Rasbian OS)

See also: [Nextcloud Forum (German)](https://help.nextcloud.com/t/zugriff-auf-mail-app-funktioniert-nicht/106769)

**Comment by st3iny** [comment] 2021-02-26 11:27
Are you running your Nextcloud server inside a docker container using alpine linux as a base image? If so, this bug is fixed via #4453. The backport to 1.8 is still pending at #4483.

Iconv is broken on apline linux (ref https://github.com/nextcloud/mail/issues/3999).

**Comment by LloydS42** [comment] 2021-02-26 12:30
Thanks for help. No, the system is running direct on hardware, there is no virtualisation, Docker etc.
Yes, System is Gentoo Linux with musl as glibc alternitive.
Also, the same system constellation works fine with Nextcloud 19, with may sub-versions. Problem occurs since Nextcloud 20. I'm not sure about the Mail-App Versions in this time, but I always update early - Nextcloud Server and Apps.
In detail, musl and iconv works fine with Nextcloud 19 and Mail-App. In between there are updates also for musl. I have to look about that. But I'm pretty sure the problems came with Nextcloud 20.

**Comment by st3iny** [comment] 2021-02-26 12:44
The problem is that our mail app uses the non-POSIX-compliant `\\IGNORE` flag to recover from invalid utf8. As it turns out musl based systems do not implement this flag (ref #4351).

Unfortunately, you have to wait for the mentioned backport to be merged and released. In the meantime you could apply the [patch](https://patch-diff.githubusercontent.com/raw/nextcloud/mail/pull/4483.patch) manually.

**Comment by st3iny** [comment] 2021-02-26 12:48
**PS:** Older version of the mail app were not affected because we introduced the iconv call not long ago.

**Closed** 2021-02-26 12:55 UTC
Labels: 0. to triage, bug

**Comment by LloydS42** [comment] 2021-02-26 13:48
Okay. Thank you!
