### ISSUE TITLE
Show number of unread emails and format number according to available space

### ISSUE THREAD

**Issue by kevgathuku** [nextcloud/mail#967] opened 2018-07-10 20:15 UTC
### Expected behavior
Email count should not go beyond the end of the column

### Actual behavior
![output 1](https://user-images.githubusercontent.com/3721994/42534991-ed48fcc2-8496-11e8-9f44-49babb626973.png)

### Mail app

**Mail app version:** 0.8.2

**Mailserver or service:** Gmail

**Number of accounts:**  1

**Comment by ChristophWurst** [comment] 2018-07-23 07:42
Good catch. cc @jancborchardt @skjnldsv

**Comment by jancborchardt** [comment] 2018-07-24 07:40
Let's simply display "99+" as a maximum to limit it. :) (Think that's also said in the guidelines?)

**Comment by skjnldsv** [comment] 2018-07-24 07:41
999+ I think :)

**Comment by RobertZenz** [comment] 2019-10-22 12:22
It's, at least for me, not being displayed at all anymore on the latest version and NC 16. Is that by design or a problem on my end?

**Comment by skjnldsv** [comment] 2019-10-22 12:26
I think it's fixed now :)

**Comment by ChristophWurst** [comment] 2019-10-22 12:39
The counters were removed as the logic to keep them in sync was more than buggy. We're working on a new logic (#2064) that will eventually make this more reliable.

**Comment by benks-io** [comment] 2020-11-04 11:04
@ChristophWurst 
As IMAP Caching to DB is working since April 2020, this useful feature could be implemented again, I guess.

**Comment by ChristophWurst** [comment] 2020-11-04 12:01
Ah yes. I had this on my mental todo

**Comment by benks-io** [comment] 2020-11-04 12:15
I propose to rename this Issue "Show Email count, and format Number according to space"

**Comment by ChristophWurst** [comment] 2020-11-30 07:42
This is actually a duplicate of https://github.com/nextcloud/mail/issues/1400 now. Let's continue there as it also explains the context of why this was dropped as known regression.

**Closed by ChristophWurst** 2020-11-30 07:42 UTC
Labels: 1. to develop, bug, design, feature parity, papercut, priority:high
