### ISSUE TITLE
Infinite scroll doesn't load messages on mobile browsers (FF, Chromium, Morph)

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/mail#3333] opened 2020-06-29 16:32 UTC
### Expected behavior
Scrolling down to the bottom of the "other" emails triggers loading of more emails regardless of browser used

### Actual behavior
When any mobile browser tested (set to either mobile or desktop), nothing happens when scrolling to the bottom of the page. No further emails are loaded and the throbber never appears. This prevents users from loading more than the first page of "other" emails. It works fine on desktop browsers such as Firefox and Chromium on Linux.

Maybe a workaround would be to display a manual "load more" link at the bottom, which is replaced by the throbber when infinite scroll loading is triggered. That way if it isn't triggered, users can still manually click to load more emails.

### Mail app

**Mail app version:** 1.4

**Mailserver or service:** Email at Hostgator

### Server configuration

**Operating system**: Debian 9
**Web server:** Nginx
**Database:** MariaDB

**PHP version:** 7.3...I think. May be 7.2.

**Nextcloud Version:** 18.05
#### Client configuration
**Browser:** Firefox 68.9.0, Chromium, Chrome, Morph browser
**Operating system:** Android 9, except Morph which is the PinePhone UBT Community Edition Edge version.

**Comment by ChristophWurst** [comment] 2020-06-29 16:37
Yep :(

Duplicate of https://github.com/nextcloud/mail/issues/1619.

@GretaD is working on it.

**Closed by ChristophWurst** 2020-06-29 16:37 UTC
Labels: 0. to triage, bug
