### ISSUE TITLE
global user

### ISSUE THREAD

**Issue by christophe195** [nextcloud/mail#2395] opened 2019-12-18 15:59 UTC
### Feature Request

We use nextcloud for or organization, we have one email and want to grand all our staff access to it.

#### Summary

It woud be nice if we can set a hardcode username (global or something) in the admin section so we use the same settings on all users.

**Comment by ChristophWurst** [comment] 2019-12-18 18:39
Sounds like a possible duplicate of https://github.com/nextcloud/mail/issues/572. Can you confirm?

**Comment by christophe195** [comment] 2019-12-18 22:58
> Sounds like a possible duplicate of #572. Can you confirm?

I think, i want a option to overwrite the userid value so it can be "admin" or "global".

**Comment by ChristophWurst** [comment] 2019-12-19 07:49
I'm not sure I can follow. Are you saying your use case would be covered by the feature described in #572?

In any case, are you a customer of Nextcloud Gmbh? This would be something we could develop for your organization.
If you're a developer we can discuss where this would need to be added. And you can contribute the necessary changes :)

**Closed** 2020-01-09 08:06 UTC
Labels: 0. to triage, duplicate, enhancement, needs info
