### ISSUE TITLE
INBOX sub folders of multiple accounts merged in one

### ISSUE THREAD

**Issue by jroussay** [nextcloud/mail#5564] opened 2021-09-23 09:13 UTC
Hello,
### Expected behavior
Tell us what should happen
Two email accounts are setup, they have their own sub folder into there respective INBOX folder.
```
mb1@nc.org
- INBOX
  - f1
  - f2
mb2@nc.org
- INBOX
  - f3
  - f4
```
### Actual behavior
Tell us what happens instead
When two email accounts are setup into the application, sub-folders of the mailbox are merged into one account.
```
mb1@nc.org
- INBOX
  - f1
  - f2
  - f3
  - f4
mb2@nc.org
- INBOX
```
### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.10.4

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
IMAP (Infomaniak)

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian 10
**Web server:** (e.g. Apache, Nginx,...)
Apache
**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB
**PHP version:** (e.g. 7.0)
7.4
**Nextcloud Version:** (see admin page, e.g. 13.0.2)
22.1.1
#### Client configuration
**Browser:** (e.g. Firefox 48)
All
**Operating system:** (e.g. Arch Linux)
All

Thanks for your great work

**Comment by ChristophWurst** [comment] 2021-09-23 12:12
inspect your oc_mail_mailboxes. Is the mailbox name and account_id association wrong at this level already?

**Comment by jroussay** [comment] 2021-09-23 12:40
No it's ok in the database

**Comment by ChristophWurst** [comment] 2021-10-12 07:07
I don't see where we'd possibly mix up the accounts and mailboxes in the code. If you are familiar with js and Vue you could try to open Mail with Chrome and the Vue dev tools and inspect the Vuex store to see the accounts and which mailboxes are assigned to them. This info could get up one step closer to knowing where things break for you.

**Comment by rebootit** [comment] 2021-11-10 11:14
Same here, two mail account, the sub folder of the second are merged on the fist account

**Comment by ChristophWurst** [comment] 2021-11-10 11:22
> I can build a dev version for you: [mail.tar.gz](https://github.com/nextcloud/mail/files/7345777/mail.tar.gz)

@rebootit same instructions for you. Inspect the account with the Vue dev tools. Unfortunately I have not heard back from @jroussay.

**Comment by nilskamm** [comment] 2021-12-15 07:41
Duplicate of #4305

**Comment by nilskamm** [comment] 2021-12-15 07:43
Just found this one, when i wanted to update the other one. 
Hope that there will finally be a solution.
This error makes this app unusable for me since i use nextcloud.

**Comment by ChristophWurst** [comment] 2021-12-15 09:28
This bug is in fact planned to be worked on this week :v:

**Closed** 2021-12-15 09:27 UTC
Labels: bug, 0. to triage
