### ISSUE TITLE
GMail compatibility without app passwords

### ISSUE THREAD

**Issue by Hal1512** [nextcloud/mail#6454] opened 2022-05-14 20:20 UTC
### Is your feature request related to a problem? Please describe.

GMail considers the integration from this Mail app to be 'less secure'.   They claim on their site that they will no longer support apps that log into your mail account with only user name and password.   

https://support.google.com/accounts/answer/6010255?hl=en 

### Describe the solution you'd like

I believe that if the mail connector also asked for and presented an App Password to GMail, that qualifies as a more secure way to connect.

https://support.google.com/accounts/answer/185833

**Comment by feutl** [comment] 2022-06-09 11:25
This is an issue now!
I have 2 accounts which do not work with nextcloud mail any more. The workaround to use 2FA and a app password is not a sufficient solution.
Fairemail fixed the issue on Android and let me sync my mails without setting up 2FA.

How could something like this not being resolved in time? Gmail is sadly used by lots of NC users - I am quite sure.

**Comment by ChristophWurst** [comment] 2022-06-09 11:58
My personal account still works.

**Comment by feutl** [comment] 2022-06-09 12:06
@ChristophWurst 
Have you setup 2FA with an app specific password ? If so, yes it works.
If not, I am surprised, all 3 of my accounts without 2FA do not work any more.

**Comment by ChristophWurst** [comment] 2022-06-09 12:16
Right, I'm using 2FA with an app password.

**Comment by feutl** [comment] 2022-06-09 12:18
And this is the issue, if you have not setup 2FA (for whatever reason) there is no app password option in gmail. Therefor the authentication needs to be fixed for those accounts.
As I said, Fairemal - the android client - has fixed this already some time ago.

**Comment by MrPresident2** [comment] 2022-06-15 09:42
any news about that? I don't think we can use Gmail anymore

**Comment by enekonieto** [comment] 2022-06-15 15:06
Until someone is assigned I think we should hope no movement.

**Comment by MrPresident2** [comment] 2022-06-15 21:17
do you know about another way to connect Gmail to Nextcloud then?

**Comment by enekonieto** [comment] 2022-06-20 09:29
No, I am also stuck with this issue :(

**Comment by ChristophWurst** [comment] 2022-07-01 14:05
I causes a generic *Invalid credentials*. So we need to keep book about the token validity and do the refresh proactively.

**Comment by ChristophWurst** [comment] 2022-07-04 15:14
POC is at https://github.com/nextcloud/mail/pull/6830. Linking the Nextcloud Mail account to Gmail works. Keeping the access token updated works.

The open todos are mostly about handling all possible conditions during the setup and making sure the app stays usable with this new auth option.

**Comment by ChristophWurst** [comment] 2022-07-08 13:22
https://github.com/nextcloud/mail/pull/6830#issuecomment-1178964939 sneak preview

**Comment by feutl** [comment] 2022-07-11 12:18
I have the feeling that also outlook.com or MS365 accounts cannot be added to Mail right now.
I have an enterprise subscription which I wanted to add to Mail but I am struggeling. I assume the same issue.

**Comment by ChristophWurst** [comment] 2022-07-11 17:35
Related: https://github.com/nextcloud/mail/issues/6591

**Comment by Dvalin21** [comment] 2022-07-22 19:32
Google no longer or at least it doesnt show up when I got there a way to add an "App" Password.  I keep getting this setting is no longer available.

**Comment by feutl** [comment] 2022-08-17 14:03
Any news when this is getting released ?
Got quite silent the last days after the initial push by @ChristophWurst

**Comment by ChristophWurst** [comment] 2022-08-17 14:26
I can't give an ETA at this point. It's ongoing work but there are lots of things happening at the time.

**Comment by feutl** [comment] 2022-08-18 06:54
great, like to hear that lots of things are happening :D thanks

**Closed** 2022-12-02 08:18 UTC
Labels: bug, 3. to review, regression

**Comment by feutl** [comment] 2023-02-28 08:25
Any timeframe when this gets released, it is almost a year now.

**Comment by ChristophWurst** [comment] 2023-02-28 08:43
2022-12-05

**Comment by feutl** [comment] 2023-02-28 09:37
ok, I found the hint in the release notes but really struggling in getting this working.
The information in the NC admin panel as well as https://github.com/nextcloud/mail/blob/main/doc/admin.md are very rudimentary - as a non DEV ;)
Still struggling in finding the right api - app to get started.

**Comment by ChristophWurst** [comment] 2023-02-28 09:51
OAuth is technical. We can't change that. Selfhosting and OAuth is always a bit painful.

**Comment by feutl** [comment] 2023-02-28 09:53
Would be great to have more guidance, like how to setup the "OAuth-Zustimmungsbildschirm" correctly and so on
Had a look at help.nextcloud.com but could not find anything more specific there either.

**Comment by digitalrevisor** [comment] 2023-06-07 15:11
Hi, I have been trying to find the right place to write this, and here is my best bet I think.
We have an issue with Google integration Oauth.

We have set up an OAuth consent screen and a client.
And that works fine with @gmail.com accounts but Google email accounts with other domains do not, i.e. @digitalrevisor.no.

What happens when trying to log in with the @digitalrevisor.no domain I get a message below: IMAP username or password is wrong and the consent screen does not appear.
This is a Google account and works with all other Google Oauth solutions. (Including Connected Accounts in Nextcloud)

Is the login for Mail just looking for @gmail.com before it opens the consent screen?
If so, is there or can you add a possibility to add domains in the Google integration settings?

Should I create a new issue for this?

**Comment by ChristophWurst** [comment] 2023-06-07 17:08
Gmail OAuth is only used for accounts hosted by Google. Yours does not seem to be

![image](https://github.com/nextcloud/mail/assets/1374172/41d287e4-14cd-41a5-a18f-056bb37c8f50)

In any case, Github is for bugs. Please open a topic at https://help.nextcloud.com/c/apps/mail/35 for community support.

**Comment by digitalrevisor** [comment] 2023-06-09 06:54
Noted. Only Google Oauth implementation we have ever seen not accepting Google accounts with a different domain than @gmail.com is not a bug, but a feature I guess then.

Note: I believe that this is the reason why one has a separate sign-in with a Google button:
If the app had put Google.com instead of one.com it would work.

It is in no way uncommon for organizations to use their own domains for both Google and Microsoft accounts.

**Comment by tmrlvi** [comment] 2023-06-09 19:14
Are you sure you email is hosted by gmail? If so, you can try to manually set up the connection with gmail's smtp and imap configuration (without password), and the authorization screen will pop up.
However, connection (post oauth login) will fail if it isn't actually hosted on gmail.

**Comment by digitalrevisor** [comment] 2023-06-12 07:06
https://github.com/nextcloud/mail/assets/59980626/da068d63-cc09-4871-8ca2-42963a416904

Her is a video logging in via Google Oauth to Google data migration app in Nextcloud with a @digitalrevisor.no domain.
I can't believe that we are the only ones going to have issues with logging into the Mail app.
