### ISSUE TITLE
Email shows unrelated email address as sender and recipients

### ISSUE THREAD

**Issue by graue70** [nextcloud/mail#4412] opened 2021-01-27 00:21 UTC
### Expected behavior
The mail UI shows the sender of each email.

### Actual behavior
A particular email address sent me two emails. The UI shows `no-reply@zoom.us` with the zoom logo as an additional address (besides the actual sender and me, the receiver). The UI apparently thinks that zoom is the sender because the list of emails in the middle panel shows the zoom logo (see screenshot below).

If I search the source of the email for the word 'zoom', there is no search result. If I configure the email address in thunderbird, there is no trace of 'zoom' anywhere when viewing the email, particularly not as the sender. The email is not related to zoom whatsoever.

See screenshot:
![nextcloud-mail-zoom-bug-censored](https://user-images.githubusercontent.com/23035329/105921903-d94c7100-6039-11eb-9bdd-87c91d01d370.png)
In the right panel underneath the first subject line, you see Zoom on the left side. Next to it, there is the true sender and then my own address, the receiver (both censored by me).

This might be related to #4198 but I (as in my NC user account) personally have not ever deleted an email from zoom. The subject contains `#` and `[]` and the UI shows it correctly and completely.

**Update**: The UI looks the same for a different NC user account using the same email address.

### Mail app

- **Mail app version:** 1.8.0
- **Mailserver or service:** netcup.de

### Server configuration

- **Operating system**: unknown (hosted)
- **Web server:** unknown (hosted)
- **Database:** mysql
- **PHP version:** 7.3.26
- **Nextcloud Version:** 20.0.6

### Client configuration

- **Browser:** Firefox 84.0.2
- **Operating system:** Linux Mint 19.1 and probably Windows 10

**Comment by graue70** [comment] 2021-01-27 13:01
**Update that changes the issue a lot**: I let a different user account using the same email address take the same screenshot that I took. It looks exactly the same.

**Comment by ChristophWurst** [comment] 2021-01-27 13:47
> **Update that changes the issue a lot**: I let a different user account using the same email address take the same screenshot that I took. It looks exactly the same.

I'm not sure I can follow. Is this an issue if more than one user have an account configured with an identical email address?!

The issue is kind of known, but it shows very rarely. So far we couldn't identify the pattern for when this occurs.

**Comment by graue70** [comment] 2021-01-27 19:50
> I'm not sure I can follow. Is this an issue if more than one user have an account configured with an identical email address?!

I don't know whether that is a prerequisite for the issue, but in my case that is true. Two users have the same email address configured in their NC. The issue shows for both. I'm gonna find out whether it shows for other people as well.

> The issue is kind of known, but it shows very rarely. So far we couldn't identify the pattern for when this occurs.

Interesting and strange. I searched for similar issues but found only the one I linked.

**Comment by davidpr78** [comment] 2021-02-01 16:56
I' ve watched the same problem. E-mails were send with a different sender name. Strange.

**Comment by ChristophWurst** [comment] 2021-02-01 17:13
thanks for the info @davidpr78. do you see any similarities with @graue70 setup?

**Comment by ChristophWurst** [comment] 2021-02-01 17:13
also cc @blizzz who's having the exact same issue as well

**Comment by davidpr78** [comment] 2021-02-01 18:44
Client ist Chome on Windows 10, Sever? (NC ist hosted by edudocs.org)

**Comment by graue70** [comment] 2021-02-01 22:03
The issue occurs with another email from today. The true sender address is different than before. Shows zoom as well.

So for me: Different users, different true sender addresses, so far only one wrong sender address (always zoom).

**Comment by ChristophWurst** [comment] 2021-02-02 07:46
One thing that I noticed with @blizzz is that on his setup the data was already wrong in the database.

But let's try to have this confirmed. Open that message with wrong sender/recipient. The URL has the *message ID*, which is a number, like `/apps/mail/box/priority/thread/33867` -> 33867 is the ID. Now look into `oc_mail_recipients` with `message_id`=33667 -> you'll find a list of participants. Type 0 is the sender, 1 is *to, 2 is *cc* and 3 is *bcc*. Is the data correct or incorrect there?

**Comment by graue70** [comment] 2021-02-02 22:07
> One thing that I noticed with @blizzz is that on his setup the data was already wrong in the database.
> 
> But let's try to have this confirmed. Open that message with wrong sender/recipient. The URL has the _message ID_, which is a number, like `/apps/mail/box/priority/thread/33867` -> 33867 is the ID. Now look into `oc_mail_recipients` with `message_id`=33667 -> you'll find a list of participants. Type 0 is the sender, 1 is *to, 2 is _cc_ and 3 is _bcc_. Is the data correct or incorrect there?

For the two emails I originally wrote about, there are four items with the same id each:
- Type 0: Correct sender
- Type 0: Incorrect sender (zoom)
- Type 1: Correct recipient (me)
- Type 1: Correct recipient (me)

For the message that came later, there are three items:
- Type 0: Correct sender
- Type 0: Incorrect sender (zoom)
- Type 1: Correct recipient (me)

In short, the data is incorrect in the database.

**Comment by ChristophWurst** [comment] 2021-02-03 18:13
huh, so always *one additional sender* … I guess that is a pattern …

**Comment by ChristophWurst** [comment] 2021-02-05 13:37
@GretaD just ran into this and we have seen message with *one additional sender* but also *one additional recipient* and *two additional CCs*. That breaks the pattern from above.

**Comment by davidpr78** [comment] 2021-02-08 08:01
I've seen now, that a wrong sender ist displayed, when it is an reply of an e-mail with several recipients. The sender is in the list of recipients but did not answer to me. Are there any solutions yet?

**Comment by ChristophWurst** [comment] 2021-02-08 08:22
No solution yet, we still have to figure out why this actually happens. Thanks for your input.

**Comment by miaulalala** [comment] 2021-02-26 10:03
Investigate \OCA\Mail\Db\MessageMapper::insertBulk

**Comment by ChristophWurst** [comment] 2021-03-03 16:50
This is a shot in the dark but could everyone who's affected please tell us what db they use and in what precise version?

**Comment by ChristophWurst** [comment] 2021-03-03 17:07
Another thing to check please if you use mysql: ``SELECT table_name, engine  FROM information_schema.tables  WHERE table_name IN ('oc_mail_messages', 'oc_mail_recipients');`` <- we wanna know your storage engines :)

**Comment by klassikmann** [comment] 2021-03-03 17:58
I was affected as long as I used linuxserver/docker-mariadb until I got the notification in nextcloud "_MariaDB version "10.1.47-MariaDB-0ubuntu0.18.04.1" is used. Nextcloud 21 will no longer support this version and requires MariaDB 10.2 or higher._" Because MariaDB is not officially compiled for arm32 devices the linuxserver image is stuck on 10.1.*. 
(btw. linuxserver/docker-mariadb changing to alpine-10.5.8 with is in pre-release state.)

After I replaced linuxserver/docker-mariadb by webhippie/mariadb (MariaDB version is 10.4.8) the problems vanished immediately.

Perhaps my observation helps.

**Comment by ChristophWurst** [comment] 2021-03-03 19:19
Thanks a lot for the info @klassikmann. A coworker had the same problem on mysql shipped with ubuntu 18.04 – 5.7 and after the dist upgrade it's gone. turns out ubuntu 20.04 ships mysql 8. that is the version that fixed https://dev.mysql.com/worklog/task/?id=6204.

**Comment by ChristophWurst** [comment] 2021-03-04 07:04
The latest idea is that the db recycles previously used DBs. That happened on mysql until recently. More info at https://stackoverflow.com/a/18692168/2239067 and https://dev.mysql.com/worklog/task/?id=6204

This means we can't always rely on our async cleanup job that runs once a day, but we should likely clean recipients right away when a message is deleted.

* ``\OCA\Mail\Db\MessageMapper::deleteAll``
* ``\OCA\Mail\Db\MessageMapper::deleteByUid``

Are two of the obvious suspects that leave orphaned recipients.

**Comment by klassikmann** [comment] 2021-03-04 07:34
In addition to my comment (https://github.com/nextcloud/mail/issues/4412#issuecomment-789938142):
I just received a new mail with a correct header but with a content from a yesterday's mail.

**Comment by blizzz** [comment] 2021-03-04 11:24
> Another thing to check please if you use mysql: `SELECT table_name, engine FROM information_schema.tables WHERE table_name IN ('oc_mail_messages', 'oc_mail_recipients');` <- we wanna know your storage engines :)

yep, InnoDB

**Comment by klassikmann** [comment] 2021-03-04 11:29
```
MariaDB [(none)]> SELECT table_name, engine FROM information_schema.tables WHERE table_name IN ('oc_mail_messages', 'oc_mail_recipients');
+--------------------+--------+
| table_name         | engine |
+--------------------+--------+
| oc_mail_messages   | InnoDB |
| oc_mail_recipients | InnoDB |
+--------------------+--------+
2 rows in set (0.008 sec)
```

**Comment by graue70** [comment] 2021-03-05 01:34
> This is a shot in the dark but could everyone who's affected please tell us what db they use and in what precise version?

Server-Version: 5.7.33 - MySQL Community Server (GPL)

> Another thing to check please if you use mysql: `SELECT table_name, engine FROM information_schema.tables WHERE table_name IN ('oc_mail_messages', 'oc_mail_recipients');` <- we wanna know your storage engines :)

table_name | engine
-- | --
oc_mail_messages | InnoDB
oc_mail_recipients | InnoDB

**Comment by miaulalala** [comment] 2021-03-05 07:26
> In addition to my comment ([#4412 (comment)](https://github.com/nextcloud/mail/issues/4412#issuecomment-789938142)):
> I just received a new mail with a correct header but with a content from a yesterday's mail.

Would you mind opening another ticket and sharing some details @klassikmann ? I'm not sure this is related to this issue.

**Comment by klassikmann** [comment] 2021-03-05 08:26
@miaulalala 
I'm not yet fully convinced that my observation relates to a different problem.
Let me explain: The issue under discussion describes the situation that new mails with correct content contains sender and/or recipients of former (old) mails. My new observation describes the opposite: a new mail with a correct header but with a content of a former (old) mail. This could originate from the same cause, possibly. I don't know.

What's also of interest, maybe: Besides nextcloud/mail which is an IMAP-client, I use on my desktop Thunderbird accessing the same mailbox as a POP3-client in a fetch&delete configuration. This implies that most of the incoming mails will be deleted outside the scope of nextcloud/mail.

**Comment by miaulalala** [comment] 2021-03-15 13:09
@klassikmann your configuration could definitely have the same issues as the recipient query. If you're using MariaDB in above mentioned version, the same auto increment bug will represent itself in other varieties, surely.

**Comment by pierreozoux** [comment] 2022-02-07 16:51
Could this be related to https://github.com/nextcloud/mail/issues/6014 ?

**Comment by miaulalala** [comment] 2022-02-08 10:28
> Could this be related to #6014 ?

No. That looks like an UI / Frontend issue.

**Comment by ChristophWurst** [comment] 2022-10-12 09:21
Label dropped because it was a duplicate of the attribute at https://github.com/orgs/nextcloud/projects/61. The priority does **not** change.

**Comment by miaulalala** [comment] 2022-10-13 10:42
[Since we're not supporting the affected MariaDB / MySQL versions any more](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server), I'm closing this. Please feel free to open another ticket should you stumble upon this error again or comment here.

**Closed by miaulalala** 2022-10-13 10:42 UTC
Labels: bug, 1. to develop
