### ISSUE TITLE
Outbox message is sent while it's edited

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#6156] opened 2022-03-24 15:36 UTC
### Steps to reproduce

1. Compose a new message but introduce an error, e.g. an invalid email for the recipient
2. Send the message
3. Find the message in the outbox
4. Edit the message to fix the recipient
5. Wait for the draft to save
6. Change the message another time

### Expected behavior

The message isn't sent until I'm done with my modifications.

### Actual behavior

The message might be found by the background job and sent while I'm editing it.

### Mail app version

v1.12

### Additional info

This was originally discovered in https://github.com/nextcloud/mail/pull/5970#issuecomment-1075326555 and is a theoretical problem until we have https://github.com/nextcloud/mail/issues/5886.

I've discussed the problem with @st3iny and there are two possible solutions:

1) The frontend updates the message timestamp before any editing happens. The background job will therefore not attempt to send the message. Once editing is done (close modal) the current timestamp is assigned and either frontend or backend will send the message.
2) When the frontend migrates the outbox message to a draft. The modal operates on that draft and when the editing ends, the message is migrated back. This requires https://github.com/nextcloud/mail/issues/4768.

It looks like 1) is simpler to do right now so I'd go with that. Once we have https://github.com/nextcloud/mail/issues/4768 we revisit and see if 2) makes the experience any smoother.

**Comment by JuliaKirschenheuter** [comment] 2022-04-14 09:04
@ChristophWurst @st3iny I have tested this behavior and cannot reproduce it (set scheduled message in in minute -> editing message -> time is over -> message will not be sent anymore). Probably this problem has been fixed within fixing other bugs regarding #5884.

But there is an other problem: if i change the message in Outbox -> draft will not be saved. I guess this will be fixed in a second solution.

> When the frontend migrates the outbox message to a draft. The modal operates on that draft and when the editing ends, the message is migrated back. This requires https://github.com/nextcloud/mail/issues/4768.

**Comment by miaulalala** [comment] 2022-04-19 15:03
I vote for solution number 2 (https://github.com/nextcloud/mail/issues/4768) as discussed in our review call.

**Comment by ChristophWurst** [comment] 2022-05-02 08:46
> @ChristophWurst @st3iny I have tested this behavior and cannot reproduce it (set scheduled message in in minute -> editing message -> time is over -> message will not be sent anymore). Probably this problem has been fixed within fixing other bugs regarding #5884.

The front-end doesn't send the message anymore but the backend might still pick it up.

Doing this via drafts isn't feasible in the short term. Therefore we will do the following

* When the composer modal opens, *stop* the message if it has a sendAt value set
* Keep the message updated via the outbox/draft handling but make sure sendAt remains undefined
* Once the user clicks *Send* or closes the modal, we put sendAt back to its original value
  * Edge cases: by the time the user finalizes the message, the sendAt timestamp might be in the past. Let's make sure the time is always current timestamp + undo time or higher. If the sendAt is still in the future then the value stays unchanged.

**Closed** 2022-05-09 10:27 UTC
Labels: bug, 2. developing, feature: outbox
