### ISSUE TITLE
new mail not shown in inbox, notification reappearing ever minute

### ISSUE THREAD

**Issue by guzzisti** [nextcloud/mail#3266] opened 2020-06-17 09:14 UTC
### Expected behavior
New mails appear in the "Shared Inbox".

### Actual behavior
- receive a new mail
- a notification is shown that a new mail arrived
- the mail does not show up neither in the "shared inbox" nor in the specific inbox of this account
- the notification of the "new mail" is shown again and again

### Mail app
**Mail app version:** 1.4.0
**Mailserver or service:** IMAP on all-inkl.com

### Server configuration
**Operating system**: Debian Buster
**Web server:** Apache 2
**Database:** SQLite

**PHP version:** 7.4
**Nextcloud Version:** 18.0.6

#### Client configuration
**Browser:** Firefox 77
**Operating system:** Manjaro Linux

**Comment by dhrunia** [comment] 2020-06-17 14:06
I am also facing the same issue since the latest update. I get notifications for new mail but the mail doesn't show up in the inbox until refreshing the page.

**Comment by guzzisti** [comment] 2020-06-17 14:10
Thank you for adding this information. A page refresh didn't solve the issue for me. I ended up moving the  mail to another folder with another tool.

**Comment by ChristophWurst** [comment] 2020-06-17 16:32
Ugh. I had this *once* during a bunch of weeks of testing. It's now also happening on my production system. The sync returns a new message, but it's not stored locally. Thus every follow-up sync will pull in the same - supposedly new - message.

I'll have a look.

**Comment by ChristophWurst** [comment] 2020-06-18 09:55
For me this resolved once another message came in. Could the other confirm?

**Comment by dhrunia** [comment] 2020-06-18 10:07
Yes, that seems to be the case with me as well. Like I saw a notification for your comment but no mail showed up in inbox so I sent myself another email from a different account and it showed up. However, the first mail didn't show up untill refresh.

**Comment by dhrunia** [comment] 2020-06-20 12:57
Not sure if this helps. This issue is only happening in the "Pirority inbox" view. If I change to "All inboxes" view all new email are immediately showing up in the inbox.

**Comment by ChristophWurst** [comment] 2020-11-30 07:43
I could finally reproduce this a month ago, fixed by https://github.com/nextcloud/mail/pull/4015 :rocket:

**Closed by ChristophWurst** 2020-11-30 07:43 UTC
Labels: 1. to develop, bug, priority:high, regression
