### ISSUE TITLE
Emails to groups are not sent

### ISSUE THREAD

**Issue by LostinSpacetime** [nextcloud/mail#6452] opened 2022-05-14 09:16 UTC
### Steps to reproduce

1. Create a new email.
2. Add a group from your contacts app as recipient. (To, Cc or Bcc)
3. Send the email
4. Email is stuck in outbox and there is tis error in the Log: OCA\Mail\Exception\ServiceException: Could not send message: RCPT first

### Expected behavior

Emai should be sent.

### Actual behavior

Email is stuck in the Outbox.

### Mail app version

1.12.0

### Mailserver or service

IMAP

### Operating system

Ubuntu 18.04

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

This problem appeared after the update to 1.12.0.

**Comment by LostinSpacetime** [comment] 2022-05-14 09:18
If one adds a simple email address to "To" and a category to "Bcc", the email seems to be sent, but it's only sent to the recipient from "To", not to the category.

**Comment by LostinSpacetime** [comment] 2022-05-14 09:39
This bug might be a duplicate of #6382

**Comment by LostinSpacetime** [comment] 2022-05-14 09:40
OCA\Mail\Exception\ServiceException: Could not send message: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

Verursacht durch Horde_Mime_Exception: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

Verursacht durch Horde_Mail_Exception: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

Verursacht durch Horde_Smtp_Exception: RCPT first

/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp/Horde/Smtp.php - line 712:
Horde_Smtp->_getResponse()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mail/Horde/Mail/Transport/Smtphorde.php - line 143:
Horde_Smtp->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Part.php - line 1620:
Horde_Mail_Transport_Smtphorde->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/vendor/pear-pear.horde.org/Horde_Mime/Horde/Mime/Mail.php - line 479:
Horde_Mime_Part->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 208:
Horde_Mime_Mail->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/MailTransmission.php - line 271:
OCA\Mail\Service\MailTransmission->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Service/OutboxService.php - line 129:
OCA\Mail\Service\MailTransmission->sendLocalMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/apps/mail/lib/Controller/OutboxController.php - line 191:
OCA\Mail\Service\OutboxService->sendMessage()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Mail\Controller\OutboxController->send()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/AppFramework/App.php - line 157:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/vhosts/schloss-schule.wien/cloud.schloss-schule.wien/index.php - line 36:
OC::handleRequest()

**Comment by wriver4** [comment] 2022-05-14 15:40
Mail app version
1.12.0
Mailserver or service
IMAP
Operating system
Ubuntu 20.04
PHP engine version
PHP 7.4
Web server
Apache (supported)
Database
MariaDB
Additional info
This problem appeared after the update to 1.12.0.
I have the same issue also.

**Comment by escribana** [comment] 2022-05-15 06:38
#6382

**Comment by ChristophWurst** [comment] 2022-05-16 06:11
Closing as duplicate of https://github.com/nextcloud/mail/issues/6382

**Closed by ChristophWurst** 2022-05-16 06:11 UTC
Labels: bug, 0. to triage
