### ISSUE TITLE
Make message list resizable

### ISSUE THREAD

**Issue by CATER-COM** [nextcloud/mail#2936] opened 2020-04-17 17:19 UTC
The Message list panel si quite tight. Could be nice to make it  sizable

Thanks,

**Comment by jancborchardt** [comment] 2020-04-20 16:09
Duplicate of https://github.com/nextcloud/mail/issues/2827#issuecomment-614361193 → let’s continue there. :)

**Closed by jancborchardt** 2020-04-20 16:09 UTC
Labels: 0. to triage, enhancement
