### ISSUE TITLE
mail.css missing in release tarball

### ISSUE THREAD

**Issue by eonpatapon** [nextcloud/mail#747] opened 2018-01-31 19:06 UTC
Looking at the latest release it seems to me that the mail.css is missing (or not compiled properly since main.scss is present)

**Comment by ChristophWurst** [comment] 2018-01-31 19:34
Not a bug, this will be compile by the Nextcloud server AFAIK.

Closing as not-reproducible as the issue template was ignored.

**Closed by ChristophWurst** 2018-01-31 19:34 UTC
