### ISSUE TITLE
Can not create account  Request failed with status code 500

### ISSUE THREAD

**Issue by kalle-ankan** [nextcloud/mail#2412] opened 2019-12-23 08:55 UTC
Hello

When I try to create an account so do I get this error: Request failed with status code 500 

I use the latest nextcloud and mail. It has been like this for an long time though a year or so..

I noticed in the horde_imap.log:

C: 12 STATUS procmail.log (MESSAGES UIDNEXT UIDVALIDITY)
S: 12 NO [CANNOT] Mailbox isn't a valid mbox file (0.001 + 0.000 secs).
>> Command 12 took 0.048 seconds.
>> ERROR: mail server explicitly reporting an error.
C: 13 LOGOUT
S: * BYE Logging out
S: 13 OK Logout completed (0.001 + 0.000 secs).

The server that I try to connect to uses Dovecot: dovecot-imapd  1:2.3.4.1-5+deb10u1

The same mail server works well with thunderbird and roundcube webmail.

Any idea how to debug it more or something to try?

**Comment by ChristophWurst** [comment] 2020-01-07 12:21
It tries to open procmail.log. What is this mailbox?

**Comment by kalle-ankan** [comment] 2020-01-13 08:26
On 1/7/20 2:21 PM, Christoph Wurst wrote:
>
> It tries to open procmail.log. What is this mailbox?
>

Hi

Procmail was installed and configured to do  server side filtering on 
incoming email.

When i removed procmail from the server and disabled server side 
filtering on incoming email, then it started to work.

I do not know why nexcloud mail reads procmail.log since it was not an 
subscribed mailbox.

**Comment by ChristophWurst** [comment] 2020-01-21 14:14
> I do not know why nexcloud mail reads procmail.log since it was not an subscribed mailbox.

Hm. We currently list all mailboxes. We don't take the subscripted state into consideration. But IMO the IMAP server should set the `\noselect` attribute on that mailbox if clients are not allowed to access it.

**Comment by stweil** [comment] 2020-04-22 12:48
@kalle-ankan, maybe you can try the following patch which worked for our instance:

    diff --git a/lib/IMAP/FolderMapper.php b/lib/IMAP/FolderMapper.php
    index 4f677f85..6f5b7656 100644
    --- a/lib/IMAP/FolderMapper.php
    +++ b/lib/IMAP/FolderMapper.php
    @@ -68,6 +68,11 @@ class FolderMapper {
                                    return null;
                            }
     
    +                       if (strpos($mailbox['mailbox']->utf8, 'shared.') === 0) {
    +                               // Workaround for shared Horde folders.
    +                               return null;
    +                       }
    +
                            return new Folder(
                                    $account->getId(),
                                    $mailbox['mailbox'],

**Comment by jmechnich** [comment] 2020-04-22 14:52
To elaborate a bit on @stweil 's comment above:
For us, Nextcloud Mail suddenly stopped working and after some debugging we found a few shared folders were the issue. I am not sure which mechanism created them (might not necessarily be Horde) but on a raw IMAP connection I see the following:
```
. list "" "*"
* LIST (\Noinferiors \HasNoChildren) "." INBOX
* LIST (\HasNoChildren) "." Archives
* LIST (\HasNoChildren) "." Drafts
* LIST (\HasNoChildren) "." Queue
...
* LIST (\HasNoChildren) "." shared.Archives01
* LIST (\HasNoChildren) "." shared.Archives_restored
```

Querying the status of the shared mailboxes creates an error:
```
. STATUS "shared.Archives01" (messages)
. NO System I/O error
```

Because of this, Nextcloud Mail will refuse to set up an account, or if the account already existed it will stop working (exclamation mark symbol next to account in Nextcloud). Horde for example will list those folder fine and only after navigating there, it will show a popup notifying about the access failure.

I am not sure how to fix this properly. Just listing subscribed mailboxes would fix the issues for us as well, but maybe it would be better to catch the error when appropriate...so at least the working folders are displayed and can be navigated.

Unfortunately we don't have direct access to the mail server, so we can't fix the "actual" issue here.

**Comment by ChristophWurst** [comment] 2020-04-27 06:29
Could someone please provide the full stack trace from nextcloud.log? I'd like to fix this, but I can't reproduce the problem here due to the lack of a test account.

**Comment by ChristophWurst** [comment] 2020-04-27 06:31
> I can't reproduce the problem here due to the lack of a test account.

If anyone could provide one please send me the credentials via mail.

**Comment by kalle-ankan** [comment] 2020-04-27 06:56
On 4/27/20 9:29 AM, Christoph Wurst wrote:
Hi

I can't reproduce it anymore.

What was causing it before was the use of procmail.
I added procmail back but it works now for some reason..

**Comment by ChristophWurst** [comment] 2020-04-27 06:57
> I added procmail back but it works now for some reason..

Wait 2h :alarm_clock: :bomb: :boom:

**Comment by stweil** [comment] 2020-06-07 16:55
Problem still exists in 9.0. Call stack:

    Error	mail	OCA\Mail\Exception\ServiceException: IMAP errorIMAP error reported by server.

        /var/www/cloud/apps/mail/lib/BackgroundJob/SyncJob.php - line 91:
        OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {}, true)

        /var/www/cloud/lib/public/BackgroundJob/Job.php - line 80:
        OCA\Mail\BackgroundJob\SyncJob->run({ accountId: 25})

        /var/www/cloud/lib/public/BackgroundJob/TimedJob.php - line 61:
        OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

        /var/www/cloud/cron.php - line 126:
        OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    Verursacht durchHorde_Imap_Client_Exception_ServerResponse: IMAP error reported by server.

        /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4314:
        Horde_Imap_Client_Socket->_getLine(Horde_Imap_C ... }})

        /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 4242:
        Horde_Imap_Client_Socket->_sendCmdChunk(Horde_Imap_C ... }}, [ Horde_Imap ... }])

        /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php - line 1751:
        Horde_Imap_Client_Socket->_sendCmd(Horde_Imap_C ... }})

        /var/www/cloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php - line 1733:
        Horde_Imap_Client_Socket->_status([ Horde_Imap ... }], 63)

        /var/www/cloud/apps/mail/lib/IMAP/FolderMapper.php - line 115:
        Horde_Imap_Client_Base->status({ INBOX: "IN ... "})

        /var/www/cloud/apps/mail/lib/IMAP/MailboxSync.php - line 86:
        OCA\Mail\IMAP\FolderMapper->getFoldersStatus({ INBOX: OCA ... }}, Horde_Imap_C ... e})

        /var/www/cloud/apps/mail/lib/BackgroundJob/SyncJob.php - line 91:
        OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {}, true)

        /var/www/cloud/lib/public/BackgroundJob/Job.php - line 80:
        OCA\Mail\BackgroundJob\SyncJob->run({ accountId: 25})

        /var/www/cloud/lib/public/BackgroundJob/TimedJob.php - line 61:
        OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

        /var/www/cloud/cron.php - line 126:
        OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

**Comment by stweil** [comment] 2020-06-07 17:42
@ChristophWurst, how can we keep this issue open? I can help with testing. Here is another hack which allows mail access for me:

    diff --git a/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php b/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php
    index 12d6dfa..32b5c67 100644
    --- a/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php
    +++ b/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php
    @@ -4599,6 +4599,8 @@ class Horde_Imap_Client_Socket extends Horde_Imap_Client_Base
                         break;
                     }
     
    +                break;
    +
                     throw new Horde_Imap_Client_Exception_ServerResponse(
                         Horde_Imap_Client_Translation::r("IMAP error reported by server."),
                         0,

A better solution would be adding a comman handler to catch IMAP errors (see code comment some lines above the hack).

**Comment by ChristophWurst** [comment] 2020-06-08 06:45
https://github.com/nextcloud/mail/pull/3116 could potentially help with this. See the PR description on which mailboxes we now fetch.

**Comment by ChristophWurst** [comment] 2020-06-08 06:45
You can get a prerelease from https://github.com/nextcloud/mail/releases/tag/v1.4.0-rc2

**Comment by stweil** [comment] 2020-06-08 09:37
1.4.0-rc2 does not fix the issue.

**Comment by ChristophWurst** [comment] 2020-06-08 09:40
Too bad. But thanks for testing anyway.

**Comment by ChristophWurst** [comment] 2020-06-08 09:41
@stweil is your issue about `procmail.log` as well btw or is there another problematic file/mailbox that we should ignore?

**Comment by ChristophWurst** [comment] 2020-06-08 09:42
did you run `occ mail:account:sync <accountid>` btw? if not, the new code might not have updated the mailboxes list yet.

**Comment by stweil** [comment] 2020-06-08 10:08
Running that fails:

    sudo -u www-data php /var/www/cloud/occ mail:account:sync 28

    In MailboxSync.php line 88:
                                                
      IMAP errorIMAP error reported by server.  
                                                

    In Socket.php line 4602:
                                      
      IMAP error reported by server.  
                                      

    mail:account:sync [-f|--force] [--] <account-id>

**Comment by stweil** [comment] 2020-06-08 10:12
> @stweil is your issue about procmail.log as well btw or is there another problematic file/mailbox that we should ignore?

See @jmechnich's comment above. The IMAP server provides the list of folders for my user account, but some of these folders cannot be read because of missing rights. Those folders should be ignored (or listed as unaccessible), but currently they make the whole account unusable.

**Comment by stweil** [comment] 2020-06-08 10:16
After updating to mail 1.4.0-rc2 the bad mail account (id 28) is still in the database, but no longer visible in the web interface. The Nextcloud log still shows IMAP errors (`OCA\Mail\Exception\ServiceException: IMAP errorIMAP error reported by server.`)

**Comment by stweil** [comment] 2020-06-08 10:20
My [hack](https://github.com/nextcloud/mail/issues/2412#issuecomment-640253990) works with 1.4.0-rc2, too.

**Comment by ChristophWurst** [comment] 2020-06-08 10:22
I think I have a better hack :)

**Comment by stweil** [comment] 2020-06-08 10:40
I removed my hack and added your fix for MailboxSync.php. Now `occ mail:account:sync 28` works, and I can access my mail account. The Nextcloud log is also nearly silent now (only `Warning | mail | not enough messages to train a classifier`). So your hack looks good, thanks a lot.

**Comment by stweil** [comment] 2020-06-08 10:42
Creating a new account with the problematic IMAP server now works, too.

**Comment by jmechnich** [comment] 2021-01-17 09:14
@ChristophWurst Could you have a look at https://github.com/nextcloud/mail/pull/4318 ? Thanks!

**Comment by ChristophWurst** [comment] 2021-02-23 16:21
> @ChristophWurst Could you have a look at #4318 ? Thanks!

merged :)

**Closed by ChristophWurst** 2021-02-23 16:21 UTC
Labels: 0. to triage, bug
