### ISSUE TITLE
Issues with drafts [$65]

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#9] opened 2016-08-29 12:25 UTC
There are a bunch of things problematic with drafts, and we should fix them. Cause drafts are a pretty helpful feature to save your stuff and sync it.

Sorted by severity:
- [x] **For each email, a bunch of drafts are often saved and the previous one is not deleted**
- [x] When an email is sent, the drafts of that email are not deleted
- [x] The subject isn’t saved
- [x] Special characters like umlauts and `>` is escaped which is horrible for quoted text

For later:
- Drafts of replies are not shown automatically in the reply box when opening the mail again → moved to https://github.com/nextcloud/mail/issues/459
- Attachments are not saved → moved to https://github.com/nextcloud/mail/issues/458

**Comment by koreywithak** [comment] 2017-02-08 14:52
I use the Mail app with my Gmail account. I notice a few additional issues:
1. When clicking on the [Gmail] subfolder and then Drafts, it will not load the draft e-mails. It does, however, load other subfolders, like Sent.
2. When working on a new message or reply, it does save the draft into Drafts (although I can't view it in with the Nextcloud Mail app, due to above issue). However, it ends up saving multiple copies over the course of e-mail composition.

**Comment by keunes** [comment] 2017-04-18 07:17
I created an IMAP account with my hoster, and in their webmail (Roundcube) if I save a draft without a recipient, then Nextcloud Mail will say: "Something's wrong with loading your drafts :/" (manual translation). After adding a recipient in my hoster's Roundcube, Nextcloud Mail _does_ load my drafts properly.

**Comment by jrullo** [comment] 2017-04-28 02:09
Is this solved? I have close to 200 draft emails in my mail app on nextcloud instance. I've replied to less than 10 mails that I can recall while using the mail app. I have no idea why so many drafts would be saved. I usually just read the mail and delete the ones I don't need.

**Comment by jancborchardt** [comment] 2017-04-28 09:40
@ChristophWurst @irgendwie @Gomez can anyone of you look into this? :) It’s one of the most annoying bugs I encounter daily. And it actually punishes the people who use the mail app a lot. :\

**Comment by lcalaresu** [comment] 2017-06-04 13:35
Actually, no drafts are even saved on my environment using the master branch (it's working with the last stable version). The console gives me the message:

> Uncaught (in promise) TypeError: Cannot read property 'draftUID' of undefined

It seems "`this`" has been used inside an anonymous function in `js/views/composerview.js` (lines 397 & 400) ; maybe use `_this` instead?

Does anyone reproduce this? It seems that these changes in the composerview are a bit old... Or maybe nobody uses the drafts 😄 
At least, it solves the problem:

> For each email, a bunch of drafts are often saved and the previous one is not deleted 

😝

**Comment by jancborchardt** [comment] 2017-06-13 15:06
@lcalaresu if you can look into this it would be much appreciated. ;) I think @ChristopWurst said he doesn't use drafts so much.

**Comment by ChristophWurst** [comment] 2017-06-13 15:24
> @lcalaresu if you can look into this it would be much appreciated. ;) I think @christopwurst said he doesn't use drafts so much.

No, I don't write any mails at all, you know 😛

**Comment by lcalaresu** [comment] 2017-06-13 20:31
@jancborchardt 
Hehe I'm using draft a lot so, that one has interested me for a while (I could be selfish I guess ^^)
However, it looks super tricky! seems like big changes 😨 
If people here are not afraid to answer all the questions I think I'm going to ask, no problem for me though

**Comment by jancborchardt** [comment] 2017-06-14 09:08
Sure, happy to help design & interaction-wise as far as I can, and I guess @ChristophWurst / @Gomez / @nextcloud/mail can answer technical questions. :)

**Comment by jancborchardt** [comment] 2017-07-06 21:22
Just added another 50$ to the bounty! :) Any takers?

**Comment by ChristophWurst** [comment] 2017-08-02 09:41
@jancborchardt could you please try the latest master (which includes #420) and check which is items have been fixed already? Thanks.

**Comment by jancborchardt** [comment] 2017-08-02 13:24
Will do as soon as I have the Nextcloud dev environment set up on my new laptop! :)

**Comment by ChristophWurst** [comment] 2017-08-23 16:03
> Attachments are not saved
> Drafts of replies are not shown automatically in the reply box when opening the mail again

Those two are wontfixes for 0.7. I've ticket the ones that I'm unable to reproduce, probably because #420 fixed them.

**Comment by jancborchardt** [comment] 2017-08-24 15:09
@ChristophWurst yup, totally fine. The only important one left is the 

> Special characters like umlauts and > is escaped which is horrible for quoted text

cause that breaks drafts quite hard.

**Comment by jancborchardt** [comment] 2017-08-24 15:13
Moved the two other issues which are for after 0.7 to:
- Drafts: Automatically show draft of reply in the reply box when opening the mail again #459 (would be quite nice)
- Drafts: save attachments too #458 (not too important)

**Comment by ChristophWurst** [comment] 2017-08-24 15:24
> @ChristophWurst yup, totally fine. The only important one left is the
> 
>     Special characters like umlauts and > is escaped which is horrible for quoted text
> 
> cause that breaks drafts quite hard.

As discussed, I've spent quite some time on debugging this and I've not yet found a way to fix the encoding.

**Closed** 2017-08-29 09:33 UTC
Labels: 1. to develop, bounty, bug, feature:drafts, papercut, priority
