### ISSUE TITLE
Stuck at "Loading Messages" when emoticons present in email subject

### ISSUE THREAD

**Issue by bordertec** [nextcloud/mail#5728] opened 2021-11-13 13:43 UTC
### Expected behavior
Load mails

### Actual behavior
The spinning "Loading messages" dialog does not go away.
[](https://user-images.githubusercontent.com/5219726/99512492-cf4b2980-2989-11eb-91f8-f1fe25c3889d.gif)

### Mail app

**Mail app version:** 1.10.5, but also 1.7
**Mailserver or service:** easyhost.be

### Server configuration
Nextcloud is running inside a (turnkey) lxc container in a proxmox host.

**Operating system**: Debian 10.11

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 22.2.1 (also present in 21)

#### Client configuration
**Browser:** mostly Chrome 94.0, also Firefox

**Operating system:** ChromeOS, debian, windows, arch linux

Emoticons in email subject don't work. Found out by deleting emails until Inbox started loading messages and then putting mails back until it broke again.

When I manually try to sync the mailbox I get the following output:

```
[debug] Skipping mailbox sync for 54
[debug] Syncing 53
[debug] Locking mailbox 53 for new messages sync
[debug] Locking mailbox 53 for changed messages sync
[debug] Locking mailbox 53 for vanished messages sync
[debug] Running initial sync for 53
[debug] Initial sync 13:INBOX - fetch all messages from IMAP took 1s
[debug] Unlocking mailbox 53 from vanished messages sync
[debug] Unlocking mailbox 53 from changed messages sync
[debug] Unlocking mailbox 53 from new messages sync

In ImapToDbSynchronizer.php line 249:
                                                                                                    
  Sync failed for 13:INBOX: An exception occurred while executing a query: SQLSTATE[22007]: Invali  
  d datetime format: 1366 Incorrect string value: '\xF0\x9F\x9A\x80 Y...' for column `nextcloud`.`  
  oc_mail_messages`.`subject` at row 1                                                              
                                                                                                    

In ExceptionConverter.php line 114:
                                                                                                    
  An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 In  
  correct string value: '\xF0\x9F\x9A\x80 Y...' for column `nextcloud`.`oc_mail_messages`.`subject  
  ` at row 1                                                                                        
                                                                                                    

In Exception.php line 26:
                                                                                                    
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x9A\x80 Y...' f  
  or column `nextcloud`.`oc_mail_messages`.`subject` at row 1                                       
                                                                                                    

In Statement.php line 82:
                                                                                                    
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x9A\x80 Y...' f  
  or column `nextcloud`.`oc_mail_messages`.`subject` at row 1                                       `
```
Nothing valuable in the nextcloud.log that I see.
Logged in as an administrator user -> administration -> logging shows following error

```
Error	mail	OCA\Mail\Exception\ServiceException: Sync failed for 13:INBOX: An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x9A\x80 Y...' for column `nextcloud`.`oc_mail_messages`.`subject` at row 1
/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php - line 127:

OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 53}, OC\AppFramew ... {}, 42, [], true)

/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php - line 161:

OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox { id: 53}, 42, [], false, null)

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:

OCA\Mail\Controller\MailboxesController->sync(53, [], true, null)
```
I can provide the full log when necessary, but I can't get it to format nicely and it is long.

To me it looks like the emoticon doesn't fit in the database, it is bigger than the standard character size in a subject?
If I need to provide more info/logs, please let me know. For now I workaround this by moving the faulty emails to Trash. It works, a fix would be more handy!
I can also send you some of the emails which cause the erratic behaviour.

**Comment by miaulalala** [comment] 2021-11-15 07:17
Hi, what collation are you using in your DB? Inserting Emojis is only possible in utf8mb4. This could be a quick fix for you to try. Are you able to change your collation?

**Comment by ChristophWurst** [comment] 2021-11-15 07:53
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html documents the process

**Comment by bordertec** [comment] 2021-11-21 16:07
I will look into it this week. Don't have much time these days, sorry. Bad moment to have posted a bug report, my bad.
I did come accross the utf8(mb4) issue when I did my research and looked like it was fine. 

Any way to check if my database is configured correctly before trying to make the changes? Already messed up my database once recently. 

It is a recent install (less then a month old).

**Comment by miaulalala** [comment] 2021-11-22 07:21
Could you please check the tabes themselves? Sometimes table and database collations aren't the same. Your information schema will tell you which table has which collation.

**Comment by bordertec** [comment] 2021-11-22 22:37
A screenshot of what I suppose should be the right table (nextcloud -> oc_mail_messages)
The subject line has type varchar, length 255 and options utf8mb4_bin 

![Screenshot 2021-11-22 23 33 03](https://user-images.githubusercontent.com/94228001/142945143-4c0b79ab-65e4-41cc-bab2-2b0db59dc5dd.png)

**Comment by miaulalala** [comment] 2021-11-23 07:49
Can you please check your nextcloud config.php and see if your have a value `"mysql.utf8mb4" => true`?

**Comment by bordertec** [comment] 2021-11-23 19:46
That line is present indeed.

**Comment by miaulalala** [comment] 2021-11-24 09:30
Ok then I'm honestly stumped. DB is fine, so is your config. Could be the query builder escaping the string weirdly... I'll have to check it out.

**Comment by bordertec** [comment] 2021-11-24 20:00
Ok, let me know when I can provide any other info or logs. Thanks

**Comment by miaulalala** [comment] 2021-12-06 10:49
Duplicate of #4299

**Closed** 2021-12-06 11:11 UTC
Labels: bug, 1. to develop
