### ISSUE TITLE
When I go to mail app I get internal server error

### ISSUE THREAD

**Issue by panoskpv** [nextcloud/mail#8793] opened 2023-08-22 15:55 UTC
### Steps to reproduce

I have Nextcloud in docker and after updgrade to latest version, and as i erroneously was in beta channel, I got some migration error and upgrade was not possible. I disabled mail app from commnad line and proceed with the update. Now, i went back to stable channel, when I try to access mail app I get internal server error and the following error in logs "BadFunctionCallException: junkMailboxId is not a valid attribute"

### Expected behavior

Access mail app

### Actual behavior

Internal server error

### Mail app version

3.3.0

### Mailserver or service

protonmail bridge

### Operating system

docker in ubuntu server

### PHP engine version

None

### Web server

None

### Database

MySQL

**Comment by dugite-code** [comment] 2023-08-23 03:22
This may be stupid but I just saw a similar error, checked the issue tracker and saw [this user solved it by restarting](https://github.com/nextcloud/mail/issues/8790). I restarted my docker container and boom it worked. That was a bit weird, probably some cache issue somewhere.

**Comment by kesselb** [comment] 2023-08-24 17:46
> I have Nextcloud in docker and after updgrade to latest version, and as i erroneously was in beta channel, I got some migration error and upgrade was not possible. I disabled mail app from commnad line and proceed with the update. Now, i went back to stable channel, when I try to access mail app I get internal server error and the following error in logs "BadFunctionCallException: junkMailboxId is not a valid attribute"

A possible explanation is, that some migrations were executed successfully, but a faulty migration interrupted the upgrade. Likely https://github.com/nextcloud/mail/pull/8781 or https://github.com/nextcloud/mail/pull/8800. 

Idea 1: Reset the database tables and install the latest stable release https://github.com/nextcloud/mail/blob/main/doc/developer.md#resetting-the-app. You will lose your configurations!

Idea 2: Revert the migrations manually. You find junk_mailbox_id in the table oc_mail_accounts. Drop junk_mailbox_id and move_junk from the table. Change to oc_migrations and delete the row for appid = mail and version = 3001Date20230307113544. Please make a backup before, just in case! If you see an error for quota_percentage drop oc_mail_accounts.quota_percentage and migration for appid = mail and version = 3300Date20230706140531.

**Comment by Dual-0** [comment] 2023-09-14 20:46
just restart php-fpm

**Comment by c-store-cp** [comment] 2023-09-18 08:03
> just restart php-fpm

Confirmed. Had this issue on a few native installations, restarting php-fpm resolved the issue.

**Comment by joshtrichards** [comment] 2024-01-23 15:54
> I have Nextcloud in docker and after upgrade to latest version, and as i erroneously was in beta channel, 

For future reference, which image are you using?

**Comment by kesselb** [comment] 2024-06-20 13:55
Thanks for your report again :+1: 

I assume the problem is resolved now and will therefore close the issue. 

Please log a new issue by using the issue template if that problem still occurs and include a reference to this report.

**Closed by kesselb** 2024-06-20 13:55 UTC
Labels: bug, needs info, 0. to triage
