### ISSUE TITLE
Unable to move emails

### ISSUE THREAD

**Issue by hkgnp** [nextcloud/mail#2430] opened 2020-01-04 13:36 UTC
I am on the latest version of Nextcloud.

I set up an account using IMAP, and am able to send and receive emails correctly. I am not however able to move emails. When I click on the menu on each email (the 3 dots), there are only 3 options:
1) Mark unread
2) Forward
3) Delete

Tried dragging and dropping by it does not work as well. Is there another settings I should activate?

**Comment by StCyr** [comment] 2020-01-06 08:00
I've work on this a bit. If someone wants to help, it's here: https://github.com/nextcloud/mail/pull/1753

**Comment by ChristophWurst** [comment] 2020-01-07 12:51
Duplicate of #1538

**Closed by ChristophWurst** 2020-01-07 12:51 UTC
