### ISSUE TITLE
e-mail sorting

### ISSUE THREAD

**Issue by nmchm** [nextcloud/mail#9322] opened 2024-02-12 17:32 UTC
### Is your feature request related to a problem? Please describe.

There is not way to sort mails in Nextcloud. I do not know whether this is on purpose or the contributors have missed out this feature. Please let me know if someone is already working on it. I was not able to find anything when I searched online.

I feel it is an urgently required feature.

### Describe the solution you'd like

Please add the sorting feature next to the filter button on the top

**Comment by ChristophWurst** [comment] 2024-02-12 19:29
Duplicate of https://github.com/nextcloud/mail/issues/679

**Closed by ChristophWurst** 2024-02-12 19:29 UTC
Labels: enhancement, 0. to triage
