### ISSUE TITLE
visible Imatges into mail app

### ISSUE THREAD

**Issue by profeinteri** [nextcloud/mail#3284] opened 2020-06-21 07:03 UTC
### Feature Request

I'm woring with a corporative mail and need to insert some imatges in the body of the message and also , that's the most important part, in the signature, where I need to put de logo's Company.

#### Summary

Insert visibles imatge in the body and the signature of the message in mail's accounts

Thank you so much!
This is an incredibble work , we all apreciate your app !!!!

**Comment by ChristophWurst** [comment] 2020-06-24 09:23
Sounds like a duplicate of https://github.com/nextcloud/mail/issues/2733

**Comment by ChristophWurst** [comment] 2020-06-24 09:24
> Thank you so much!
> This is an incredibble work , we all apreciate your app !!!!

@nextcloud/mail :eyes: 

:heart: thanks!

**Closed by ChristophWurst** 2020-06-24 09:23 UTC
Labels: 0. to triage, enhancement
