### ISSUE TITLE
Not full mail visible on mobile

### ISSUE THREAD

**Issue by rullzer** [nextcloud/mail#1740] opened 2019-05-08 12:42 UTC
I noticed a bug when using the mail app on mobile. When viewing a message the content of the mail is to wide.

![localhost_apps_mail_](https://user-images.githubusercontent.com/45821/57375984-23732c00-719f-11e9-95c0-71ff94a0aa0d.png)

As you can see in the screenshot above.
I happens mostly in emails with log of recipients.

I found the cause of a few of the issues

1. The recipient list is not wrapping as it should
2. The composer part on the bottom
  a. The account selection is to wide and not wrapping as it should
  b. The recipeient (To, CC, BCC) are not wrapping as they should

If I remove the above mentioned elements the mail is fully readbale.

Of course making all element wrap properly is best here.
But at the least I should have a horizontal scroll bar if there is wider content ;)

**Comment by ChristophWurst** [comment] 2019-11-04 19:15
:eyes: @GretaD

**Comment by jancborchardt** [comment] 2020-02-26 10:49
This seems to be a duplicate of https://github.com/nextcloud/mail/issues/1641, closing hence.

**Closed by jancborchardt** 2020-02-26 10:49 UTC
Labels: 1. to develop, bug, design, good first issue
