### ISSUE TITLE
Cannot send email after typing/pasting an address into to/cc/etc 

### ISSUE THREAD

**Issue by mjog** [nextcloud/mail#3296] opened 2020-06-24 01:45 UTC
### Expected behavior

Typing or pasting an address into the to/cc/bcc fields then clicking on subject or body should automatically accept the entered email address so the Send button is enabled.

People should be able to e.g. paste an email address, then press Tab or click in a different field and the address should be automatically added.

### Actual behavior

Typing or pasting an address into the to/cc/bcc fields requires a second action - clicking on the `+ email@example.com` entry on the address autocompete - before the Send button is enabled.

The same person I was on phone support to couldn't send the mail because after entering the recipient's email address, they did not click the `+` dropdown - they clicked elsewhere to get the autocomplete to go away, and then did not understand why the Send button was disabled.
### Mail app

**Mail app version:** 1.4.0

**Mailserver or service:** Dovecot

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** Whatever comes with Debian 10

**Nextcloud Version:** 19.0.0

#### Client configuration
**Browser:** GNOME Web 3.36.2

**Operating system:** Ubuntu 20.04

**Comment by ChristophWurst** [comment] 2020-06-24 08:35
Duplicate of #2769, I guess

**Closed by ChristophWurst** 2020-06-24 08:35 UTC
Labels: 0. to triage, bug
