### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by GretaD** [nextcloud/mail#4812] opened 2021-03-23 15:45 UTC
```json
{
  "status": "error",
  "message": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 5 database is locked",
  "data": {
    "debug": true,
    "type": "OC\\DB\\Exceptions\\DbalException",
    "message": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 5 database is locked",
    "code": 5,
    "trace": [
      {
        "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 320,
        "function": "wrap",
        "class": "OC\\DB\\Exceptions\\DbalException"
      },
      {
        "file": "/home/user/nextcloud/lib/public/AppFramework/Db/QBMapper.php",
        "line": 211,
        "function": "executeUpdate",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
      },
      {
        "file": "/home/user/nextcloud/apps/mail/lib/Db/MailboxMapper.php",
        "line": 228,
        "function": "update",
        "class": "OCP\\AppFramework\\Db\\QBMapper"
      },
      {
        "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
        "line": 246,
        "function": "unlockFromVanishedSync",
        "class": "OCA\\Mail\\Db\\MailboxMapper"
      },
      {
        "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
        "line": 121,
        "function": "sync",
        "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
      },
      {
        "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
        "line": 161,
        "function": "syncMailbox",
        "class": "OCA\\Mail\\Service\\Sync\\SyncService"
      },
      {
        "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 218,
        "function": "sync",
        "class": "OCA\\Mail\\Controller\\MailboxesController"
      },
      {
        "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 127,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher"
      },
      {
        "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher"
      },
      {
        "file": "/home/user/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App"
      },
      {
        "file": "/home/user/nextcloud/lib/base.php",
        "line": 998,
        "function": "match",
        "class": "OC\\Route\\Router"
      },
      {
        "file": "/home/user/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC"
      }
    ],
    "previous": {
      "type": "Doctrine\\DBAL\\Exception\\LockWaitTimeoutException",
      "message": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 5 database is locked",
      "code": 5,
      "trace": [
        {
          "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1728,
          "function": "convert",
          "class": "Doctrine\\DBAL\\Driver\\API\\SQLite\\ExceptionConverter"
        },
        {
          "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1667,
          "function": "handleDriverException",
          "class": "Doctrine\\DBAL\\Connection"
        },
        {
          "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1146,
          "function": "convertExceptionDuringQuery",
          "class": "Doctrine\\DBAL\\Connection"
        },
        {
          "file": "/home/user/nextcloud/lib/private/DB/Connection.php",
          "line": 260,
          "function": "executeStatement",
          "class": "Doctrine\\DBAL\\Connection"
        },
        {
          "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
          "line": 213,
          "function": "executeStatement",
          "class": "OC\\DB\\Connection"
        },
        {
          "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 287,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Query\\QueryBuilder"
        },
        {
          "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 318,
          "function": "execute",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
        },
        {
          "file": "/home/user/nextcloud/lib/public/AppFramework/Db/QBMapper.php",
          "line": 211,
          "function": "executeUpdate",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
        },
        {
          "file": "/home/user/nextcloud/apps/mail/lib/Db/MailboxMapper.php",
          "line": 228,
          "function": "update",
          "class": "OCP\\AppFramework\\Db\\QBMapper"
        },
        {
          "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
          "line": 246,
          "function": "unlockFromVanishedSync",
          "class": "OCA\\Mail\\Db\\MailboxMapper"
        },
        {
          "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
          "line": 121,
          "function": "sync",
          "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
        },
        {
          "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
          "line": 161,
          "function": "syncMailbox",
          "class": "OCA\\Mail\\Service\\Sync\\SyncService"
        },
        {
          "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 218,
          "function": "sync",
          "class": "OCA\\Mail\\Controller\\MailboxesController"
        },
        {
          "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 127,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher"
        },
        {
          "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
          "line": 157,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher"
        },
        {
          "file": "/home/user/nextcloud/lib/private/Route/Router.php",
          "line": 302,
          "function": "main",
          "class": "OC\\AppFramework\\App"
        },
        {
          "file": "/home/user/nextcloud/lib/base.php",
          "line": 998,
          "function": "match",
          "class": "OC\\Route\\Router"
        },
        {
          "file": "/home/user/nextcloud/index.php",
          "line": 37,
          "function": "handleRequest",
          "class": "OC"
        }
      ],
      "previous": {
        "type": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
        "message": "SQLSTATE[HY000]: General error: 5 database is locked",
        "code": 5,
        "trace": [
          {
            "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
            "line": 84,
            "function": "new",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          },
          {
            "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1136,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement"
          },
          {
            "file": "/home/user/nextcloud/lib/private/DB/Connection.php",
            "line": 260,
            "function": "executeStatement",
            "class": "Doctrine\\DBAL\\Connection"
          },
          {
            "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
            "line": 213,
            "function": "executeStatement",
            "class": "OC\\DB\\Connection"
          },
          {
            "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 287,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Query\\QueryBuilder"
          },
          {
            "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 318,
            "function": "execute",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
          },
          {
            "file": "/home/user/nextcloud/lib/public/AppFramework/Db/QBMapper.php",
            "line": 211,
            "function": "executeUpdate",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
          },
          {
            "file": "/home/user/nextcloud/apps/mail/lib/Db/MailboxMapper.php",
            "line": 228,
            "function": "update",
            "class": "OCP\\AppFramework\\Db\\QBMapper"
          },
          {
            "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
            "line": 246,
            "function": "unlockFromVanishedSync",
            "class": "OCA\\Mail\\Db\\MailboxMapper"
          },
          {
            "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
            "line": 121,
            "function": "sync",
            "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
          },
          {
            "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
            "line": 161,
            "function": "syncMailbox",
            "class": "OCA\\Mail\\Service\\Sync\\SyncService"
          },
          {
            "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 218,
            "function": "sync",
            "class": "OCA\\Mail\\Controller\\MailboxesController"
          },
          {
            "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 127,
            "function": "executeController",
            "class": "OC\\AppFramework\\Http\\Dispatcher"
          },
          {
            "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
            "line": 157,
            "function": "dispatch",
            "class": "OC\\AppFramework\\Http\\Dispatcher"
          },
          {
            "file": "/home/user/nextcloud/lib/private/Route/Router.php",
            "line": 302,
            "function": "main",
            "class": "OC\\AppFramework\\App"
          },
          {
            "file": "/home/user/nextcloud/lib/base.php",
            "line": 998,
            "function": "match",
            "class": "OC\\Route\\Router"
          },
          {
            "file": "/home/user/nextcloud/index.php",
            "line": 37,
            "function": "handleRequest",
            "class": "OC"
          }
        ],
        "previous": {
          "type": "PDOException",
          "message": "SQLSTATE[HY000]: General error: 5 database is locked",
          "code": "HY000",
          "trace": [
            {
              "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
              "line": 82,
              "function": "execute",
              "class": "PDOStatement"
            },
            {
              "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
              "line": 1136,
              "function": "execute",
              "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement"
            },
            {
              "file": "/home/user/nextcloud/lib/private/DB/Connection.php",
              "line": 260,
              "function": "executeStatement",
              "class": "Doctrine\\DBAL\\Connection"
            },
            {
              "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
              "line": 213,
              "function": "executeStatement",
              "class": "OC\\DB\\Connection"
            },
            {
              "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
              "line": 287,
              "function": "execute",
              "class": "Doctrine\\DBAL\\Query\\QueryBuilder"
            },
            {
              "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
              "line": 318,
              "function": "execute",
              "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
            },
            {
              "file": "/home/user/nextcloud/lib/public/AppFramework/Db/QBMapper.php",
              "line": 211,
              "function": "executeUpdate",
              "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
            },
            {
              "file": "/home/user/nextcloud/apps/mail/lib/Db/MailboxMapper.php",
              "line": 228,
              "function": "update",
              "class": "OCP\\AppFramework\\Db\\QBMapper"
            },
            {
              "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
              "line": 246,
              "function": "unlockFromVanishedSync",
              "class": "OCA\\Mail\\Db\\MailboxMapper"
            },
            {
              "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
              "line": 121,
              "function": "sync",
              "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
            },
            {
              "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
              "line": 161,
              "function": "syncMailbox",
              "class": "OCA\\Mail\\Service\\Sync\\SyncService"
            },
            {
              "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
              "line": 218,
              "function": "sync",
              "class": "OCA\\Mail\\Controller\\MailboxesController"
            },
            {
              "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
              "line": 127,
              "function": "executeController",
              "class": "OC\\AppFramework\\Http\\Dispatcher"
            },
            {
              "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
              "line": 157,
              "function": "dispatch",
              "class": "OC\\AppFramework\\Http\\Dispatcher"
            },
            {
              "file": "/home/user/nextcloud/lib/private/Route/Router.php",
              "line": 302,
              "function": "main",
              "class": "OC\\AppFramework\\App"
            },
            {
              "file": "/home/user/nextcloud/lib/base.php",
              "line": 998,
              "function": "match",
              "class": "OC\\Route\\Router"
            },
            {
              "file": "/home/user/nextcloud/index.php",
              "line": 37,
              "function": "handleRequest",
              "class": "OC"
            }
          ],
          "previous": {
            "type": "OCA\\Mail\\Exception\\ServiceException",
            "message": "Sync failed for 15:INBOX: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 5 database is locked",
            "code": 0,
            "trace": [
              {
                "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
                "line": 121,
                "function": "sync",
                "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
              },
              {
                "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
                "line": 161,
                "function": "syncMailbox",
                "class": "OCA\\Mail\\Service\\Sync\\SyncService"
              },
              {
                "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 218,
                "function": "sync",
                "class": "OCA\\Mail\\Controller\\MailboxesController"
              },
              {
                "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 127,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher"
              },
              {
                "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
                "line": 157,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher"
              },
              {
                "file": "/home/user/nextcloud/lib/private/Route/Router.php",
                "line": 302,
                "function": "main",
                "class": "OC\\AppFramework\\App"
              },
              {
                "file": "/home/user/nextcloud/lib/base.php",
                "line": 998,
                "function": "match",
                "class": "OC\\Route\\Router"
              },
              {
                "file": "/home/user/nextcloud/index.php",
                "line": 37,
                "function": "handleRequest",
                "class": "OC"
              }
            ],
            "previous": {
              "type": "Doctrine\\DBAL\\Exception\\LockWaitTimeoutException",
              "message": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 5 database is locked",
              "code": 5,
              "trace": [
                {
                  "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
                  "line": 1728,
                  "function": "convert",
                  "class": "Doctrine\\DBAL\\Driver\\API\\SQLite\\ExceptionConverter"
                },
                {
                  "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
                  "line": 1667,
                  "function": "handleDriverException",
                  "class": "Doctrine\\DBAL\\Connection"
                },
                {
                  "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
                  "line": 1146,
                  "function": "convertExceptionDuringQuery",
                  "class": "Doctrine\\DBAL\\Connection"
                },
                {
                  "file": "/home/user/nextcloud/lib/private/DB/Connection.php",
                  "line": 260,
                  "function": "executeStatement",
                  "class": "Doctrine\\DBAL\\Connection"
                },
                {
                  "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
                  "line": 213,
                  "function": "executeStatement",
                  "class": "OC\\DB\\Connection"
                },
                {
                  "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
                  "line": 287,
                  "function": "execute",
                  "class": "Doctrine\\DBAL\\Query\\QueryBuilder"
                },
                {
                  "file": "/home/user/nextcloud/apps/mail/lib/Db/MessageMapper.php",
                  "line": 388,
                  "function": "execute",
                  "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
                },
                {
                  "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
                  "line": 383,
                  "function": "updateBulk",
                  "class": "OCA\\Mail\\Db\\MessageMapper"
                },
                {
                  "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
                  "line": 223,
                  "function": "runPartialSync",
                  "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
                },
                {
                  "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
                  "line": 121,
                  "function": "sync",
                  "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
                },
                {
                  "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
                  "line": 161,
                  "function": "syncMailbox",
                  "class": "OCA\\Mail\\Service\\Sync\\SyncService"
                },
                {
                  "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                  "line": 218,
                  "function": "sync",
                  "class": "OCA\\Mail\\Controller\\MailboxesController"
                },
                {
                  "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                  "line": 127,
                  "function": "executeController",
                  "class": "OC\\AppFramework\\Http\\Dispatcher"
                },
                {
                  "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
                  "line": 157,
                  "function": "dispatch",
                  "class": "OC\\AppFramework\\Http\\Dispatcher"
                },
                {
                  "file": "/home/user/nextcloud/lib/private/Route/Router.php",
                  "line": 302,
                  "function": "main",
                  "class": "OC\\AppFramework\\App"
                },
                {
                  "file": "/home/user/nextcloud/lib/base.php",
                  "line": 998,
                  "function": "match",
                  "class": "OC\\Route\\Router"
                },
                {
                  "file": "/home/user/nextcloud/index.php",
                  "line": 37,
                  "function": "handleRequest",
                  "class": "OC"
                }
              ],
              "previous": {
                "type": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
                "message": "SQLSTATE[HY000]: General error: 5 database is locked",
                "code": 5,
                "trace": [
                  {
                    "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
                    "line": 84,
                    "function": "new",
                    "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception"
                  },
                  {
                    "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
                    "line": 1136,
                    "function": "execute",
                    "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement"
                  },
                  {
                    "file": "/home/user/nextcloud/lib/private/DB/Connection.php",
                    "line": 260,
                    "function": "executeStatement",
                    "class": "Doctrine\\DBAL\\Connection"
                  },
                  {
                    "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
                    "line": 213,
                    "function": "executeStatement",
                    "class": "OC\\DB\\Connection"
                  },
                  {
                    "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
                    "line": 287,
                    "function": "execute",
                    "class": "Doctrine\\DBAL\\Query\\QueryBuilder"
                  },
                  {
                    "file": "/home/user/nextcloud/apps/mail/lib/Db/MessageMapper.php",
                    "line": 388,
                    "function": "execute",
                    "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
                  },
                  {
                    "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
                    "line": 383,
                    "function": "updateBulk",
                    "class": "OCA\\Mail\\Db\\MessageMapper"
                  },
                  {
                    "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
                    "line": 223,
                    "function": "runPartialSync",
                    "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
                  },
                  {
                    "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
                    "line": 121,
                    "function": "sync",
                    "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
                  },
                  {
                    "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
                    "line": 161,
                    "function": "syncMailbox",
                    "class": "OCA\\Mail\\Service\\Sync\\SyncService"
                  },
                  {
                    "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                    "line": 218,
                    "function": "sync",
                    "class": "OCA\\Mail\\Controller\\MailboxesController"
                  },
                  {
                    "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                    "line": 127,
                    "function": "executeController",
                    "class": "OC\\AppFramework\\Http\\Dispatcher"
                  },
                  {
                    "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
                    "line": 157,
                    "function": "dispatch",
                    "class": "OC\\AppFramework\\Http\\Dispatcher"
                  },
                  {
                    "file": "/home/user/nextcloud/lib/private/Route/Router.php",
                    "line": 302,
                    "function": "main",
                    "class": "OC\\AppFramework\\App"
                  },
                  {
                    "file": "/home/user/nextcloud/lib/base.php",
                    "line": 998,
                    "function": "match",
                    "class": "OC\\Route\\Router"
                  },
                  {
                    "file": "/home/user/nextcloud/index.php",
                    "line": 37,
                    "function": "handleRequest",
                    "class": "OC"
                  }
                ],
                "previous": {
                  "type": "PDOException",
                  "message": "SQLSTATE[HY000]: General error: 5 database is locked",
                  "code": "HY000",
                  "trace": [
                    {
                      "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
                      "line": 82,
                      "function": "execute",
                      "class": "PDOStatement"
                    },
                    {
                      "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
                      "line": 1136,
                      "function": "execute",
                      "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement"
                    },
                    {
                      "file": "/home/user/nextcloud/lib/private/DB/Connection.php",
                      "line": 260,
                      "function": "executeStatement",
                      "class": "Doctrine\\DBAL\\Connection"
                    },
                    {
                      "file": "/home/user/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
                      "line": 213,
                      "function": "executeStatement",
                      "class": "OC\\DB\\Connection"
                    },
                    {
                      "file": "/home/user/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
                      "line": 287,
                      "function": "execute",
                      "class": "Doctrine\\DBAL\\Query\\QueryBuilder"
                    },
                    {
                      "file": "/home/user/nextcloud/apps/mail/lib/Db/MessageMapper.php",
                      "line": 388,
                      "function": "execute",
                      "class": "OC\\DB\\QueryBuilder\\QueryBuilder"
                    },
                    {
                      "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
                      "line": 383,
                      "function": "updateBulk",
                      "class": "OCA\\Mail\\Db\\MessageMapper"
                    },
                    {
                      "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php",
                      "line": 223,
                      "function": "runPartialSync",
                      "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
                    },
                    {
                      "file": "/home/user/nextcloud/apps/mail/lib/Service/Sync/SyncService.php",
                      "line": 121,
                      "function": "sync",
                      "class": "OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer"
                    },
                    {
                      "file": "/home/user/nextcloud/apps/mail/lib/Controller/MailboxesController.php",
                      "line": 161,
                      "function": "syncMailbox",
                      "class": "OCA\\Mail\\Service\\Sync\\SyncService"
                    },
                    {
                      "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                      "line": 218,
                      "function": "sync",
                      "class": "OCA\\Mail\\Controller\\MailboxesController"
                    },
                    {
                      "file": "/home/user/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                      "line": 127,
                      "function": "executeController",
                      "class": "OC\\AppFramework\\Http\\Dispatcher"
                    },
                    {
                      "file": "/home/user/nextcloud/lib/private/AppFramework/App.php",
                      "line": 157,
                      "function": "dispatch",
                      "class": "OC\\AppFramework\\Http\\Dispatcher"
                    },
                    {
                      "file": "/home/user/nextcloud/lib/private/Route/Router.php",
                      "line": 302,
                      "function": "main",
                      "class": "OC\\AppFramework\\App"
                    },
                    {
                      "file": "/home/user/nextcloud/lib/base.php",
                      "line": 998,
                      "function": "match",
                      "class": "OC\\Route\\Router"
                    },
                    {
                      "file": "/home/user/nextcloud/index.php",
                      "line": 37,
                      "function": "handleRequest",
                      "class": "OC"
                    }
                  ],
                  "previous": null
                }
              }
            }
          }
        }
      }
    }
  },
  "code": 5
}
```

**Comment by st3iny** [comment] 2021-03-25 11:11
Is this fixed by #4819? The issue can be closed then.

**Comment by ChristophWurst** [comment] 2021-03-25 12:01
> Is this fixed by #4819? The issue can be closed then.

Not quite. #4819 just helps with the automatic unlocking, but the mystery of why the database was locked is yet to be solved :)

**Comment by st3iny** [comment] 2021-03-25 12:07
Alright. I noticed @miaulalala  using `See` instead of `Fixes` in some PR descriptions and was not sure if this was intended or not :D

**Comment by miaulalala** [comment] 2021-03-25 14:17
> Alright. I noticed @miaulalala using `See` instead of `Fixes` in some PR descriptions and was not sure if this was intended or not :D

Oh, I didn't know there was a standard for this :grimacing:

**Comment by miaulalala** [comment] 2021-08-06 13:39
I haven't had this issue in a while now. Closing.

**Closed by miaulalala** 2021-08-06 13:39 UTC
Labels: bug, 2. developing, priority:high

**Comment by sazanof** [comment] 2022-03-17 14:11
### Hello guys! 
I transfer mail using the imapsync utility from an office 365 server to a server with postfix dovecot. NC is located on the same server.
Mailboxes (10 test ones in total) are linked to users automatically (your very cool feature!).
After syncing with imapsync, I log into the user's mailbox and notice that emails are not uploaded to all folders.
I open the console, I see
`{"status":"fail","data":{"message":"34 is already being synced","type":"OCA\\Mail\\Exception\\MailboxLockedException"}}`
I log on to the server. Executing the command
`sudo -u www-data php occ mail:account:sync 1`
At the moment, while I am writing this text, the command is being executed. It may be executed correctly

```
[debug] Syncing 62
[debug] Locking mailbox 62 for new messages sync
[debug] Locking mailbox 62 for changed messages sync
[debug] Locking mailbox 62 for vanished messages sync
[debug] Running initial sync for 62
[debug] Initial sync 315:INBOX - fetch all messages from IMAP took 0s
[debug] Initial sync 315:INBOX - persist messages in database took 0s
[debug] Initial sync 315:INBOX took 0s
[debug] Unlocking mailbox 62 from vanished messages sync
[debug] Unlocking mailbox 62 from changed messages sync
[debug] Unlocking mailbox 62 from new messages sync

```
... There is a 409 error in the mail web interface. We're waiting....

Sometimes there is an exception with the text "NNN is already being synced"

I looked at the source code and saw that the table with emails was being blocked.
Opened mysql
`select count(*) from oc_mail_messages;` 
outputs 10001 message. During the execution of the occ command, the number of emails does not change in the database.

I don't quite understand, can you explain the algorithm why this can happen, why the database is constantly blocked?

I assumed that synchronization should be performed once (or it is performed by the crown) for one mailbox. And everything.

I've been testing NC mail for 4 days now. And this error appears in the mail constantly. Maybe block the table for writing, but allow it to be read, I don't know.

If, say, there are 6 thousand letters in one mailbox, how are they recorded in the database? This process happens once, but in portions? Maybe I should just "wait"? =)

```
root@post:/var/www/nextcloud# sudo -u www-data php occ mail:account:diagnose 1
IMAP capabilities:
- AUTH
- ENABLE
- ID
- IDLE
- IMAP4REV1
- LITERAL+
- LOGIN-REFERRALS
- SASL-IR
Account has 6890 messages in 34 mailboxes
```
Well, I have completed the text, and so far the synchronization is being performed (the same thing is in progress).
Tell me please, im confused=).

**Comment by sazanof** [comment] 2022-03-17 14:46
Proof - Right now in the console https://disk.yandex.ru/i/bCZATScyD_6cvA =(
