### ISSUE TITLE
Moving mails does not work

### ISSUE THREAD

**Issue by avanc** [nextcloud/mail#370] opened 2017-05-04 12:01 UTC
### Steps to reproduce
1. Click a mail
2. Drag it into another folder (belonging to the same account)
3.

### Expected behaviour
The mail is moved to another folder.
According to the following PR, it should be available:
https://github.com/nextcloud/mail/pull/211

### Actual behaviour
The mail is not dragable at all.
If I click the mail and move the mouse while holding the button, the text is marked as normal for any other text. 

### Mail app

**Mail app version:** (see apps admin page)
0.6.3

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL

**Number of accounts:**
2

#### Client configuration
**Browser:**
Firefox 45.5.1

**Operating system:**
Windows 7

##### Browser log
Only one event while trying to drag and drop:

    [message] "load" Array [ Object, Object, Object, Object ] mail.min.js:148:14867

**Comment by joergmschulz** [comment] 2017-05-04 20:15
In my case, drag'n'drop worked between folders of the SAME account, but not between folders of different accounts.

**Comment by 1337sup3rh4x0r** [comment] 2017-05-06 13:28
I too cannot move mails with latest  Mail app version (0.6.4, but it also did not work with 0.6.3).

Same behaviour as @avanc decribes: 

> The mail is not dragable at all.
If I click the mail and move the mouse while holding the button, the text is marked as normal for any other text.

Using Owncloud 11.0.3 (stable)

I also tried disabling all other apps next to mail, but to no avail.

Same behaviour in latest chrome and firefox

**Comment by pixelipo** [comment] 2017-05-08 06:09
I can confirm this issue, running Mail 0.6.3 and 0.6.4 on Nextcloud 11.0.3

**Comment by ChristophWurst** [comment] 2017-05-08 06:40
This is expected with 0.6.4 and lower because the feature is not part of those releases. See https://github.com/nextcloud/mail/pull/211, it will probably come with 0.6.5.

**Closed by ChristophWurst** 2017-05-08 06:40 UTC
