### ISSUE TITLE
MIME email display broken - 

### ISSUE THREAD

**Issue by pgauret** [nextcloud/mail#1107] opened 2018-09-14 20:23 UTC
### Expected behavior
Open Nextcloud Mail, select a MIME message with embedded images and get the email to display properly.

### Actual behavior
Display of the message is broken (shows parts of the mime headers in the UI, some images do not load at all). See screenshots attached.

<img width="823" alt="screen shot 2018-09-14 at 22 21 38" src="https://user-images.githubusercontent.com/5214927/45573350-a3453280-b86c-11e8-9220-b05857110d44.png">

<img width="785" alt="screen shot 2018-09-14 at 22 23 11" src="https://user-images.githubusercontent.com/5214927/45573406-d25ba400-b86c-11e8-975b-c9df02064df3.png">

### Mail app

**Mail app version:** 

**Mailserver or service:** Dovecot, self hosted

**Number of accounts:** 1

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 14

**Updated from an older version or fresh install:**

Fresh install, database contents upgraded from NC 13

**List of activated apps:**
```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - news: 13.0.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
```

##### Server log (data/nextcloud.log)
```
TypeError: Argument 2 passed to OCA\Mail\Http\AttachmentDownloadResponse::__construct() must be of the type string, null given, called in /usr/share/nextcloud/apps/mail/lib/Controller/MessagesController.php on line 266

    /usr/share/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 266:

    OCA\Mail\Http\AttachmentDownloadResponse->__construct("\r\n--Apple ... n", null, "application/octet-stream")

    /usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OCA\Mail\Controller\MessagesController->downloadAttachment(3, "SU5CT1g=", 8496, 2)

    /usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "downloadAttachment")

    /usr/share/nextcloud/lib/private/AppFramework/App.php - line 118:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "downloadAttachment")

    /usr/share/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Mail\\ ... r", "downloadAttachment", OC\AppFramew ... {}, { accountId: ... "})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})

    /usr/share/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { accountId: ... "})

    /usr/share/nextcloud/lib/base.php - line 989:

    OC\Route\Router->match("/apps/mail/ ... 2")

    /usr/share/nextcloud/index.php - line 42:

    OC::handleRequest()
```

**Comment by ekric** [comment] 2018-11-18 08:56
Same here, also using Dovecot, trying to download a file:

`
Error | index | Exception: The requested uri(/apps/mail/api/accounts/1/folders/RWlua2F1ZmVuLldvaG5lbg==/messages/238/attachment/ocs/v2.php/apps/notifications/api/v2/notifications) cannot be processed by the script '/apps/notifications/api/v2/notifications')/var/www/servers/nextcloud/lib/base.php - line 930: OC\AppFramework\Http\Request->getRawPathInfo()/var/www/servers/nextcloud/index.php - line 42: OC::handleRequest() | 2018-11-18T09:49:41+0100
`

`
Error | index | TypeError: Argument 2 passed to OCA\Mail\Http\AttachmentDownloadResponse::__construct() must be of the type string, null given, called in /var/www/servers/nextcloud/apps/mail/lib/Controller/MessagesController.php on line 266/var/www/servers/nextcloud/apps/mail/lib/Controller/MessagesController.php - line 266: OCA\Mail\Http\AttachmentDownloadResponse->__construct("\r\n--Apple ... n", null, "application/octet-stream")/var/www/servers/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Mail\Controller\MessagesController->downloadAttachment(1, "RWlua2F1ZmVuLldvaG5lbg==", 238, 2)/var/www/servers/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Con ... {}, "downloadAttachment")/var/www/servers/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Con ... {}, "downloadAttachment")/var/www/servers/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Mail\\ ... r", "downloadAttachment", OC\AppFramew ... {}, { accountId: ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ accountId: ... "})/var/www/servers/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { accountId: ... "})/var/www/servers/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/mail/ ... 2")/var/www/servers/nextcloud/index.php - line 42: OC::handleRequest() | 2018-11-18T09:49:41+0100
`

**Comment by ekric** [comment] 2018-11-18 09:01
Seems like the attachments name is empty. Following workaround let's you download the file. But not much value without the file extension:

`return new AttachmentDownloadResponse(
                        $attachment->getContents(), $attachment->getName() ? $attachment->getName() : "no-name", $attachment->getType());`

**Comment by ChristophWurst** [comment] 2018-11-19 07:12
> Seems like the attachments name is empty. Following workaround let's you download the file. But not much value without the file extension:

Great finding! Could figure out why it's empty?

**Comment by ahobitt** [comment] 2018-11-20 18:16
> Great finding! Could figure out why it's empty?

It is moste of the time a strange naming of the file. 

Eg: "kurzanleitung_info_.pdf" or "Okt. 24, Dok. 1.pdf"

The mime type detection seems not to work with this files and I get the same error message as seen above.

**Comment by ekric** [comment] 2018-11-24 15:06
> > Great finding! Could figure out why it's empty?
> 
> It is moste of the time a strange naming of the file.
> 
> Eg: "kurzanleitung_info_.pdf" or "Okt. 24, Dok. 1.pdf"
> 
> The mime type detection seems not to work with this files and I get the same error message as seen above.

Same for me, unfortunately I'm not able to reproduce it at this time, but I also notice some encoding problems like this:

`soll bitte auf der Seite der K=C3=BCche sei= n`

Maybe that helps?

**Comment by ChristophWurst** [comment] 2019-01-08 15:18
Dup of https://github.com/nextcloud/mail/issues/1391, fixed in https://github.com/nextcloud/mail/pull/1448

**Closed by ChristophWurst** 2019-01-08 15:18 UTC
Labels: 1. to develop, bug, regression
