### ISSUE TITLE
Allow folders filering in the folder selection dialog 

### ISSUE THREAD

**Issue by ratermir** [nextcloud/mail#10183] opened 2024-09-23 08:49 UTC
### Describe the solution you'd like

When I want to move mail into a folder by selecting target folder, it would be very useful to allow "filtering" folders by typing text fragment in the dialog, where I select target folder. 
If I have many folders, it isreally annoying to open all mails again and again to select target. 
It would be much faster to filter the list - most users usually know name of the target folder.

**Comment by ChristophWurst** [comment] 2024-10-16 13:09
Thank you for your report!

This appears to be a duplicate of https://github.com/nextcloud/mail/issues/7536.

I'm closing this.

**Closed by ChristophWurst** 2024-10-16 13:09 UTC
Labels: enhancement, 0. to triage
