### ISSUE TITLE
Mail fails to update or reinstall after update to Nextcloud 20

### ISSUE THREAD

**Issue by goligo** [nextcloud/mail#4041] opened 2020-11-08 14:58 UTC
### Expected behavior
Mail can be upgraded to version 1.6.0 after upgrading Nextcloud to version 20.0.1

### Actual behavior
Updating or reinstalling Mail shows error "Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.", log file reports

      Error   index   Exception: Class 'Horde_Mail_Rfc822_Address' not found at              2020-11-08T14:44:12+00:00
                  lib/private/AppFramework/Http/Dispatcher.php line 110

                  0. .../App.php line 152
                     OC\AppFramework\Http\Dispatcher->dispatch(

                     )
                  1. .../Route/Router.php line 308
                     OC\AppFramework\App::main(

                     )
                  2. lib/base.php line 1009
                     OC\Route\Router->match(

                     )
                  3. index.php line 37
                     OC::handleRequest(

                     )

                  Caused by Error: Class 'Horde_Mail_Rfc822_Address' not found at
                  apps/mail/lib/Migration/FixCollectedAddresses.php line 72

                   0. .../FixCollectedAddresses.php line 56
                      OCA\Mail\Migration\FixCollectedAddresses->fixAddress(

                      )
                   1. .../Repair.php line 106
                      OCA\Mail\Migration\FixCollectedAddresses->run(

                      )
                   2. lib/private/legacy/OC_App.php line 1042
                      OC\Repair->run(

                      )
                   3. .../Installer.php line 160
                      OC_App::executeRepairSteps(

                      )
                   4. .../AppSettingsController.php line 448
                      OC\Installer->installApp(

                      )
                   5. .../Dispatcher.php line 169
                      OCA\Settings\Controller\AppSettingsController->enableApps(

                      )
                   6. .../Dispatcher.php line 100
                      OC\AppFramework\Http\Dispatcher->executeController(

                      )
                   7. .../App.php line 152
                      OC\AppFramework\Http\Dispatcher->dispatch(

                      )
                   8. .../Route/Router.php line 308
                      OC\AppFramework\App::main(

                      )
                   9. lib/base.php line 1009
                      OC\Route\Router->match(

                      )
                  10. index.php line 37
                      OC::handleRequest(

                      )

### Mail app

**Mail app version:** 1.6.0

**Mailserver or service:** Dovecot IMAP

### Server configuration

**Operating system**: FreeBSD 12.1

**Web server:** Apache 2.4 / PHP-FPM

**Database:** MariaDB 10.5

**PHP version:** 7.4

**Nextcloud Version:** 20.0.1

#### Client configuration
**Browser:** Chrome 86

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment] 2020-11-09 08:45
Duplicate of https://github.com/nextcloud/mail/issues/3784

**Closed by ChristophWurst** 2020-11-09 08:45 UTC
Labels: 0. to triage, bug
