### ISSUE TITLE
Some feedback on 1.3 Beta 3

### ISSUE THREAD

**Issue by szaimen** [nextcloud/mail#2852] opened 2020-04-03 13:51 UTC
Hi, I've tested the new beta release a bit and it seems to be really promising. 
Especially the new html view is much better now because it uses almost all available space. Also beeing able to show the raw messsage source is great and the app feels really snappy!

Some bugs that I have found, don't know if they are already reported in earlier versions or if they are new to this version:

- [ ] Drafts are saved successfuly but are not shown in the drafts folder, the same for files that get deleted; they are not visible in the trash bin folder. (I am not sure if they just get shown later on but are definitely not visible in these folders instantly) On other mail programs with the same account they are shown correctly (instantly).
- [ ] when clicking on the account settings section and afterwards on the "all mail inboxes" section, a spinning wheel appears on the bottom of the mail list that is spinning for forever.
- [ ] sometimes a mail is shown in an imap folder that was already moved into another imap folder on another client. Then opening the mail doesn't work and you get the error message: "Not found - the message couldn't get loaded"
- [ ] on mobile: you click on the hamburger button to open the hamburger menu. Now you can close and open the side menu via a gesture too easily. If you close it with a geature and click on the hamburger button again, it doesn't open, and is still closed but now steady again. Only if you click on that button again, it opens the hamburger menu.
- [x] showing the raw message source could use some more space on mobile (see the screenshot below)
![photo5204071818430885011](https://user-images.githubusercontent.com/42591237/78367591-9c068680-75c2-11ea-9689-7fd1b80eb51e.jpg)
- [ ] of course those errors are still appearing: #2695 #2699

**Comment by ChristophWurst** [comment] 2020-04-07 08:25
>     * showing the raw message source could use some more space on mobile (see the screenshot below)

@gretad @jancborchardt could you have a look?

**Comment by ChristophWurst** [comment] 2020-04-07 14:13
> Drafts are saved successfuly but are not shown in the drafts folder, the same for files that get deleted; they are not visible in the trash bin folder. (I am not sure if they just get shown later on but are definitely not visible in these folders instantly) On other mail programs with the same account they are shown correctly (instantly).

Not a new problem. This app just has to get more data from the server to know the new state. This isn't trivial and we can't do this for v1.3.

> when clicking on the account settings section and afterwards on the "all mail inboxes" section, a spinning wheel appears on the bottom of the mail list that is spinning for forever.

Can't reproduce. This was possibly fixed by #2480 

> sometimes a mail is shown in an imap folder that was already moved into another imap folder on another client. Then opening the mail doesn't work and you get the error message: "Not found - the message couldn't get loaded"

I'll look into that.

> on mobile: you click on the hamburger button to open the hamburger menu. Now you can close and open the side menu via a gesture too easily. If you close it with a geature and click on the hamburger button again, it doesn't open, and is still closed but now steady again. Only if you click on that button again, it opens the hamburger menu.

Also not a new issue, I think. This is more a problem of https://github.com/nextcloud/nextcloud-vue but @skjnldsv or @GretaD might know more.

**Comment by skjnldsv** [comment] 2020-04-07 14:18
> > on mobile: you click on the hamburger button to open the hamburger menu. Now you can close and open the side menu via a gesture too easily. If you close it with a geature and click on the hamburger button again, it doesn't open, and is still closed but now steady again. Only if you click on that button again, it opens the hamburger menu.

I guess fixed with the work we did w/ Marco

**Comment by jancborchardt** [comment] 2020-04-07 15:11
> * showing the raw message source could use some more space on mobile (see the screenshot below)

This sounds like an issue for the modal component, right @juliushaertl @skjnldsv? Keeping it a tad bigger on mobile would indeed be good.

**Comment by skjnldsv** [comment] 2020-04-07 15:19
> This sounds like an issue for the modal component, right @juliushaertl @skjnldsv? Keeping it a tad bigger on mobile would indeed be good.

Most likely just increase the predefined size to `full`
https://nextcloud-vue-components.netlify.com/#/Components/Modal 
https://github.com/nextcloud/nextcloud-vue/blob/9f525decb32e9e89f0c4fdeefb266c356199c4d2/src/components/Modal/Modal.vue#L269

**Comment by ChristophWurst** [comment] 2020-04-07 16:49
> Most likely just increase the predefined size to `full`

Sounds good :) @GretaD could you give that a try?

**Comment by szaimen** [comment] 2020-04-08 12:16
> on mobile: you click on the hamburger button to open the hamburger menu. Now you can close and open the side menu via a gesture too easily. If you close it with a geature and click on the hamburger button again, it doesn't open, and is still closed but now steady again. Only if you click on that button again, it opens the hamburger menu.

This is still happening on 1.3.0 RC1

**Comment by szaimen** [comment] 2020-04-08 12:18
> when clicking on the account settings section and afterwards on the "all mail inboxes" section, a spinning wheel appears on the bottom of the mail list that is spinning for foreve

Could you remove the spinning wheel on the bottom? I don't know if it tries to fetch new messages but it still seems to need a lot of time to try to fetch new messages: around 10-20seconds? (which feels endless if there are actually no new ones...)

**Comment by szaimen** [comment] 2020-04-08 12:19
> Drafts are saved successfuly but are not shown in the drafts folder, the same for files that get deleted; they are not visible in the trash bin folder. (I am not sure if they just get shown later on but are definitely not visible in these folders instantly) On other mail programs with the same account they are shown correctly (instantly).

I think this could get solved by automatically reloading that imap folder when clicking on it... doesn't seem to happen on 1.3.0 RC1 though...

**Comment by szaimen** [comment] 2020-04-08 12:21
> sometimes a mail is shown in an imap folder that was already moved into another imap folder on another client. Then opening the mail doesn't work and you get the error message: "Not found - the message couldn't get loaded"

I think that has to do with not automatically reloading that imap folder from time to time. BTW: now it doesn't show an error message if the message isn't in this imap folder anymore on 1.3.0 RC1

And I would suggest adding a visible button that you can click on to reload imap folders, because the reloading shortcut "r" is not really discoverable and not executable on mobile...

**Comment by ChristophWurst** [comment] 2020-04-08 12:51
> Could you remove the spinning wheel on the bottom? I don't know if it tries to fetch new messages but it still seems to need a lot of time to try to fetch new messages: around 10-20seconds? (which feels endless if there are actually no new ones...) Maybe that could just trigger the reloading of the whole imap folder?

I think I just did: #2889

**Comment by ChristophWurst** [comment] 2020-04-08 12:53
> And I would suggest adding a visible button that you can click on to reload imap folders, because the reloading shortcut "r" is not really discoverable and not executable on mobile...

Yes, we should definitely improve that. But it's not a new limitation, hence not a blocker for v1.3.

**Comment by jancborchardt** [comment] 2020-04-08 17:45
> > This sounds like an issue for the modal component, right @juliushaertl @skjnldsv? Keeping it a tad bigger on mobile would indeed be good.
> 
> Most likely just increase the predefined size to `full`
> https://nextcloud-vue-components.netlify.com/#/Components/Modal
> https://github.com/nextcloud/nextcloud-vue/blob/9f525decb32e9e89f0c4fdeefb266c356199c4d2/src/components/Modal/Modal.vue#L269

But look at the screenshot above – this sizing looks wrong and should use more on mobile. It’s something to be fixed in that size, as we want to keep the modal style even on mobile, and not go to full. :) We just need to make sure that on mobile it uses more width and possibly height.

cc @GretaD @ChristophWurst

**Comment by jancborchardt** [comment] 2020-04-20 16:39
There is a pull request for review about the modal size open at https://github.com/nextcloud/nextcloud-vue/pull/1028 by @GretaD 

@ChristophWurst you reacted with a "confused" emoji to my previous comment, can you explain?

**Comment by jancborchardt** [comment] 2020-04-20 16:40
Btw @szaimen it would be good if you can open the issues as separate issues and not an overview issue. As you see the discussion is mostly about one point, and the others get lost. So could I ask you to reopen the ones which still appear (and don’t have an open issue already) as separate issues? Thank you so much! :)

**Closed by jancborchardt** 2020-04-20 16:40 UTC
Labels: 1. to develop, bug
