### ISSUE TITLE
“No sent mailbox configured. Please pick one in the account settings.” - Mail app not able to send email

### ISSUE THREAD

**Issue by IanChok** [nextcloud/mail#5833] opened 2021-12-12 22:46 UTC
### Expected behavior
**User should be able to send email via SMTP**
([Forum Post](https://help.nextcloud.com/t/no-sent-mailbox-configured-please-pick-one-in-the-account-settings-mail-app-not-able-to-send-email/129146))
I have two NC accounts: account A (admin), and account B (non-admin)

I’m able to send and receive email through the mail app for my account A using A’s specific email (a@email.com)

I’m able to receive but NOT send through the mail app for account B using B’s specific email (b@email.com)

The error the app gives is: `Error sending your message No sent mailbox configured. Please pick one in the account settings.`

In the admin logs, it says: `Error mail Saving draft failed: No drafts mailbox configured`

Account B has the same email (b@email.com) registered in its NC account user email field.

### Actual behavior
Receive error message: `Error sending your message No sent mailbox configured. Please pick one in the account settings.`

### Mail app

**Mail app version:** 1.11.1

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MySql

**PHP version:** PHP 7.3.31-1~deb10u1

**Nextcloud Version:** 23.0.0

#### Client configuration
**Browser:** Brave Browser

**Comment by miaulalala** [comment] 2021-12-13 10:03
Can you check in the settings if those two mailboxes are configured? You can find them in the three dot menu on your account -> Account Settings -> Default Folders

![image](https://user-images.githubusercontent.com/7427347/145791821-647213e2-f8ee-4072-8df6-37c408714c83.png)

**Comment by pierreozoux** [comment] 2022-01-26 11:11
This looks very similar to https://github.com/nextcloud/mail/issues/4153

I'll close this one in favor of the older one.

Please add your :+1: or comments to improve the description of the issue.

**Closed by pierreozoux** 2022-01-26 11:11 UTC
Labels: bug, 0. to triage

**Comment by miaulalala** [comment] 2022-01-26 11:16
Duplicate of #4153
