### ISSUE TITLE
Suggestion: Multiselection and drag'n'drop for eMails

### ISSUE THREAD

**Issue by SublimeProphets** [nextcloud/mail#1336] opened 2018-11-26 11:38 UTC
Hi

I love the mail app but often i wish to be able to select multiple Mails at one time to delete them all at once. Furthermore, if we have multiselection some drag & drop into folders would be awesome as well.

My suggestion ist to implement multiselection through the common hotkey "ctrl" to select on click and shift to select everything between the last selected and newly selected. Not as important but we could alos use ctrl + A to select all mails.

Drag & Drop should be obvious: the ability to click and hold one or multiple eMails and we could show a indicator which or how many eMails will be affected (positioned close to the mouse).

Greetings Chris

**Comment by ChristophWurst** [comment] 2018-11-26 11:52
Duplicate of https://github.com/nextcloud/mail/issues/1008.

**Closed by ChristophWurst** 2018-11-26 11:52 UTC
