### ISSUE TITLE
enter email address - press tab key - address not added & jumps to CC instead of subject

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/mail#3242] opened 2020-06-11 21:27 UTC
### Expected behavior
enter email address in "To:"
press tab key 
address gets added visibliy 
cursor jumps to "subject" field

### Actual behavior
enter email address in "To:"
press tab key 
looks like address gets added, but not really (e.g. send button does not work because there is no address added)
cursor jumps to CC/BCC

### Mail app
**Mail app version:**  1.3.5

### Server configuration
**Nextcloud Version:** 18.0.2

#### Client configuration
**Browser:** Firefox 77.0.1 

tell me if u need more info

**Comment by ChristophWurst** [comment] 2020-06-15 06:46
I'd say this is a duplicate of https://github.com/nextcloud/mail/issues/2769

**Closed by ChristophWurst** 2020-06-15 06:46 UTC
Labels: 0. to triage, bug

**Comment by alexanderdd** [comment] 2020-06-18 20:33
@ChristophWurst  it might be related, but this issue here is specifically about using tab key to navigate. 

Also this issue here has two parts: (1) address not added     (2) jumps to CC instead of subject

or should I open a separate one about (2) ?

**Comment by ChristophWurst** [comment] 2020-06-24 09:35
> jumps to CC instead of subject

But … that is fine, right? That is the most logic order in my opinion. cc @jancborchardt

**Comment by jancborchardt** [comment] 2020-06-24 11:04
> > jumps to CC instead of subject
> 
> But … that is fine, right? That is the most logic order in my opinion. cc @jancborchardt 

Yep:
- if the Cc field is shown already, it should tab to Cc (then Bcc if shown, then Subject)
- If not, it should tab to the Cc/Bcc toggle, then Subject.

**Comment by alexanderdd** [comment] 2020-07-02 23:08
@ChristophWurst please reopen this issue. 
Pressing tab key does not add the adress, but it should. Its not a duplicate.

Never mind about (2) (see above), I agree now after Jan's comment. Feel free to edit the title of this.

**Comment by ChristophWurst** [comment] 2020-07-03 06:25
> Pressing tab key does not add the adress, but it should. Its not a duplicate.

That should go into #2769
