### ISSUE TITLE
Undefined offset: -1 at lib/IMAP/MessageMapper.php

### ISSUE THREAD

**Issue by AutomCoding** [nextcloud/mail#6027] opened 2022-02-10 10:43 UTC
### Expected behavior

I open this because I get the same error in my logs as a previous, unresolved, ticket. I haven't seen it in action personally.

### Actual behavior

This is a reopening of #6007 as I get the same error message in the logs occasionally. I have asked the other users if they have seen it as described in that ticket, still waiting for answers.

I haven't looked at the script to see how it would manifest for a user so the title is just placeholder.

### Steps to reproduce

I don't recall seeing anything like described in the previous issue myself, so I cannot say anything useful here yet.

### Mail app version

1.11.6

### Operating system

Debian 11.2.0

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

[PHP] Error: Undefined offset: -1 at /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php#186

    /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php - line 186:
    OC\Log\ErrorHandler::onError()

    /var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php - line 294:
    OCA\Mail\IMAP\MessageMapper->findAll()

    /var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php - line 226:
    OCA\Mail\Service\Sync\ImapToDbSynchronizer->runInitialSync()

    /var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php - line 127:
    OCA\Mail\Service\Sync\ImapToDbSynchronizer->sync()

    /var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php - line 161:
    OCA\Mail\Service\Sync\SyncService->syncMailbox()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
    OCA\Mail\Controller\MailboxesController->sync()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 302:
    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1006:
    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:
    OC::handleRequest()

**Comment by GretaD** [comment] 2022-02-10 11:25
The ticket was closed because it didnt follow the template data not because it was resolved. 
Please change the title of this issue and also send the nextcloud.logs(maybe different name) that is saved on your /data so we can see where the problem happens. I personally cannot reproduce it.

**Comment by AutomCoding** [comment] 2022-02-10 14:52
I set that title because I only know that these errors appears in the log; I am not sufficiently familiar with the codebase to know what it's about and give it a more descriptive title.

This is the what it looks like in nextcloud.log (username redacted):

{"reqId":"jLTMQKJHgqWBUyniQayS","level":3,"time":"2022-02-10T02:56:00+00:00","remoteAddr":"2600:70ff:b127:0:ae09:2d37:a7a4:ba09","user":"redacted","app":"PHP","method":"POST","url":"/apps/mail/api/mailboxes/1/sync","message":"Undefined offset: -1 at /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php#186","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0","version":"23.0.0.10","exception":{"Exception":"Error","Message":"Undefined offset: -1 at /var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php#186","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MessageMapper.php","line":186,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":294,"function":"findAll","class":"OCA\\Mail\\IMAP\\MessageMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":226,"function":"runInitialSync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/SyncService.php","line":127,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/MailboxesController.php","line":161,"function":"syncMailbox","class":"OCA\\Mail\\Service\\Sync\\SyncService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"sync","class":"OCA\\Mail\\Controller\\MailboxesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6205238fa68d2"}

That user has three email accounts connected so I can't say which provider this mailbox is connected to.

**Comment by influjensbahr** [comment] 2022-02-10 16:58
Possibly related to: https://github.com/nextcloud/mail/pull/5976
And Nextcloud forum: https://help.nextcloud.com/t/mail-loads-forever-floods-with-error-warnings/133474

**Comment by st3iny** [comment] 2022-05-27 13:44
Fixed by https://github.com/nextcloud/mail/pull/5976.

**Closed by st3iny** 2022-05-27 13:44 UTC
Labels: bug, 1. to develop, priority:high
