### ISSUE TITLE
when in settings, "new message" gives blank page

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/mail#2667] opened 2020-02-19 12:51 UTC
### Expected behavior
click on email address in left sidebar to edit account settings
click "new message" at the top
compose window opens

### Actual behavior
click on email address in left sidebar to edit account settings
click "new message" at the top
sidebar stays, rest of page is white

### Mail app

**Mail app version:** 1.1.2

**Mailserver or service:** irrelevant

### Server configuration

**Operating system**:?

**Web server:** ?

**Database:**?

**PHP version:** ?

**Nextcloud Version:** 18.0.0

#### Client configuration
**Browser:** Firefox 73

**Operating system:** Linux Mint

**Comment by ChristophWurst** [comment] 2020-02-21 09:44
Duplicate of #110 and possibly fixed by https://github.com/nextcloud/mail/pull/2480

**Closed by ChristophWurst** 2020-02-21 09:44 UTC
Labels: 0. to triage, bug
