### ISSUE TITLE
Auto Collection/Notification: Nextcloud Mail App

### ISSUE THREAD

**Issue by rr4444** [nextcloud/mail#6210] opened 2022-04-07 21:42 UTC
### Is your feature request related to a problem? Please describe.

Can this auto sync IMAP? Or is there a webhook than I can cron curl for?

And can new IMAP mails alert the user to new mail via notifications/activity? 

### Describe the solution you'd like

I need to check email A via next cloud IMAP, but send new mail alerts to my NC account registered email B, which is a different address.

Is this alerting possible?

**Comment by rr4444** [comment] 2022-04-07 21:43
Many thanks. People seem to moan about this app, but I think that cleanly does the basics and integrates with NC to some extent.

**Comment by ChristophWurst** [comment] 2022-04-08 13:24
Sounds like a duplicate of https://github.com/nextcloud/mail/issues/6170

The app keeps the mailboxes in sync in the background. It works best if you use cron https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html#cron

**Closed by ChristophWurst** 2022-04-08 13:24 UTC
Labels: enhancement, 0. to triage
