### ISSUE TITLE
Various issues when writing emails with latest versions of Firefox

### ISSUE THREAD

**Issue by doc75** [nextcloud/mail#4104] opened 2020-11-19 11:43 UTC
### Expected behavior

Writing mail, I should be able to delete text by using delete or backspace key. I also should be able to copy/paste text.

### Actual behavior

When I answer a mail, I can delete 1 or 2 chars with backspace and then it stops working and I cannot anymore delete chars (even with delete key). The only solution is to select text with mouse and type another text to overwrite it (though the final result that the recipient will receive may not look the same as what you see).

Copying text to the clipboard doesn't work neither.

Issues are not reproducible in Chromium 84.

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** Personal server (Dovecot + Postfix)

### Server configuration

**Operating system**: Official Docker fpm image 

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** Official docker image

**Nextcloud Version:** 19.0.4

#### Client configuration
**Browser:** Firefox 83

**Operating system:** Windows

**Comment by doc75** [comment] 2020-11-19 11:51
I can find in the web console this type of error when the issue occurs:
```
Uncaught CKEditorError: a is undefined                                                                    mail.js:1:64080
    <anonymous> VueJS
    value range.js:348
    value deletecommand.js:107
    value model.js:805
    value model.js:231
    value deletecommand.js:76
    decorate observablemixin.js:255
    fire emittermixin.js:209
    e observablemixin.js:259
    value commandcollection.js:68
    value editor.js:288
    value delete.js:55
    fire emittermixin.js:209
    c deleteobserver.js:87
    u deleteobserver.js:50
    fire emittermixin.js:209
    value domeventobserver.js:96
    value keyobserver.js:28
    value domeventobserver.js:79
    fire emittermixin.js:209
    r emittermixin.js:235
    construct self-hosted:2653
    s mail.js:1
    r mail.js:1
    construct self-hosted:2653
    f mail.js:5
    d ckeditorerror.js:66
    value ckeditorerror.js:118
    value model.js:236
    value deletecommand.js:76
    decorate observablemixin.js:255
    fire emittermixin.js:209
    e observablemixin.js:259
    value commandcollection.js:68
    value editor.js:288
    value delete.js:55
    fire emittermixin.js:209
    c deleteobserver.js:87
    u deleteobserver.js:50
    fire emittermixin.js:209
    value domeventobserver.js:96
    value keyobserver.js:28
    value domeventobserver.js:79
    fire emittermixin.js:209
    r emittermixin.js:235
```

```
Uncaught CKEditorError: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…t/error-codes.html#error-model-nodelist-offset-out-of-bounds
 {"offset":10,"nodeList":[{"data":"Ho  can i"}]}                                            mail.js:1:63758
    r mail.js:1
    f mail.js:5
    d ckeditorerror.js:66
    value nodelist.js:161
    value element.js:188
    d position.js:1091
    get position.js:221
    v document.js:481
    value document.js:390
    n documentselection.js:646
    fire emittermixin.js:209
    value selection.js:479
    value selection.js:370
    value documentselection.js:734
    value documentselection.js:421
    value writer.js:1177
    convertSelectionChange upcasthelpers.js:413
    value model.js:173
    convertSelectionChange upcasthelpers.js:412
    fire emittermixin.js:209
    value selectionobserver.js:183
    value selectionobserver.js:104
    fire emittermixin.js:209
    r emittermixin.js:235
    construct self-hosted:2653
    r mail.js:1
    construct self-hosted:2653
    f mail.js:5
    d ckeditorerror.js:66
    value nodelist.js:161
    value element.js:188
    d position.js:1091
    get position.js:221
    v document.js:481
    value document.js:390
    n documentselection.js:646
    fire emittermixin.js:209
    value selection.js:479
    value selection.js:370
    value documentselection.js:734
    value documentselection.js:421
    value writer.js:1177
    convertSelectionChange upcasthelpers.js:413
    value model.js:173
    convertSelectionChange upcasthelpers.js:412
    fire emittermixin.js:209
    value selectionobserver.js:183
    value selectionobserver.js:104
    fire emittermixin.js:209
    r emittermixin.js:235
```

**Comment by ChristophWurst** [comment] 2020-11-20 09:20
Hmmmm I've seen that `Given offset cannot be found in the node list` a while ago.

Do you have formatting enabled for that reply or is it off?

**Comment by doc75** [comment] 2020-11-20 10:15
@ChristophWurst by default formatting is not activated on my side.
I just checked and I am able to reproduce the issue **with** and **without** formatting activated.

**Comment by alexanderdd** [comment] 2020-11-21 18:51
Can reproduce on Linux Mint 19.3, Firefox 83.0, same server and mail app as report (Nextcloud 19.04, Mail 1.4.1)

@ChristophWurst unusable interface, please assign a **high priority** to this bug! A coworker complained about this today, people can't work because of this. (I know, buy a Nextcloud subscription..... just telling you that probably thousands of other people have this problem right now, but they don't know that it can be reported here).

@doc75 Does updating to 19.0.5 help?

Let me know if you need info from me.

**Comment by doc75** [comment] 2020-11-21 21:42
@alexanderdd @ChristophWurst , same issue on NC 19.0.5 and also on Linuxx (still with Firefox 83).
Not reproducible on Chromium 86 on Linux

**Comment by alexanderdd** [comment] 2020-11-22 18:01
Just noticed: everthing works fine (also enter, delete keys) until you use the backspace key. Then the backspace, enter, delete key does not work anymore.

This is only in Firefox, Chromium works fine.

**Comment by bernatnan** [comment] 2020-11-22 19:31
I have the same problem, as how @alexanderdd say, only fail with Firefox. Brave (based on Chromium) works well too.

I'm using Firefox v83.0 too, but Nextcloud 20.0.2 and MAil 1.7.0.

Any thing that you need ¿?

**Comment by ChristophWurst** [comment] 2020-11-23 10:17
> @ChristophWurst unusable interface, please assign a **high priority** to this bug! A coworker complained about this today, people can't work because of this. (I know, buy a Nextcloud subscription..... just telling you that probably thousands of other people have this problem right now, but they don't know that it can be reported here).

More than 200k installations of Mail and three users reported this.

I'm fine with the label. But with the assignment we don't fix it. We need someone who can reproduce this in a development environment.

So, who wants to dive into this?

**Comment by ChristophWurst** [comment] 2020-11-23 10:17
The first thing to check would be bug reports of the CKEditor version in use in an affected version and if anything like that has been reported upstream.

**Comment by joober** [comment] 2020-11-23 16:16
Just chiming in to let you know that I have the same issue on NC 19.0.5, Mail 1.4.1. on Apache. I use Firefox 83 on Linux.
I don't have a development environment available but if I can be helpful in testing or providing more information, I'd be happy to help.

**Comment by laurentiu2** [comment] 2020-11-24 09:09
Can confirm also. NC 19.04 Firefox 83

**Comment by ChristophWurst** [comment] 2020-11-24 09:23
You can use the :+1: on the original report. Thanks.

**Comment by ChristophWurst** [comment] 2020-11-24 09:30
This also happens on latest master: ``Uncaught CKEditorError: Range.setStart: Argument 1 is not an object.``.

Did anyone check CKEditor for existing bug reports?

**Comment by doc75** [comment] 2020-11-24 11:25
I checked a little bit, and found this: https://stackoverflow.com/questions/50951667/ckeditor5-receiving-model-nodelist-offset-out-of-bounds-what-are-possible-r
In one of the anwsers it link to this article: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#fixing-position-mapping

There is also a tutorial mentionning similar error: https://github.com/ckeditor/ckeditor5/blob/4cb8158a87f6c44026b4199eabfaf10302142ace/docs/framework/guides/tutorials/implementing-an-inline-widget.md#fixing-position-mapping

I hope this is relevant in our case. Sorry if not.

**Comment by ChristophWurst** [comment] 2020-11-24 11:59
Thanks a lot. I'll check them :)

**Comment by StCyr** [comment] 2020-11-24 14:41
Hello @ChristophWurst 

Can I help?

**Comment by johanneshorak** [comment] 2020-11-25 20:35
For me this problem occurs too, both when composing a new message or replying to an existing one. I type some characters and then back space wont do anything. I'm using Firefox 83.0. I tested with Chrome as well, the problem did not occur there.

What can I provide to help finding the issue?

**Comment by ChristophWurst** [comment] 2020-11-26 07:53
What I find a bit strange is that this is showing up now for so many different versions of Mail at the same time. The 1.4.x for 19 was released in early July. And since then we updated CKEditor a at least two times as far as I remember. Therefore it's possible to be something that changed in the browser(s).

Does anyone have access to older Firefoxes (e.g. ESR) to check if the problem is reproducible there as well?

**Comment by bernatnan** [comment] 2020-11-26 08:03
> What I find a bit strange is that this is showing up now for so many different versions of Mail at the same time. The 1.4.x for 19 was released in early July. And since then we updated CKEditor a at least two times as far as I remember. Therefore it's possible to be something that changed in the browser(s).
> 
> Does anyone have access to older Firefoxes (e.g. ESR) to check if the problem is reproducible there as well?

I have a laptop with Firefox ESR version., but until I finish working and arrive at home I won't have it. I willl test then.

> FWIW I can't reproduce the bug at https://ckeditor.com/ckeditor-5/demo/

**Comment by joober** [comment] 2020-11-26 08:10
> Does anyone have access to older Firefoxes (e.g. ESR) to check if the problem is reproducible there as well?

I just tried this on Firefox 68.12.0esr on Windows 10. The problem doesn't appear to exist there. I wrote a rather long email, used Enter and Backspace a lot on purpose. Didn't run into an issue.

Let me know if you need me to test anything specific.

**Comment by bernatnan** [comment] 2020-11-26 10:01
In the end, I was able to do the test. Tried on a Firefox 78.5.0esr and works well too.

**Comment by TheFoxStudio** [comment] 2020-11-26 14:22
I am "happy" to join in. Same issue since I updated to Nextcloud 20.0.2, Mail Version 1.7.0
No backspace or delete. Usually happens a few seconds after I start writing the reply.

**Comment by cdehe7519** [comment] 2020-11-28 16:33
**Same problem for me on Mail 1.7 since a about a week.**  Ubuntu LTS and Firefox.  Was on Nextcloud 19.0 a week ago, and now on 20.0.  Problem is on both. 
log on console
Uncaught CKEditorError: Index or size is negative or greater than the allowed amount
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-Index or size is negative or greater than the allowed amount
    value domconverter.js:307
    value view.js:393
    value delete.js:59
    fire emittermixin.js:209
    l deleteobserver.js:87
    c deleteobserver.js:50
    fire emittermixin.js:209
    value domeventobserver.js:96
    value keyobserver.js:28
    value domeventobserver.js:79
    fire emittermixin.js:209
    r emittermixin.js:247

**Comment by nursoda** [comment] 2020-11-30 19:21
Same here, on multiple NC 20 installations.

**Comment by ChristophWurst** [comment] 2020-11-30 20:01
I planned to look into it this week. Can't promise anything at this moment but we'll figure it out.

**Comment by nursoda** [comment] 2020-11-30 20:40
Thanks. I just played further with it. Strange things happened:

- Tried to create an all new address; just created auth creds in dovecot, never used on Thunderbird or any other MUA. Couldn't set up the account in NC mail though. Noticed errors in nextcloud.log complaining about "non-existend special folder 'Drafts'". So I set up the account in TB to make sure I made no mistake with creds. Worked fine. After creating (INBOX), Trash, Sent and Drafts, I could set up the account in NC Mail. So that's another NC Mail glitch. Shall I open a bug for that?
- Then I tried to write a new message in NC Mail, to reproduce the editing issue. But I couldn't. It clicked "Create new message" but nothing happened, waiting didn't help. So I Ctrl-Shift-R(eloaded) the Mail page. Now I saw five(!) identical(!) accounts resulting from the multiple retries. I deleted the first four of them and only left that that contained all folders I set up in TB. After deletion, I clicked "Create new message" again … and it worked.
- So I now finally could test the write something and delete it with backspace issue – but it is not present THERE. I'm baffled. It was there for another user in the SAME NC (he just showed me live in a video session), and I could reproduce it in another NC on the same server. Common is that these are accounts that were set up on NC 19 or older (or in Mail versions prior to 1.7 (or most probably even prior to 1.6). The NEW account does NOT show the symptom described above HERE.
- After fiddling with insert and delete, I decided to sent that test message. Worked fine. But in Drafts, I see multiple versions of the message just sent … drafts, that should be overwritten during editing, and deleted after being sent.

Setup here is: Arch server, Nginx+PHP-FPM+MariaDB, NC 20.0.2, Mail 1.7.0.

**Comment by ChristophWurst** [comment] 2020-12-01 09:03
Thanks for the updated title, @StCyr. Hadn't realized all reports are about Firefox, so that's good and we can focus on a single browser.

**Comment by StCyr** [comment] 2020-12-01 09:06
> 
> 
> Thanks for the updated title, @StCyr. Hadn't realized all reports are about Firefox, so that's good and we can focus on a single browser.

Apparently it's some inconsistency between the editor's model and its view. 

I'm willing to work on this. However, I've hard time understanding how to show the editor model and view in the console.

**Comment by ChristophWurst** [comment] 2020-12-01 13:23
> Apparently it's some inconsistency between the editor's model and its view.

Mind linking to a resource if you found this info in some docs?

Btw switching from `@ckeditor/ckeditor5-vue` to `@ckeditor/ckeditor5-vue2` didn't help.

**Comment by StCyr** [comment] 2020-12-01 13:26
Ho, it's in a link posted earlier: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#fixing-position-mapping

**Comment by ChristophWurst** [comment] 2020-12-01 14:56
Some findings

* https://github.com/ckeditor/ckeditor5/issues/8548 sounds similar
* https://github.com/vuejs/vue/issues/6845 sounds similar, as the code that does :boom: is
```
    // notify change
    ob.dep.notify();
```

![Bildschirmfoto von 2020-12-01 15-54-45](https://user-images.githubusercontent.com/1374172/100756561-9d0be400-33ed-11eb-9899-6d1f916d4457.png)

… as far as I understand the `__ob__` is Vue's reactive object. For some reason it's not available on this object and therefore we see an error. I think the out of bounds error is just another symptom and possible fixed as soon as this original error is resolved.

**Comment by ChristophWurst** [comment] 2020-12-01 17:41
Did anyone see any consistent steps that reliably trigger the error? For me it seems rather random. One time it occurs soon, the next time I have to try rather long until this shows. :thinking:

**Comment by joober** [comment] 2020-12-01 18:08
For me, it triggers very reliably. I start typing an email, hit enter or backspace and usually it happens right away. Typically while writing the first line.

**Comment by nursoda** [comment] 2020-12-01 18:10
I can also provide access to a system/account where it is triggered all the time.

**Comment by ChristophWurst** [comment] 2020-12-01 18:15
Thanks for the offer @nursoda. The problem with that is that I can't modify the sources. Hence I would preferably have this locally where I can add debug statements and try a few things to see if they make the situation any better.

**Comment by cdehe7519** [comment] 2020-12-01 18:16
For me, it seems to happen immediately after a copy of the message I am currently working on is sending a copy to draft.

**Comment by nursoda** [comment] 2020-12-01 18:23
I understand that adding debug is necessary, but at least I could increase log level and you could see what is logged when it happens? Or are you beyond this point ;)

**Comment by cdehe7519** [comment] 2020-12-01 18:23
If a take the copy in draft it works again for a few seconds.  Then again impossible do correct the text . Possibly another copy in dradt added

**Comment by nursoda** [comment] 2020-12-01 18:25
I can backspace ONCE, it seems that this triggers something. After that, I cannot backspace or delete in that session. But I can overwrite text that I mark with Shift+Arrows.

**Comment by StCyr** [comment] 2020-12-01 19:21
Yes, same here: it’s very reliable: juste hit backspace 2 or 3 times

**Comment by ChristophWurst** [comment] 2020-12-02 11:06
Fix is at https://github.com/nextcloud/mail/pull/4163 for anyone who has a test/dev environment set up :v:

**Closed** 2020-12-02 11:16 UTC
Labels: 3. to review, bug, help wanted, priority:high

**Comment by nursoda** [comment] 2020-12-02 11:41
Hmmm, it seems like an easy fix (delete one line of code) and I can edit files within my setup, but I was unable to locate that file. I have no real dev setup, but if you'd --verbose a bit, I'd like to try!

**Comment by StCyr** [comment] 2020-12-02 11:51
> Hmmm, it seems like an easy fix (delete one line of code) and I can edit files within my setup, but I was unable to locate that file. I have no real dev setup, but if you'd --verbose a bit, I'd like to try!

Just update your app. I'm guessing the update will be available from the store as from tomorrow.

**Comment by ChristophWurst** [comment] 2020-12-02 12:10
I will try to release updates soon. You can't edit that file on your production instance because our javascript code gets compiled and you don't have the source file.

**Comment by StCyr** [comment] 2020-12-02 12:28
Oups. Sorry. I thought releases were automaticaly published

**Comment by ChristophWurst** [comment] 2020-12-02 12:37
I'm the automatism that publishes :P

**Comment by doc75** [comment] 2020-12-02 18:35
@ChristophWurst gald you find how to fix.
Too bad that the version compatible with NC19 is not getting the fix as far as I saw (1.4 branch did not get the fix) ;-(

**Comment by ChristophWurst** [comment] 2020-12-02 18:39
yeah, I haven't totally given up on that but somehow the CI pipeline for the stable1.4 branch broke. If I get it working again I can look into a release for that as well. But since we're moving rather quickly at the moment and add lots of features the backporting effort is high, hence I'm putting more focus on the new releases. Sorry for that, we'll do better once everything stabilized a bit again.

**Comment by cdehe7519** [comment] 2020-12-02 19:31
An update was available today. Was applied. Its now working fine for me. Thanks.

**Comment by johanneshorak** [comment] 2020-12-02 19:44
Updated the mail app to 1.7.1 and the bug appears to be gone now! I just did some small tests the previously resulted in the described problem (e.g. replying to a mail, writing something and backspacing a couple of times while doing so for good measure).

I'll report back should it stop working or in case I did not trigger the bug that way (even though this behaviour did before).

Thanks for the fix!

**Comment by joober** [comment] 2020-12-08 10:35
Received the update to 1.4.2. this morning. It appears this issue is not fully resolved (for me anyway).
Everything works fine, drafts saved, Enter key, etc. until I press the Backspace key once. 
It then throws this error :

Uncaught CKEditorError: a is undefined
    <anonymous> VueJS
    value range.js:348
    value deletecommand.js:107
    value model.js:805
    value model.js:231
    value deletecommand.js:76
    decorate observablemixin.js:255
    fire emittermixin.js:209
    e observablemixin.js:259
    value commandcollection.js:68
    value editor.js:288
    value delete.js:55
    fire emittermixin.js:209
    c deleteobserver.js:87
    u deleteobserver.js:50
    fire emittermixin.js:209
    value domeventobserver.js:96
    value keyobserver.js:28
    value domeventobserver.js:79
    fire emittermixin.js:209
    r emittermixin.js:235
mail.js:1:64080
    construct self-hosted:2653
    s mail.js:1
    r mail.js:1
    construct self-hosted:2653
    f mail.js:5
    d ckeditorerror.js:66
    value ckeditorerror.js:118
    value model.js:236
    value deletecommand.js:76
    decorate observablemixin.js:255
    fire emittermixin.js:209
    e observablemixin.js:259
    value commandcollection.js:68
    value editor.js:288
    value delete.js:55
    fire emittermixin.js:209
    c deleteobserver.js:87
    u deleteobserver.js:50
    fire emittermixin.js:209
    value domeventobserver.js:96
    value keyobserver.js:28
    value domeventobserver.js:79
    fire emittermixin.js:209
    r emittermixin.js:235

After that, I can input text still but input from Enter, Delete and Backspace is ignored.
