### ISSUE TITLE
Mail content cropped on big screens

### ISSUE THREAD

**Issue by bitsandnumbers** [nextcloud/mail#2455] opened 2020-01-10 08:47 UTC
### Expected behavior
The content should take the whole screen.
Or the mails list should be larger (<--- most needed !)

### Actual behavior
The content is cropped with scollbars.
(screenshot provided) --- I have "checkerboxed" the empty spaces
![Capture Nextcloud Mail](https://user-images.githubusercontent.com/3384570/72138896-aaf3e900-3385-11ea-94a1-167030af2bf5.png)

### Mail app

**Mail app version:** 0.21.1

**Mailserver or service:** Not relevant

### Server configuration

**Operating system**: Ubuntu (Official Nextcloud Docker Container : nextcloud:17.0.2-fpm)

**Web server:** (e.g. Apache, Nginx,...) Nginx

**Database:** PostgreSQL

**PHP version:** (e.g. 7.0) 7.3.13

**Nextcloud Version:**  17.0.2

#### Client configuration
**Browser:** Icecat 68.3 but bug also on Firefox 72.0.1

**Operating system:** Manjaro

**Comment by ChristophWurst** [comment] 2020-01-10 09:25
Duplicate of https://github.com/nextcloud/mail/issues/2449 :)

**Closed by ChristophWurst** 2020-01-10 09:25 UTC
Labels: 0. to triage, bug

**Comment by bitsandnumbers** [comment] 2020-01-10 09:41
> Duplicate of #2449 :)

Oups, sorry. I think I should have searched also in the "closed" issues :/

**Comment by ChristophWurst** [comment] 2020-01-10 09:54
No worries :)
