### ISSUE TITLE
Empty message in message list

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/mail#6527] opened 2022-05-23 07:08 UTC
### Steps to reproduce

No idea, just opened the mail app this morning, the sender is not different that many other of my emails (zammad). Refreshing the page doesn't help

### Expected behavior

Display email subject and sender

### Actual behavior

![image](https://user-images.githubusercontent.com/23653902/169762630-5627685e-36f9-4d06-9e11-3e3ee4a27f93.png)

But opening the email works as expected

If this helps: the ids of the emails with the bug are 3085033, 3085034, 3085035, 3085036 3085037 on cloud.nextcloud.com

### Mail app version

latest

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

**Comment by mcking230** [comment] 2022-07-22 08:18
![Снимок экрана от 2022-07-22 11-17-57](https://user-images.githubusercontent.com/37830492/180395886-d8f80224-3b84-4b81-be86-9f4d9ed1915e.png)

**Comment by husten1997** [comment] 2022-07-25 17:48
Also encountered this bug. E-Mail host is strato with imap protocol and a shared inbox with several users.

**Comment by vFabse91** [comment] 2022-07-26 09:57
Same problem for sended mails
![grafik](https://user-images.githubusercontent.com/61843487/180979143-cc0d6fb3-4848-47c2-9b07-e9f9e5b1ef86.png)

**Comment by ossconsulting** [comment] 2022-07-26 11:58
Same here. The messages are completely empty and actually do not seem to exist in the IMAP server.
<img width="528" alt="Screenshot 2022-07-26 at 13 56 53" src="https://user-images.githubusercontent.com/61664935/181000541-6710c49a-56df-47ed-80a8-2fb54aea59ea.png">

**Comment by zullinux** [comment] 2022-08-04 17:39
Same problem here.

Seems to apply to email already present in INBOX.

Other folders work correctly.

**Comment by miaulalala** [comment] 2022-08-04 19:29
ad we have some more information and a linked pr in the other ticket I'm closing this

Duplicate of #6938 6938

**Closed by miaulalala** 2022-08-04 19:29 UTC
Labels: bug, 0. to triage, regression
