### ISSUE TITLE
Unable to add email.cz account, status code 500

### ISSUE THREAD

**Issue by t0mashunter** [nextcloud/mail#4808] opened 2021-03-23 10:37 UTC
### Expected behavior
Adding email account.

### Actual behavior
While adding email.cz mailbox I get status code 500, and when I click again on mail I get Internal server error - I am attaching pictures also with log.

I found a temporary fix [link,](https://github.com/nextcloud/mail/issues/2105#issuecomment-739408194) but now folder mapping is not working properly (Inbox is not mapped as inbox, but it is named INBOX - and is showed as regular folder) and after update i have to fix it again.

I am adding some pictures and logs as attachments. 
[log.log](https://github.com/nextcloud/mail/files/6188765/log.log)
I was hoping for something more permanent, preferably from developers.

### Mail app

**Mail app version:1.9.3

**Mailserver or service: email.cz (e.g. Outlook, Yahoo, Gmail, Exchange,...)

### Server configuration

**Operating system**: Debian 8

**Web server: Apache

**Database: MariaDB

**PHP version: 7.4.16

**Nextcloud Version: 21.0.0

#### Client configuration
**Browser: Chrome 89

**Operating system: Windows 10 20H2

##Attachments

![log in](https://user-images.githubusercontent.com/81227618/112130607-f2504900-8bc8-11eb-9300-a0414a0bc0b3.PNG)
![internal server error](https://user-images.githubusercontent.com/81227618/112130611-f2e8df80-8bc8-11eb-9cf0-11630be0321f.PNG)

**Comment by ChristophWurst** [comment] 2021-03-23 11:38
so this is a duplicate of #2105? can we just continue there?

we still need someone who has time to look into a proper fix

**Comment by t0mashunter** [comment] 2021-03-23 12:07
I was not sure it was completely same issue, i didn't have any problems with ssl, now i see that it looks the same.
Should I close this thread then?

**Closed** 2021-03-23 12:09 UTC
Labels: 0. to triage, bug
