### ISSUE TITLE
Cannot move mail to folder

### ISSUE THREAD

**Issue by Inixi** [nextcloud/mail#2804] opened 2020-03-27 19:30 UTC
### Expected behavior
I should be able to move mail or conversation from inbox to folder

### Actual behavior
There is no button nor drag and drop option or at least I am not able to figure it out.
When I am trying to drag and drop - nothing happens. I does not matter which browser Iam using. No errors in JS console either.

### Mail app

**Mail app version:** 1.1.4

**Mailserver or service:** not relevant

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 18.0.2

#### Client configuration
**Browser:** Chromium 80.0.3987.132, Firefox 74.0

**Operating system:** All systems

**Comment by ChristophWurst** [comment] 2020-03-30 10:16
Duplicate of https://github.com/nextcloud/mail/issues/1538

**Closed by ChristophWurst** 2020-03-30 10:16 UTC
Labels: 0. to triage, bug
