### ISSUE TITLE
Add Folders

### ISSUE THREAD

**Issue by ArchdukeNavaron** [nextcloud/mail#935] opened 2018-06-09 10:34 UTC
Hi,
it would be great, if you could add folders to your mailbox.
As far as I saw, it's just possible to list all available folders but not to create new ones.

**Comment by ChristophWurst** [comment] 2018-06-18 09:32
Yes, that would be a great enhancement.

Btw, I'm curious why you didn't use the template for feature requests? Did you see the issue template chooser at https://github.com/nextcloud/mail/issues/new/choose? I'd like to gain some feedback on why people choose to ignore it. Your ticket is fine as it is, I'm just trying to get more structure into our tickets :wink:

**Comment by ArchdukeNavaron** [comment] 2018-06-18 18:47
Sorry for not useing your template.
I am rather new to Github and just used the "New Issue" Button which didn't give me a choice, as it does now.

**Comment by ChristophWurst** [comment] 2018-06-19 05:07
No problem. Thank you for your feedback :)

**Comment by ChristophWurst** [comment] 2019-04-11 06:56
Duplicate of https://github.com/nextcloud/mail/issues/199

**Closed by ChristophWurst** 2019-04-11 06:56 UTC
Labels: 1. to develop, enhancement, feature parity

**Comment by pwepwe973** [comment] 2019-06-19 14:18
Hello
Yes, this is it planned in the future because it's been 1 year since this post has been posted and I face the same problem
cordially

**Comment by ChristophWurst** [comment] 2019-06-21 09:04
It's done and shipped https://github.com/nextcloud/mail/pull/1698
