### ISSUE TITLE
Add an option to disable marking messages automatically as read

### ISSUE THREAD

**Issue by Amain** [nextcloud/mail#7753] opened 2022-12-08 23:31 UTC
### Is your feature request related to a problem? Please describe.

When opening an e-mail, after a second or two, it automatically gets marked as read. I would like to decide by myself when I actually read through / am done with the e-mail. 

### Describe the solution you'd like

If time permits, I would appreciate an option to disable the automatic marking as read feature. For example an account level setting, user setting, global admin setting or global setting controlled via the CLI.

### Describe alternatives you've considered

I've looked around in the account, user and global settings and was not able to locate a setting that would disable the auto mark as read.

**Comment by jbernal-ej2sistemas** [comment] 2023-04-20 18:48
I think that it will useful that you can config the time for mark as read the message.

**Comment by ferdiga** [comment] 2023-12-08 05:21
would be very useful!
mark read: config the delay in seconds - and allow "never"
FYI: currently I use the mail app (only) as a mail storage to allow searching in files and mails in ONE place, which works fine.
In an high volume environment it's very risky to have a quick look at a mail, get disturbed by something and forget to mark the mail unread. So I use Thunderbird and Bluemail with automatic mark as read turned off.

**Comment by piratPavel** [comment] 2024-04-02 08:07
lately (a month ago) it happens to me that opening nextcloud on the mail app means marking all messages as read - quite an unpleasant experience. I haven't figured out how or where to change it yet. 
Any tip wouldn't be ?

**Comment by ChristophWurst** [comment] 2024-10-16 12:53
Duplicate of https://github.com/nextcloud/mail/issues/6390. There are options to make the feature opt-in as admins, and for users to opt-out/in.

**Closed by ChristophWurst** 2024-10-16 12:53 UTC
Labels: enhancement, 1. to develop
