### ISSUE TITLE
Enhancement proposal: Show only subfolder names

### ISSUE THREAD

**Issue by Shorty365** [nextcloud/mail#642] opened 2017-11-28 13:18 UTC
### Steps to reproduce
1. Open Inbox in Mail client to see subfolders
2. Subfolders show in a way like "Inbox.xxxxxx" end "Inbox.yyyyyyy"
3.

### Expected behaviour
It would be nicer to show only the actual name of the subfolder instead the subfolder with a prefix.

### Actual behaviour
The subfolders show with a prefix containing teh techical name of the parent folder

Mail app

**Mail app version: 0.7.5 (see apps admin page)

**Mailserver or service: Dovecot 2.2.22 on Ubuntu 16.04

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**Mail app version build date:** (only if you are using a Nightly Build)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server: Apache 2.4.18

**Database: Mysql 5.7.20

**PHP version: 7.0.22

**Version:** (see admin page)

**Updated from an older version or fresh install: Updated

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by ChristophWurst** [comment] 2017-11-28 13:24
Hi,

thanks for reporting. This is actually a duplicate of #185.

Thanks

**Closed by ChristophWurst** 2017-11-28 13:24 UTC

**Comment by slideup-benni** [comment] 2017-12-12 13:43
i have the same problem as described here. I'm using the latest version of this app (0.7.6).
I think issue #185 is not fixed.

**Comment by ChristophWurst** [comment] 2017-12-12 13:51
> I think issue #185 is not fixed.

See https://github.com/nextcloud/mail/pull/652.

This ticket is unrelated.
