### ISSUE TITLE
Sending E-Mail from mobile device not possible

### ISSUE THREAD

**Issue by Cijay22** [nextcloud/mail#10021] opened 2024-08-20 08:02 UTC
### Steps to reproduce

1. Install the latest mail client 
2. Open the nextcloud on mobile device and create a new email 
3. Try to enter receiver, subject and mail content
4. You will notice that the field are not reacting and entering data is not possible 
5. Testet with android and apple device (chrome, firefox and safari)

### Expected behavior

Sending email from mobile device should be possible

### Actual behavior

Field are not reacting for entering data

### Mail app version

3.7.7

### Mailserver or service

Postfix 3.6.4 - Dovecot 2.3.16

### Operating system

Ubuntu 22

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database

MariaDB

**Comment by Cijay22** [comment] 2024-08-20 08:14
I have switched to the old releases and it seems to be after version 3.7.5 it stop working on mobile devices

**Comment by ChristophWurst** [comment] 2024-08-20 08:17
https://github.com/nextcloud/mail/compare/v3.7.5...v3.7.7

**Comment by ChristophWurst** [comment] 2024-08-20 10:51
I can confirm. With Nextcloud 28 and Mail 3.7 it's not possible to focus any inputs of the composer modal. Click events work. This could be an issue with the focus trap library.
Nextcloud 30 and Mail 4 are not affected.

**Comment by ChristophWurst** [comment] 2024-08-20 10:54
@GretaD @st3iny could one of you take this? I consider this a critical regression because you can't write email I'm this state.

**Comment by st3iny** [comment] 2024-08-28 11:11
Was able to reproduce this on stable3.7. It is fixed on main.

**Comment by st3iny** [comment] 2024-08-28 11:29
Minor correction: It is broken on `v3.7.7` and fixed on `stable3.7`. I tried again without caching to make sure.

So a new release will fix the issue

(Tested on Chrome on Android)

**Closed by st3iny** 2024-08-28 11:29 UTC
Labels: bug, 2. developing, regression
