### ISSUE TITLE
Potential bug disabling automatic marking of mails as important

### ISSUE THREAD

**Issue by jpschewe** [nextcloud/mail#5295] opened 2021-07-08 10:49 UTC
### Expected behavior
Tell us what should happen

Unchecking the box "Automatically classify importance of new email" should stop nextcloud mail from automatically labeling messages with the Important label.

### Actual behavior
Tell us what happens instead

After unchecking the box, messages are still being marked as important.

Am I misunderstanding what this checkbox is controlling?

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.10.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
IMAP server on host running nextcloud

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
PostgreSQL

**PHP version:** (e.g. 7.0)
7.4.3

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
21.0.3

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 89.0.2

**Operating system:** (e.g. Arch Linux)
Ubuntu Linux 20.04

**Comment by ChristophWurst** [comment] 2021-07-08 12:58
Duplicate of https://github.com/nextcloud/mail/issues/5290 :)

**Closed by ChristophWurst** 2021-07-08 12:58 UTC
Labels: 0. to triage, bug
