### ISSUE TITLE
Configured Signature isn't append to a new eMail

### ISSUE THREAD

**Issue by Troubardix20** [nextcloud/mail#6632] opened 2022-06-02 14:04 UTC
### Steps to reproduce

1. Open eMail-App account-properties "Signature"
2. Insert a Signature Text and Save
3. Create a new eMail and send it to any recipient (it doesn't matter if used "Text" or "Rich-Text" for body of the eMail)

### Expected behavior

The configured Signature should be append at the end of the Body of the eMail

### Actual behavior

No Signature is append

### Mail app version

1.13.0

### Mailserver or service

Postfix/Dovecot

### Operating system

Ubuntu 20.04LTS

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database

MariaDB

**Comment by ChristophWurst** [comment] 2022-06-02 14:39
Duplicate of https://github.com/nextcloud/mail/issues/6361. We are working on a fix :pray:

**Closed by ChristophWurst** 2022-06-02 14:39 UTC
Labels: bug, 0. to triage
