### ISSUE TITLE
Memory exhausted during cron job while sorting ids

### ISSUE THREAD

**Issue by luizluca** [nextcloud/mail#7445] opened 2022-10-17 17:42 UTC
### Steps to reproduce

1. Use a large mailbox
2. Let cronjob run

### Expected behavior

3. It should work

### Actual behavior

3. It crashes while sorting messages ids at https://github.com/horde/Imap_Client/blob/0e1173f7e3e680a42fef8c44e1f4fe3e48d407c9/lib/Horde/Imap/Client/Ids.php#L241

### Mail app version

1.14.1

### Mailserver or service

Zimbra

### Operating system

SLES15SP4

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

I have already increased memory to 512MBytes but it looks like it is still not enough. I'm still getting this error with no extra info about which mailbox exactly triggered it:

```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 33554440 bytes) in /srv/www/htdocs/nextcloud/apps_extras/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Ids.php on line 241
```

It looks like it is an external library used by nextcloud mail app. Anyway, it is affecting nextcloud. I don't know if it is the sort that is exhausting the memory of it is just the last drop of memory allocation that triggered the OOM. At least nextcould should give a better hint about what failed, like which user/mailbox/folder is failling.

**Comment by ChristophWurst** [comment] 2022-10-17 18:22
Sounds like a duplicate of https://github.com/nextcloud/mail/issues/6887.

> At least nextcould should give a better hint about what failed, like which user/mailbox/folder is failling.

Sure sure, except that it's not possible to recover from these errors.

**Comment by luizluca** [comment] 2022-10-17 18:37
> Sounds like a duplicate of #6887.

I checked it before submitting but it was at a different object.

> > At least nextcould should give a better hint about what failed, like which user/mailbox/folder is failling.
> 
> Sure sure, except that it's not possible to recover from these errors.

It feels strange for a id sort (normally integer numbers) to exhaust memory. It looks like a bug because it was failing at the same place with much less memory (4 times less). Maybe it was failing before with less memory already with a smaller folder and now it is failing with a much larger one. I could find out that easily if the error could show some context about what it was doing.

**Comment by ChristophWurst** [comment] 2024-07-01 14:39
The situation should be better with https://github.com/nextcloud/mail/pull/9581

**Closed by ChristophWurst** 2024-07-01 14:39 UTC
Labels: bug, 0. to triage

**Comment by ChristophWurst** [comment] 2025-03-18 15:12
https://github.com/nextcloud/mail/pull/10696 will help to. Today I learned that the horde IDs object contains all UIDs passed for ranges. If you tell if `1:3` it contains 1, 2 and 3. If you tell it `1:10000000` you have  a problem.
