### ISSUE TITLE
PHP Error: Undefined index: HEADER.FIELDS 

### ISSUE THREAD

**Issue by Arjoni** [nextcloud/mail#762] opened 2018-02-06 15:49 UTC
### Steps to reproduce
1. Open email app and add an account
2. Refresh

It should work as expected and it does. But I see this error at Nextcloud logs repeated too many times:

Error | PHP | Undefined  index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at  /var/www/cloud.domain.com/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#3208

### Mail app

**Mail app version:** (see apps admin page)
0.7.9

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Yandex, Gmail

**Number of accounts:**
2

### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:**  Nginx

**Database:** MariaDB

**PHP version:** PHP7

**Version:** (see admin page) 7.0.27

**Updated from an older version or fresh install:** Updated from RC4

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - deck: 0.3.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.2
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.2.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.0.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - unsplash: 1.0.5
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - announcementcenter
  - encryption
  - external
  - ojsxc
  - sharerenamer
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

<details>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "maintenance": false,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```

#### Client configuration
**Browser:** Firefox 59.0b6 

**Operating system:** Windows 10

##### Web server error log
```
2018/02/06 10:03:17 [error] 1220#0: *271210 access forbidden by rule, client:MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517907797164 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 10:03:20 [error] 1220#0: *271210 access forbidden by rule, client:MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517907800646 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 10:03:23 [error] 1220#0: *271210 access forbidden by rule, client:MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517907803799 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 10:03:27 [error] 1220#0: *271210 access forbidden by rule, client:MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517907806819 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 10:03:30 [error] 1220#0: *271210 access forbidden by rule, client:MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517907810209 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 12:10:51 [error] 1221#0: *272545 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 79.106.163.195, server: cloud.domain.com, request: "GET /apps/mail/api/accounts/1/folders/SU5CT1g%3D/messages?ids=3040%2C3039%2C3038%2C3035%2C3031%2C3030%2C3029%2C3025%2C3023 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock", host: "cloud.domain.com"
2018/02/06 13:56:37 [error] 1229#0: *273888 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517921798129 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 13:56:41 [error] 1229#0: *273888 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517921802134 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 13:57:52 [error] 1229#0: *273888 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517921872587 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 13:57:57 [error] 1229#0: *273888 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517921878051 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 14:38:46 [error] 1224#0: *274912 upstream timed out (110: Connection timed out) while reading response header from upstream, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /apps/mail/api/accounts/1/folders/SU5CT1g%3D/sync?syncToken=VTMwNDgsVjE0NTg5MTc4MjQsTTEwMjI%3D&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985&uids%5B%5D=2978 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock", host: "cloud.domain.com"
2018/02/06 15:41:47 [error] 1229#0: *275636 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 193.24.32.42, server: cloud.domain.com, request: "GET /apps/mail/api/accounts/1/folders/SU5CT1g%3D/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock", host: "cloud.domain.com"
2018/02/06 16:19:17 [error] 1229#0: *275953 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517930358005 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 16:19:20 [error] 1229#0: *275953 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517930361717 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 16:23:17 [error] 1229#0: *275953 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517930598224 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 16:23:21 [error] 1229#0: *275953 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517930601985 HTTP/2.0", host: "cloud.domain.com"
2018/02/06 16:23:25 [error] 1229#0: *275953 access forbidden by rule, client: MY-HIDDEN-IP, server: cloud.domain.com, request: "GET /data/.ocdata?t=1517930606564 HTTP/2.0", host: "cloud.domain.com"
```

##### Server log (data/nextcloud.log)
<details>
```
{"reqId":"32PmtzFn2bfoLvcNwRBH","level":3,"time":"2018-02-06T15:25:11+00:00","remoteAddr":"MY-HIDDEN-IP","user":"Dave","app":"PHP","method":"GET","url":"\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud.domain.com\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}
{"reqId":"32PmtzFn2bfoLvcNwRBH","level":3,"time":"2018-02-06T15:25:11+00:00","remoteAddr":"MY-HIDDEN-IP","user":"Dave","app":"PHP","method":"GET","url":"\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud.domain.com\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}
{"reqId":"32PmtzFn2bfoLvcNwRBH","level":3,"time":"2018-02-06T15:25:11+00:00","remoteAddr":"MY-HIDDEN-IP","user":"Dave","app":"PHP","method":"GET","url":"\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud.domain.com\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}
{"reqId":"32PmtzFn2bfoLvcNwRBH","level":3,"time":"2018-02-06T15:25:11+00:00","remoteAddr":"MY-HIDDEN-IP","user":"Dave","app":"PHP","method":"GET","url":"\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud.domain.com\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}
{"reqId":"32PmtzFn2bfoLvcNwRBH","level":3,"time":"2018-02-06T15:25:11+00:00","remoteAddr":"MY-HIDDEN-IP","user":"Dave","app":"PHP","method":"GET","url":"\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud.domain.com\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}
{"reqId":"32PmtzFn2bfoLvcNwRBH","level":3,"time":"2018-02-06T15:25:11+00:00","remoteAddr":"MY-HIDDEN-IP","user":"Dave","app":"PHP","method":"GET","url":"\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud.domain.com\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}
{"reqId":"32PmtzFn2bfoLvcNwRBH","level":3,"time":"2018-02-06T15:25:11+00:00","remoteAddr":"MY-HIDDEN-IP","user":"Dave","app":"PHP","method":"GET","url":"\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/sync?syncToken=VTMwNDksVjE0NTg5MTc4MjQsTTEwMjM%3D&uids%5B%5D=3048&uids%5B%5D=3040&uids%5B%5D=3039&uids%5B%5D=3038&uids%5B%5D=3035&uids%5B%5D=3031&uids%5B%5D=3030&uids%5B%5D=3029&uids%5B%5D=3025&uids%5B%5D=3023&uids%5B%5D=3012&uids%5B%5D=3003&uids%5B%5D=3001&uids%5B%5D=2998&uids%5B%5D=2996&uids%5B%5D=2993&uids%5B%5D=2991&uids%5B%5D=2989&uids%5B%5D=2988&uids%5B%5D=2985","message":"Undefined index: HEADER.FIELDS (CONTENT-TYPE X-PRIORITY LIST-POST IMPORTANCE) at \/var\/www\/cloud.domain.com\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#3208","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.0.14"}

```
</details>

##### IMAP log (data/horde_imap.log)
<details>
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```
Not present, enable debug-mode. 
```
Enable debug mode and insert your horde IMAP log here, see https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html#debug-mode
```
</details>

##### Browser log
<details>
```
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data Resource URL: https://cloud.domain.com/core/vendor/core.js?v=fd5267d9-24 Source Map URL: purify.min.js.map[Learn More]
```
</details>

**Comment by ChristophWurst** [comment] 2018-02-07 20:37
Duplicate of https://github.com/nextcloud/mail/issues/433

**Closed by ChristophWurst** 2018-02-07 20:37 UTC
