### ISSUE TITLE
Sort order mixed up - neither ASC nor DESC

### ISSUE THREAD

**Issue by ghost** [nextcloud/mail#470] opened 2017-08-26 10:35 UTC
### Steps to reproduce
1. login to NC and switch to Mail
2. expand the Inbox
3. order is mixed up

![grafik](https://user-images.githubusercontent.com/20593693/29740722-2e600208-8a5d-11e7-9718-4479c823056f.png)
 
![grafik](https://user-images.githubusercontent.com/20593693/29740523-a10abe4c-8a58-11e7-89d8-d182a11db345.png)

### Expected behaviour
Sort order should look like:
![grafik](https://user-images.githubusercontent.com/20593693/29740511-694e1b48-8a58-11e7-9ce7-603192d9620b.png)

### Actual behaviour
Sort order is mixed up in subfolders

### Mail app

**Mail app version:** 0.7.0

**Mailserver or service:** all-inkl.com || kasserver.com

**Transport security - IMAP:** STARTTLS /143

**Transport security - SMTP:** STARTTLS / 587

**Number of accounts:** 1 active

### Server configuration
**Operating system**: Ubuntu 16.0.3 LTS x64

**Web server:** nginx 1.13.4

**Database:** 10.0.31-MariaDB

**PHP version:** 7.1.8

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**
root@nc:-# sudo -u www-data php /var/www/nextcloud/occ app:list
Enabled:
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_clipboard: 0.6.4
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - rainloop: 5.0.1
  - sharebymail: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - comments
  - encryption
  - federation
  - files_external
  - files_versions
  - firstrunwizard
  - serverinfo
  - survey_client
  - systemtags
  - twofactor_totp
  - user_external
  - user_ldap

**The content of config/config.php:**
root@nc:-# sudo -u www-data php /var/www/nextcloud/occ config:list system
{
    "system": {
        "instanceid": "oc84hxlnpsu0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xyz.c-rieger.de",
            "192.168.2.117"
        ],
        "datadirectory": "\/ncdata",
        "overwrite.cli.url": "https:\/\/xyz.c-rieger.de",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "xyz_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "log_rotate_size": 104857600,
        "cron_log": true,
        "filesystem_check_changes": 1,
        "quota_include_external_storage": false,
        "knowledgebaseenabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "theme": "",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "mail_from_address": "xyz",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "c-rieger.de",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "xyz.kasserver.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

#### Client configuration
**Browser:** Firefox 55.03 x64 / Microsoft Edge

**Operating system:**
W10 Prof / Ubuntu 16.04.3 LTS XENIAL x64

**Comment by jancborchardt** [comment] 2020-02-26 10:07
This seems to be fixed by now to be alphabetical, at least I can not reproduce this anymore.

**Closed by jancborchardt** 2020-02-26 10:07 UTC
Labels: 1. to develop, enhancement
