### ISSUE TITLE
Mail body IFrame only 150px height on Chrome 86

### ISSUE THREAD

**Issue by mosenturm** [nextcloud/mail#3791] opened 2020-10-12 08:53 UTC
### Actual behavior
The IFrame height for display the mail body is only 150px on Chrome 86. On Firefox the height seems ok.

### Mail app

**Mail app version:** 1.5.0

**Mailserver or service:** own Mailserver

### Server configuration

**Nextcloud Version:** 20.0

#### Client configuration
**Browser:** Chrome 86

**Operating system:** Ubuntu 20.4

**Comment by ChristophWurst** [comment] 2020-10-12 09:50
Likely a duplicate of https://github.com/nextcloud/mail/issues/3696

**Closed by ChristophWurst** 2020-10-12 09:50 UTC
Labels: 0. to triage, bug
