### ISSUE TITLE
Nextcloud label support

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/mail#2426] opened 2019-12-30 09:12 UTC
### Feature Request

As mail is part of Nextcloud it would be very nice to have Label support.

#### Summary

The idea is that you have an project specific label and when you select this label all labeled folders, files, but also the related mail folder an related mail, ... will be shown at one place.

**Comment by ChristophWurst** [comment] 2020-01-07 12:32
What's the connection between files in Nextcloud and label on IMAP messages? Just a simple match on the name?

IIRC labels on IMAP are not always supported but depend on the IMAP implementation.

**Comment by sunjam** [comment] 2020-04-28 15:18
Are labels the same thing as [tags](https://github.com/nextcloud/server/issues/13330) in this case?

**Comment by DarkknightAK** [comment] 2020-04-28 15:36
Yes tags support is the idea

**Comment by sunjam** [comment] 2020-04-28 15:39
Cool, would you mind updating the title.  This would be a great addition as things progress.

**Comment by ChristophWurst** [comment] 2020-04-28 17:36
> What's the connection between files in Nextcloud and label on IMAP messages? Just a simple match on the name?
> 
> IIRC labels on IMAP are not always supported but depend on the IMAP implementation.

so?

**Comment by sunjam** [comment] 2020-10-31 06:15
Perhaps this request would relate to Project support.

**Comment by wiswedel** [comment] 2020-12-16 10:49
Is this a duplicate of https://github.com/nextcloud/mail/issues/25?

**Comment by sunjam** [comment] 2020-12-16 17:11
Yes, seems this labels / tags request is a duplicate

**Closed** 2020-12-16 18:25 UTC
Labels: 0. to triage, enhancement
