### ISSUE TITLE
Mail can't connect when user has no permission on one of the folders

### ISSUE THREAD

**Issue by pagaille** [nextcloud/mail#1730] opened 2019-05-04 12:53 UTC
When connecting to a mailbox, on a NethServer managed Centos 7 / Dovecot imap server with Shared Mailbox enabled, the client can't connect and fails with You do not have adequate permissions to carry out this operation.

It turned out that for whatever reason the `Public Folder` containing the shared mailboxes is not accessible to anyone; only its subfolder are. 

Here is the IMAP log : 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/1886799/57179232-bea49280-6e7b-11e9-8dca-ccc81bda6f61.png">

And here is the folder structure :

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1886799/57179253-f6133f00-6e7b-11e9-9a24-e1f1de9762d2.png">

Opening the `Public` folder is not permitted. Opening `Public/Test` is ok. That case should be handled.

### Mail app

**Mail app version:** 0.11.1

**Mailserver or service:** Dovecot 2.2.36

**Comment by ChristophWurst** [comment] 2019-05-06 06:22
> **Mail app version:** 0.11.1

v0.14.0 is the latest version. Since 0.11.x a lot of fixes have been merged, so this might be fixed already. Please try again with the latest version. If that is still a bug, please file a ticket following the *full* [issue template](https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=).

**Closed by ChristophWurst** 2019-05-06 06:22 UTC
Labels: 0. to triage, bug

**Comment by pagaille** [comment] 2019-05-06 07:30
Sorry I installed the latest available version through the UI. I'll test again.

**Comment by ChristophWurst** [comment] 2019-05-06 07:36
No worries. If you're on an older version of Nextcloud 0.11 might be the latest version. For 15 it's 0.12.x and anything newer requires Nextcloud 16.

**Comment by pagaille** [comment] 2019-05-06 07:39
Indeed I'm running NC 15. Will update a report back if needed.

**Comment by matejak** [comment] 2020-09-24 20:35
Duplicate of #1735
