### ISSUE TITLE
Incorrect behaviour of Mail app in case messahes are movedy by external IMAP client

### ISSUE THREAD

**Issue by ratermir** [nextcloud/mail#10034] opened 2024-08-21 10:26 UTC
### Steps to reproduce

Behaviour of the Nextcloud mail app in case of mails moved by external IMAP application (like Snappy mail or Roundcube)  to different folder is incorrect. Mails, that were moved from the "root" folder (aka "Incomming mails") using other SMNP tool 
- stay still visible in the mail list. 
- if I click to the message in the list, I get message "Not found" as a mail body (see image)
- if I try to delete such message (which don't exist in reality), I get message "Cannot delete the mail", it disapears from the list but agter refresh it is visible again 
- when I move such message to any folder, the behaviour is as it was deleted

Such mails are visible in the target folder (where there were moved by different IMAP client - which is OK), also mails deleted the same way are not visible in the list (which also correct). The incorrect behaviour was observes only by moved mails.

### Expected behavior

messages are visible only in the target folder 

### Actual behavior

messages are visible in the list of original folder

### Mail app version

3.7.7

### Mailserver or service

mailu (self-hosted)

### Operating system

docker installation on OpenSuSE 15.6 

### PHP engine version

None

### Web server

Nginx

### Database

PostgreSQL

**Comment by ChristophWurst** [comment] 2024-08-21 10:27
Very well observed. Duplicate of https://github.com/nextcloud/mail/issues/9168

**Closed by ChristophWurst** 2024-08-21 10:27 UTC
Labels: bug, 0. to triage
