### ISSUE TITLE
Signature written in HTML code

### ISSUE THREAD

**Issue by m1l4n89** [nextcloud/mail#5356] opened 2021-07-21 14:39 UTC
In work we use a signature written in HTML. Where the font style, size and color are set. We have also the company logo in the signature. Would it be possible to add HTML support?

Thank you in advance for your reply

**Comment by ChristophWurst** [comment] 2021-07-26 08:16
duplicate of https://github.com/nextcloud/mail/issues/4707

**Closed by ChristophWurst** 2021-07-26 08:16 UTC
Labels: 0. to triage, enhancement
