### ISSUE TITLE
Account Configuration/Creation with LDAP Backend

### ISSUE THREAD

**Issue by juliusstoerrle** [nextcloud/mail#858] opened 2018-03-28 14:54 UTC
Currently it is possible to use the users log-in credentials as the mail server (if it has the same credentials).
We use LDAP for our user management, but our mail server is separate and has its own password. 
Is there a possibility to pull some configuration (like the password) from the LDAP User Back-end and add it as an account?

Another use-case similiar is that I might have a mail box a specific group has access to and it would be great to automatically add this as a seccond mailbox to the users accounts

At least it would be nice if we can supply all the configuration and the user has to only enter the password.

Happy to do some coding, but someone will need to tell me what the best way/starting point to solve this is :)

**Comment by ChristophWurst** [comment] 2018-03-28 15:07
> At least it would be nice if we can supply all the configuration and the user has to only enter the password

Duplicate of https://github.com/nextcloud/mail/issues/849 :wink: 

> Currently it is possible to use the users log-in credentials as the mail server (if it has the same credentials).
> We use LDAP for our user management, but our mail server is separate and has its own password.
> Is there a possibility to pull some configuration (like the password) from the LDAP User Back-end and add it as an account?

IMO sounds like a very specific setup, so it's unlikely that we'd have such an integration with LDAP and the user back-ends. But since this is open source you're of course free to just change the code to support that.

> Happy to do some coding, but someone will need to tell me what the best way/starting point to solve this is :)

Awesome! However, I don' think we would integrate such a specific feature because those are hard to setup up and test and therefore developers forget about them and they break unexpectedly. We try to focus on those features that benefit all users first. I hope that makes sense.

cc @nextcloud/mail

**Closed** 2018-03-28 15:07 UTC

**Comment by juliusstoerrle** [comment] 2018-03-28 15:15
Oh yep, your right. I just searched by "LDAP" should have looked a bit more :)

>  We try to focus on those features that benefit all users first. I hope that makes sense.
Yep sure makes sense, in the long run we should just get a new mail server anyway...

Also related to https://github.com/nextcloud/mail/issues/572

**Comment by ChristophWurst** [comment] 2018-03-28 15:22
> Also related to #572

Correct. Forgot about that one :wink: 

So if you're interested in helping with #849, #572 or any other issue let me know!

**Comment by ChristophWurst** [comment] 2018-04-03 08:48
> If not specified this will default to true (the current behavior); i set to false the user will be prompted the "Create Account" Page on initial opening of the app, but all other fields will be prefilled

Sounds good. There should be a flag in the accounts table so that configurations is pulled from config.php instead of a once-initialized one to make it possible for admins to e.g. change the mail server name.

**Comment by rasos** [comment] 2018-09-29 12:01
We would even like to see a combination of both options described by @juliusstoerrle plus the function of the `Auto Mail Accounts` App : Allow to specify an array of servers, with the domain as key, AND adding for each     
    'useLoginPassword' => true
AND store them in the `oc_mail_accounts` table (to make them a full featured account, allowing to set aliases etc).
When `useLoginPassword` is set to false, the user is prompted once for the password, which is then stored in `oc_mail_accounts`.

This would then also cover password-less nextcloud authentication mechanisms, see our use case description https://github.com/nextcloud/mail/issues/849#issuecomment-425626110
