### ISSUE TITLE
Paste or copy several e-mail addresses into address fields at once

### ISSUE THREAD

**Issue by handkerchief333** [nextcloud/mail#9298] opened 2024-02-07 14:09 UTC
### Is your feature request related to a problem? Please describe.

It is currently not possible to paste or copy several e-mail addresses into address fields at once. Whether with comma separators or semicolons, nothing works. 

At the moment you can only add each e-mail address individually. To make matters worse, if you want to copy all the e-mail addresses entered from the address field again, this is not possible. Unfortunately, this is sometimes necessary because there is an error when sending and the draft is not sent. The only solution is to rewrite the message and you have to insert each e-mail address again individually.

### Describe the solution you'd like

When entering and editing e-mail messages, it should be possible to copy several e-mail addresses into the address field at once. The same applies to copying all email addresses out of address fields.

With Gmail, this is possible, for example, by copying addresses through commas or semicolons like this: example@test.com;example2@test.com

### Describe alternatives you've considered

Although it is possible to specify a group, the contacts must first be entered as such, which is quite tedious, especially as these e-mail addresses are not required as contacts.

**Comment by ChristophWurst** [comment] 2024-02-26 10:05
Duplicate of https://github.com/nextcloud/mail/issues/6013

**Closed by ChristophWurst** 2024-02-26 10:05 UTC
Labels: enhancement, 1. to develop
