### ISSUE TITLE
 Autocompletion in Version 0.11.0

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#1219] opened 2018-10-23 06:00 UTC
Hello, 

I installed the latest version and I'm wondering if the autocompletion is ok.

On my system: Users are not regognized as email receivers but all groups. 

Is this the desired behavior?

Thanks!

**Comment by ChristophWurst** [comment] 2018-10-23 06:03
Duplicate of #1215. Users were never autocompleted. There should be only

* Entries from your address book (contacts)
* Entries from your groups
* Entries from people you've contacted before

Ref https://github.com/nextcloud/mail/blob/ccdb94e3280cb585e91ba039132291977a560da5/lib/Service/AutoCompletion/AutoCompleteService.php#L49-L51.

I remember that we once had a privacy issue where the app would autocomplete all user's emails from the instance but that is often not desired because the instance is used by different entities which must not see each other.

**Closed by ChristophWurst** 2018-10-23 06:03 UTC

**Comment by ChristophWurst** [comment] 2018-10-23 06:05
-> https://github.com/nextcloud/mail/issues/848
