### ISSUE TITLE
Mail is not loading when logged in without a password

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/mail#5966] opened 2022-01-19 07:44 UTC
### Expected behavior
When i log in with my tomu usb key
And i go to the mail app
And i click a mail
I should see the mails content

### Actual behavior
Spinning wheel forever.

### Mail app

**Mail app version:** 1.11.0

**Mailserver or service:** nextcloud.com

### Server configuration

Current cloud.nextcloud.com
**Nextcloud Version:** 23.0.1rc1 (i guess)

#### Client configuration
**Browser:** Firefox 96 deb package

**Operating system:** Ubuntu 21.10

**Comment by miaulalala** [comment] 2022-01-19 10:36
The issue is that the password field is empty.

**Comment by miaulalala** [comment] 2022-01-26 11:07
Duplicate of #5933

**Closed by miaulalala** 2022-01-26 11:07 UTC
Labels: bug, 1. to develop
