### ISSUE TITLE
Could not resolve accountService! Class accountService does not exist

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#241] opened 2016-12-14 20:18 UTC
Occurs with latest master on both server and Mail app:
![capture du 2016-12-14 21-17-24](https://cloud.githubusercontent.com/assets/925062/21199199/c8b11e66-c242-11e6-8a44-fd4f523613cc.png)
Any idea @ChristophWurst? @LukasReschke can help if needed but we couldn’t find what the issue is so far.

**Comment by LukasReschke** [comment] 2016-12-14 20:25
Strange thing that works for me locally. 

@ChristophWurst That error is normally thrown when a class can't be autoresolved by the container… But I'm curious why this could happen here.

**Comment by ChristophWurst** [comment] 2016-12-14 21:30
Wild guess: duplicate of https://github.com/nextcloud/mail/issues/237?

**Comment by ChristophWurst** [comment] 2016-12-14 21:30
yup: https://github.com/nextcloud/server/pull/2665

**Closed** 2016-12-14 21:31 UTC
Labels: 1. to develop, bug
