### ISSUE TITLE
Problems to select attachement from files on the cloud

### ISSUE THREAD

**Issue by schmitzerwien** [nextcloud/mail#700] opened 2018-01-11 08:11 UTC
### Steps to reproduce
1. Login as normal user
2. Click on mail app (configured)
3. Click on new message
4. new message window appears on the right side
5. Select attachement from cloud files
6. Window with directorys and files appears
7. Select file (example pdf-file)
8. No possibility to select a file, window
9. No button to close the file window
10. no possibility to close the file window

### Mail app

**Mail app version:** (see apps admin page) 0.7.7

**Mailserver or service:** Normal hosting account

**Transport security - IMAP:** None)

**Transport security - SMTP:** None

**Number of accounts:** 1

**Mail app version build date:** 0.7.7

**Comment by ChristophWurst** [comment] 2018-01-11 08:37
Hi,

this is a duplicate of #626

**Closed by ChristophWurst** 2018-01-11 08:37 UTC
