### ISSUE TITLE
[0.18.0] Blank page after update

### ISSUE THREAD

**Issue by delete-exe** [nextcloud/mail#2205] opened 2019-10-29 10:40 UTC
Hi!

after updating to day to 0.18.0 the Mail App page is blank. I tried restarting the Ubuntu host system and different browsers, computers with cleared browser cache. This the same result.

![29-10-_2019_11-39-39](https://user-images.githubusercontent.com/38488241/67760153-13971f00-fa41-11e9-98be-406701ddde31.jpg)

After the update of NC to 17.0.0.9 the app worked fine until the update today. No errors in the logs.
Is it possible to roll back to the previous version to verify it's in the current update?

It's the only app that is not working at the moment of ca. 20 apps in use.

**Comment by ChristophWurst** [comment] 2019-10-29 11:04
Duplicate of #2204

**Closed by ChristophWurst** 2019-10-29 11:04 UTC
Labels: 0. to triage

**Comment by delete-exe** [comment] 2019-10-29 11:52
Why did you close this issue?
My problem is **not** solved by flushing the occ cache by restarting the server & webserver?

**Comment by ChristophWurst** [comment] 2019-10-29 12:20
If you open a real bug report ticket, I might be able to understand your problem. But not from the sparse info you gave. See https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=.
