### ISSUE TITLE
Font color in Dark Theme Mode

### ISSUE THREAD

**Issue by menaceone** [nextcloud/mail#1742] opened 2019-05-10 11:26 UTC
As stated in #1363 I open a seperate Issue for the font behaviour in Dark Theme mode:

### Expected behavior
Having Light Grey Font Color in Mails when Dark Theme is activated.

### Actual behavior
Black Font Color on Black Background.
![Black Font Color](https://user-images.githubusercontent.com/1039753/49704650-ed447700-fc15-11e8-98ba-4b047932f4ec.png)

### Mail app

**Mail app version:** 0.14.0

**Mailserver or service:** independent from server/service

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySql

**PHP version:** 7.3.5

**Nextcloud Version:** 16.0.0.9

#### Client configuration
**Browser:** Firefox 66

**Operating system:** Windows

**Comment by ChristophWurst** [comment] 2019-05-10 12:53
I think this is a task for our *Head of Dark Mode @skjnldsv*

**Comment by skjnldsv** [comment] 2019-05-10 20:21
I guess it can be overridden by the html in the mail itself? Otherwise using the css variable works as-is :)

**Comment by menaceone** [comment] 2019-05-13 08:07
You mean, every Mail declares it's own font color?

**Comment by skjnldsv** [comment] 2019-05-13 08:39
@menaceone it's possible yes

**Comment by tanghus** [comment] 2019-09-11 11:56
Another example and a suggestion.

Here's a mail, where the html part doesn't declare a background color:

![nextcloud-mail-html](https://user-images.githubusercontent.com/533222/64694915-2ce90980-d49b-11e9-8a98-b007c3e9167f.png)

Most parties (spam/your friends/authorities/etc) sending html mail, assume they will always have a light canvas to paint on.

Suggestion:
- If pure text/plain show light on dark
- If it's multipart html and plain:
    - Select either (based on settings or a switch in the reader, like with loading images?).
        - If plain, show light on dark.
        - If html, show html on white background. The html part can override it.

**Comment by rigrig** [comment] 2020-04-02 09:21
(copy of https://github.com/nextcloud/mail/issues/2482#issuecomment-597758859 because that issue was closed as duplicate)

Maybe you could use
```css
#message-container {
    filter: invert(100%);
}
```
To simply invert message colors completely?
It might need some fiddling to double-invert images (and maybe other things?)
(And people replying with "my comments in red" will become even more of an annoyance)

Actual screenshots: (inverted by adjusting CSS through Firefox developer console)
| Regular  | Dark theme | Dark theme Inverted |
| ---------- | ---------------- | --------------------------- |
| ![image](https://user-images.githubusercontent.com/2941436/76441420-a7013900-63bf-11ea-9e44-a0ece6076c53.png) | ![image](https://user-images.githubusercontent.com/2941436/76441782-46263080-63c0-11ea-84b4-4d285fd3e378.png) | ![image](https://user-images.githubusercontent.com/2941436/76441906-69e97680-63c0-11ea-8c02-1c001d0ed607.png) |

Test message:
```html
<div>Regular text</div>
<div>&nbsp;</div>
<div><span style="color: #000000;">Black text</span></div>
<div>&nbsp;</div>
<div><span style="color: #ffffff;">White text</span><br /><br /></div>
<div><span style="background-color: #000000;">Black background</span></div>
<div>&nbsp;</div>
<div><span style="background-color: #ffffff;">White background</span></div>
<div>&nbsp;</div>
<div><span style="color: #000000; background-color: #ffffff;">Black-on-white text</span></div>
<div>&nbsp;</div>
<div><span style="color: #ffffff; background-color: #000000;">White-on-black text</span></div>
```

**Comment by tanghus** [comment] 2020-04-02 10:09
That could solve it for very simply HTML parts (I wish all were), but having tried using various browser plugins claiming to do exactly that, I really wouldn't recommend it. There are just too many unknown factors and the result wouldn't be pretty. Better give HTML emails a lighter canvas to paint on. Like the gray background in the old Mosaic and Netscape browsers 😃

**Comment by TheGreatestJannet** [comment] 2020-05-21 09:53
Is there any progress on this? In a meantime maybe an option to override the dark theme with the white theme only for the mail app could be added. Currently with the dark theme enabled the mail app is pretty much unusable as nearly every email is unreadable due to black text on a black background.

**Comment by jhallenb** [comment] 2020-05-24 21:45
@TheGreatestJannet   +1 
I prefer dark theme, but cannot use it due to the email app.

**Comment by tanghus** [comment] 2020-05-25 00:25
As a lousy workaround one can select all text in the email, then it's possible to read it. KMail suffers from the same problem, so I have to do it regularly.
But an option to only view the text/plain part would be nice ;)

**Comment by jhallenb** [comment] 2020-05-25 06:49
I found a breeze dark theme at the addons section. It solved the problem.
One get a dark theme but the email is still readable (at least on the phone)



Den mån 25 maj 2020 02:25Thomas Tanghus <notifications@github.com> skrev:

**Comment by alexanderdd** [comment] 2021-01-03 01:05
so maybe someone can go to "dark mode" developer (who is that?) and tell them that "breeze dark theme" devs figured something out with mail app, and ask if he/she can also implement it in normal "dark mode"?

**Comment by HannesJo0139** [comment] 2021-01-13 15:53
@jhallenb @alexanderdd This is unfortunately wrong. Breeze Dark manages to display some mails better than the built-in Dark Theme, but some other mails are no longer displayed properly. Eg Amazon Mails are unreadable with builtin Dark Theme but readable with Breeze Dark. The other way around Breeze Dark cannot display Github Mails properly, while built-in Dark Theme can.
Dev of Breeze Dark just stated that both issues come from font colouring in the Mail App. (See mention above)

**Comment by ChristophWurst** [comment] 2021-01-13 18:52
> So I think it's up to the mail app devs to make dark themes working.

Today's your lucky day https://github.com/nextcloud/mail/pull/4353

**Comment by HannesJo0139** [comment] 2021-01-13 20:17
> > So I think it's up to the mail app devs to make dark themes working.
> 
> Today's your lucky day #4353

I think not, unfortunately. It seems like my Amazon E-Mail was actually readable at least on narrow screens because of that bug (dark text on white background due to the bug). With that fix my Amazon E-Mail is now not only unreadable on the desktop but also on narrow screens.


![Screenshot from 2021-01-13 21-08-11ANON](https://user-images.githubusercontent.com/42114183/104505724-a5f2f680-55e4-11eb-8f83-6047bf5b007a.png)

**Comment by ChristophWurst** [comment] 2021-01-14 15:49
> Edit: I just looked a bit into it and I guess there is simply no proper solution to style every kind of HTML-Mails unless you want to send every Mail through a parser or so that removes any custom style statements. What I can say, every common Mail-Client will display the E-Mail itself on a white or light-gray background even if you use dark Themes. This is of course a bit ugly but they most likely doin it because it is the only way to get a proper display of all E-Mails.

Well that quite aligns with the proposal of https://github.com/nextcloud/mail/issues/1742#issuecomment-530347369, well maybe without the user setting.

So I too think that we should probably only really use bright/dark theme for plain text emails and HTML emails should always be dark, unless that email overwrites it.

**Comment by tanghus** [comment] 2021-01-14 20:22
> > Edit: I just looked a bit into it and I guess there is simply no proper solution to style every kind of HTML-Mails unless you want to send every Mail through a parser or so that removes any custom style statements. What I can say, every common Mail-Client will display the E-Mail itself on a white or light-gray background even if you use dark Themes. This is of course a bit ugly but they most likely doin it because it is the only way to get a proper display of all E-Mails.
> 
> Well that quite aligns with the proposal of [#1742 (comment)](https://github.com/nextcloud/mail/issues/1742#issuecomment-530347369), well maybe without the user setting.
> 
> ... HTML emails should always be dark, unless that email overwrites it.

Shouldn't it be HTML emails always light/white?

**Comment by HannesJo0139** [comment] 2021-01-14 20:25
I think he meant the text :D

**Comment by tanghus** [comment] 2021-01-14 22:09
That should be defined in the emails style.

**Comment by kbftech** [comment] 2021-01-16 01:33
Hi.

I don't expect this to be a breakthrough, I just wanted to chime in as I am having this issue. I sent myself a test e-mail in plain text and I get a white background with white text.
https://nextcloud.kfoster.tech/index.php/s/DdRYCKT89RSppzx/preview

Not sure it can/will help in any way, but changing that value works pretty good:
https://nextcloud.kfoster.tech/index.php/s/rKLLKFjoiFQY6we/preview

On the flip side, it's a neat privacy feature!

**Comment by mwalbeck** [comment] 2021-01-16 17:30
> That should be defined in the emails style.

I totally agree, but we still have a situation where not all emails have a text colour set, so we also have to take that into account. So we also need to specify a dark text colour along with the light background colour.

@kbftech I can see your email was sent as a HTML email even though it only contains plain text. I can see in your images that the email is shown in an iframe and only HTML emails are shown in iframes. For the Breeze Dark theme plain text emails are shown on a dark background with light text.

HTML emails, on the other hand, are shown on a light background, because in my experience, it is more common for emails to not have a background colour set, but still expect to be shown on a light background. This impacts your email because is has neither a background colour set or a text colour set which means it will be shown light on light. Currently I can't change the text colour for HTML emails so I have to make a trade-off between which of the two groups of emails to show.

**Comment by kbftech** [comment] 2021-01-16 18:50
@mwalbeck Thanks for taking the time to reply to my nonsense. FYI, this was a "basic" e-mail sent through gmail. I would expect that most of the email traffic comes from gmail, so this is probably a wide-spread "issue". I'm guessing google figured that using HTML all the time was the right "default" setting for most of its users.

Now following your trail of thoughts, if we suppose e-mails are to be written in a dark font over a light background, if there isn't any color set for the text, we could assume it's meant to be black and set it that way? I'd even go as far as saying that if the text color isn't set, since we can assume it should be black, and the background should be light, it would work in most - if not all - cases to use the "default" behavior (therefore allow the dark background and light text if using dark mode).

Does any of that make sense to you?

**Comment by mwalbeck** [comment] 2021-01-17 15:30
> @mwalbeck Thanks for taking the time to reply to my nonsense. FYI, this was a "basic" e-mail sent through gmail. I would expect that most of the email traffic comes from gmail, so this is probably a wide-spread "issue". I'm guessing google figured that using HTML all the time was the right "default" setting for most of its users.

Okay, that's good to know.

> Now following your trail of thoughts, if we suppose e-mails are to be written in a dark font over a light background, if there isn't any color set for the text, we could assume it's meant to be black and set it that way? I'd even go as far as saying that if the text color isn't set, since we can assume it should be black, and the background should be light, it would work in most - if not all - cases to use the "default" behavior (therefore allow the dark background and light text if using dark mode).

To catch more edge cases I think it might be best to both check if there is a background colour and text colour set. If neither is set then I think it would be fairly safe to assume the email can be shown with a dark theme (dark background / light text). It may be a good compromise between being able to show some HTML emails with a dark theme, but at the same time still being able to show all HTML emails in a readable way.

**Comment by kbftech** [comment] 2021-01-17 15:48
@mwalbeck Again, thanks for taking the time. 

@ChristophWurst, Sorry to bother you. I'd like to know what you think?

**Comment by tanghus** [comment] 2021-01-17 23:17
It's been a really long time since I've done any web dev, but shouldn't be enough to enclose HTML emails in a CSS class with `background-color: white; color: black;`? It should cascade. Any styles defined in the email would overrule it? Really just asking.

**Comment by kbftech** [comment] 2021-01-18 01:48
@tanghus Seems logical to me but I'm in the same boat; I haven't been actively developing for at least 10 years! 

If we're taking that approach though, why not do it all the way and add a radio button to give the end-user the option to activate or deactivate dark mode on the fly for this iframe? Checked, you've got your theme stuff going on, unchecked you're defaulting to the black text on white background.

Everyone's happy, no more edge case on the loose. That makes any sense?

**Comment by tanghus** [comment] 2021-01-18 08:17
I like your design :smile: but I'm not quite sure what @jancborchardt would say?

**Comment by rigrig** [comment] 2021-01-21 12:22
Sadly, I think the manual toggle is definitely needed, as there are just too many differently horrible ways to style emails to make dark mode work for all cases. (I've had people send me messages with inline "My comments in blue" \**shudder*\*)

That does leave the question how agressively(= complicated) should the dark mode be?
I think it's a good idea to explicitly decide, so it is clear that the scope of dark mode is one of
1. As simple as possible: set the theme foreground+background colors and that's it.   
  Expectation: many HTML emails show up bright anyway. Also a fair amount of emails only set the foreground color, so you will need to use the toggle to read them.   
   -> bug reports for broken dark mode dismissed with "that would overcomplicate things: just use the toggle button"
2. Try a bit to make emails dark: e.g. set the theme foreground+background colors, then try to simply strip out all color from emails so the dark theme is mostly used. Basically a few "simple" search/replace operations, and accept it won't work all the time.
   Expectation: will work ok in most cases, sometimes you end up with (partially) unreadable emails, but we accept that because you can always use the toggle button. (Also some bickering about what constitutes "simple")  
   -> bug reports (and PRs!) for edge cases dismissed with "fixing it would break other cases and/or overcomplicate things: just use the toggle button"
3. Try as hard as possible: keep trying to get dark mode right for all cases.   
   Expectation: will work fine in (eventually) almost all cases, the toggle button will probably still be needed every now and then.
   -> try to fix every edge case, resulting in ever increasing complexity and the need to test a lot against regressions (also need to figure out some way to automate testing whether "this email is readable")   

Or possibly 2.5: Try a bit harder: e.g. set the theme foreground+background colors, and we fix edge cases as long as they don't add "excessive" complexity. (But lots of "simple" fixes piled on top of each other might eventually result in 3. anyway)


My preference would be option 2, but we should at least clearly pick one path to not end up closing bug reports with a "Sorry, we don't handle `<font color=black>`, just use the toggle" while at the same time accepting PRs with 20000 lines of code that "make messages from HUEC(Horribly Uncompliant E-mail Client) v5.2.3-f display correctly in dark mode"

**Comment by kbftech** [comment] 2021-01-21 18:53
@rigrig, I would tend to aim low on this one. It's more a "nice to have" than an "it breaks everything". I'd be very happy if a toggle could be implemented as a quick-and-dirty "catch-all". Then, if anyone wants to build on the complex stuff afterward, awesome. At least we already have the toggle for when things break.

![image](https://user-images.githubusercontent.com/77502706/105398131-fa533300-5bef-11eb-971a-7b2868582351.png)

**Comment by ChristophWurst** [comment] 2021-02-09 12:39
Alright, so here's our new fix: https://github.com/nextcloud/mail/pull/4376

**Comment by kbftech** [comment] 2021-02-09 14:14
Nice! Has it been merged? I had a look but I'm not that familiar with the process. To me, it seemed like some unit tests failed (missing code coverage?).

Anyway, what's the accepted solution? If I'm getting the gist of it, you're now checking the background color instead of the text color and you're adjusting consequently?

**Closed** 2021-02-12 14:31 UTC
Labels: 1. to develop, bug, design

**Comment by st3iny** [comment] 2021-02-12 14:42
> Nice! Has it been merged? I had a look but I'm not that familiar with the process. To me, it seemed like some unit tests failed (missing code coverage?).
> 
> Anyway, what's the accepted solution? If I'm getting the gist of it, you're now checking the background color instead of the text color and you're adjusting consequently?

It just got merged. You can expect the fix to be included in the next release (e.g. 1.9.0).

The implemented solution is to force a white background on the message content. Due to the incredible complexity of html mails this seems to be the most practical solution.

**Comment by kbftech** [comment] 2021-03-15 11:48
I can confirm that after the latest update, e-mails are displaying correctly in my use case.

Thanks!
