### ISSUE TITLE
`snap run nextcloud.occ upgrade` fails with mysql error `An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes`

### ISSUE THREAD

**Issue by christiansacks** [nextcloud/mail#8706] opened 2023-08-09 16:11 UTC
### Steps to reproduce

```
root@nextcloud:~# snap run nextcloud.occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
Exception: Database error when running migration 3300Date20230801124717 for app mail
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
Update failed
Maintenance mode is kept active
Resetting log level
```

### Expected behavior

To upgrade without error

### Actual behavior

```
root@nextcloud:~# snap run nextcloud.occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <mail> ...
Exception: Database error when running migration 3300Date20230801124717 for app mail
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
Update failed
Maintenance mode is kept active
Resetting log level
```

### Mail app version

I can't get into it to see now

### Mailserver or service

postfix

### Operating system

Ubuntu Server 22.04

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

Was told to create an issue here from over https://github.com/nextcloud-snap/nextcloud-snap/issues/2491

**Comment by ChristophWurst** [comment] 2023-08-09 16:19
Please find us the full nextcloud.log entry for the error so we can see the stack trace

**Comment by christiansacks** [comment] 2023-08-09 16:20
> Please find us the full nextcloud.log entry for the error so we can see the stack trace

https://github.com/nextcloud-snap/nextcloud-snap/files/12290684/debug.log

**Comment by christiansacks** [comment] 2023-08-09 16:23
```
root@nextcloud:~# snap logs nextcloud -f
2023-08-09T16:22:51Z nextcloud.apache[733482]: Updated database
2023-08-09T16:22:52Z nextcloud.apache[733482]: Updating <mail> ...
2023-08-09T16:22:55Z nextcloud.apache[733482]: Exception: Database error when running migration 3300Date20230801124717 for app mail
2023-08-09T16:22:55Z nextcloud.apache[733482]: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
2023-08-09T16:22:55Z nextcloud.apache[733482]: Update failed
2023-08-09T16:22:55Z nextcloud.apache[733482]: Maintenance mode is kept active
2023-08-09T16:22:55Z nextcloud.apache[733482]: Resetting log level
2023-08-09T16:22:55Z nextcloud.apache[732937]: Unable to upgrade Nextcloud. Will try again.
2023-08-09T16:22:55Z nextcloud.apache[732937]: Disabling maintenance mode...
2023-08-09T16:22:56Z nextcloud.apache[732937]: done
2023-08-09T16:23:09Z nextcloud.apache[732900]: Failed to setup nextcloud
2023-08-09T16:23:09Z systemd[1]: snap.nextcloud.apache.service: Main process exited, code=exited, status=1/FAILURE
2023-08-09T16:23:09Z systemd[1]: snap.nextcloud.apache.service: Failed with result 'exit-code'.
2023-08-09T16:23:09Z systemd[1]: snap.nextcloud.apache.service: Consumed 6.031s CPU time.
2023-08-09T16:23:09Z systemd[1]: snap.nextcloud.apache.service: Scheduled restart job, restart counter is at 4092.
2023-08-09T16:23:09Z systemd[1]: Stopped Service for snap application nextcloud.apache.
2023-08-09T16:23:09Z systemd[1]: snap.nextcloud.apache.service: Consumed 6.031s CPU time.
2023-08-09T16:23:09Z systemd[1]: Started Service for snap application nextcloud.apache.
2023-08-09T16:23:09Z nextcloud.apache[734038]: Making sure nextcloud is setup...
2023-08-09T16:23:10Z nextcloud.apache[734190]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:10Z nextcloud.apache[734190]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:10Z nextcloud.apache[734190]: System config value redis => host set to string /tmp/sockets/redis.sock
2023-08-09T16:23:11Z nextcloud.apache[734265]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:11Z nextcloud.apache[734265]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:11Z nextcloud.apache[734265]: System config value redis => port set to integer 0
2023-08-09T16:23:11Z nextcloud.apache[734339]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:11Z nextcloud.apache[734339]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:11Z nextcloud.apache[734339]: System config value memcache.locking set to string \OC\Memcache\Redis
2023-08-09T16:23:12Z nextcloud.apache[734412]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:12Z nextcloud.apache[734412]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:12Z nextcloud.apache[734412]: System config value memcache.local set to string \OC\Memcache\Redis
2023-08-09T16:23:12Z nextcloud.apache[734485]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:12Z nextcloud.apache[734485]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:12Z nextcloud.apache[734485]: No such app enabled: updatenotification
2023-08-09T16:23:13Z nextcloud.apache[734559]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:13Z nextcloud.apache[734559]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:13Z nextcloud.apache[734074]: Making sure nextcloud is fully upgraded...
2023-08-09T16:23:13Z nextcloud.apache[734632]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:13Z nextcloud.apache[734632]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:13Z nextcloud.apache[734632]: Setting log level to debug
2023-08-09T16:23:15Z nextcloud.apache[734632]: Updating database schema
2023-08-09T16:23:15Z nextcloud.apache[734632]: Updated database
2023-08-09T16:23:16Z nextcloud.apache[734632]: Updating <mail> ...
2023-08-09T16:23:19Z nextcloud.apache[734632]: Exception: Database error when running migration 3300Date20230801124717 for app mail
2023-08-09T16:23:19Z nextcloud.apache[734632]: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
2023-08-09T16:23:19Z nextcloud.apache[734632]: Update failed
2023-08-09T16:23:19Z nextcloud.apache[734632]: Maintenance mode is kept active
2023-08-09T16:23:19Z nextcloud.apache[734632]: Resetting log level
2023-08-09T16:23:19Z nextcloud.apache[734074]: Unable to upgrade Nextcloud. Will try again.
2023-08-09T16:23:19Z nextcloud.apache[734074]: Disabling maintenance mode...
2023-08-09T16:23:19Z nextcloud.apache[734074]: done
2023-08-09T16:23:32Z nextcloud.apache[734038]: Failed to setup nextcloud
2023-08-09T16:23:32Z systemd[1]: snap.nextcloud.apache.service: Main process exited, code=exited, status=1/FAILURE
2023-08-09T16:23:32Z systemd[1]: snap.nextcloud.apache.service: Failed with result 'exit-code'.
2023-08-09T16:23:32Z systemd[1]: snap.nextcloud.apache.service: Consumed 6.660s CPU time.
2023-08-09T16:23:33Z systemd[1]: snap.nextcloud.apache.service: Scheduled restart job, restart counter is at 4093.
2023-08-09T16:23:33Z systemd[1]: Stopped Service for snap application nextcloud.apache.
2023-08-09T16:23:33Z systemd[1]: snap.nextcloud.apache.service: Consumed 6.660s CPU time.
2023-08-09T16:23:33Z systemd[1]: Started Service for snap application nextcloud.apache.
2023-08-09T16:23:33Z nextcloud.apache[734752]: Making sure nextcloud is setup...
2023-08-09T16:23:33Z nextcloud.apache[734903]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:33Z nextcloud.apache[734903]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:33Z nextcloud.apache[734903]: System config value redis => host set to string /tmp/sockets/redis.sock
2023-08-09T16:23:34Z nextcloud.apache[734974]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:34Z nextcloud.apache[734974]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:34Z nextcloud.apache[734974]: System config value redis => port set to integer 0
2023-08-09T16:23:34Z nextcloud.apache[735047]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:34Z nextcloud.apache[735047]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:34Z nextcloud.apache[735047]: System config value memcache.locking set to string \OC\Memcache\Redis
2023-08-09T16:23:35Z nextcloud.apache[735117]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:35Z nextcloud.apache[735117]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:35Z nextcloud.apache[735117]: System config value memcache.local set to string \OC\Memcache\Redis
2023-08-09T16:23:35Z nextcloud.apache[735190]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:35Z nextcloud.apache[735190]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:35Z nextcloud.apache[735190]: No such app enabled: updatenotification
2023-08-09T16:23:36Z nextcloud.apache[735264]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:36Z nextcloud.apache[735264]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:36Z nextcloud.apache[734789]: Making sure nextcloud is fully upgraded...
2023-08-09T16:23:36Z nextcloud.apache[735336]: Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2023-08-09T16:23:36Z nextcloud.apache[735336]: You may use your browser or the occ upgrade command to do the upgrade
2023-08-09T16:23:36Z nextcloud.apache[735336]: Setting log level to debug
2023-08-09T16:23:36Z nextcloud.apache[735336]: Turned on maintenance mode
2023-08-09T16:23:37Z nextcloud.apache[735336]: Updating database schema
2023-08-09T16:23:37Z nextcloud.apache[735336]: Updated database
2023-08-09T16:23:38Z nextcloud.apache[735336]: Updating <mail> ...
2023-08-09T16:23:41Z nextcloud.apache[735336]: Exception: Database error when running migration 3300Date20230801124717 for app mail
2023-08-09T16:23:41Z nextcloud.apache[735336]: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
2023-08-09T16:23:41Z nextcloud.apache[735336]: Update failed
2023-08-09T16:23:41Z nextcloud.apache[735336]: Maintenance mode is kept active
2023-08-09T16:23:41Z nextcloud.apache[735336]: Resetting log level
2023-08-09T16:23:41Z nextcloud.apache[734789]: Unable to upgrade Nextcloud. Will try again.
2023-08-09T16:23:41Z nextcloud.apache[734789]: Disabling maintenance mode...
2023-08-09T16:23:41Z nextcloud.apache[734789]: done
```
or this?

**Comment by ChristophWurst** [comment] 2023-08-09 16:25
Found it

```
{
  "reqId": "Hl9jPnCv7Q8KN4u3g90O",
  "level": 3,
  "time": "2023-08-08T11:32:13+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "no app in context",
  "method": "",
  "url": "--",
  "message": "Database error when running migration 3300Date20230801124717 for app mail\nAn exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes",
  "userAgent": "--",
  "version": "28.0.0.0",
  "exception": {
    "Exception": "Exception",
    "Message": "Database error when running migration 3300Date20230801124717 for app mail\nAn exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes",
    "Code": 0,
    "Trace": [
      {
        "file": "/snap/nextcloud/36723/htdocs/lib/private/legacy/OC_App.php",
        "line": 776,
        "function": "migrate",
        "class": "OC\\DB\\MigrationService",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
        "line": 360,
        "function": "updateApp",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
        "line": 272,
        "function": "doAppUpgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
        "line": 140,
        "function": "doUpgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/core/Command/Upgrade.php",
        "line": 222,
        "function": "upgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Command/Command.php",
        "line": 298,
        "function": "execute",
        "class": "OC\\Core\\Command\\Upgrade",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
        "line": 1040,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
        "line": 301,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
        "line": 171,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/lib/private/Console/Application.php",
        "line": 213,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/console.php",
        "line": 100,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/36723/htdocs/occ",
        "line": 11,
        "args": [
          "/snap/nextcloud/36723/htdocs/console.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/snap/nextcloud/36723/htdocs/lib/private/DB/MigrationService.php",
    "Line": 421,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
      "Message": "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes",
      "Code": 1071,
      "Trace": [
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1814,
          "function": "convert",
          "class": "Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1749,
          "function": "handleDriverException",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1055,
          "function": "convertExceptionDuringQuery",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Connection.php",
          "line": 262,
          "function": "executeQuery",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1843,
          "function": "executeQuery",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Migrator.php",
          "line": 162,
          "function": "query",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Migrator.php",
          "line": 68,
          "function": "applySchema",
          "class": "OC\\DB\\Migrator",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Connection.php",
          "line": 589,
          "function": "migrate",
          "class": "OC\\DB\\Migrator",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/MigrationService.php",
          "line": 534,
          "function": "migrateToSchema",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/MigrationService.php",
          "line": 417,
          "function": "executeStep",
          "class": "OC\\DB\\MigrationService",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/legacy/OC_App.php",
          "line": 776,
          "function": "migrate",
          "class": "OC\\DB\\MigrationService",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
          "line": 360,
          "function": "updateApp",
          "class": "OC_App",
          "type": "::",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
          "line": 272,
          "function": "doAppUpgrade",
          "class": "OC\\Updater",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
          "line": 140,
          "function": "doUpgrade",
          "class": "OC\\Updater",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/core/Command/Upgrade.php",
          "line": 222,
          "function": "upgrade",
          "class": "OC\\Updater",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Command/Command.php",
          "line": 298,
          "function": "execute",
          "class": "OC\\Core\\Command\\Upgrade",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
          "line": 1040,
          "function": "run",
          "class": "Symfony\\Component\\Console\\Command\\Command",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
          "line": 301,
          "function": "doRunCommand",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
          "line": 171,
          "function": "doRun",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/lib/private/Console/Application.php",
          "line": 213,
          "function": "run",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/console.php",
          "line": 100,
          "function": "run",
          "class": "OC\\Console\\Application",
          "type": "->"
        },
        {
          "file": "/snap/nextcloud/36723/htdocs/occ",
          "line": 11,
          "args": [
            "/snap/nextcloud/36723/htdocs/console.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php",
      "Line": 119,
      "Previous": {
        "Exception": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
        "Message": "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes",
        "Code": 1071,
        "Trace": [
          {
            "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php",
            "line": 77,
            "function": "new",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
            "type": "::"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1050,
            "function": "query",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Connection",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Connection.php",
            "line": 262,
            "function": "executeQuery",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1843,
            "function": "executeQuery",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Migrator.php",
            "line": 162,
            "function": "query",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Migrator.php",
            "line": 68,
            "function": "applySchema",
            "class": "OC\\DB\\Migrator",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Connection.php",
            "line": 589,
            "function": "migrate",
            "class": "OC\\DB\\Migrator",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/MigrationService.php",
            "line": 534,
            "function": "migrateToSchema",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/MigrationService.php",
            "line": 417,
            "function": "executeStep",
            "class": "OC\\DB\\MigrationService",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/legacy/OC_App.php",
            "line": 776,
            "function": "migrate",
            "class": "OC\\DB\\MigrationService",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
            "line": 360,
            "function": "updateApp",
            "class": "OC_App",
            "type": "::",
            "args": [
              "*** sensitive parameters replaced ***"
            ]
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
            "line": 272,
            "function": "doAppUpgrade",
            "class": "OC\\Updater",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
            "line": 140,
            "function": "doUpgrade",
            "class": "OC\\Updater",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/core/Command/Upgrade.php",
            "line": 222,
            "function": "upgrade",
            "class": "OC\\Updater",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Command/Command.php",
            "line": 298,
            "function": "execute",
            "class": "OC\\Core\\Command\\Upgrade",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
            "line": 1040,
            "function": "run",
            "class": "Symfony\\Component\\Console\\Command\\Command",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
            "line": 301,
            "function": "doRunCommand",
            "class": "Symfony\\Component\\Console\\Application",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
            "line": 171,
            "function": "doRun",
            "class": "Symfony\\Component\\Console\\Application",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/lib/private/Console/Application.php",
            "line": 213,
            "function": "run",
            "class": "Symfony\\Component\\Console\\Application",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/console.php",
            "line": 100,
            "function": "run",
            "class": "OC\\Console\\Application",
            "type": "->"
          },
          {
            "file": "/snap/nextcloud/36723/htdocs/occ",
            "line": 11,
            "args": [
              "/snap/nextcloud/36723/htdocs/console.php"
            ],
            "function": "require_once"
          }
        ],
        "File": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php",
        "Line": 30,
        "Previous": {
          "Exception": "PDOException",
          "Message": "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes",
          "Code": "42000",
          "Trace": [
            {
              "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php",
              "line": 72,
              "function": "query",
              "class": "PDO",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
              "line": 1050,
              "function": "query",
              "class": "Doctrine\\DBAL\\Driver\\PDO\\Connection",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Connection.php",
              "line": 262,
              "function": "executeQuery",
              "class": "Doctrine\\DBAL\\Connection",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Connection.php",
              "line": 1843,
              "function": "executeQuery",
              "class": "OC\\DB\\Connection",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Migrator.php",
              "line": 162,
              "function": "query",
              "class": "Doctrine\\DBAL\\Connection",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Migrator.php",
              "line": 68,
              "function": "applySchema",
              "class": "OC\\DB\\Migrator",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/Connection.php",
              "line": 589,
              "function": "migrate",
              "class": "OC\\DB\\Migrator",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/MigrationService.php",
              "line": 534,
              "function": "migrateToSchema",
              "class": "OC\\DB\\Connection",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/DB/MigrationService.php",
              "line": 417,
              "function": "executeStep",
              "class": "OC\\DB\\MigrationService",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/legacy/OC_App.php",
              "line": 776,
              "function": "migrate",
              "class": "OC\\DB\\MigrationService",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
              "line": 360,
              "function": "updateApp",
              "class": "OC_App",
              "type": "::",
              "args": [
                "*** sensitive parameters replaced ***"
              ]
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
              "line": 272,
              "function": "doAppUpgrade",
              "class": "OC\\Updater",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/Updater.php",
              "line": 140,
              "function": "doUpgrade",
              "class": "OC\\Updater",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/core/Command/Upgrade.php",
              "line": 222,
              "function": "upgrade",
              "class": "OC\\Updater",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Command/Command.php",
              "line": 298,
              "function": "execute",
              "class": "OC\\Core\\Command\\Upgrade",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
              "line": 1040,
              "function": "run",
              "class": "Symfony\\Component\\Console\\Command\\Command",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
              "line": 301,
              "function": "doRunCommand",
              "class": "Symfony\\Component\\Console\\Application",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/3rdparty/symfony/console/Application.php",
              "line": 171,
              "function": "doRun",
              "class": "Symfony\\Component\\Console\\Application",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/lib/private/Console/Application.php",
              "line": 213,
              "function": "run",
              "class": "Symfony\\Component\\Console\\Application",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/console.php",
              "line": 100,
              "function": "run",
              "class": "OC\\Console\\Application",
              "type": "->"
            },
            {
              "file": "/snap/nextcloud/36723/htdocs/occ",
              "line": 11,
              "args": [
                "/snap/nextcloud/36723/htdocs/console.php"
              ],
              "function": "require_once"
            }
          ],
          "File": "/snap/nextcloud/36723/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php",
          "Line": 72
        }
      }
    },
    "message": "Database error when running migration 3300Date20230801124717 for app mail\nAn exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes",
    "exception": {},
    "CustomMessage": "Database error when running migration 3300Date20230801124717 for app mail\nAn exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes"
  }
}
```

I am not familiar with snap

**Comment by christiansacks** [comment] 2023-08-09 16:33
ok as a work-around I did `snap run nextcloud.occ app:disable mail` and then re-ran the upgrade, which then worked and I can get back into the system now... but the mail app is useful and would like it get fixed

**Comment by christiansacks** [comment] 2023-08-09 16:54
> https://github.com/nextcloud/mail/issues?q=is%3Aissue+%22Specified+key+was+too+long%22+is%3Aclosed

I'm a little confused why you linked this as it's from Apr 4 2021, I would imagine the fix for that issue either has been undone or something else is causing this issue? Sorry I'm not much more help on this but I would like to have the mail app working again and this seems to be impossible with the current version of it...

```
root@nextcloud:~# snap run nextcloud.occ app:list|grep -i -- "- mail"
  - mail: 3.4.0-alpha.3 (installed 3.3.0-rc.1)
```

I can't upgrade the mail app as this error occurs, so it's stuck to being disabled until there's a fix somehow.
Let me know if there's anything more I can do to help

**Comment by christiansacks** [comment] 2023-08-09 17:13
by the way I have removed the mail app entirely seeing as I can't use it at the moment, but can see there are a bunch of tables in the database left behind, do you think it would fix the problem if I deleted these tables and then reinstalled the app letting it recreate the tables?

```
root@nextcloud:~# snap run nextcloud.mysql-client -e 'use nextcloud; show tables like "oc_mail_%";'
+---------------------------------+
| Tables_in_nextcloud (oc_mail_%) |
+---------------------------------+
| oc_mail_accounts                |
| oc_mail_aliases                 |
| oc_mail_attachments             |
| oc_mail_classifiers             |
| oc_mail_coll_addresses          |
| oc_mail_local_messages          |
| oc_mail_mailboxes               |
| oc_mail_message_tags            |
| oc_mail_messages                |
| oc_mail_provisionings           |
| oc_mail_recipients              |
| oc_mail_smime_certificates      |
| oc_mail_tags                    |
| oc_mail_trusted_senders         |
+---------------------------------+
```

**Comment by st3iny** [comment] 2023-08-19 16:28
Duplicate of #8748

**Closed by st3iny** 2023-08-19 16:28 UTC
Labels: bug, 3. to review, needs info
