### ISSUE TITLE
Mail app upgrade failure while updating from V1.9.5 to V1.10.0

### ISSUE THREAD

**Issue by JMLatGitHub** [nextcloud/mail#5291] opened 2021-07-07 09:17 UTC
### Expected behavior
I wanted to update from Mail V1.9.5 to V1.10.0 via command line.

### Actual behavior
During the update process via command line and got the following error message:

`mail new version available: 1.10.0`
`An unhandled exception has been thrown:`
`Error: Call to undefined method OCA\Mail\Db\MailboxMapper::findAllIds() in /var/www/nextcloud/apps/mail/lib/Migration/Version1100Date20210512142306.php:34`
`Stack trace:`
`#0 /var/www/nextcloud/lib/private/DB/MigrationService.php(548): OCA\Mail\Migration\Version1100Date20210512142306->postSchemaChange()`
`#1 /var/www/nextcloud/lib/private/DB/MigrationService.php(426): OC\DB\MigrationService->executeStep()`
`#2 /var/www/nextcloud/lib/private/legacy/OC_App.php(993): OC\DB\MigrationService->migrate()`
`#3 /var/www/nextcloud/lib/private/Installer.php(212): OC_App::updateApp()`
`#4 /var/www/nextcloud/core/Command/App/Update.php(116): OC\Installer->updateAppstoreApp()`
`#5 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute()`
`#6 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()`
`#7 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()`
`#8 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()`
`#9 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()`
`#10 /var/www/nextcloud/console.php(100): OC\Console\Application->run()`
`#11 /var/www/nextcloud/occ(11): require_once('...')`
`#12 {main}`

I currently did deisable the Mail application.

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
V1.9.5 => V1.10.0 (currently disabled due to the update error)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
RainLoop V1.14

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian Testing (11, Bullseye)

**Web server:** (e.g. Apache, Nginx,...)
NGINX V1.21.0

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB V10.5.10

**PHP version:** (e.g. 7.0)
PHP V8.0.7

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
Nextcloud V21.0.2.1

#### Client configuration
**Browser:** (e.g. Firefox 48)

**Operating system:** (e.g. Arch Linux)

**Comment by ChristophWurst** [comment] 2021-07-07 09:49
https://github.com/nextcloud/mail/issues?q=is%3Aissue+findAllIds+is%3Aclosed :wink: 

Duplicate of https://github.com/nextcloud/mail/issues/5286

**Closed by ChristophWurst** 2021-07-07 09:49 UTC
Labels: 0. to triage, bug

**Comment by JMLatGitHub** [comment] 2021-07-07 10:07
Thanks for the info, @ChristophWurst. What is the advice? Waiting for a fix or rollback?

**Comment by ChristophWurst** [comment] 2021-07-14 13:35
You can update now.

**Comment by JMLatGitHub** [comment] 2021-07-15 23:05
Thanks for coming back to me, @ChristophWurst. I did the installation manually a few days ago, following this procedure:
- mysqldump
- wget https://github.com/nextcloud-releases/mail/releases/download/v1.10.0/mail.tar.gz
- mv mail app directory away from Nextcloud apps path
- tar -xvzf mail.tar.gz to Nextcloud apps directory
- chown -R www-data:www-data /var/www/
- cd /var/www/nextcloud/apps/
- find ./mail -type d -exec chmod 0750 {} \;
- find ./mail -type f -exec chmod 0644 {} \;
- run occ app:enable mail
- run occ app:update mail

So far, everything seems to work. After that, I updated to Mail V1.10.1 without any kind of issue.

Thank you all for your amazing work and continuous support.

Kind regards
JML

**Comment by ChristophWurst** [comment] 2021-07-16 09:42
Thanks for the kind words.

This unfortunate upgrade bug will always pass on the second attempt. The reason for the error in the first place is that when code is replaced, php still cached the old version within the same process.

**Comment by JMLatGitHub** [comment] 2021-07-16 09:58
Well, we live in an imperfect world, so we have to deal with that. Fortunately, most of the time there are acceptable workarounds. Nevertheless, in my opinion, a cache should always support reinitialization on demand...

Best regards
JML
