### ISSUE TITLE
Cannot scroll HTML message on Firefox for Android [$75]

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#729] opened 2018-01-23 11:35 UTC
### Steps to reproduce
1. Open the app
2. Open a HTML message on Firefox for Android
3. See only the very top content of the message

### Expected behaviour
I should be able to scroll down to see the full message body

### Actual behaviour
Scrolling is fixed. The only way to see more content is to long-click on some text and use the text selection markers to hack your way down. This is super ugly.

### Mail app

**Mail app version:** basically any version in the last few months.

@skjnldsv @jancborchardt does anbody of you use Mail on mobile Firefox? Does scrolling work for you?

I've dug into the code and even attached the FF web IDE to my Android phone to see what's going on. Even after tweaking element height and overflow properties, I couldn't get it to work. Note that it's not an issue on the desktop, where you have a mouse/touchpad.

**Comment by lbidoux** [comment] 2018-02-18 13:41
I can confirm this one with Mail 0.7.9 on Nextcloud 13.0.0. It used to work before unfortunately I am not able to tell in which version the regression has been introduced as I rarely use the application from my smartphone.

**Comment by Fastigium** [comment] 2018-04-01 13:17
After about 10 hours of debugging and investigation, I was able to isolate this issue as being caused by a bug in Firefox for Android. I created a minimal html document to reproduce the issue with and filed [a bug with Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1450555). Hopefully they'll be able to fix it. I'm not sure what this means for the bounty, but I'm fully willing to share or pass on the bounty if that seems appropriate.

**Comment by ChristophWurst** [comment] 2018-04-01 13:37
Thanks a lot, @Fastigium! :raised_hands:

**Comment by alexanderdd** [comment] 2018-04-02 22:11
In my opinion, @fastigium should post an update here once the issue is fixed by mozilla, and then she/he can have the bounty. She/He isolated the problem and took steps to fix it for our userbase. (If it was $1000 I'd probably say that the mozdevs should get a share :-)

**Comment by Fastigium** [comment] 2018-04-07 08:48
> In my opinion, @Fastigium should post an update here once the issue is fixed by mozilla, and then she/he can have the bounty

That sounds like a plan, though I'll probably still ask the mozdevs if they want a share :slightly_smiling_face:. I also considered trying to fix the bug in Firefox myself, but seeing the complexity of [the technical info they just posted in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1450555#c1) I'm glad I waited :sweat_smile:

**Comment by ChristophWurst** [comment] 2018-08-01 05:40
Little heads up: the Nextcloud server and app's structure changes with Nextcloud 14 (https://github.com/nextcloud/server/pull/9982) and although there are a few breaking changes like https://github.com/nextcloud/mail/issues/981 right now, I am finally able to scroll the details of a message on my phone again.

Let's see how the app works after https://github.com/nextcloud/mail/pull/1001.

Even if this restructuring magically fixed the FF bug for us, I'd still vote for giving @Fastigium the bounty for putting a [lot of effort](https://github.com/nextcloud/mail/issues/729#issuecomment-377786261) into this :rocket:

**Comment by ChristophWurst** [comment] 2018-08-01 05:42
> Even if this restructuring magically fixed the FF bug for us, I'd still vote for giving @Fastigium the bounty for putting a lot of effort into this rocket

cc @joewashear007 since we're the two who posted bounties on this ticket :)

**Comment by Fastigium** [comment] 2018-08-01 17:56
> Even if this restructuring magically fixed the FF bug for us,

The bug requires the iframe to be scrolled inside a div, and according to https://github.com/nextcloud/server/pull/9982 the div is being replaced by scrolling the whole page. That would circumvent the circumstances that trigger the bug :slightly_smiling_face:

> [...] I'd still vote for giving @Fastigium the bounty for putting a lot of effort into this

Thanks, though I don't feel like I deserve the full $75 bounty. The $25 it was when I did the investigation feels right to me. So if the magic fix works and the bounty is awarded to me, I'll give $50 back to the nextcloud team on Bountysource. Alternatively, you might be able to revoke or migrate the $50 bounty by contacting Bountysource support ([according to the FAQ](https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#can-i-receive-a-refund-for-a-bounty-i-posted)). Either method is fine in my book :+1:

**Comment by sourenaraya** [comment] 2019-06-12 05:30
Looks like its working now. Checked with latest mobile firefox and latest mail app, nextcloud 16.0.1.1

**Comment by ChristophWurst** [comment] 2019-12-17 16:38
Yes, I think so too. I don't have these problems anymore.

**Comment by jancborchardt** [comment] 2020-02-29 03:30
Closing then as it’s fixed. Does the Bounty go back to the donors or into the pool @ChristophWurst?

**Closed by jancborchardt** 2020-02-29 03:30 UTC
Labels: 1. to develop, bounty, bug

**Comment by ChristophWurst** [comment] 2020-03-02 07:58
From https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

> If the issue was closed as a "won't fix", or is deemed not in line with the project's goals, the bounty is refunded.

So sounds like this is done automatically? I couldn't find more info on the process. cc @johanlives

**Comment by johanlives** [comment] 2020-03-04 02:52
> From https://github.com/bountysource/core/wiki/Frequently-Asked-Questions
> 
> > If the issue was closed as a "won't fix", or is deemed not in line with the project's goals, the bounty is refunded.
> 
> So sounds like this is done automatically? I couldn't find more info on the process. cc @johanlives

Hi guys,
Refunds are not automated. 
You need to send a quick email to support@bountysource.com.
