### ISSUE TITLE
Error log in Nextcloud logging

### ISSUE THREAD

**Issue by sergiupapuc** [nextcloud/mail#8664] opened 2023-08-02 18:12 UTC
### Steps to reproduce

1.read mail
2.foreach() argument must be of type array|object, bool given at /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php#527
3.

### Expected behavior

No error in interface

### Actual behavior

No error in interface, error logged in Logging Nextcloud 
foreach() argument must be of type array|object, bool given at /var/www/nextcloud/apps/mail/lib/IMAP/ImapMessageFetcher.php#527

### Mail app version

Latest

### Mailserver or service

Imap exchange

### Operating system

Ubuntu 22.04

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment] 2023-08-03 15:25
Duplicate of https://github.com/nextcloud/mail/issues/8568

**Closed by ChristophWurst** 2023-08-03 15:25 UTC
Labels: bug, 0. to triage
