### ISSUE TITLE
Can't scroll to older mails

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/mail#5257] opened 2021-06-28 15:18 UTC
### Expected behavior

I should be able to scroll to my older emails.

### Actual behavior

I only see the current mails. Scrolling down doesn't result in anything:

<img width="1374" alt="Screenshot 2021-06-28 at 17 16 31" src="https://user-images.githubusercontent.com/878997/123661424-cfbb7500-d834-11eb-9c58-653d441dc716.png">

### Mail app

c.nc.c

#### Client configuration
**Browser:** Safari 14.1

**Operating system:** macOS

**Comment by LukasReschke** [comment] 2021-06-28 15:21
There's nothing in the console. The network tab also doesn't seem to show any XHR requests.

**Comment by ChristophWurst** [comment] 2021-06-28 15:53
Duplicate of https://github.com/nextcloud/mail/issues/5234

**Closed by ChristophWurst** 2021-06-28 15:53 UTC
Labels: 0. to triage, bug
