### ISSUE TITLE
Can't move mails

### ISSUE THREAD

**Issue by LIyoai** [nextcloud/mail#3022] opened 2020-04-29 08:29 UTC
### Expected behavior
I can move a mail to another folder

### Actual behavior
When I try to drag & drop a mail it's not working
![image](https://user-images.githubusercontent.com/6205123/80575711-4a57ed00-8a04-11ea-85be-61b50af1df32.png)

Mail app

Mail app version: 1.3.4

Mailserver or service: Courier IMAP
Server configuration

Operating system: Debian 10

Web server: Apache

Database: MariaDB

PHP version: 7.3

Nextcloud Version: 18.0.4
Client configuration

Browser: Firefox 75 & Chrome 81

Operating system: Windows 10

**Comment by ChristophWurst** [comment] 2020-04-29 08:32
Duplicate of https://github.com/nextcloud/mail/issues/1538

**Comment by ChristophWurst** [comment] 2020-04-29 08:32
Please use the ticket search before opening new ones

**Closed by ChristophWurst** 2020-04-29 08:32 UTC
Labels: 0. to triage, bug
