### ISSUE TITLE
Cannot change mail formatting setting in composer

### ISSUE THREAD

**Issue by mat-m** [nextcloud/mail#3114] opened 2020-05-14 23:51 UTC
### Expected behavior
Tell us what should happen

1. I reply to an email
2. I click on the Enable Formatting checkbox
3. Type in some text
4. Select some text
I should have the option bar displayed

### Actual behavior
Tell us what happens instead
I see a floating bar with undo/redo buttons.
When I check the 3 dots drop-down, the checkbox Enable formatting is disabled.

As a side note, I didn't find any setting to define a default behavior for this, although mentioned in https://github.com/nextcloud/mail/pull/1988#issuecomment-539848160

### Mail app

**Mail app version:** 1.3.4
**Mailserver or service:** gandi.net

### Server configuration

**Operating system**:  Raspbian 10

**Web server:** nginx

**Database:**  MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 18.0.4

#### Client configuration
**Browser:** (e.g. Firefox 48) Opera 68, chromium-based, Firefox 76

**Operating system:** (e.g. Arch Linux) Linux Mint 19.3

**Comment by ChristophWurst** [comment] 2020-05-15 11:11
Do you have a screenshot for us? Are there any js errors on the console?

**Comment by GretaD** [comment] 2020-05-22 10:19
The problem its the  writing mode and it only happens on the 18th version. The rich text doesn't save. If you click Rich Text and you go and reply an email or write a new email, and go back to writing mode, the one clicked its the plain text. @mat-m can you confirm?

**Comment by Khalphion** [comment] 2020-05-29 12:18
I have the same problem. Either answer an email or write a new one, the WYSIWYG editor does not show up when enabling the "Enable Formatting" checkbox in the "..." context menu bottom right.

The checkbox automatically unticks immediately after closing the context menu.
![grafik](https://user-images.githubusercontent.com/10117554/83257173-1c58fa80-a1b4-11ea-9a34-5d3028048e22.png)

When typing:
```
[DEBUG] mail: TextEditor input changed to <<p style="margin:0;">asdasdads</p>> 
Object { app: "mail", uid: "xyz" }
```

Nextcloud (Docker container version), 18.0.4 behind Nginx proxy
Browser: Firefox 76, Chrome 83

**Comment by ChristophWurst** [comment] 2020-05-29 12:45
I can confirm the bug.

**Comment by wiswedel** [comment] 2020-06-02 21:40
Whatever is set as default (plain or rich text) for an account, the switcher check box in the composer doesn't react to a change to the respective other.

Tested with 1.3.5 and 1.4.0 Beta 2

**Comment by ChristophWurst** [comment] 2020-06-03 07:28
Yep, @GretaD is working on it :)

**Comment by ChristophWurst** [comment] 2020-06-03 07:29
My insights from yesterday are that https://github.com/nextcloud/mail/pull/2874 broke it.

**Comment by GretaD** [comment] 2020-06-05 14:32
@ChristophWurst vs no-response bot

**Comment by ChristophWurst** [comment] 2020-06-05 20:54
What is going on

**Comment by dehnhardt** [comment] 2020-06-05 21:05
Somebody/something wants to keep you away from the weekend - or force you to?

**Comment by dehnhardt** [comment] 2020-06-05 21:37
This is might be explanation: "closes issues where **the author** hasn't responded to a request for more information"
I deleted the "needs info" label. Maybe it helps???

**Comment by ChristophWurst** [comment] 2020-06-08 07:30
Oooooof. Of course it was because of that label :see_no_evil:

**Closed** 2020-06-08 10:07 UTC
Labels: 2. developing, bug, priority, regression
