### ISSUE TITLE
Replying to / forwarding rich text emails replaces original links with redirect links

### ISSUE THREAD

**Issue by mwalbeck** [nextcloud/mail#5233] opened 2021-06-24 15:22 UTC
### Expected behavior
When an email account is set to use rich text and an email containing links is forwarded to another email address and viewed from a different client than Mail, the original links should in the email and not the redirect links added when viewing the email in Mail.

If the forwarded email is view in Mail, the link should only redirect once.

### Actual behavior
When viewing the forwarded email from a different client than Mail, the redirect links inserted by Mail have replaced the original links. So if the email is forwarded to someone who doesn't have a user on the Nextcloud instance the email was sent from, they get redirected to the login screen of that Nextcloud instance when clicking on the link.

If the forwarded email is viewed from Mail another redirect is added to the links, so the user is redirected twice before getting sent to the original destination.

### Mail app

**Mail app version:** 1.9.5

**Mailserver or service:** Tested on Runbox and Simply.com

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MySQL 8.0.24

**PHP version:** 7.4.18

**Nextcloud Version:** 21.0.1 (snap)

### Client configuration
**Browser:** Firefox 89

**Operating system:** KDE Neon (Ubuntu 20.04)

**Comment by ChristophWurst** [comment] 2021-07-02 09:04
So I guess we need to use the original HTML for the quoted reply/forward instead of the rewritten one for display purposes.

**Comment by mwalbeck** [comment] 2021-07-02 10:18
Yeah, initially it didn't seem to affect replies, but it seems I was just messing those tests up. Doing a few more tests It's also happening when one is replying to HTML emails.

**Comment by ChristophWurst** [comment] 2022-10-12 09:21
Label dropped because it was a duplicate of the attribute at https://github.com/orgs/nextcloud/projects/61. The priority does **not** change.

**Comment by ChristophWurst** [comment] 2024-02-27 18:37
This appears to be fixed

**Closed by ChristophWurst** 2024-02-27 18:37 UTC
Labels: bug, 3. to review, feature:editor
