### ISSUE TITLE
Archive emails button

### ISSUE THREAD

**Issue by ntimo** [nextcloud/mail#3722] opened 2020-10-05 10:35 UTC
### Feature Request

An "Archive" button should be available to quickly move emails to the archive folder. 

#### Summary

An "Archive" button should be available to quickly move emails to the archive folder. This is going to make it possible to move emails the archive pretty fast and thus streamline the workflow process, for people using the Inbox zero concept.

**Comment by ChristophWurst** [comment] 2020-10-05 11:33
Duplicate of https://github.com/nextcloud/mail/issues/22

**Closed by ChristophWurst** 2020-10-05 11:33 UTC
Labels: 0. to triage, enhancement
