### ISSUE TITLE
multiple identities per email account

### ISSUE THREAD

**Issue by ufgum** [nextcloud/mail#2924] opened 2020-04-16 17:56 UTC
### Feature Request

Multiple identities per email account

#### Summary

In one of my IMAP mail accounts I receive mails to different email addresses (lets say my private account collects all of my private email addresses). So it would be very helpful to be able to replay from the depending email, even it has the same IMAP/SMTP server settings.

**Comment by ChristophWurst** [comment] 2020-04-17 06:30
Duplicate of #1722

**Closed by ChristophWurst** 2020-04-17 06:30 UTC
Labels: 0. to triage, enhancement
