### ISSUE TITLE
Inbox doesn't auto-refresh with new e-mail.

### ISSUE THREAD

**Issue by asincero** [nextcloud/mail#5968] opened 2022-01-19 19:27 UTC
### Expected behavior
Inbox should show new e-mail automatically when it comes in.

### Actual behavior
New e-mail doesn't appear in the Inbox unless you manually refresh the browser.

### Mail app

**Mail app version:** 
1.11.5

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Dovecot 2.3.13 IMAP server.

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian Linux 11.2

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4.52

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
Postgresql 13.5

**PHP version:** (e.g. 7.0)
7.4.25

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
23.0.0

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 96.0.1 (64-bit)
Chrome 97.0.4692.71 (64-bit)

**Operating system:** (e.g. Arch Linux)
Microsoft Windows 10 Education (version 20H2)

Side notes:

1. RainLoop will automatically show new e-mail in the Inbox without needing to manually refresh the web browser.
2. The "Important mail" dashboard widget doesn't appear to update either.

**Comment by miaulalala** [comment] 2022-01-20 11:40
Duplicate of #4925

**Closed by miaulalala** 2022-01-20 11:40 UTC
Labels: bug, 0. to triage
