### ISSUE TITLE
Automatically fetch more messages when the list shrinks

### ISSUE THREAD

**Issue by m4200** [nextcloud/mail#1537] opened 2019-02-18 16:05 UTC
### Expected behavior
When I delete multiple emails, the list should be refreshed with the following emails. 

### Actual behavior
I delete emails one by one, at one point no emails are shown but a message stating that inbox is empty

### Mail app

**Mail app version:** 0.11.0

**Mailserver or service:** self-hosted email server available through imaps

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud Version:** 15.0.2

#### Client configuration
**Browser:** Firefox 64

**Operating system:** Linux Mint 18

**Comment by ChristophWurst** [comment] 2019-02-21 14:02
Updated the title accordingly :+1:

**Comment by danxuliu** [comment] 2019-06-24 19:33
I think that this is a duplicate of #863, but if I am wrong please feel free to reopen :-)

**Closed by danxuliu** 2019-06-24 19:33 UTC
Labels: 0. to triage, bug
