### ISSUE TITLE
problems with office365

### ISSUE THREAD

**Issue by dl6dbh** [nextcloud/mail#7501] opened 2022-10-28 14:41 UTC
### Steps to reproduce

1.
2.
3.

### Expected behavior

since mail 1.14.1 i have problems with office365.
other acountś running well

### Actual behavior

since mail 1.14.1 i have problems with office365.
other acountś running well

### Mail app version

1.14.1

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment] 2022-10-31 11:04
Thanks for the report.

To make your reports most useful for developers, please fill in the form properly. E.g. tell us how you reproduce the bug. Then we can see if it also happens for us.

From the information given I assume this ticket is a duplicate of https://github.com/nextcloud/mail/issues/6591

**Closed by ChristophWurst** 2022-10-31 11:04 UTC
Labels: bug, 0. to triage
