### ISSUE TITLE
Mail app doesnt work with shared mailboxes

### ISSUE THREAD

**Issue by matejak** [nextcloud/mail#3625] opened 2020-09-21 17:59 UTC
### Expected behavior

The mail app is able to work when an inbox is shared to the account.

### Actual behavior

The mail app fails to work - the :

- providing no feedback to the user, and
- providing insufficient feedback to the admin - "You do not have adequate permissions to carry out this operation" without any context.

I attach the screenshot of the email app when the shared inbox is set up:
![image](https://user-images.githubusercontent.com/2823847/93803145-b4d42880-fc44-11ea-93b8-a99044e89aea.png)

As soon as the shared mailbox is not advertised any longer by dovecot (by tampering with the appropriate dovecot dictionary), the app resumes functioning normally again.

I think that the issue I experience is the same as #1730. I don't know whether it is possible to have the root of shared mailboxes somehow accessible, so this error is not trigerred.

### Mail app

**Mail app version:** 1.4.1

**Mailserver or service:** dovecot 2.3.4.1

### Server configuration

**Operating system**: CentOS 7 running Nextcloud 19 container `nextcloud:19-apache`

**Web server:** Apache + Nginx proxy

**Database:** PostgreSQL

**PHP version:** 7.4.10

**Nextcloud Version:** 19.0.3

#### Client configuration
**Browser:** Firefox 80

**Operating system:** Arch Linux

**Comment by ChristophWurst** [comment] 2020-09-21 18:20
have you had a look at the nextcloud logs?

**Comment by matejak** [comment] 2020-09-21 18:59
I think that this is the related message:

```
[mail] Fatal: OCA\Mail\Exception\ServiceException: IMAP errorYou do not have adequate permissions to carry out this operation. at <<closure>>

0. /var/www/html/custom_apps/mail/lib/Service/MailManager.php line 101
   OCA\Mail\IMAP\MailboxSync->sync(OCA\Mail\Account {})
1. /var/www/html/custom_apps/mail/lib/Controller/PageController.php line 119
   OCA\Mail\Service\MailManager->getFolders(OCA\Mail\Account {})
2. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Mail\Controller\PageController->index()
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\PageController {}, "index")
4. /var/www/html/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\PageController {}, "index")
5. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "mail.page.index"})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "mail.page.index"})
7. /var/www/html/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {_route: "mail.page.index"})
8. /var/www/html/lib/base.php line 1012
   OC\Route\Router->match("/apps/mail/")
9. /var/www/html/index.php line 37
   OC::handleRequest()

GET /apps/mail/
from 151.237.228.224 by ... at 2020-09-21T17:49:04+00:00
```

Would you be interested in a Dovecot setup that causes this behavior in a form of a container image?

**Comment by matejak** [comment] 2020-09-21 19:07
Here is [a more detailed traceback](https://github.com/nextcloud/mail/files/5257615/report.txt), where user `denton@mail.example.com` has issues with a shared mailbox `it@mail.example.com`.

**Comment by ChristophWurst** [comment] 2020-09-22 06:59
> You do not have adequate permissions to carry out this operation

Thanks. This helps. The bug reported is a duplicate of https://github.com/nextcloud/mail/issues/1735. Let's continue there :)

**Comment by ChristophWurst** [comment] 2020-09-22 07:00
> Would you be interested in a Dovecot setup that causes this behavior in a form of a container image?

This would be brilliant!

**Closed by ChristophWurst** 2020-09-22 06:59 UTC
Labels: 0. to triage, bug
