### ISSUE TITLE
Foward email to others, the attachment and image being removed

### ISSUE THREAD

**Issue by RabbitDuck** [nextcloud/mail#748] opened 2018-02-01 03:40 UTC
### Steps to reproduce
1. Open an email with image or attachment
2. Click Forward and Send the email to someone
3. The one received the forwarded email find no attachment or image

### Expected behaviour
The one received the mail can see the attachment or image

### Actual behaviour
All attachments, html format and images are removed

### Mail app

**Mail app version:** (see apps admin page)
v0.7.9

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

Postfix and Dovecot

It seems that the forward function will remove all the html format and attachment of the original email
I think it is better to treat the original email as an mail attachment instead of "inline" when it is being forwarded

**Comment by ChristophWurst** [comment] 2018-02-01 07:09
Duplicate of https://github.com/nextcloud/mail/issues/246

**Closed by ChristophWurst** 2018-02-01 07:09 UTC
