### ISSUE TITLE
Attach emails to projects

### ISSUE THREAD

**Issue by loxK** [nextcloud/mail#4314] opened 2021-01-05 07:03 UTC
### Feature Request

In a few words the feature that would allow attaching emails to Nextcloud projects.

**Comment by ChristophWurst** [comment] 2021-01-07 15:03
Interesting. I guess we need some custom labels or similar for this.

**Comment by loxK** [comment] 2021-07-14 12:54
Keep it opened please

**Comment by ChristophWurst** [comment] 2021-07-14 13:21
it's a duplicate of https://github.com/nextcloud/mail/issues/2093

**Closed by ChristophWurst** 2021-07-14 13:21 UTC
Labels: 1. to develop, enhancement, help wanted, priority:low
