### ISSUE TITLE
[Bug]: Horde_Stream/Horde/Stream.php on line 203 OOM

### ISSUE THREAD

**Issue by 0xpr03** [nextcloud/mail#6280] opened 2022-04-21 13:01 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I get a ton of errors mails for being OOM in the mail application of nextcloud

### Steps to reproduce

1. Install nextcloud and setup some mail account with IMAP login

### Expected behavior

No memory allocation error

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.3

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "censored.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/censored.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "htaccess.RewriteBase": "\/",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 1,
        "defaultapp": "files",
        "updater.release.channel": "stable",
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
- accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.2
  - checksum: 1.1.3
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.5.0
  - groupfolders: 11.1.2
  - impersonate: 1.10.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.4.2
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.3
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_gateway: 0.19.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
[PHP] Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes) at /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream/Horde/Stream.php#203

at 2022-04-21T12:10:29+00:00

PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes) in /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream/Horde/Stream.php on line 203
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 1052672 bytes) in /var/www/nextcloud/apps/mail/lib/Cache/Cache.php on line 126
```

### Additional info

I get a ton of these entries and mails, over multiple months

**Comment by joshtrichards** [comment] 2023-07-03 19:44
Can you provide the entries from your `nextcloud.log` from immediately to these memory errors?

Actually it sounds like you're likely getting these from cron, so can you run the cron `occ` commands manually with the `-v` parameter to see what's going on?

**Comment by eickeh** [comment] 2023-07-13 13:24
Thanks for the reply. We uninstalled the mail app shortly after this ticket as we didn't use it very much. So I can't test anything manually anymore unfortunately. 

But I dug out the logs from an old backup. They are probably not all directly related to the error above but seem nevertheless strange to me so maybe there's a connection. The error message above show up at 2022-04-21T12:10:29+00:00 again. I added some empty lines to group the messages.

```
{"reqId":"wSSrPh4GvU0pi4XsrL7H","level":1,"time":"2022-04-21T11:35:20+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"not enough messages to train a classifier","userAgent":"--","version":"23.0.3.2"}
{"reqId":"wSSrPh4GvU0pi4XsrL7H","level":1,"time":"2022-04-21T11:35:20+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"not enough messages to train a classifier","userAgent":"--","version":"23.0.3.2"}
{"reqId":"wSSrPh4GvU0pi4XsrL7H","level":1,"time":"2022-04-21T11:35:20+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"not enough messages to train a classifier","userAgent":"--","version":"23.0.3.2"}

{"reqId":"wSSrPh4GvU0pi4XsrL7H","level":3,"time":"2022-04-21T11:35:29+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"Cron mail sync failed for account 13","userAgent":"--","version":"23.0.3.2","exception":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"IMAP error synchronizing account 13: Mail server denied authentication.","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":108,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},true]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":13}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":150,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","Line":107,"Previous":{"Exception":"Horde_Imap_Client_Exception","Message":"Mail server denied authentication.","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":838,"function":"_login","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1389,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":60,"function":"listMailboxes","class":"Horde_Imap_Client_Base","type":"->","args":["*",5,{"delimiter":true,"attributes":true,"special_use":true}]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","line":104,"function":"getFolders","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"Horde_Imap_Client_Socket","cacheFields":["HICenv","HICflags","HIChdrs","HICdate","HICsize","And 1 more entries, set log level to debug to see all entries"],"changed":true,"statuscache":true}]},{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":108,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},true]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":13}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":150,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":572},"CustomMessage":"Cron mail sync failed for account 13"}}

{"reqId":"3cKNA7HH1u8iVyTeLya1","level":2,"time":"2022-04-21T11:45:02+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"User 22c05af5-1d53-433a-a00a-30a4d14e45a7 still has unscanned files after running background scan, background scan might be stopped prematurely","userAgent":"--","version":"23.0.3.2"}
{"reqId":"MnHTVhmfnghtEysEdzx7","level":1,"time":"2022-04-21T11:45:34+00:00","remoteAddr":"95.223.73.232","user":"--","app":"no app in context","method":"GET","url":"/s/nPWLwQ25pAAMGD7","message":"Deprecated event type for OCA\\Files_Sharing::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.3.2"}
{"reqId":"c9nTgA4FTctWzKTr5k3h","level":2,"time":"2022-04-21T12:00:02+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"User 22c05af5-1d53-433a-a00a-30a4d14e45a7 still has unscanned files after running background scan, background scan might be stopped prematurely","userAgent":"--","version":"23.0.3.2"}
{"reqId":"usDbPip2dAFhJX5rh0uP","level":1,"time":"2022-04-21T12:03:59+00:00","remoteAddr":"95.223.73.232","user":"--","app":"no app in context","method":"GET","url":"/s/5a9nbGFoYzTQ6iD","message":"Deprecated event type for OCA\\Files_Sharing::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.3.2"}
{"reqId":"TEYwireBUI3Zw8vzN67Y","level":3,"time":"2022-04-21T12:10:29+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes) at /var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Stream/Horde/Stream.php#203","userAgent":"--","version":"23.0.3.2"}

{"reqId":"x8wlh56DHyuUluXDeeza","level":2,"time":"2022-04-21T12:15:02+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"User 22c05af5-1d53-433a-a00a-30a4d14e45a7 still has unscanned files after running background scan, background scan might be stopped prematurely","userAgent":"--","version":"23.0.3.2"}
{"reqId":"RKVG7Grc8BHspTj5A2tq","level":2,"time":"2022-04-21T12:30:02+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"User 22c05af5-1d53-433a-a00a-30a4d14e45a7 still has unscanned files after running background scan, background scan might be stopped prematurely","userAgent":"--","version":"23.0.3.2"}
{"reqId":"RSaAU6rwRyUNHB7GM2gM","level":3,"time":"2022-04-21T12:40:04+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"Could not classify incoming message importance: Could not deserialize persisted classifier 75: File at oc_tmp_jfquEk does not contain any data.","userAgent":"--","version":"23.0.3.2","exception":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"Could not deserialize persisted classifier 75: File at oc_tmp_jfquEk does not contain any data.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/Classification/PersistenceService.php","line":162,"function":"load","class":"OCA\\Mail\\Service\\Classification\\PersistenceService","type":"->","args":[75]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Classification/ImportanceClassifier.php","line":301,"function":"loadLatest","class":"OCA\\Mail\\Service\\Classification\\PersistenceService","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Listener/NewMessageClassificationListener.php","line":118,"function":"classifyImportance","class":"OCA\\Mail\\Service\\Classification\\ImportanceClassifier","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\Db\\Mailbox","id":230},[{"__class__":"OCA\\Mail\\Db\\Message","id":null},{"__class__":"OCA\\Mail\\Db\\Message","id":null}]]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Mail\\Listener\\NewMessageClassificationListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"},"OCA\\Mail\\Events\\NewMessagesSynchronized",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"OCA\\Mail\\Events\\NewMessagesSynchronized",{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"},"OCA\\Mail\\Events\\NewMessagesSynchronized"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":380,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCA\\Mail\\Events\\NewMessagesSynchronized",{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":230,"function":"runPartialSync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\Db\\Mailbox","id":230},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},42,null]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":135,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\Db\\Mailbox","id":230},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},42,null,false,true]},{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":109,"function":"syncAccount","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":3}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":150,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/mail/lib/Service/Classification/PersistenceService.php","Line":205,"Previous":{"Exception":"Rubix\\ML\\Exceptions\\RuntimeException","Message":"File at oc_tmp_jfquEk does not contain any data.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/Service/Classification/PersistenceService.php","line":203,"function":"load","class":"Rubix\\ML\\Persisters\\Flysystem","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Classification/PersistenceService.php","line":162,"function":"load","class":"OCA\\Mail\\Service\\Classification\\PersistenceService","type":"->","args":[75]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Classification/ImportanceClassifier.php","line":301,"function":"loadLatest","class":"OCA\\Mail\\Service\\Classification\\PersistenceService","type":"->","args":[{"__class__":"OCA\\Mail\\Account"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Listener/NewMessageClassificationListener.php","line":118,"function":"classifyImportance","class":"OCA\\Mail\\Service\\Classification\\ImportanceClassifier","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\Db\\Mailbox","id":230},[{"__class__":"OCA\\Mail\\Db\\Message","id":null},{"__class__":"OCA\\Mail\\Db\\Message","id":null}]]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Mail\\Listener\\NewMessageClassificationListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"},"OCA\\Mail\\Events\\NewMessagesSynchronized",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"OCA\\Mail\\Events\\NewMessagesSynchronized",{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"},"OCA\\Mail\\Events\\NewMessagesSynchronized"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":380,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCA\\Mail\\Events\\NewMessagesSynchronized",{"__class__":"OCA\\Mail\\Events\\NewMessagesSynchronized"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":230,"function":"runPartialSync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\Db\\Mailbox","id":230},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},42,null]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/Sync/ImapToDbSynchronizer.php","line":135,"function":"sync","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OCA\\Mail\\Db\\Mailbox","id":230},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},42,null,false,true]},{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":109,"function":"syncAccount","class":"OCA\\Mail\\Service\\Sync\\ImapToDbSynchronizer","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":3}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":150,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/mail/vendor/rubix/ml/src/Persisters/Flysystem.php","Line":140},"CustomMessage":"Could not classify incoming message importance: Could not deserialize persisted classifier 75: File at oc_tmp_jfquEk does not contain any data."}}
{"reqId":"RSaAU6rwRyUNHB7GM2gM","level":3,"time":"2022-04-21T12:40:12+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"Cron mail sync failed for account 4","userAgent":"--","version":"23.0.3.2","exception":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"IMAP error synchronizing account 4: Mail server denied authentication.","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":108,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},true]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":4}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":150,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","Line":107,"Previous":{"Exception":"Horde_Imap_Client_Exception","Message":"Mail server denied authentication.","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":838,"function":"_login","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1389,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":60,"function":"listMailboxes","class":"Horde_Imap_Client_Base","type":"->","args":["*",5,{"delimiter":true,"attributes":true,"special_use":true}]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","line":104,"function":"getFolders","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"Horde_Imap_Client_Socket","cacheFields":["HICenv","HICflags","HIChdrs","HICdate","HICsize","And 1 more entries, set log level to debug to see all entries"],"changed":true,"statuscache":true}]},{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":108,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"__class__":"OC\\AppFramework\\ScopedPsrLogger"},true]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":4}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":95,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":150,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":572},"CustomMessage":"Cron mail sync failed for account 4"}}
```

I can provide more info if helpful.

**Comment by st3iny** [comment] 2024-08-13 08:33
Duplicate of #7495 

Let's continue there.

**Closed by st3iny** 2024-08-13 08:33 UTC
Labels: bug, 0. to triage
