### ISSUE TITLE
Mailvelope not working in the Mail app

### ISSUE THREAD

**Issue by alucryd** [nextcloud/mail#9807] opened 2024-07-06 09:07 UTC
### Steps to reproduce

1. Install Mailvelope
2. Link to system GnuPG
3. Authorize nextcloud domain

### Expected behavior

Mailvelope should decrypt encrypted emails and offer the option to send encrypted emails.

### Actual behavior

Encrypted emails just show an encrypted.asc attachment. Writing emails does not show the mailvelope button.

Mailvelope is working fine on GMail.

### Mail app version

3.7.2

### Mailserver or service

Stalwart Mail (self-hosted)

### Operating system

Arch Linux

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Installed nextcloud with the standard docker image, exposing it via Traefik for TLS encryption. I'm using Firefox as my browser of choice.

**Comment by ChristophWurst** [comment] 2024-07-08 10:27
@pabzm could you have a look?

**Comment by pabzm** [comment] 2024-07-11 08:09
@alucryd Thank you for the report! I cannot reproduce the problem yet. To debug, could you please check that Mailvelope works with your Nextcloud instance using the OpenPGP.js backend?
Also please check what the "Mailvelope" section in "Mail settings" says.

**Comment by alucryd** [comment] 2024-07-11 10:14
@pabzm Thanks for reaching out. It would seem mailvelope isn't detected at all, settings always prompt me to install it.
![image](https://github.com/nextcloud/mail/assets/1561084/8cab9dac-0240-4d86-a949-991894c784ba)

I can reproduce on 2 different computers, mailvelope is working in gmail and outlook, but not in nextcloud. I used the `authorize this domain` button, and toggled API on, is there anything else I need to do?

**Comment by pabzm** [comment] 2024-07-11 14:29
In Mail v3.7.2 that section is static and doesn't check if Mailvelope is installed (that changes with https://github.com/nextcloud/mail/pull/9751, which will be released in v4.0.0).
To see if Mailvelope works with Mail v3.7.2 please check if when composing a message the three-dots-menu next to the send-button has the checkbox labelled "Encrypt message with Mailvelope".

**Comment by alucryd** [comment] 2024-07-11 16:09
No problem. The 3 button check does exist, and I am able to send encrypted emails via the system gnupg using my smartcard, but I can't read them for some reason.
![image](https://github.com/nextcloud/mail/assets/1561084/7d9e5650-ea4a-4d68-9ae2-fbdabb999b19)

**Comment by pabzm** [comment] 2024-07-11 16:16
Ok, a little progress :)

Are there any errors in the Web Developer Tools console when viewing the encrypted email?

**Comment by pabzm** [comment] 2024-07-16 06:06
@alucryd I looked a little bit deeper into this and your problem is actually not a bug but a missing feature of the Mail app: it doesn't yet handle PGP/MIME-message in a special way that Mailvelope would require. It is a duplicate of #3833, thus I'm closing this. (If you disagree please re-open and explain.)

**Closed by pabzm** 2024-07-16 06:06 UTC
Labels: bug, 0. to triage, feedback-requested

**Comment by alucryd** [comment] 2024-07-17 09:40
@pabzm Thanks for the heads up. Hope it's going to come soon, the mail app was the main reason I gave nextcloud a try in the first place.
