### ISSUE TITLE
[1.7.0] Unexpected error during account creation - enhance regardless of nc log_level/debug

### ISSUE THREAD

**Issue by working-name** [nextcloud/mail#4085] opened 2020-11-15 19:38 UTC
### Feature Request
Spit out a useful error message containing details as to why regardless of nextcloud log level setting. In fact, I'd argue this has nothing to do with nextcloud and in fact it only concerns the mail app and the email server it's trying to connect to.

#### Summary
The UI error should have a "show more" link if you're trying to be clean, which should exactly state what the Horde Socket Client encountered while attempting to connect. You don't need the exact php file and line number, but for example something like "SSL: Handshake timed out" would suffice to help a (power)user start figuring out what's up.

Thanks!

**Comment by ChristophWurst** [comment] 2020-11-16 09:05
I'd say duplicate of https://github.com/nextcloud/mail/issues/3006, right?

**Closed by ChristophWurst** 2020-11-16 09:05 UTC
Labels: 0. to triage, enhancement

**Comment by working-name** [comment] 2020-11-16 14:58
Ooops, sorry, didn't find that one.
