### ISSUE TITLE
Add email id to contacts app from the existing emails in inbox

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/mail#3818] opened 2020-10-15 02:08 UTC
It will be more useful to have an option to add a link to add the email id to contacts app from the existing emails in either inbox or sent mail.

**Comment by ChristophWurst** [comment] 2020-10-15 05:17
duplicate of https://github.com/nextcloud/mail/issues/143

**Closed by ChristophWurst** 2020-10-15 05:17 UTC
Labels: 0. to triage, enhancement
