### ISSUE TITLE
Mails Randomly Marked as "Important", Also For Other IMAP Clients

### ISSUE THREAD

**Issue by gohrner** [nextcloud/mail#5323] opened 2021-07-13 06:28 UTC
### Expected behavior
Mails should not be randomly marked as "Important" - I could not find any documentation about how to specifically configure and/or disable automatic tagging of mails as "Important".

The only related information I could find was this announcement: https://nextcloud.com/blog/nextcloud-mail-introduces-machine-learning-for-priority-inbox/

We mainly use Thunderbird to read mails. Tagging of mails is basically solely performed in Thunderbird, and more or less for most of the users serves as a kind of "TODO" tag - there's something about "Important" mails that still needs to be dealt with.

### Actual behavior
After upgrading the NextCloud Mail App to 1.10.0, mails in other IMAP clients seem to be randomly classified as "Important", even if the NextCloud Mail App was not "actively" used by a user.

This totally breaks the logic of using "Important" to mark mails which still need to be dealt with, does not seem to have happened in previous versions of NextCloud Mail (at least by for not as obvious), and is not desired.

Also, the NextCloud Mail App does not seem to "learn" which mails are "unmarked" as "not important" in other IMAP clients (specifically, Thunderbird).

### Mail app

**Mail app version:** 1.10.0

**Mailserver or service:** self-hosted Dovecot server

### Server configuration

**Operating system**: Debian 10 Buster

**Web server:** Apache httpd

**Database:** MariaDB

**PHP version:** 7.0.33

**Nextcloud Version:** 20.0.11 (most recent release currently offered through the Stable channel for this server)

#### Client configuration
**Browser:** N/A

**Operating system:** N/A

**Comment by ChristophWurst** [comment] 2021-07-13 07:06
Your users can turn this off: https://github.com/nextcloud/mail/issues/5260

Thea reason why the important messages now also show in Thunderbird is that we now are fully interoperable with Thunderbird and its tagging conventions. Anything marked as important here is also important there. Turn off the classification for manual workflows.

> Also, the NextCloud Mail App does not seem to "learn" which mails are "unmarked" as "not important" in other IMAP clients (specifically, Thunderbird).

It actually does based on a naive bayes algorithm. Messages (or merely senders) with similar characteristics as previous email are classified respectively. The model is retrained once an hour. Therefore it should be possible for the algorithm to somewhat pick up your preferences over time. The more data it gets, the better it will be able to classify.

**Closed by ChristophWurst** 2021-07-13 07:07 UTC
Labels: 0. to triage, bug

**Comment by ChristophWurst** [comment] 2021-07-13 07:10
Please also see https://github.com/nextcloud/mail/issues/3968 for a bit more discussion around this feature and its quality :v:

**Comment by gohrner** [comment] 2021-07-13 10:56
@ChristophWurst: Ok, thanks! From #5290 I get that disabling still does not really work for Mail 1.10.0 and 1.10.1, but will be fixed in 1.10.2 - correct?

Also, how can I imagine the "learning" - say I only use Thunderbird to (re)classify my mails as "Important" or "Not Important". However I also move my mails to other IMAP folders immediately after dealing with it, so the following will happen often:
* NextCloud Mail tags a mail as "Important" which I don't consider to be.
* I remove the "Important" flag in Thunderbird and immediately move the mail to one of my many topic-specific folders.
* Up to an hour later, the NextCloud Mail classifier will take the next look at my inbox.

Will NextCloud Mail still notice that I considered the "Important" tag as a misclassification in this constellation and update its statistics accordingly?

Or will it think I just deleted the mail from the inbox and the classification it did was correct?

**Comment by ChristophWurst** [comment] 2021-07-13 11:37
> @ChristophWurst: Ok, thanks! From #5290 I get that disabling still does not really work for Mail 1.10.0 and 1.10.1, but will be fixed in 1.10.2 - correct?

Correct :)

> Will NextCloud Mail still notice that I considered the "Important" tag as a misclassification in this constellation and update its statistics accordingly?

It depends. If Nextcloud is configured to also synchronize the other mailbox at which the message is now stored for background syncs (checkbox in the ... menu in the sidebar) then it will have that message as non-important reference. Then it can learn your pattern.

If the mailbox is not indexed nor synchronized by Nextcloud Mail then it won't be able to learn from your feedback.

There is one other quirk you might encounter. 
1) A new messages is received
2) Mail marks it as important
3) You unmark and move the message
4) The message is detected in the new mailbox, Mail marks it as important again

This will happen because from Mail's perspective we don't know the message was ever unmarked from being important, our application doesn't keep track of before/after states. It "just" finds this new message in a mailbox and then does its classification.

As opposed to `$junk` and `$notjunk` there is no negated IMAP flag for `$label1` (important). If Thunderbird and other clients set a `$notimportant` or similar on IMAP then our application would be able to know that something was either already classified or changed by the user. Right now either no flag is set or `$label1`. If the flag is set then we don't classify, we assume that this state is already correct. In the absence of the flag we start our classifier.

**Comment by gohrner** [comment] 2021-07-16 07:02
@ChristophWurst:

> The message is detected in the new mailbox, Mail marks it as important again

Actually I have the impression that Nextcloud Mail also even marks mails in the inbox again which were misclassified and which I unmarked, without them being moved anywhere.

I assume this should not happen, should I file another bug for this? However I probably cannot provide much more information than this at the moment...

**Comment by ChristophWurst** [comment] 2021-07-16 08:33
Well there is no code for that. Only when messages are indexed for the first time they are classified.

Could you observe it a little longer to find a pattern of when that happens exactly?

**Comment by gohrner** [comment] 2021-07-16 11:24
(Shall I move this conversation to the forum or PM; it's probably not (yet) suitable for a bug tracker.)

Could this be related to re-marking messages as unread?

What I do is, I get a bunch of new mails, which wait in "unread" state in my mailbox and after a while Nextcloud Mail marks some mails as "important". I use Thunderbird to open the mails, reset the "important" flag to "not important" and re-mark the mail as "unread".

Could this cause Nextcloud Mail to tag the mails as "important" again?

In any case, this already happened again.

Mailserver is the Dovecot version contained in Debian 10 Buster.


Also a question - if

> Only when messages are indexed for the first time they are classified.

is the case, how does Nextcloud Mail notice later changes to the "Important" flag for training? Or does it monitor already classified mails if the flag changes, but does the classification and tagging only once when adding the mail to the index?

**Comment by bjoernv** [comment] 2023-06-28 07:19
I observe the same problem. Only new messages are marked as "Important".

The setup is more recent compared with the initial report:
Web Server: Apache 2.4.57
PHP: 8.2
MySQL: 5.7.42
IMAP: Dovecot IMAP 2.2.33.2
Nextcloud: 25.0.8

**Comment by NextTherapist** [comment] 2023-07-08 06:10
> Actually I have the impression that Nextcloud Mail also even marks mails in the inbox again which were misclassified and which I unmarked, without them being moved anywhere.

I can confirm this for Nextcloud 26.0.3 and PHP 8.1 with Thunderbird 102.11.
Why is this buggy feature activated by default?

**Comment by Jacques-Olivier-Farcy** [comment] 2025-03-13 17:16
Hi,

I really don't understand why in Nextcloud Mail this setting is activ by default.
Mail Settings - Assistance features - Mark as important should be uncheck by default.
I am using thunderbird for years with an IMAP server.
Today i had to configure mail in my nextcloud, i realised after that all my messages were marked as important when i opened thunderbird again.

I had no way of knowing that there was this option to tick before configuring mail in nextcloud.

I know have to reconfigure all my mail history to change the important tag.
I don't think it can be closed.

**Comment by zulu64** [comment] 2025-03-14 15:48
Hi,

Referring to the issues original text:
"Mails should not be randomly marked as "Important" - I could not find any documentation about how to specifically configure and/or disable automatic tagging of mails as "Important".

The mails are not randomly marked as Important.
The mail setting "Assisted features / Mark as important" will switch off the functionality you do not like.

I recommended the ticket be closed 'cause it isn't a problem. It sounds like you would like a feature (change) request to default the mail setting "Assisted Feature / Mark as important" to unchecked. I suggest you do that as this ticket doesn't cover that.

**Comment by gohrner** [comment] 2025-03-15 20:52
@zulu64: It's a problem if
1. this feature is on by default
2. marks many mails as important according to some hidden logic which simply looks "random" to the user
3. causes messed up information or even information loss by messing with the users currently used "important" tagging for mails.

Either this feature should be off by default, or it should mark mails MUCH more defensively and better explain why it's doing what it's doing.

Currently, if Nextcloud Mail gets enabled - possibly by accident - suddenly tons of mails in your mailbox get tagged as "important" and you'll have a fun time to reconstruct what was actually "important". (Disclaimer: Probably only very few if you have that many mails in your inbox.)

**Comment by yitzhaq** [comment] 2025-03-23 01:35
> In case this helps anyone:
> 
> This is neither a bug in Thunderbird nor Nextcloud.

Unfortunately no, I'm afraid this does not really actually help anyone. The fact that the functionality is leveraging standard message flags is the cause of the issue - not an answer to it.

> If your email server type is IMAP, all changes made by any of your email clients will be received by the other email clients. This doesn't mean those changes are always visible, but the "Important" tag is one feature that is shared by Thunderbird and the Nextcloud Mail app.

And yet only one of them flags a user's messages indiscriminately, without warning, by default.

> I confirm this still happens today with: Thunderbird 128.8.0 Mail 4.2.5 on Nextcloud 31.0.0 (Hub 10)
> 
> If you don't want this to happen in Thunderbird, ensure that other email clients don't automatically set the "Important" tag - in my case, change the setting in the Nextcloud Mail app: Mail Settings - Assistance features - Mark as important - uncheck

The "other email clients" in this case is Nextcloud, which is why the issue is reported here. I am not aware of any other email clients with this particular behavior.

While the existence of a user setting might be claimed to minimally mitigate this issue, it unfortunately is not enough.

1. The setting should *also* be an admin setting, so it can be disabled globally for an entire Nextcloud instance - either as default or forcibly (so admins are empowered to prevent users from shooting themselves in the foot)

2. The user setting should arguably be disabled rather than enabled by default, considering the consequences of having it enabled.

Among desktop MUAs, Thunderbird is likely the most popular. At least if you disregard Outlook, which unlike Thunderbird does not support the open and interoperable protocols offered by Nextcloud. A Nextcloud user is likely to use Thunderbird, and a Thunderbird user's email experience is severely negatively impacted by this current (and long-time) behavior.

I know of several cases where users have been frustrated for months, and spent countless hours trying to figure out why their trusty Thunderbird suddenly and unexpectedly "got broken" over night, before figuring out this issue was to blame. And those are only the cases where the user actually did figure it out.
Before these users could even go hunting for an obscure setting, they first would have to know that it is in fact the common perfect storm interaction between Nextcloud and Thunderbird causing it, and then realize it is in fact within Nextcloud they need to find and make the right change to return their Thunderbird back to normality.

This does *not* describe a good user experience, and it has to change.

> As this issue is in Triage for 4 years now, and cannot be fixed (and doesn't need to be), I suggest it can be closed.

It was already closed 4 years ago, and yet here we all are, still discussing it. This strongly suggests the feature is not working optimally, and requires reconsideration.

**Comment by ChristophWurst** [comment] 2025-03-24 10:46
> The setting should _also_ be an admin setting, so it can be disabled globally for an entire Nextcloud instance - either as default or forcibly (so admins are empowered to prevent users from shooting themselves in the foot)

Please see https://github.com/nextcloud/mail/issues/6390. This setting exists.

**Comment by zulu64** [comment] 2025-03-24 11:56
@gohrner & @yitzhaq 

Thanks for the feedback. Like you, I'm a user, and like you, I don't like surprises or black boxes when installing things.

As noted by @ChristophWurst above, I found the new Admin setting last week hidden in "Groupware - Enable classification by importance by default" which solves a lot, but explains little. I raised #10907 to cover missing documentation. Please feel free to add to that.

**Comment by ChristophWurst** [comment] 2025-09-18 10:20
Thank you for the feedback @bernd-wechner! We've decided to look into https://github.com/nextcloud/mail/issues/11716 as way to hopefully improve transparency about the feature.
