### ISSUE TITLE
Add support for Inbox folders and rule based sort to folder

### ISSUE THREAD

**Issue by thisiszeev** [nextcloud/mail#9870] opened 2024-07-16 22:08 UTC
### Is your feature request related to a problem? Please describe.

not a problem

### Describe the solution you'd like

In almost all desktop mail clients, you can have folders in your inbox. You are also able to create rules (if from name@domain.net / if subject contains keyword) so that incoming emails can be automatically moved to the folders.

**Comment by ChristophWurst** [comment] 2024-07-17 06:05
Duplicate of https://github.com/nextcloud/mail/issues/44

**Closed by ChristophWurst** 2024-07-17 06:05 UTC
Labels: enhancement, 0. to triage
