### ISSUE TITLE
Error while loading messages. Inbox

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/mail#337] opened 2017-03-22 19:06 UTC
### Steps to reproduce
1. Open Mail App
2. If not in Inbox, select inbox
3. Scroll down to see older messages

### Expected behaviour
1. When scrolling and reaching the bottom, older messages should load and show.

### Actual behaviour
1. First scroll down to bottom loads new batch of older messages
2. Second scroll down to bottom triggers "Error while loading messages."

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
Error	index	TypeError: Argument 1 passed to OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in /home/share/public_html/apps/mail/lib/Model/ConvertAddresses.php on line 74
    /home/share/public_html/apps/mail/lib/Model/ConvertAddresses.php - line 74: OCA\Mail\Model\IMAPMessage->hordeToAssoc(Object(Horde_Mail_Rfc822_Group))
    /home/share/public_html/apps/mail/lib/Model/IMAPMessage.php - line 225: OCA\Mail\Model\IMAPMessage->convertAddressList(Object(Horde_Mail_Rfc822_List))
    /home/share/public_html/apps/mail/lib/Model/IMAPMessage.php - line 494: OCA\Mail\Model\IMAPMessage->getToList(true)
    /home/share/public_html/apps/mail/lib/Mailbox.php - line 190: OCA\Mail\Model\IMAPMessage->jsonSerialize()
    /home/share/public_html/apps/mail/lib/Controller/MessagesController.php - line 137: OCA\Mail\Mailbox->getMessages(42, 21, '')
    [internal function] OCA\Mail\Controller\MessagesController->index(2, 'SU5CT1g=', 42, 62, '', NULL)
    /home/share/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /home/share/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'index')
    /home/share/public_html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'index')
    /home/share/public_html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /home/share/public_html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /home/share/public_html/lib/base.php - line 1010: OC\Route\Router->match('/apps/mail/acco...')
    /home/share/public_html/index.php - line 40: OC handleRequest()
    {main}
</details>

It only happens in Inbox thusfar it does not happen in other folders like sent items...

**Comment by ChristophWurst** [comment] 2017-03-22 19:14
> OCA\Mail\Model\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address

Duplicate of https://github.com/nextcloud/mail/issues/53 :-)

**Closed by ChristophWurst** 2017-03-22 19:14 UTC
