### ISSUE TITLE
Missing 'oc_mail_messages' table blocks upgrade to Nextcloud 19

### ISSUE THREAD

**Issue by mlaradji** [nextcloud/mail#3336] opened 2020-06-30 22:15 UTC
I'm not sure if this should be filed under this repo, or the main `nextcloud/nexcloud` repo.

### Expected behavior
I expected that the 'oc_mail_messages' table would be automatically created, or the 'Mail' app would be automatically disabled (which might be more of an upstream Nextcloud issue).

### Actual behavior
Nextcloud upgrade cannot proceed:
```bash
root@nextcloud-server:~# nextcloud.occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <mail> ...
Doctrine\DBAL\Schema\SchemaException: There is no table with name 'nextcloud.oc_mail_messages' in the schema.
Update failed
Maintenance mode is kept active
Reset log level
``` 
Upgrading the apps worked, but did not help (which is not surprising since the Mail app was not updated by the command):
```
root@nextcloud-server:~# nextcloud.occ app:update --all
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
bookmarks new version available: 3.2.4
bookmarks updated
deck new version available: 1.0.4
deck updated
notes new version available: 3.6.0
notes updated
social new version available: 0.3.1
social updated
```

### Mail app

**Mail app version:** 1.3.5

**Mailserver or service:** [irrelevant]

### Server configuration

**Operating system**: ubuntu 16.04 LTS amd64 (release) (20180912) (LXD container)

**Web server:** Apache (through Nextcloud Snap)

**Database:** MySQL (through Nextcloud Snap)

**PHP version:** [Not sure]

**Nextcloud Version:** 19.0.0snap1

#### Client configuration
[irrelevant]
**Browser:** Firefox 77.0.1

**Operating system:** Ubuntu Neon 18.04

### Fix
I was able to resolve this by disabling the `mail` app and then proceeding with `nextcloud.occ upgrade`. I'm not sure if there is a better or simpler way to resolve this issue.

**Comment by ChristophWurst** [comment] 2020-07-01 15:23
Is this a duplicate of https://github.com/nextcloud/mail/issues/3273?

I really don't why this is a problem. Is it the first time you have the app installed?

> I was able to resolve this by disabling the `mail` app and then proceeding with `nextcloud.occ upgrade`. I'm not sure if there is a better or simpler way to resolve this issue.

:exploding_head:

**Closed by ChristophWurst** 2020-07-01 15:23 UTC
Labels: 0. to triage, bug

**Comment by mlaradji** [comment] 2020-07-02 23:32
@ChristophWurst Oops, this is certainly a duplicate of #3273. The issue was not resolved per-se, but I was able to continue the nextcloud upgrade by disabling the mail app.

I've had the mail app for a very long time, and the failure happened with an automatic snap upgrade to Nextcloud 19.

**Comment by ChristophWurst** [comment] 2020-07-03 06:23
Thanks, no worries about the duplicate :)
